### ISSUE TITLE
Dropdown box for votes doesn't scale well to many votes

### ISSUE THREAD

**Issue by arhag** [steemit/condenser#10]
Take this post for example:
https://steemit.com/steemservices/@steemservices/getting-started-with-steemit

First of all, nice touch on extending the bottom of the page with enough whitespace to fit the largest vote dropdown. I'm glad that I didn't have to report that as a bug.

However, notice how much whitespace needs to be added for that post simply to fit the (currently) 51 votes of the root post. It would be even worse if the comment closest to the bottom of the page (for some given sort order presumably other than trending) had all those votes. And this problem will only get worse as the site gets bigger and popular posts end up having many many more votes. 

I propose that the vote dropdown only shows at most the top N (choose a reasonable N) votes by abs_rshares. And then if there are more votes than that, it includes an item at the bottom that says "M more votes..." (except replace M with the actual number). Alternatively, if all the votes for the comment are displayed in the dropdown, it instead includes an item at the bottom that says "Show vote details...". If the user clicks on either of those bottom items, it takes them to another page which shows all of the ranked votes for that particular post/comment.This view could have a lot more detail about the votes such as the user-selected weight, the rshares value, time of voting, and current vote weight (the one that determines fraction of curation rewards earned). And this data can be in a table that allows sorting by any of the columns in ascending or descending order.

**Comment by arhag** [comment]
By the way, I think it would be nice if the upvotes and downvotes were color coded in the dropdown. The + and - is very subtle. But if in addition to the + and -, the upvotes were green and downvotes were red, it would be very obviously which was which.

**Comment by arhag** [comment]
In addition to the above, I think the dropdown text should say "`N` Net Votes by `V` Voters" (instead of the current "`N` Votes" displayed on steemit.com) where `N` is the number of net votes as in number of upvotes - number of downvotes, and `V` is the number of voters as in number of upvotes + number of downvotes.

Then when you click on the dropdown it shows the top `M` voters ranked by `abs_rshares` (for some reasonable site-wide positive integer constant `M`). Once again, upvotes would be prepended by a + and be colored green, while downvotes would be prepended by a - and be colored red. 

At the bottom of the dropdown list (i.e. item number `M+1` in the dropdown list) would be either a link saying "Show vote details..." (if `M == V`) or a link saying "`V-M` more voters..." (if `V > M+1`) or a link saying "1 more voter..." (if `V == M+1`). (That is for English-specific rendering of the UI. Obviously, adjust to follow proper internalization/localization standards for rendering UI in other languages.) In either of those cases, the link would open a new tab to a page (same page for all cases) that shows the detailed votes for that post/comment as described in the OP.

**Comment by roadscape** [comment]
This is implemented except for the displaying of extra vote details. Should suffice for the 99.9%
