### ISSUE TITLE
Don't show number of voters on a post/comment but show a number related to rshares

### ISSUE THREAD

**Issue by abitmore** [steemit/condenser#1004]
The number how many people have voted on a post makes less sense than how much stake has voted. We can show the voter list like this:
* a_mega_whale x 5000 (SP or VESTS or something related)
* a_whale x 1000
* another_whale x 890
* a_dophin x 123
* another_dophin x 96
* a_minnow x 15
* another_minnow x 11
* ...

ordered by quantity of rshares contributed. And have a number that sums all the numbers. Then the reward would be somehow related to this number.

With this, people will know how whales affect the rewards. People can spend thousands on online games buying virtual items, there should be quite some like a number shows after their names, perhaps better it's opt-in or opt-out.

**Comment by sneak** [comment]
This would make sense if our goal in the UI is to focus specifically on rewards.

However, we anticipate a larger number of users with relatively small amounts of stake in the future.  Most new users can't be expected to fund their brand new account.  We want to focus more on the user interactions than the weight of the rewards, if that makes sense.

**Comment by roadscape** [comment]
Rshares are already reflected in the payout. The vote count is fine, but it should just filter known bots IMO.
