### ISSUE TITLE
Suggestion: when downvoting, the impact to be relative to the total amount of the rewards already allocated to the post, not to the entire reward pool.

### ISSUE THREAD

**Issue by dragosroua** [steemit/condenser#1008]
Example: voter A can move 10% of the reward pool. He upvotes a post to which, as a result, it assigns $100 from the reward pool (hypothetically, the reward pool is $1000). 

Voter B comes in, doesn't like the posts and he downvotes it. Voter B can also move 10% of the reward pool. 

But when he downvotes, he can move (take away, in this case) only _10% from the rewards already there at the moment of downvoting_.

Rationale and potential benefits in this article:

https://steemit.com/steemit/@dragosroua/a-proposal-for-solving-flagging-downvotes-and-spam-management-on-steemit

**Comment by roadscape** [comment]
I'm not sure I fully understand, but it sounds like a consensus logic change, not a UI feature.
