### ISSUE TITLE
Using code markup in the post gives image saving error

### ISSUE THREAD

**Issue by tibonova** [steemit/condenser#1012]
I've tried to include [this template](http://pastebin.com/CjjSYay2) into my post, but I've got the following error:
> An image in this post did not save properly. 

I've changed the Markdown code symbols at the start and the end to `<code>...</code>`, and after I had checked the rendered source of one of my similar post, to `<pre><code>...</code></pre>`.
The error was similar in all cases, the interesting thing was that the preview mode rendered the code well when I used Markdown, and produced glitch when I used HTML.

I've checked the FF Console and it's given the following error:

> 01:40:12.279 Blocked, image tag src does not appear to be a url img Object { src: "¶¶DIRECT-LINK¶¶", alt: "¶¶ALT¶¶" }

I think it wants to render an image while I tell the engine it's code. It shouldn't check the validity of the code. 

(Just in case if you have similar problem: I'll use a screenshot + pastebin link as a workaround.)

**Comment by roadscape** [comment]
Does the problem persist?

**Comment by plink01001** [comment]
Is this still an issue, or can it be closed?

**Comment by plink01001** [comment]
Please re-open if this is still an issue.

**Comment by ThierryDD** [comment]
I have a similar problem with the following code fragment:

```
```html
<img alt="highligh" src="data:image/png;base64,iVBORw0KGgoAAAAN...iAABJRU5ErkJggg==">
` ``
```
The error message I get is:

`Blocked, image tag src does not appear to be a url img`

**Comment by roadscape** [comment]
@ThierryDD thanks, this is a different problem, but feel free to open a new issue.
