### ISSUE TITLE
Mentions tab

### ISSUE THREAD

**Issue by tibonova** [steemit/condenser#1027]
I like the new push feature (it worked when transfer was made), thanks for that.
However, I wish we had a `Mentions` tab beside the `Comments` and `Replies`.
 
That would be the most useful when the mention is not a reply, and you want to manage your unread mentions later. Push notifications are good for instant reply, but not for the good old procrastination (that is required when you have to concentrate on something.) Also, I can imagine what would happen if any of the whales or popular users would allow push notifications...

**Comment by roadscape** [comment]
We'll implement this once we get the middleware running.
