### ISSUE TITLE
Issues with Mobile Notification

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/condenser#1036]
Hi!

I have a Android LG G5 and when I click on the notifications coming from steemit.com, it leads me to a /undefined page.

**Comment by valzav** [comment]
Could you check if it's fixed now?

**Comment by robrigo** [comment]
This is still happening for me using Chrome on Android.

**Comment by RenaudGagne** [comment]
Still happening for me too

**Comment by clayop** [comment]
Worked with comment notifications. Mention notification didn't work IIRC.

**Comment by roadscape** [comment]
Please open new ticket if this is still an issue.
