### ISSUE TITLE
image orientation is wrong in some cases

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/condenser#1047]
spotted few times after image proxy changed:
[example1](https://steemit.com/introduceyourself/@emittt/i-m-young-and-new-here) and [exmaple2](https://steemit.com/introduceyourself/@vorticieflux6626/hello-world-introduction)

Exif orientation seems to not be taken into account

**Comment by pfunks** [comment]
Is the new proxy stripping all EXIF data?

**Comment by jcalfee** [comment]
EXIF data is removed only on upload..  That feature is not live yet so .. not it is not.

**Comment by jcalfee** [comment]
That image has EXIF data in it.  This looks interesting (from the image):
`Orientation                     : Rotate 180`

If I download and open the image it appears correctly in my image viewer..

**Comment by jcalfee** [comment]
I can't think of any changes I made other than to add a signed url (basically a forward) to fetch this image from Amazon's S3 service.

Opening the example1 image from the post in a new tab makes the image appear right side up (correctly)..  I noticed the EXIF Orientation is "Rotate 180" and that this is present in the main post as well as the new tab.

I can open it directly by URL too (https://steemitimages.com/0x0/https://i.imgsafe.org/57429cc529.jpg) and see it correctly.  It is only when the <img tag is used with steemitimages does the image appear up-side down.

**Comment by Gandalf-the-Grey** [comment]
Partial solution might be using (not widely supported) CSS's 
```
img {
  image-orientation: from-image;
}
```
but stripping Exif data along with re-encoding all images might be a better idea

**Comment by jcalfee** [comment]
I pushed a change to the image proxy and hosting service..  This should capture and resolve this issue for all new posts in all cases.  The server will apply this rotation and remove the EXIF tag:

http://sharp.readthedocs.io/en/stable/api-operation/#rotate

There is still a issue in the markdown preview if an external link is given (such as 57429cc529.jpg above).  Right now the w3c image-orientation css property is only supported in Firefox.  It might be desirable to apply the image proxy prefix to the markdown preview.  That would trigger the rotation and caching earlier before the post gets saved.

**Comment by jcalfee** [comment]
Actually, the markdown preview is already applying the image proxy prefix.. :) .. It just has not been deployed yet..  Ok, so I think this ticket can be closed soon.

**Comment by jcalfee** [comment]
Related: https://github.com/steemit/steemit.com/issues/1098

**Comment by jcalfee** [comment]
This change will direct the image proxy server to auto-rotate and cache images like these:
Related: https://github.com/steemit/steemit.com/issues/1098
