### ISSUE TITLE
Missing posting authority error for content-specific issues

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/condenser#1075]
User `the-future` had issues while trying to submit his post.
Error: `Missing posting authority` was misleading because real cause was related to content.
User was making copy&paste of descriptions below figures.
We were able to isolate issue to FIG 1 description as in
https://arxiv.org/pdf/1609.08684v1.pdf
Then, even more, reduced to: (_H<sub>1</sub>_)
User reproduced above error (copied from Adobe Reader, pasted to Google Chrome on Windows Vista).
I was unable to reproduce it on my system (totally different software).

**Comment by roadscape** [comment]
I copy-pasted from Chome's PDF reader into a Chome tab on OSX, and did not face any issues.

Could you have him try copy-pasting from the PDF opened in Chrome? Sounds like it's either an Adobe Reader or Vista quirk.

**Comment by roadscape** [comment]
Haven't heard anything more about this, closing
