### ISSUE TITLE
Optional automatic upvote on our own comments

### ISSUE THREAD

**Issue by tibonova** [steemit/condenser#1083]
I didn't feel that important until downvoter bots started to vote on comments immediately after they've appeared. 
One could hide the fresh comments with only 1, low-weight downvote (and also posts, but we fortunately have auto-UV option there). With auto-UV, we would have a convenient way to mitigate the harm on our visibility.

**Comment by TimCliff** [comment]
The downvote bot has now been countered by the @seraph bot. Is there still a need for this change?

**Comment by tibonova** [comment]
It's good to hear about the @seraph bot. I've just experienced it in action. 

I think we need this because it's just the start of the downvotes. It also won't defend individuals from personal attacks. I'm glad we experienced this in beta and not in later stages, and we can start a discussion about it. 

I don't understand why we don't have automatic comment UV option when we have it for posts? What's the difference? Are comments not worthwhile enough? Or why we have it for posts at the first place? Maybe I'll see the difference if I know that.

**Comment by TimCliff** [comment]
@sneak - do you want me to work on this?

**Comment by sneak** [comment]
No, I think this is a non-solution to a non-problem.

**Comment by roadscape** [comment]
This doesn't seem to be an issue anymore
