### ISSUE TITLE
mention - notifications (self)

### ISSUE THREAD

**Issue by fxnormaluser** [steemit/condenser#1103]
On Steemit.com, using chrome browser:

I get notifications for being mentioned, when i mention myself.

Steemit post about this:
https://steemit.com/steemit/@felixxx/steemit-improvement-proposal-regarding-mention-notification

**Comment by TimCliff** [comment]
The issue has been mentioned here: https://github.com/steemit/steemit.com/issues/1052

**Comment by fxnormaluser** [comment]
That's about when a user recieves a reply and is also being mentioned in same reply, I think.

**Comment by TimCliff** [comment]
Yeah, it is something they are planning at a later date, when they revamp notifications (as per the comment in issue 1052).

**Comment by roadscape** [comment]
Still a problem?

**Comment by fxnormaluser** [comment]
Mentions on steemit.com don't seem to be working at the moment.
Last time it worked, I still got notifications for mentioning myself. 
I can't definitely confirm it though.

**Comment by plink01001** [comment]
The changes for notifications are being tracked in https://github.com/steemit/condenser/issues/72
