### ISSUE TITLE
Can't Reach Bottom of Blog Page

### ISSUE THREAD

**Issue by KrNel** [steemit/condenser#1109]
I have tested this on my account logged in, not logged in on another browser, and also another account with many posts, https://steemit.com/@papa-pepper. Scrolling down eventually stops short of the end.

I reached a resteem I made: Let's Talk About SteemIt Voting Power Issues on "Whale" @fuzzyvest's Awesome Beyond Bitcoin Show
https://steemit.com/beyondbitcoin/@nonlinearone/let-s-talk-about-steemit-voting-power-issues-on-whale-fuzzyvest-s-awesome-beyond-bitcoin-show

And another two times this post I made which is 1 lower than the above resteem: Shatter, Destroy and Stop the Falsity
https://steemit.com/evil/@krnel/shatter-destroy-and-stop-the-falsity

For papa-pepper, the last post was: THE EDIBLE OUTDOORS #2 - Lamb's Quarters
https://steemit.com/food/@papa-pepper/the-edible-outdoors-2-lamb-s-quarters

Thank you for looking at this issue. It's important to be able to reach all of someone's posts.

Thanks for all your work! Peace.

**Comment by roadscape** [comment]
Related: https://github.com/steemit/steem/issues/1137

**Comment by roadscape** [comment]
Resolved with new hive API.
