### ISSUE TITLE
Can we get a list of transactions?

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/condenser#1133]
When it trade money on the internal market I would like to keep track of what transpired.

It shouldn't show, it can be hidden like the steem I've put onto the market is?

**Comment by roadscape** [comment]
Could you clarify the question? Are you wanting to see which trades have been filled?

**Comment by FreeBornAngel** [comment]
Trades on the internal market mainly.
So I can keep track of my trading history.

**Comment by FreeBornAngel** [comment]
Closed transactions is what I am looking for.
Open transactions we got, but unless I write down my trades I have no way to track what I am doing.

**Comment by roadscape** [comment]
I believe a backend change for showing filled orders has been implemented recently, will verify

**Comment by FreeBornAngel** [comment]
Alright,...thanks,...
