### ISSUE TITLE
Change views count to an estimated value but not the number tracked from Steemit.com only

### ISSUE THREAD

**Issue by abitmore** [steemit/condenser#1138]
It brings much confusion that views count is often great than votes, which is bad UX. I think it's better to play a trick, for example just add votes count up to the views count.

**Comment by TimCliff** [comment]
I'm not sure on this one. It seems like it masks the problem people have - which is that posts are not really getting many 'human' views, and a large portion of the voting happens by bots. I also worry that a lot of people will see it as misrepresenting the data.

**Comment by abitmore** [comment]
I know it's arguable. IMHO, currently views counts the views on Steemit.com only, but votes counts votes from all the Steem network (including ones from BUSY, eSteem, Streemian, Steemdb and etc). So the views count is already inaccurate. Putting this two data together is bad UX. If we can't make it looks better, I'd rather remove it. Public the formula, people want to know the underlying data will figure out by themselves.

**Comment by abitmore** [comment]
Another proposal: show the views count as an estimated value: 
```
estimated_total_view_counts = views_on_this_site * votes_from_all_sources / votes_from_this_site
```
Detailed info can be shown on hover.

**Comment by jcalfee** [comment]
If the votes are really all bots then that the focus needs to be on the vote count not the view count.

**Comment by jcalfee** [comment]
Lol .. You should probably change the title of this ticket, although it is brining people in to comment!

**Comment by abitmore** [comment]
Title changed.
By the way, if `views_on_this_site` < `votes_from_this_site` we have an issue about the tracking of views and/or votes.

**Comment by roadscape** [comment]
It might make sense to modify how we show the vote count, but I don't think view count needs any changes.
