### ISSUE TITLE
Show last edit time of a post

### ISSUE THREAD

**Issue by abitmore** [steemit/condenser#1146]
At least mark a post as edited.

**Comment by sneak** [comment]
We definitely want to do this, but it's a pretty low priority.

**Comment by roadscape** [comment]
Let's add an asterisk to timestamp if there was an edit.

**Comment by plink01001** [comment]
Are there plans to make any changes for this issue, or should it be moved to the `enhancement-review` category?

**Comment by pkattera** [comment]
With possible unlimited editing with HF20, here is a possible quick solution:

![screen shot 2018-10-05 at 1 45 09 pm](https://user-images.githubusercontent.com/1121139/46559370-0131cc80-c8a5-11e8-8b51-735035c769c4.png)
