### ISSUE TITLE
Filter box under Tags and Topics on main page should search over all categories (not first 100)

### ISSUE THREAD

**Issue by valzav** [steemit/condenser#115]

**Comment by mcifani** [comment]
Agree.  Is this still an open item?  I can look at improving the search.

**Comment by valzav** [comment]
yes, still open, would be nice if you could take a look

**Comment by KrNel** [comment]
Has there been any progress on adding access to all tags for us to view?

**Comment by sneak** [comment]
@krnel not yet - if there is, you will see it referenced here.

**Comment by roadscape** [comment]
Will revisit more powerful tag search later.
