### ISSUE TITLE
follow/mute buttons missing on logged out profile view

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1161]
<img width="793" alt="screen shot 2017-02-15 at 20 33 51" src="https://cloud.githubusercontent.com/assets/408977/23003335/0dbb6ac8-f3be-11e6-95c1-a0c89513102f.png">

The follow/mute buttons should remain on logged out views, popping up a big "login/signup" modal.  It's an opportunity to convert people.

**Comment by sneak** [comment]
Oh, also, the padding between the bottom of the profile image and the top of the user's descriptive text should be increased 50-100%.

**Comment by mcifani** [comment]
Updates in PR https://github.com/steemit/condenser/pull/1217
