### ISSUE TITLE
there is no signup link on the authenticate modal when you click to vote on something while logged out

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1162]
also "authenticate for this transaction" makes it sound like i'm in total recall

**Comment by mcifani** [comment]
PR now in https://github.com/steemit/steemit.com/pull/1171.   Authenticate popup is now improved with action specific title, inclusion of sign up for user conversions.  Screenshot attached.

**Comment by mcifani** [comment]
<img width="703" alt="screen shot 2017-02-16 at 1 27 15 pm" src="https://cloud.githubusercontent.com/assets/1158463/23035216/675287fe-f44c-11e6-931c-96bb9a11078a.png">

**Comment by mcifani** [comment]
New PR up at https://github.com/steemit/steemit.com/pull/1176

- New call to action for new users
- Track sign up click and broadcast type(vote, comment, post, etc)

**Comment by mcifani** [comment]
<img width="734" alt="screen shot 2017-02-16 at 6 12 11 pm" src="https://cloud.githubusercontent.com/assets/1158463/23045699/c4d392d4-f473-11e6-8776-c51e246f4273.png">

**Comment by sneak** [comment]
if that isn't a call to action i don't know what is
