### ISSUE TITLE
our comment field should show up and be greyed out and our call to action should be not weaksauce

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1163]
<img width="489" alt="screen shot 2017-02-15 at 20 39 38" src="https://cloud.githubusercontent.com/assets/408977/23003438/d8f70292-f3be-11e6-87bd-fdc2362e22bc.png">

**Comment by sneak** [comment]
@valzav I would like to see our specific conversion rate from this link.

**Comment by roadscape** [comment]
Same goes for the main homepage upper banner

**Comment by mcifani** [comment]
Post update was refreshed in pr https://github.com/steemit/condenser/pull/1207  - closing this/a separate ticket exists for comment box refresh.
