### ISSUE TITLE
the new/hot/trending/promoted second level nav should appear on BOTH of the modal page view/full page view, or NEITHER.

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1165]

**Comment by mcifani** [comment]
Are we sure we want to do this?  

- I don't think putting this sub-nav on the modal is good.  
- I do see some merit from removing on the full page view, but feel it might severally limit users navigation when they land here(post full page view).  At the very least, we'd need to replace it with a < like we do on the collapsed state.

**Comment by roadscape** [comment]
What's the status, can we close this for now?

**Comment by plink01001** [comment]
Should this be closed?

**Comment by plink01001** [comment]
Closing as modals have been removed. Please re-open if this is still an issue.
