### ISSUE TITLE
wip: redesign signup ux

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1172]
1: remove 1/2/3 milestones from top bar and just show progress bar. make it unclear how many steps there are.

first step should obviously be choose username, get them invested. realtime ajax red/green feedback. giant next button animates in or illuminates when a suitable name is chosen.

second step is email. everyone gives those out like candy. same giant dopamine granting next button appears with a splash when a valid email is entered.

last step we finally tell them is the last step and ask for a phone number, explaining that it is to prevent people from getting UNLIMITED FREE MONEY because we are about to give them some FREE MONEY just for being awesome.

actual last step is text code confirm. we shouldn't have that much abandonment here if we do this right. 

email confirm happens later after signup. if we get a text confirmed and they typoed email, we can just let them change it later or sms confirm a change.

**Comment by sneak** [comment]
![image_uploaded_from_ios](https://cloud.githubusercontent.com/assets/408977/23040956/4fc53b26-f461-11e6-9477-ae432da131c7.jpg)

**Comment by mcifani** [comment]
Screenshot images of new sign up flow/preview.  1. Username, 2. Email, 3. Phone.   Styling& verbiage needs to be further tweaked. 

<img width="1188" alt="screen shot 2017-03-20 at 4 56 12 pm" src="https://cloud.githubusercontent.com/assets/1158463/24121662/7a1c2afa-0d8f-11e7-9c51-aef8f0022332.png">
<img width="1041" alt="screen shot 2017-03-20 at 4 58 52 pm" src="https://cloud.githubusercontent.com/assets/1158463/24121661/7a1c1092-0d8f-11e7-8985-bed679f9e75e.png">
<img width="955" alt="screen shot 2017-03-20 at 5 03 29 pm" src="https://cloud.githubusercontent.com/assets/1158463/24121663/7a1d58bc-0d8f-11e7-90ba-e6a3458fdbeb.png">

**Comment by sneak** [comment]
Do we no longer have any sort of positional indicator/progress bar at the top?

**Comment by mcifani** [comment]
It's there just commented out atm removing step indicators. What are you thoughts displaying percentage?

**Comment by mcifani** [comment]
The old style even without steps seemed a bit dated. Foundation includes a nice progress bar and better imho.  Example attached.  
<img width="1217" alt="screen shot 2017-03-21 at 4 44 30 pm" src="https://cloud.githubusercontent.com/assets/1158463/24170042/ebbc1d66-0e55-11e7-8a7f-d8c8a5fc3c80.png">

**Comment by sneak** [comment]
Looks good.
