### ISSUE TITLE
display user avatar in the reply comment popup

### ISSUE THREAD

**Issue by dragosroua** [steemit/condenser#1181]
Right now, if you access a reply form the "Replies" tab, in the popup that opens you don't get to see the user's avatar, just the placeholder. In the same view, if you click the dropdown button near the username, the popover doesn't have the avatar image either.

**Comment by mcifani** [comment]
Thanks @dragosroua good find will correct shortly.

**Comment by dragosroua** [comment]
Thank you!

**Comment by roadscape** [comment]
It seems this behavior was fixed when Userpic was added to FullPost
