### ISSUE TITLE
on post page load, preload author avatar image in the size used on the author-additional-info popover so it doesn't have to load/lag when opening the popover

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1186]

**Comment by roadscape** [comment]
Is the lag still significant?

**Comment by pkattera** [comment]
I don't believe we show the author additional info popover anywhere on the site at the moment, so I'm closing this issue for now.

**Comment by Smittyvb** [comment]
![image](https://user-images.githubusercontent.com/10530973/46561759-11f33a00-c8c7-11e8-990a-46a16e56d911.png)
Isn't this the author popover? I can see it.
