### ISSUE TITLE
The instructions in  README.md seem really out of date now

### ISSUE THREAD

**Issue by neoxian** [steemit/condenser#1188]
You've updated node to 7.5.  The readme still talks about version 6.

No mention is made of yarn.  

Is Sqlite needed now?

**Comment by sneak** [comment]
The Dockerfile is authoritative, and it uses 7.5.

It also uses yarn. 

sqlite is optional. It's used for the service's database in the event you don't need/want mysql - the ORM is agnostic. It's the default if you don't specify a mysql server in the database URL.

We could certainly do with a comprehensive review of our documentation. Send us a PR? :)

**Comment by neoxian** [comment]
Well I can't get it to run in the first place, because I don't know what I'm doing.
 
I do this:

docker pull steemit/steemit.com

docker run --name steemweb -p 8080:8080 steemit/steemit.com

Then browse to localhost:8080

The website does come up, but then I can't logon, it hangs on the Login screen.

Also I see this on the console.
Error in /page_view api call 1588383e332af6eb5126672004 SQLITE_ERROR: no such table: pages

**Comment by mcifani** [comment]
You will need to run the migrations, which are noted in the readme.  For your reference:  Run 'sequelize db:migrate' in db/ directory.

**Comment by sneak** [comment]
@mcifani This is actually a bug; on sqlite init with a new file it should run them automatically. I had this code in and forgot to move it to this branch. I will get this sorted. @neoxian you did exactly the right steps, this is our bug and I will sort it out Monday or Tuesday for you.

**Comment by sneak** [comment]
This is actually two bugs because the homepage should degrade gracefully even with no sqlite/mysql/db server available at all.

**Comment by neoxian** [comment]
Thank you!

**Comment by neoxian** [comment]
It's been months later and I'm still getting this error:
Error in /page_view api call 728f4fcf4f87899aa179c06830 SQLITE_ERROR: no such table: pages

**Comment by jredbeard** [comment]
@neoxian you will receive such an error message if you are not running a sql instance for it to connect to. If you are, then you can specify it like this when running the docker image:

`docker run -it --name steemit --env SDC_DATABASE_URL="mysql://user:pass@localhost" -p 8080:8080 steemit/condenser`

The software is designed to run alongside a sql instance, and even though it will work without one, you will see those error messages if not.

**Comment by neoxian** [comment]
Hi @jredbeard , thank you so much for your answer.  How do I run that sql instance, is there a docker file or instructions for that?  Thanks again.

**Comment by jredbeard** [comment]
@neoxian - yes, there are instructions in the readme for that and as far as I know should still be accurate. Remember to run sequelize.

Also, just to mention, at the time you originally posted this there was a bug but it's been resolved - the reason you'd see that error message now is just simply because a sql instance is not available.

When I have time I'll make a PR for adding docker specific instructions to the readme.

**Comment by roadscape** [comment]
Has this been resolved?

**Comment by neoxian** [comment]
nvm install v6

npm install
npm install -g babel-cli

No, I still have no clue why the instructions refer to 6.  Still have no luck running Steemit.com from docker.

**Comment by jredbeard** [comment]
@neoxian - `docker run -it --name steemit -p 8080:8080 steemit/condenser` brings up a condenser instance for me without issue and should for anyone running docker - what happens on your end?

**Comment by neoxian** [comment]
docker: Error response from daemon: failed to create endpoint steemit on network bridge: failed to add the host (veth17d8e3f) <=> sandbox (veth198a88f) pair interfaces: operation not supported.

**Comment by jredbeard** [comment]
@neoxian I heavily updated the readme - it's completely up-to-date now and has a lot of new information. If you're still having trouble, please reach out to me directly (justinw on steemit.chat) and I'll be happy to assist.
