### ISSUE TITLE
"Decoded memo did not match" when trying to "Login"

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/condenser#1195]
After clicking "Login" from a clean session I am getting this:
```
app.56d5f0d0c24d2e569f3e.js:15 Decoded memo did not match (memo encryption is unavailable)
(anonymous) @ app.56d5f0d0c24d2e569f3e.js:15
```

I can log in successfully but I found this after complains of an user that is unable to log in from Firefox, but neither I nor other users was able to reproduce his issue yet.

**Comment by roadscape** [comment]
@jcalfee could you pls remind me what's the state of encrypted memos?

**Comment by roadscape** [comment]
I believe this just stems from https://github.com/steemit/condenser/issues/98
