### ISSUE TITLE
California AT&T # cannot be verified for sign-ups...why?

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/condenser#1197]
>Hi, I'm trying to sign up for steemit but can't because steemit "Unable to verify phone, please try again later." I've tried several times with no success. My number is a California AT&T mobile number. Please help. Thanks.

Thank you for your support

**Comment by roadscape** [comment]
There have been a lot of updates to the signup system, if the issues have not been resolved please comment here or open a new ticket.
