### ISSUE TITLE
Steemit.com Markdown rendering adds line breaks on every newline

### ISSUE THREAD

**Issue by arhag** [steemit/condenser#12]
I find this very frustrating. In Markdown, I can add a single line break in my source text without triggering a new paragraph or a line break in the rendered output.

If I actually want a line break (but not a new paragraph), I need to add at least two spaces at the end of my line.

See [this post](https://steemit.com/test/@arhag/re-arhag-testing-tags-20160521t004125070z) and compare it to how it should be done on [steemd.com](http://steemd.com/test/@arhag/re-arhag-testing-tags-20160521t004125070z).

**Comment by roadscape** [comment]
This doesn't seem to be a concern any longer; feel free to comment if this is not the case.

**Comment by arhag** [comment]
It appears the discrepancy between steemd.com and steemit.com rendering for my example has been resolved, **but by now breaking steemd.com rendering**!

The Markdown specifications that I find on the internet say that if you have just a single newline (with at most 1 space at the end of the line) it will not start a new paragraph. 
The rendering on steemit.com (and apparently now steemd.com) does not follow that.
And apparently neither does GitHub's renderer. But try it out [here](http://markdownlivepreview.com/) and you can see what I mean. Check the difference between the two rendered paragraphs in the following Markdown code.
```
First line for the first paragraph ends with only one space after the period. 
This is the second line in the Markdown source and it ends with no space after the period.
This is the third line of the Markdown source and it is still part of the first paragraph.
 
This is the first line for the second paragraph (there was at least one line above with at most only whitespace characters separating this paragraph from the first one) and it again ends with only one space after the period. 
This is now a new line representing the second sentence of the second paragraph and it ends with two spaces after the period.  
This is yet another line representing the third sentence of the second paragraph, but because the previous line ended with at least two space, this sentence is now separated from the previous one by a line break (represented in HTML with the br tag), even though they are both still part of the second paragraph.
```

Not doing it this way is limiting to people who prefer to avoid WYSIWYG (if that's what someone wants then they should be using a WYSIWYG editor rather than writing raw Markdown code). I am not able to break up sentences within a paragraph in my Markdown code (intended for Steem) into multiple lines for clarity of the writer/editor because those line breaks will show up in the rendered HTML on steemit.com. I am thus forced to put all text within a paragraph into a single line in my text editor. Using a different client to do the editing or submit the transaction doesn't solve the issue because I am still concerned about how my formatted text shows up to the vast majority of readers viewing my post through the steemit.com interface.

**Comment by roadscape** [comment]
This is one issue with markdown, there are so many configurations... it seems we have for now settled on something resembling GitHub-flavored Markdown (GFM).

Since we use markdown for comments on the site, it's important to use settings which are most intuitive for most users. And I imagine most users expect a newline to be a newline. 

I can't think of any simple compromises here, but suggestions welcome..

**Comment by arhag** [comment]
I can't think of simple compromises either. I guess the only long-term general solution (not a priority for now) I can think of is to allow different rendering engines for posts and specify which one should be used in the comment's JSON metadata. For example, you can have pure (sanitized) HTML with no Markdown processing at all, a Markdown render with a configuration that fits well with those who write/edit in raw Markdown (meaning line break behavior described above), a Markdown render with a more user-friendly configuration (like steemit.com's current Markdown configuration), a reStructuredText render, and whatever future rendering engines / configurations the Steem community wants to support in the future.

**Comment by sneak** [comment]
> Since we use markdown for comments on the site, it's important to use settings which are most intuitive for most users. And I imagine most users expect a newline to be a newline.

Disagree strongly.  If we're using Markdown, users can expect Markdown. Markdown says two newlines is a paragraph break (so does life).  This is how reddit (and every other user-facing markdown editor) works.

**Comment by chpio** [comment]
We could also add an additional option section to all posts, which would allow "advanced" options to be set by the user.

**Comment by chpio** [comment]
Anything new on this one?

**Comment by pkattera** [comment]
I agree with sneak, that it should have been implemented as per the markdown spec.

However, now that we've kept the newline = newline implementation for so long (similar to Github), we should keep it as is for now because people who've been using our markdown editor for the last two years will now have this behavior as their expectation. 

Closing this issue for now.

**Comment by sneak** [comment]
Everyone seems to think that a markdown editor is a disadvantage. I don’t agree, but whether it is or isn’t: only having a markdown editor that is out of spec and doesn’t work right is worse than only having an in-spec markdown editor.
