### ISSUE TITLE
Make pre-payout estimate visually indicated as such

### ISSUE THREAD

**Issue by thrize** [steemit/condenser#1211]
[I explained to a newbie yesterday](https://steemit.com/steemit/@reveurgam/how-confusing-upvoting-vs-views#@personz/re-reveurgam-how-confusing-upvoting-vs-views-20170224t035810984z) how no money is "taken away" from people by downvoting since before payout this is potential payout and an estimate.

Another poster [mentioned it today](https://steemit.com/steemit/@kevinwong/just-another-topical-remark-about-downvotes-bonus-a-survival-guide-for-steemians), so I though the payout should probably be indicated as an estimate.

This could either be with coloring, or with the addition of ```est.``` before the dollar sign. But there is probably another better idea out there, nothing is coming to me unfortunately.

Counter argument is that I suspect an indication was purposely left out so as not to devalue the prestige of the value on one's post climbing. But in my opinion addressing the confusion trumps this.

**Comment by TimCliff** [comment]
Hi @thrize - It is a good suggestion, but this is not the place to make enhancement suggestions. Please review the <a href="https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md">guidelines for contributing to the GitHub repository</a> before creating issues.

**Comment by thrize** [comment]
My apologies! 🙂   I actually did read it recently but it completely slipped my mind. I think it was actually in conversation with you 😳  Sorry again

**Comment by TimCliff** [comment]
No biggie. It would be a good thing to write a post about. If you get good feedback from the community, you can email it to @sneak. Would you mind closing the GitHub issue?

**Comment by thrize** [comment]
I think I will, thanks for the tip. Closing
