### ISSUE TITLE
UX Suggestion: Replace dollar estimation of post rewards with a visual indicator

### ISSUE THREAD

**Issue by robrigo** [steemit/condenser#1212]
As you may be aware, there has been a lot of drama clogging the front page of steemit.com with regards to flagging. Some of the flagging that is happening may be construed to be an abuse of voting power, however since one of the reasons to flag is subjective (disagreement on rewards), any flag can be considered valid.

Given the mechanics of vote flagging, perhaps the root of the issue is in fact that people are hurt by seeing their post reward drop by half, or a considerable amount. They may feel as if someone has a personal vendetta against them to deprive them of "their reward". 

I think the actual problem is how apparent this reduction in rewards is to the user. While showing the estimated dollar amount of rewards could give the site some of its "stickiness" (users love to see that number go up), perhaps it would be better for the psychological well being of the users to not so easily know their post reward (until it is paid and final). Instead, I propose that some visual indicator is added to each post that represents how much the post is valued vs. all other posts. This would still give the ability for users to see how well their post is doing in relation to others, but could abstract away the dollars lost due to having less stake voting for your post (due to either other posts got voted on more or flags). 

As a simple example, maybe a little label where the dollar estimation is could go from blue to red (cold to hot), or something to that effect.

**Comment by thrize** [comment]
@robrigo I actually raised the same thing here #1211 but @TimCliff reminded me that [this isn't the forum for it](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md#enhancement-suggestions), need to post on steemit.

By the etiquette I think you should close this, see my ticket for the exchange there.

**Comment by robrigo** [comment]
I'm happy to work on the pull request if the devs want something like this. It's up to them at the end of the day how they wish to change the platform. I'm not going to spend time advocating for it on steemit.com unless there is at least some consensus from their team that it is worth pursuing.

Similar to how Bitcoiner worked on the feature to split resteems into a separate tab that was never merged, I don't want to spend more time than necessary advocating for something if it doesn't at least get a hat tip from @sneak or the rest of the team.

**Comment by TimCliff** [comment]
@robrigo - not showing the payout amount for posts is going to be a very controversial change. I would suggest trying to get consensus from the community first before engaging the dev team. If it is something that the community wants done and you are willing to work on a pull request, then at that point I'd send an email to @sneak and see if it is something that Steemit would want changed. I suspect that you are going to run into a fair amount of resistance from people in the community though.

I would close the issue for now though and move the discussion to Steemit.com.

**Comment by sneak** [comment]
I personally like the potential payout display the way it is and think it adds value to the list view. People's butthurt over counting unhatched eggs will subside. I am pretty firmly of the belief that most site drama storms do not require that we respond with technical solutions and am biased substantially toward *not* allocating developer resources or attention to things that arise out of the periodic swirls of finger pointing. If we grant all site drama merit as evidence of a technical problem warranting a technical solution, we won't get anywhere meaningful until our team is a lot larger. I don't want that.

**Comment by robrigo** [comment]
@sneak point taken. I figured you guys would be in favor of leaving the payout display. And I understand the reasons for that- it's definitely an engaging part of the site. I'm sure a lot of traffic to the site is simply to check where the numbers are at. And there are bigger priorities to focus on.

There are pros and cons of making payouts more visible vs. more subtle. And you certainly can't please everybody. I suppose individual communities should implement this behavior as they wish on their own respective front ends to Steem.

Thanks for the replies @sneak and @TimCliff. I'll close this out for now.
