### ISSUE TITLE
"View the full context" link for a comment doesn't work as expected if parent comment is hidden due to low reputation

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/condenser#1213]
"View the full context" link for a comment doesn't work as expected if parent comment is hidden due to low reputation

Example:
https://steemit.com/steemit/@gtg/fun-with-flags#@gtg/re-skeptic-re-gtg-fun-with-flags-20170226t135925693z
This shows top level post as if link to a top level post would be used.
On a bottom of a page there's: 
`Comments were hidden due to low ratings. [SHOW]`
After clicking '[SHOW]' I get this comment displayed in a way I would expect it to be displayed initially, i.e. while using "View the full context" link for that comment.
Please note that parent comment is in that case still hidden with `[Reveal comment]` as option, which is OK.

Also I am not sure about view that we get for top level post: https://steemit.com/steemit/@gtg/fun-with-flags
i.e. not flagged comment from a positive reputation user is hidden only because it is a reply to a comment from low reputation user.

Edit: former probably works like that as long as comment payout is `$0.00` (despite low-power upvotes), so upvoting own comment would not mitigate that issue if user has not enough voting power to generate non-zero potential payout.

**Comment by roadscape** [comment]
I can see how this is confusing, though it's low-priority. IMO it's a fairly rare case that one would need to link to a comment within a zero-value thread. I fixed this case by upvoting your comment a few cents ;)

Currently, the comment display logic hides posts by a neg-rep user (at any level), and any/all of its children, unless there is a child with more than $0.02 payout. In that case, the neg-rep posts are shown, but collapsed. This reduces visual noise while ensuring anything with a pending payout is always displayed.

**Comment by roadscape** [comment]
As I said, I believe this is a rare case. With new APIs we might change handling altogether.
