### ISSUE TITLE
"Resteemed by" header not loading when user's blog is loaded directly

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1215]
If you go to your feed and one of your own posts was resteemed by people you follow, then it shows the "Resteemed by" header:
![image](https://cloud.githubusercontent.com/assets/20735105/23393238/1fadf100-fd47-11e6-88de-8d2c9e2e0cea.png)

If you then go to your blog after that, it still shows the "Resteemed by" header:
![image](https://cloud.githubusercontent.com/assets/20735105/23393258/43e06cc4-fd47-11e6-9816-8030bd831b37.png)

If you go to your blog page directly though (without first being on your feed), then it does not show the "Resteemed by" header:
![image](https://cloud.githubusercontent.com/assets/20735105/23393278/5ff85d86-fd47-11e6-9291-a7f1dfef31eb.png)

It seems like it should consistently show it, regardless of how the page is loaded.

**Comment by roadscape** [comment]
This has to do with the way we cache post data. Resteemed by should only show on your feed and not on your blog. But depending on the order in which you load the pages this extra data makes it in. IMO it's not worth fixing at this time as these API calls will be getting replaced.

**Comment by TimCliff** [comment]
Ok
