### ISSUE TITLE
Giving the active key log you out of your session

### ISSUE THREAD

**Issue by tibonova** [steemit/condenser#1219]
When I'm logged in with my _posting key_ and do a transaction that require my _active key_, steemit.com will log me out after the transaction. It happens when I set _stay logged in_ option, too. 

IMO, it happens because you don't support log-in with _active key_. The problem is I'm already logged-in with my _posting key_, and I want that the app keep me logged-in with that. 

OS: Ubuntu 14.04
Browser: Chromium 53.0

**Comment by sneak** [comment]
Good report, thank you. :)
