### ISSUE TITLE
Add functionality to claim reward balances

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#1221]
With HF17 we have separate rewards balances. We need to show them in the UI and allow users to claim them into their main balance. The claim operation requires only the posting key.

**Comment by ausbitbank** [comment]
I just claimed my first rewards - can this issue be closed now ?

**Comment by roadscape** [comment]
Closing this issue as a dupe of #1236 and created new issue #1311 for @ausbitbank's report
