### ISSUE TITLE
change flag icon to downvote

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#1222]
With communities, we'll have a dedicated non-consensus flag/report feature (in addition to a downvote function).

To prepare for this change and correct some misunderstandings in the short term, the flag icon should be replaced with a downvote (as it was originally).

**Comment by sneak** [comment]
I think the community one should be a "report", not a flag. I'm for leaving the flag in place as it is. A "downvote" means something else.

**Comment by pfunks** [comment]
In the meantime before some actual flagging functionality is added, the flag icon and word from the downvote recommendation guide can be removed to prevent further confusion about the nature of Steem downvotes.

**Comment by pfunks** [comment]
If communities aren't a feature that is coming soon it would be nice to end all user confusion about Steem downvotes right now.

**Comment by plink01001** [comment]
Are there plans to make any changes for this issue, or should it be moved to the `enhancement-review` category?

**Comment by plink01001** [comment]
Moved to enhancement-review
