### ISSUE TITLE
Transfer with wrong password needs a better error message

### ISSUE THREAD

**Issue by jcalfee** [steemit/condenser#1224]
Try to transfer with a posting key, the UI reports a transaction broadcast error appearing to be a bug.  It should probably report instead: incorrect password ...

**Comment by jcalfee** [comment]
It is probably safe to test the error message for `/missing .* authority/` and convert that to `incorrect password.`

**Comment by mcifani** [comment]
@jcalfee Agree. I'll tweak the message.  Putting to low priority/currently some higher pressing items atm.

**Comment by mcifani** [comment]
PR updates in https://github.com/steemit/condenser/pull/1344
