### ISSUE TITLE
User in China can't sign up https://steemit.com

### ISSUE THREAD

**Issue by abitmore** [steemit/condenser#1225]
This is a repost of https://github.com/steemit/steem/issues/908

>Hi, yesterday, a question in [china Quora](https://www.zhihu.com/question/48976357) is viewed by 71 thousands of people, many people want to sign up to https://steemit.com , but in Phone verification, it always show "Unfortunately, we don't yet have support to send SMS to your carrier, please try again later.",
>
>![image](https://cloud.githubusercontent.com/assets/15062548/23640988/e03ff7c6-032b-11e7-828a-3827fba888c0.png)
>
>hope deal this problem soon

**Comment by abitmore** [comment]
@cxgreat2014 actually this is not a UI issue either, but an operating issue. I guess best place to report this is the supporting system? Anyone have a link?

**Comment by cxgreat2014** [comment]
@abitmore I've sent contact@steemit.com an email before open issue...but it seems not work?

**Comment by sneak** [comment]
The country code erroneously got flagged for spam due to the big spike in signups.  We've un-flagged it and this should be resolved now.

**Comment by cxgreat2014** [comment]
Thanks a lot :+1: @sneak

**Comment by geromino24** [comment]
@sneak please un-flag also this country code: +7
I can't register on steemit, thanks
