### ISSUE TITLE
In wallet balance page, show "collecting X% APR" message by savings account balance

### ISSUE THREAD

**Issue by jcalfee** [steemit/condenser#1227]
The Steem Dollar APR also applies to savings account (in addition to the regular SD balance).  This should probably be shown in the text (by balance subject to 3 day withdraw) making it clear to the end-user: 

![image](https://cloud.githubusercontent.com/assets/204121/23663309/d5049e84-0317-11e7-8204-a0e3bd3ac3be.png)

https://github.com/steemit/steem/blob/3e46cf27e1c504ef512d61aeea182944e5dc6063/libraries/chain/database.cpp#L3503-L3505

**Comment by mcifani** [comment]
Updates in PR https://github.com/steemit/condenser/pull/1228
