### ISSUE TITLE
Denmark Phone Number SMS Verification Issue

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/condenser#1229]
A lady is having a valid cellphone number in Denmark yet it returns: "Unable to confirm phone number"
Is there a ban on Denmark phone numbers?

**Comment by TimCliff** [comment]
Hi @RenaudGagne - please read the <a href="https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md">guidelines for contributing</a> before opening GitHub issues. Issues should not be opened for login or account creation support. Please direct these questions to the #help channel of Steemit chat.

**Comment by sneak** [comment]
There shouldn't be a ban on Danish phone numbers, no.  Our SMS reputation provider isn't great, though - we've been having some issues with certain numbers.  We're currently overhauling the signup process to solve this very issue.

I suggest that your friend try again with a different number, or wait a week or two until we get the new signup system launched.  Sorry for the inconvenience, we know this is a major issue and are working on fixing it right now.
