### ISSUE TITLE
Long gone feature re-request: Direct links

### ISSUE THREAD

**Issue by pfunks** [steemit/condenser#1238]
A long time ago on Steemit, one could make a post containing only a link, and clicking the post link from a post listing would bring someone directly to that external link. This was Reddit-style. At some point, an icon indicating an external link was added to the post title.

A vocal minority spoke against allowing external links like this. I recall there was a misguided security concern about them. They were removed and the end result was a culture shift in Steemit posting. There was a move away from Reddit-style linking posts and a move towards long form blogging. Some users got confused and even believed that every post needed to be original content.

I think that there is room for Steemit's original design of allowing direct links, which wasn't explicitly "Reddit+crypto rewards" but certainly was reminiscent of it. smooth pointed out it's part of the reason for the anachronistic design. Reddit is successful partly because it's a platform where people can view and participate in it with a very small time commitment. If all there are on Steemit are multi-paragraph blogs, it's not a site people want to pop into on their lunch breaks, or while on a bus on their phones. Personal free time is a big factor in the "attention economy."

I'm requesting that condenser/steemit.com re-enable support for direct, external linking from post titles to expand its scope and depth of votable content.

**Comment by inertia186** [comment]
In addition, I would like to see direct links receive rewards consistent with curation amounts rather than the full author reward.  This will lead to an incentive to post original content directly as a post rather than merely link off site.

Maybe make it an option for the author.

**Comment by sneak** [comment]
As community discussion and voting is the central point of Steemit, it is unlikely that this feature will be reintroduced.  Such a post, when linked to, would offer no way to comment or vote on the top-level post.

Additionally, we don't want to alter the UX on the existing condenser interface very much at this time until we've synchronized the mobile effort with the pending communities release.  The problem that this solves (having to click again on the link for a link post) isn't really enough of a problem that needs solving when the solution actively discourages the primary mode of interacting with the site (voting and commenting).

**Comment by sneak** [comment]
@inertia186 The allocation of rewards is consensus code, and consensus code can't tell the difference between a "direct link" or a short post with a link or a big image that's a link, et c.  Whether or not a post is just a link post is a subjective evaluation and should be evaluated by voters.

If stakeholders don't want it rewarded as much, they will vote less or downvote it.
