### ISSUE TITLE
Missing in progress conversions in wallet

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1246]
This looks like a repeat of https://github.com/steemit/condenser/issues/896, but that issue looks like it is already closed.

I have these conversions in progress:
`get_conversion_requests timcliff`

[{
    "id": 13194,
    "owner": "timcliff",
    "requestid": 1489716972,
    "amount": "100.000 SBD",
    "conversion_date": "2017-03-20T14:16:18"
  },{
    "id": 13200,
    "owner": "timcliff",
    "requestid": 1489767452,
    "amount": "100.000 SBD",
    "conversion_date": "2017-03-21T04:17:45"
  },{
    "id": 13206,
    "owner": "timcliff",
    "requestid": 1489804380,
    "amount": "100.000 SBD",
    "conversion_date": "2017-03-21T14:33:24"
  },{
    "id": 13237,
    "owner": "timcliff",
    "requestid": 1489902083,
    "amount": "100.000 SBD",
    "conversion_date": "2017-03-22T17:41:33"
  }
]

Only the most recent one is showing up:
![image](https://cloud.githubusercontent.com/assets/20735105/24078516/c2ed09c8-0c3d-11e7-894f-bd3190621bb4.png)

The other three were showing up until today.

**Comment by mcifani** [comment]
@TimCliff This should be resolved now, I'm seeing 3 results returned in the API and reflected correctly in the UI(looking at your account for example).  If you could please confirm.   Thanks.  

<img width="548" alt="screen shot 2017-03-24 at 12 14 40 pm" src="https://cloud.githubusercontent.com/assets/1158463/24303226/9d0821be-108b-11e7-9b91-16c380caf111.png">
<img width="223" alt="screen shot 2017-03-24 at 12 13 47 pm" src="https://cloud.githubusercontent.com/assets/1158463/24303227/9edc48bc-108b-11e7-9478-ebd69afd9a13.png">

**Comment by roadscape** [comment]
When we upgraded our nodes to `0.17`, we started receiving more account history data. This fixes these concerns for most cases.

Relevant discussions:
https://github.com/steemit/condenser/issues/375
https://github.com/steemit/steem/issues/521

**Comment by TimCliff** [comment]
looks good now, thanks!
