### ISSUE TITLE
Disable the spellcheck attr on text inputs for the transfer fields.

### ISSUE THREAD

**Issue by aaroncox** [steemit/condenser#1247]
In #1139 and #1143, a number of attributes were added to help prevent mistakes when transferring steem. One more I believe should still be added:

`spellcheck="false"`

Some browsers are still autocorrecting and the polonium account struck again.

**Comment by pfunks** [comment]
Jeez, that's a shame. My issue recommended disabling that too, as per the reference link, but the issue was closed and it was not implemented like that.

**Comment by mcifani** [comment]
Thanks @aaroncox, definitely agree. Updates pushed. Spellcheck on those inputs will be disabled in our next UI release.
