### ISSUE TITLE
Market trade history does not refresh with new transactions

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1255]
After leaving the market page open for a few minutes, it still shows the same transactions

![image](https://cloud.githubusercontent.com/assets/20735105/24177509/09617418-0e71-11e7-8f9d-341b3c058f05.png)

After manually refreshing the page it shows:
![image](https://cloud.githubusercontent.com/assets/20735105/24177521/20dd0a94-0e71-11e7-9f77-539ba15cc0a7.png)

**Comment by roadscape** [comment]
Can't replicate this. Are you logged in when this happens?

**Comment by TimCliff** [comment]
Yes. Using Firefox.

**Comment by roadscape** [comment]
I can replicate this in Firefox. However there are no errors in the console.

**Comment by roadscape** [comment]
Probably has something to do with Firefox's date handling
