### ISSUE TITLE
Warn about fully powering down disabling an account

### ISSUE THREAD

**Issue by pfunks** [steemit/condenser#1263]
I've been seeing an issue come up lately now that we're 13 weeks past December 6th. People power down their accounts' full amount of STEEM and then are unable to transact. This is taking people by surprise and it does seem unintuitive especially without any warning of the potential for this happening. It takes manual intervention from another account to power the accounts up so they can transact again.

 I'm not sure what would be the best way of tackling the issue, but the minimum solution would be a warning about it in the power down transaction dialog.

**Comment by roadscape** [comment]
I presume this only affects inactive accounts, as even a few cents of rewards would be enough to transact. Rather than a warning, we could just subtract e.g. 0.0001 VESTS from withdraw amount, or just write a bot that tops off accounts with a fraction of STEEM when they reach this condition.

**Comment by roadscape** [comment]
There's currently only 35 accounts with no vests and a value of more than $1, so the ideal approach would be a bot rather than tweaking withdraw amounts or adding more warnings to the UI.

**Comment by abitmore** [comment]
Check how many accounts have `to_withdraw - withdrawn == vesting_shares`.

**Comment by roadscape** [comment]
656 accounts, ignoring ones with less than 10 STEEM and 1 SBD.

**Comment by pfunks** [comment]
It's an issue, and it won't stop being an issue. 

![image](https://cloud.githubusercontent.com/assets/22420130/24592635/7f481dd6-17df-11e7-9f04-c040ed98ab53.png)

![image](https://cloud.githubusercontent.com/assets/22420130/24592648/b569cedc-17df-11e7-84da-ede3a48a3057.png)

![image](https://cloud.githubusercontent.com/assets/22420130/24592653/ce66b490-17df-11e7-98b3-bf14356c664c.png)

![image](https://cloud.githubusercontent.com/assets/22420130/24592657/e8c5490a-17df-11e7-9f81-3797e249f7ff.png)

![image](https://cloud.githubusercontent.com/assets/22420130/24592663/fc54245a-17df-11e7-9385-b7b37218deb7.png)

And these are just the people who seek help on chat, and copied the error message. This is an issue that could hurt user retention and possibly make people get confused and think they got banned or something.

One potential solution is to dynamically adjust the vesting amount when powering down to leave 5-10 SP in an account.

**Comment by FedericoPistono** [comment]
I had this very issue. 25,000+ STEEM powered down, wasn't able to do anything. No posting, no voting, no transferring, nothing.

Huge bummer.

**Comment by pfunks** [comment]
@FedericoPistono is a perfect example of what I talked about above. What if he didn't come into steemit.chat and ask for help? He might assume the whole thing was a scam and be turned off the platform forever. I can't imagine this would take a huge amount of work to implement a solution here. It would be as simple as subtracting 15000 VESTS from the powerdown total.

**Comment by sneak** [comment]
@pfunks cryptocurrencies have risk, especially technical risk. simply being not a scam is sufficient for us—as pointed out above this isn't an issue affecting very many people. I fielded a support question about this recently too, it was no biggie.

We have some planned changes to the blockchain that will probably permit a tiny amount of bandwidth to accounts even with 0SP. It's on our radar.

Regardless, this isn't a condenser bug or feature request, so I'm closing this.

**Comment by pfunks** [comment]
It's a bug if people can't use the website due to poor implentation of the power down feature, with a fix being not technically complicated at all. Saying "blockchains have risk" is a cop out.
