### ISSUE TITLE
Unable to complete phone number verification

### ISSUE THREAD

**Issue by conman1136** [steemit/condenser#1269]
I have tried 2 different cell numbers.   I have tried using the format xxx-xxx-xxxx and xxxxxxxxxx.

No matter what, I get this error: "Unable to verify your phone number. Please try a different phone number."

I sent an email to contact@steemit.com and have not heard back yet, so I figured I would reach out here.

Thanks!

**Comment by TimCliff** [comment]
Please try out the help channel in Steemit.chat.

**Comment by roadscape** [comment]
@conman1136 try again, we have adjusted phone verification. Please re-open and share your country code if issue persists.

**Comment by Kakerate** [comment]
I am unable to use my phone number as well. Steemit doesn't seem very future - proof if somebody who used to have your phone number can deny you access to an account.

**Comment by thomxo** [comment]
Got the same problem, Country Code 49,
my number is 1 digit too long for the input to let me go to the next step,
it's 49-1511-xxxxxxx

**Comment by lenovouser** [comment]
Same issue.

`+49 151 xxxxxxxx`

**Comment by jnordberg** [comment]
We are aware of this issue and working on a fix, thanks for the reports.

Refs https://github.com/steemit/faucet/issues/195

**Comment by szczepanbarszczowski** [comment]
Same issue here `+48 574 xxx xxx`

**Comment by TimCliff** [comment]
Please ask for help in the help channel of steemit chat.

**Comment by pvaghasiya** [comment]
same issue here country code +91.

**Comment by tusharbjobs** [comment]
Hello, is this resolved?

I still get the same error for the Indian number which is valid and working to date.

Thought of checking since this seems to be a very old issue.
