### ISSUE TITLE
Posting interface "Editor" mode is broken

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1272]
The editor mode is not working correctly. One example is if you type text, then put the cursor in the middle of the text, then hit backspace - it backspaces the last character and not the one where the cursor is. 

Here is the post where it was reported by a user:
https://steemit.com/bug/@whatsup/bug-report-steemit-editor

**Comment by roadscape** [comment]
Still an issue?

**Comment by TimCliff** [comment]
Appears fixed. Thanks!
