### ISSUE TITLE
Mobile Glitch - Need to click the upvote button twice (iPhone)

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1273]
When clicking the upvote button on my iPhone, the vote slider does not show up the first time I click on the upvote button. When I click it a second time, it shows up.

**Comment by mcifani** [comment]
@TimCliff Testing on Iphone6s, safari, no issues.  I'll go through further testing with browser stack. Can you please tell me your model, browser, etc. Thanks.

**Comment by TimCliff** [comment]
I'm using iPhone 5s. Sorry, I'm a stupid user when it comes to my phone. Not sure how to check safari version.

A lot of users that I talked to are reporting similar issues.

One on Mac os 10.9/safari and IOS safari said they experienced intermittent issues. Some are unable to vote at all.

**Comment by mcifani** [comment]
Thanks @TimCliff newer devices should be fine, will be updating for potential bottlenecks on older ones.
