### ISSUE TITLE
Wallet Savings implies STEEM balance earns interest

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1274]
The wallet savings stores both STEEM and SBD. If a user stores STEEM in their wallet, the UI seems to imply that it earns APR too.

![image](https://cloud.githubusercontent.com/assets/20735105/24404535/829497fa-1387-11e7-8671-6dbcd4614662.png)

**Comment by mcifani** [comment]
Updates in PR https://github.com/steemit/condenser/pull/1275
