### ISSUE TITLE
sorting (i.e. new/hot/trending) doesn't work as expected for tags/categories

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/condenser#1276]
some people complain about new behavior on steemit.com  related to tags/categories
previously to find `new` posts in `#health`
one would click on the right on `#health` category
then on top on `new`

currently when clicking `#health` shows `trending` `#health` by default
but then when clicking on `new` we get all `new`, i.e. not `#health` `new`

(way to get `new` from `#health` is to click `new` and then `#health`)

**Comment by roadscape** [comment]
Bug was introduced in https://github.com/steemit/condenser/pull/1267
