### ISSUE TITLE
Promoted Page Showing Posts Past 24h Payout Window

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1278]
I'm not sure if this is a feature or a bug, or a condenser/steem issue - but the promoted page is showing posts that are past the 24 hour payout window. 

![image](https://cloud.githubusercontent.com/assets/20735105/24436839/50e1b7c0-1403-11e7-93fb-659b0978067c.png)

**Comment by roadscape** [comment]
This behavior is expected, when we switch to 7-day payouts it will not be an issue.
