### ISSUE TITLE
After 2-3 nesting comments the comment disappear  

### ISSUE THREAD

**Issue by liondani** [steemit/condenser#1292]
It appears again  only when refreshing/reloading the page

***EDIT** same with delete comments! After deletion they don't disappear.Only when you refresh/reload the page.

Linux Mint vs Mozilla Firefox

![screenshot from 2017-03-31 01 30 51](https://cloud.githubusercontent.com/assets/6908400/24529022/f524fed2-15b1-11e7-8330-b9081a1bb59b.png)

**Comment by ausbitbank** [comment]
I just replied to a single comment (only one in the thread), and when I submitted my reply it disappeared until I refreshed the whole page. This is new since the last HF..

**Comment by liondani** [comment]
THIS ^^^
