### ISSUE TITLE
Welcome screen still shows up 

### ISSUE THREAD

**Issue by svk31** [steemit/condenser#1294]
The first time I open steemit.com I still always get this welcome screen:

![image](https://cloud.githubusercontent.com/assets/6890015/24539684/f6295902-15ef-11e7-9d52-b20c4f966e99.png)

I suggest storing a boolean in localStorage so it gets hidden for users who've successfully logged in from that particular browser.

**Comment by mcifani** [comment]
@svk31 There's logic in place to not persist the banner.  What's your stack/browser setup it happened on?  Curious if there's an edge case.  Thanks.

**Comment by svk31** [comment]
Happens to me both in Firefox and Chrome on Ubuntu. Pretty sure it happens on Windows Chrome too, can check later.

**Comment by mcifani** [comment]
No issues on Windows Chrome/57 & Firefox/52.   Will test on a Ubuntu box.

**Comment by mcifani** [comment]
@svk31 Tested on Ubuntu 16.04, no issues.  Seems like it could be isolated with some settings you might have.

**Comment by svk31** [comment]
Also happens to me in Windows 10 on Chrome. Tried Internet Explorer and there it doesn't happen.

**Comment by plink01001** [comment]
This seems resolved. Please re-open if it is still an issue.
