### ISSUE TITLE
Dynamically collapse comments, condense the comments UI

### ISSUE THREAD

**Issue by sens2** [steemit/condenser#1298]
Currently, all comments are visible upto 6 threads, and beyond that things are collapsed. Furthermore, expanding takes you to a different page without enough context. 

This design is not scalable at all to prepare for thousands of comments. I'm sure this is just a placeholder, but thought it would be an important reminder. Reddit does this well, so there are plenty of things to take from there. We need - 

1) Condensed UI - currently there are massive indents between each tree, which means you can only fit 6 in the same page. Reddit can fit in 12 without any readability issues.
2) Low payout comments are collapsed within each tree - Currently there may be high payout comments being hidden if they are beyond the 6th tree, whereas a comment with zero votes on the 1st tree is visible on top. This should be fixed so high payout comments are visible irrespective of which tree they belong too, and low payout comments are collapsed. 
3) Expand in-line - Pretty obvious, we don't need a new page to expand threads. 
4) Improving on Reddit's system, I'd like to see a dynamic expanding system which works beyond the 12 threads - after that expanding should not take you to a new page, but instead collapse previous threads in-line and expand the 12+ threads. 
5) A more obvious visual aid to indicate which tree the comment is on. The dots are OK, but won't be very effective once there are hundreds of comments. Reddit has a new alternate shadowing UI, but I feel there could be a better solution here. 

I'm sure many of these are in the works, but this is an important reminder - these are critical for driving serious engagement.

**Comment by roadscape** [comment]
We are not ready to revamp the comment layout but your points have been noted. Thanks.
