### ISSUE TITLE
Issue with vote dropdown on comments when visited via profile > replies tab

### ISSUE THREAD

**Issue by ausbitbank** [steemit/condenser#1299]
Instead of the vote dropdown showing usernames, it simply says "... and 1 more" with no usernames.

![image](https://cloud.githubusercontent.com/assets/1692203/24578325/25cecfa8-172a-11e7-88b3-f78b97c0762f.png)

To reproduce it, go to a users profile, click replies , then search for a comment with a single upvote and click its title to make the full text load in the frame. Then click the "vote" dropdown , and where you would normally see the usernames that voted you'll just see ".. and 1 more"

I can't reproduce the bug when I view comments via any other path, this seems to be specific to coming via the replies tab.

**Comment by roadscape** [comment]
This bug was introduced when vote pruning was added to address response size.

**Comment by plink01001** [comment]
Has this been addressed / can this be closed?

**Comment by plink01001** [comment]
This appears to be addressed. Please re-open if still an issue.
