### ISSUE TITLE
Tag restrictions not enforced when using #tags in post body

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1301]
There are restrictions placed on tags when entering them at the bottom of the post editor

![image](https://cloud.githubusercontent.com/assets/20735105/24581861/119b1686-16e9-11e7-9281-2111696253a3.png)

![image](https://cloud.githubusercontent.com/assets/20735105/24581863/1f521b80-16e9-11e7-9da0-567ba47ef1ef.png)

If users use a #tag in the post body, the same restrictions are not enforced and it links the tag to the post:

![image](https://cloud.githubusercontent.com/assets/20735105/24581872/4c2b5ac2-16e9-11e7-90b5-69c286982abf.png)

**Comment by roadscape** [comment]
Hm, it would be kind of awkward to restrict hashtag length in content body. On the backend they're all getting truncated anyway.

**Comment by TimCliff** [comment]
I agree that it wouldn't make sense to restrict them in the content body. What is happening with the tags that are showing up in the UI for the post tags? Would it be more correct to show the truncated values there too, if that is what is getting saved on the back-end?

**Comment by roadscape** [comment]
I should clarify that when I say they're getting truncated, it's just for indexing purposes. The full value is stored but only 24-32(?) chars are indexed.

**Comment by TimCliff** [comment]
Seems like no change is needed. Closing
