### ISSUE TITLE
Tag page not updating or only counting first tags ?

### ISSUE THREAD

**Issue by Transisto** [steemit/condenser#1302]
#steemdev has a lot of posts but is not in https://steemit.com/tags

**Comment by roadscape** [comment]
There is a bug in the tags plugin: https://github.com/steemit/steem/issues/798

**Comment by Transisto** [comment]
This is still an issue, there is a lot of activity in #steemdev but it's nowhere to be found.

**Comment by roadscape** [comment]
Tags plugin still broken.

**Comment by roadscape** [comment]
Tags API is now served by hive. Data served is slightly different but should be more consistent.
