### ISSUE TITLE
Offer hosting for avatar images in Settings page

### ISSUE THREAD

**Issue by pfunks** [steemit/condenser#1303]
Now that Steemit is hosting images for posts and comments, an option to host the avatar on the Settings page is intuitive.

**Comment by Gandalf-the-Grey** [comment]
(Until implemented, users can do that by themselves by including avatar image in their post and then re-using link)

**Comment by pfunks** [comment]
Yep, but it's clumsy.

**Comment by plink01001** [comment]
Issue is being worked on in https://github.com/steemit/condenser/issues/2430
