### ISSUE TITLE
Show "STEEM POWER" instead of "VESTS" in claim transaction history on wallet pages

### ISSUE THREAD

**Issue by pfunks** [steemit/condenser#1304]
The STEEM Power portion of claims are currently denominated in VESTS. 

![image](https://cloud.githubusercontent.com/assets/22420130/24596969/78b112c4-1808-11e7-88cb-801f19fa9cba.png)

**Comment by mcifani** [comment]
PR updates in https://github.com/steemit/condenser/pull/1305.
