### ISSUE TITLE
block crawlers on dev/stage env

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#1309]
we should use `<meta name="robots" content="noindex, nofollow, noarchive, nosnippet">` and `<meta name="googlebot" content="noindex, nofollow, noarchive, nosnippet">` when env var NODE_ENV is set to staging or dev

**Comment by roadscape** [comment]
Will be done in nginx

**Comment by jredbeard** [comment]
Resolved through sub_filter module in nginx (sdc-frontend repo) via setting NODE_ENV environment variable to 'dev' or 'staging'
