### ISSUE TITLE
Improve handling for user exchange transactions/typos

### ISSUE THREAD

**Issue by mcifani** [steemit/condenser#1313]

**Comment by Gandalf-the-Grey** [comment]
Adding well known status to exchange accounts + explicit transfer target could be enough to avoid such mistakes:
Transfer to: 
- [ ] User
- [ ] ~Trusted~ Well Known Exchange (then provide list of whitelisted)

It might be useful to not only whitelist well known exchanges but also quick and easy way to blacklist (in condenser config).That's in case of issues with an exchange ( security, maintenance ) or users (known fraud accounts)

**Comment by mcifani** [comment]
Thanks @ausbitbank @Gandalf-the-Grey - For now we are going to improve validations on the current transfer form without over-complicating the UI.  Users will receive warnings for possible phishing accounts(When entered).   If you have any bad actors you feel should be included in the list please update here.

**Comment by pfunks** [comment]
Not a complete list, but ones found using the list_accounts command

"bitterx",
"bittex",
"bittrax",
"bittre",
"bittres",
"bittrex"
"bittrex.com",
"bittrexe",
"bittrexx",
"bittrez",
"bittrix",
"bittrx",
"bitttrex",
"bitrex",
  "bitrexx",
"bitrix",
 "bitrrex",
  "bitrupee",
  "bitrx",



"poloiex",
  "poloinex",
  "polomiex",
  "polon",
  "poloneex",
  "poloneix",
  "polonex",
  "poloni",
  "poloniax",
  "polonie",
  "poloniec",
  "poloniee",
  "polonieex",
  "poloniek",
  "polonieks",
  "polonies",
  "poloniet",
  "poloniets",
  "poloniex.com",
  "poloniexcold",
  "poloniexe",
  "poloniexs",
  "poloniext",
  "poloniexwallet", <- not malicious, Poloniex owns the (BTS @poloniexwallet) key, but still a blackhole of funds.
  "poloniexx",
  "poloniey",
  "poloniez",
  "poloniiex",
  "poloniix",
  "poloniks",
  "poloniox",
  "polonium", <- Apple autocorrect for poloniex
  "polonix",
  "polonniex",
  "polooniex",
"pooniex",
 "poooniex",

"blocktardes",
"blocktrade",
"bocktrades",

"changelly.com",
"changely",

"shapeshif",
"shapeshift",

"livecoin.net",

**Comment by mcifani** [comment]
Thanks @pfunks for the list, appreciated. Please open another ticket for adding future abuse accounts. Closing ticket/new warning will be up in next release.
