### ISSUE TITLE
Claiming rewards cause visual glitch in wallet history

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/condenser#1316]
When I claimed rewards on my wallet page, it appeared in History with memo duplicated from previous transaction.
![claiming_rewards_history_glitch](https://cloud.githubusercontent.com/assets/6341057/24848984/c2f52318-1dc9-11e7-875b-f81e5b1acd97.png)
It is just a visual glitch, i.e. after refreshing extra memo is gone.

**Comment by lukestokes** [comment]
I noticed this also:

![image](https://user-images.githubusercontent.com/344748/27100736-b288a542-5044-11e7-8c79-7e4dac784465.png)

Glad to know a simple refresh clears it up.

**Comment by sneak** [comment]
@TheIntrnet this might be a good one to track down

**Comment by lukestokes** [comment]
The pattern, I think, is to claim rewards right after doing a transfer with a memo. Just saw it again tonight:

![](https://content.screencast.com/users/lukestokes/folders/Jing/media/ae9e1433-6203-4d31-82e8-11401972dc93/00003602.png)

**Comment by plink01001** [comment]
This seems to be resolved. Please re-open if it is still an issue.
