### ISSUE TITLE
Wallet confusion.

### ISSUE THREAD

**Issue by TheDegenSloth** [steemit/condenser#1318]
Wallet has permissions and password which most users would look for these under settings.

Permissions and password should be moved to the settings page.

**Comment by TimCliff** [comment]
@TheDegenSloth this seems like a good change to submit a pull request for. You could email @sneak first though to see if it is something that Steemit is on board with.

**Comment by TheDegenSloth** [comment]
Whats his email?

**Comment by TimCliff** [comment]
Sneak@steemit.com
