### ISSUE TITLE
Delegated sp link

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/condenser#1335]
Can we make a link from the delegated sp in a wallet to whomever has delegated it so that we can see who is backing whom?

**Comment by TimCliff** [comment]
Good suggestion, but again this is not the appropriate place to make these suggestions. @sneak to close.

**Comment by FreeBornAngel** [comment]
Remind me again, where do I get these issues resolved?

**Comment by TimCliff** [comment]
https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md

**Comment by FreeBornAngel** [comment]
Thanks, I'll try to keep that in mind,...
