### ISSUE TITLE
Steemit Developers

### ISSUE THREAD

**Issue by madorian** [steemit/condenser#1336]
I have a little trouble finding where Steemit development occurs?

I mean, it can't be all in this bug tracker?;)

Is there some tag on Steemit, or a mailing list, web forum, chat room somewhere?

**Comment by TimCliff** [comment]
All of the changes are checked in to this GitHub repository. If you view the pull requests tab, you can see all of the changes.

There is also a separate repository for the Steem blockchain code.

**Comment by madorian** [comment]
I think you misunderstand me;). Where does discussion happen?

**Comment by TimCliff** [comment]
A lot of the discussions happen behind the scenes. Steemit employees make a lot of the decisions internally. For discussion with the community, the best place for those discussions is via posts on Steemit.

**Comment by TimCliff** [comment]
@sneak to close

**Comment by madorian** [comment]
A lot of the discussion happens behind the scenes, ok, but if a lot happens behind the scene, some has to happen in front of the scene. Where does this in front of the scene happen? Isn't there a public mailing list or something public where you can interact with developers? Is Steemit a closed secret society or something?

**Comment by TimCliff** [comment]
The community and development team interact via posts and conversions on Steemit.com.

**Comment by baroen96** [comment]
including the display log in in steemit condenser?
