### ISSUE TITLE
Users are unable to register via Steemit!

### ISSUE THREAD

**Issue by noisy** [steemit/condenser#1340]
I believe, this should be handled ASAP.

![selection_837](https://cloud.githubusercontent.com/assets/201263/25094187/3bdbb996-2396-11e7-890d-8ac920748e3f.png)

**Comment by TimCliff** [comment]
The issue is being worked on. Not a code issue though. @sneak to close.

**Comment by noisy** [comment]
@TimCliff before this issue will be closed, at least two things could be done to better handle this kind of situation:

* error handling (this kind of error message should never be displayed to end user)
* if the reason behind that issue was low amount of VESTS on particular account, some kind of notification system should sent high priority message to people, which could handle this before this become a real issue.

Those are just suggestions, but it is super unprofessional to welcome new users in such way like this. Users which encountered this error may never return :(

**Comment by TimCliff** [comment]
1. Agreed. Maybe a good idea to leave this issue open to improve the error message.
2. Yes, they are working on a solution to this.

**Comment by steevc** [comment]
The error messages in general are not useful to general users. There was one caused by system clocks being out of sync. It should suggest a solution. This particular issue is critical as we need the new users. Steemit could do with a status page so we know if there are current issues being worked on.

**Comment by noisy** [comment]
@TimCliff @mvandeberg @sneak @nedsteem

it looks like this problems is still occurring! People cannot register!
![selection_854](https://cloud.githubusercontent.com/assets/201263/25207400/95b4b510-256e-11e7-9d39-623e420232a6.png)

**Comment by TimCliff** [comment]
Thanks. I believe Steemit is already aware, but I let them know just in case.

**Comment by MELCHEZEDEK776** [comment]
Storage password phone:
R.BT7R-LHBR-NGRS-YZZ2

**Comment by noisy** [comment]
Is this still the same?
![selection_868](https://cloud.githubusercontent.com/assets/201263/25319699/d54f7afe-28a0-11e7-91ae-1c6cd3ca86fa.png)

**Comment by TimCliff** [comment]
I know Steemit is aware of the issue, but I don't believe it has been fixed yet. Sorry, I don't have an eta.

**Comment by sneak** [comment]
Fix to be rolled out today.  Apologies for the confusion.

**Comment by noisy** [comment]
:+1:

**Comment by richardcrill** [comment]
Must not be fixed! I just tried to sign my friend up. He used his android phone and got the Assert Exception error. That was after about the 10th convo I had with him. He was considering investing!!! Hope this is resolved quickly!

**Comment by steevc** [comment]
The Steem account needs topping up again as it has delegated all its SP.

https://steemit.com/@steem/transfers

We've had about another 250 users in the last 24 hours and they get 106 SP delegated to them. It will get interesting if we suddenly get a flood of new users. I assume the Steemit account needs to transfer when Steem is running low. Is this automated?
