### ISSUE TITLE
Can't receive SMS when signing up.

### ISSUE THREAD

**Issue by grammyleung** [steemit/condenser#1343]
Hi,

I failed in receiving SMS while registering as a new member, with both USA's and Hong Kong's phone numbers, though I passed the step of email confirmation, with the same email with this Github account.

Jacob Gadikian told me that posting an issue here might work.

Thanks,
Grammy

**Comment by roadscape** [comment]
There have been a lot of updates to the signup system, if the issues have not been resolved please comment here or open a new ticket.

**Comment by nshadab** [comment]
i am facing the same problem, no SMS arrived. Trying for the last 8 days. Resent several times but no luck.
