### ISSUE TITLE
Unclaimed rewards: undefined

### ISSUE THREAD

**Issue by noisy** [steemit/condenser#1345]
SteemPower value is not displayed correctly by notification.

![selection_843](https://cloud.githubusercontent.com/assets/201263/25112429/5554c3f8-23f1-11e7-8646-011967ad49e6.png)

After I claimed everything, my logs shows:

> Claim rewards: 0.017 SBD, 0.000 STEEM, and 0.125 STEEM POWER

----------

PS. What will happen if I will no claim rewards for a long time?

**Comment by TimCliff** [comment]
There is already a pull request for it here:
https://github.com/steemit/condenser/pull/1342

They will just sit there in your account until claimed.

**Comment by mcifani** [comment]
Closing ticket it's been resolved.
