### ISSUE TITLE
More typo exchange Steem accounts

### ISSUE THREAD

**Issue by pfunks** [steemit/condenser#1346]
New issue as requested by @mcifani in #1313 

"plolniex",
"ploniex",
"plooniex",
"poloex",
"oloniex",
"ittrex"
"pooloniex",

### Exchange accounts owned by Steemit but not active

coinbase, bitfinex, bitstamp etc. Sometimes people send to these accounts thinking they can cash out directly. Steemit Inc should have the full list of placeholder accounts owned.

### Exchange accounts not owned by Steemit Inc

bitmex
btc-e
huobi
hitbtc <- looks like at least one person has transferred STEEM to this one 

And probably more

**Comment by mcifani** [comment]
Updated in PR https://github.com/steemit/condenser/pull/1355
