### ISSUE TITLE
Being logged out

### ISSUE THREAD

**Issue by TheDegenSloth** [steemit/condenser#1361]
More times then not when i use my active key for anything i get logged out.

edit:
I think i found the problem, well when it happens.
On page load of new a refresh you're logged out instantly.

Currently using firefox on windows 10 it also happened on chrome as well.

**Comment by TheDegenSloth** [comment]
I think i found the problem, well when it happens.
On page load of new a refresh you're logged out instantly.

**Comment by roadscape** [comment]
Dupe of #1219
