### ISSUE TITLE
What is a LICENCE for this repository?

### ISSUE THREAD

**Issue by noisy** [steemit/condenser#1365]
lately, steemit/steem changed licence to MIT. I am wondering what is licence for condenser?

There reason why I am asking, is because Polish social media site http://strimi.pl/ is going to be migrated on to Steem. The fastest way would be to use some parts from this repo.

and... BTW, where i repository of website steem.io (and what is licence of it)? Polish community would like to translate this into Polish, but we cannot find the repo.

**Comment by pfunks** [comment]
Good catch. Steemit Inc announced the license was changed to MIT, but there is no LICENSE.md anywhere. The only place I could find it in the repo is here: https://github.com/steemit/condenser/blob/master/package.json#L21

@roadscape, could a LICENSE.md file be added?

**Comment by jredbeard** [comment]
The license for condenser has been MIT all along. It's located in the 'doc' folder. https://github.com/steemit/condenser/blob/master/doc/LICENSE.md

**Comment by jredbeard** [comment]
And @noisy I'll see if I can get the steem.io source into a public repo in the near future. Afaik there shouldn't be any problems doing that.

**Comment by jredbeard** [comment]
@noisy github.com/steemit/steem.io is now public and has an MIT license as well

**Comment by jredbeard** [comment]
Sorry, I spoke prematurely on the licensing of steem.io. The repo is publicly viewable.

**Comment by Mowilimi** [comment]
So what will be the license now?

2017-04-27 22:03 GMT+02:00 Justin Welch <notifications@github.com>:

**Comment by sneak** [comment]
The license for condenser remains MIT. The content on steem.io is not licensed for external use (all rights reserved).

**Comment by sneak** [comment]
Be advised that the current steem.io site is pretty significantly out of date and is presently being completely overhauled from scratch. :)

**Comment by noisy** [comment]
> Be advised that the current steem.io site is pretty significantly out of date and is presently being completely overhauled from scratch. :)

Polish community want to focus on translations, so could you elaborate, whether everything will be changed (layout, description or maybe even whitepaper will be updated), or changes will be only about layout?

I do no see other branches than master on https://github.com/steemit/steem.io

**Comment by sneak** [comment]
Give us 2-4 weeks to get the new site up. It's a new repo, not on a branch, and will replace the current repo.

The whitepaper update is a separate project for now, and that will be released within 4-8 weeks.
