### ISSUE TITLE
Phone verification rejects UK Lycamobile numbers

### ISSUE THREAD

**Issue by 0x27** [steemit/condenser#1370]
Been trying to register an account, however, the site seems to reject my number (Unable to verify... error). 

Steps to reproduce (assuming a valid lycamobile uk number is available).

1. Select "UK" from dropdown menu.  
2. Put in number in format "7424-XXXXXX" or "7424XXXXXX".  
3. Shake head in frustration, try again, fail, and make github issue ;)

Email account used to register was (antispam_base64) ```ZGFycmVuKCkweDI3Lm1l```.

**Comment by roadscape** [comment]
There have been a lot of updates to the signup system, if the issues have not been resolved please comment here or open a new ticket.

**Comment by 0x27** [comment]
I managed to sign up with a different phone number and username in the end. Might try register a friend using a Lycamobile number at some point and reopen if issues continue :)
