### ISSUE TITLE
issues with account creation

### ISSUE THREAD

**Issue by guystyles** [steemit/condenser#1372]
Hello, I was having trouble creating a steem account (@guystyles), getting the long error message that was posted earlier.
I looked at the code, and figured steemit was just low on steem, waited 12 hours, and tried again with success.
Unfortunately, the password I had saved is not valid, _perhaps because I didn't refresh the browser before hitting submit._
Who do I talk to in order to get things straightened out? No info anywhere.
Maybe the create account should check the password field with the password being used before going ahead.

**Comment by roadscape** [comment]
There have been a lot of updates to the signup system, if the issues have not been resolved please open a new ticket.
