### ISSUE TITLE
Posts not editable after seven days

### ISSUE THREAD

**Issue by creatorguy** [steemit/condenser#1373]
In the run-up to HF17, content creators were promised that as part of that fork, the restriction on editing posts more than a month old would be lifted.

"We propose removing the restriction on editing of past posts. It is a user-interface responsibility to show revision history and enable restoration of unintentional changes made by compromised accounts." - quoted from the [**Steem 0.17 Change Proposal Introduction**](https://steemit.com/steem/@steemitblog/steem-0-17-change-proposal-introduction)

Instead of being lifted, that restriction is now even worse; posts are no longer editable after seven days...

As a content creator, I find this tremendously frustrating and restrictive. I and others would greatly appreciate it if the long awaited promise of edibility could be fixed and fulfilled.

You can contact me on Steemit itself or in the Steemit Chat as @creatr if you have any questions or concerns about this request. THANK YOU IN ADVANCE for your consideration.

**Comment by roadscape** [comment]
Related: https://github.com/steemit/steem/issues/1266

**Comment by TimCliff** [comment]
The steem issue has been closed, so #waiting-for-backend can be removed.

**Comment by roadscape** [comment]
Posts are editable 👍

**Comment by creatorguy** [comment]
Hey!
Just stopping by to say a hearty "Thank You" to everyone who had a hand in resolving this issue.
Your efforts have not gone unnoticed, and I greatly appreciate you! :D
