### ISSUE TITLE
Can't copy and paste from the site in the editor.

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/condenser#1375]
It gives a bunch of code.

I copy and paste quotes of what has been said, but all i'm getting in paste is code, and not the text I wanted to quote.

I guess that would be a feature if folks were cheating, but I am trying to build some community,...

**Comment by FreeBornAngel** [comment]
Some of it.

Version:1.0 StartHTML:000000239 EndHTML:000031064 StartFragment:000030888 EndFragment:000030950 StartSelection:000030888 EndSelection:000030950 SourceURL:https://steemit.com/ladiesonly/@freebornsociety/freedom-tuesday-next-tuesday  Freedom Tuesday, next Tuesday? â€” Steemit .Button__root___1t9vg {   display: inline-block;   margin: 0 5px 0 0;   padding: 3px 8px;   height: 30px;   line-height: 22px;   box-sizing: border-box;   background: none #fdfdfd;   background: linear-gradient(to bottom, #fdfdfd 0%,#f6f7f8 100%);   border: 1px solid #999;   border-radius: 2px;   color: #333;   text-decoration: none;   font-size: inherit;   font-family: inherit;   cursor: pointer;   white-space: nowrap; }  .Button__root___1t9vg:disabled {   cursor: not-allowed;   background: none transparent; }  .Button__root___1t9vg:disabled > * {   opacity: .5; }  .ButtonWrap__root___2qgcQ {   display: inline-block;   position: relative;   /* This ensures the popover will show on top of the editor. */   z-index: 10; }  .IconButton__root___2awWb {   padding-left: 3px;   padding-right: 3px; }  .IconButton__icon___2DdFx {   display: inline-block;   width: 22px;   height: 22px;   background-position: center center;   background-repeat: no-repeat;   background-size: 18px; }  .IconButton__isActive___2rZ4Z {   background: none #d8d8d8; }  .IconButton__icon-undo___2w6D8 {   background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0Ij48cGF0aCBkPSJNMTcuODU2IDI0YzIuNjY1LTQuODMgMy4xMTUtMTIuMTk1LTcuMzU2LTExLjk1VjE4bC05LTkgOS05djUuODJDMjMuMDM4IDUuNDk1IDI0LjQzNSAxNi44OSAxNy44NTYgMjR6Ii8

**Comment by roadscape** [comment]
The current WYSIWYG editor will need to be replaced.
