### ISSUE TITLE
Redeem rewards button overlaps rewards amount on mobile

### ISSUE THREAD

**Issue by jredbeard** [steemit/condenser#1381]
When viewing your wallet on mobile and you have pending rewards to redeem, the button to redeem overlaps the amount of rewards you will be redeeming:

![img_0505](https://cloud.githubusercontent.com/assets/23157604/25564894/15c5a696-2d8b-11e7-9bfe-127e9bc11f03.PNG)

**Comment by mcifani** [comment]
Fixes in PR https://github.com/steemit/condenser/pull/1396
