### ISSUE TITLE
Adjust waitlist/signup messages to be more accurate and less confusing

### ISSUE THREAD

**Issue by jredbeard** [steemit/condenser#1382]
Currently when signing up in the new approval list/pending flow you receive a message at the end of the process that says:

```
You've been added to the wait list and pending approval.

To process your account, you must validate your email by clicking the link in your welcome email.
```

This is confusing because the user has already received an email at this point that is actually titled `Welcome to steemit! Please confirm your email` - however, this is not the 'welcome' email they are actually waiting on once they are approved. The user may or may not have actually had to already confirm their email at this point, but if they did, then the message above is entirely incorrect - their email may have already been verified at this point and either way the wording of both the email and the signup message could be confusing (and/or inaccurate).

My suggestion would be to adjust the final signup message to something more like this:

```
You've been added to the pending approval list.

Please wait for a followup email to login to your account once approved.
```

In addition, the 'Welcome to steemit! Please confirm your email` should maybe say something about the manual approval process.

We should also consider possibly saying something about the approval process at the beginning of the process in case users don't read the final message about being in pending status - but adjusting the email and the wording of the message we already have may be enough.

In addition, if you attempt to sign up again after already being on the approval list, you receive a message saying you already have an account.

**Comment by steevc** [comment]
I see they changed the page to say "You will receive an email confirmation soon when you can log into
your shiny new account - usually less than one business day." I hope new users are being processed now. We were not getting any added for a few days.

**Comment by sneak** [comment]
fixed in #1395

**Comment by sneak** [comment]
@steevc we built the queue system first, i think the approval system goes live today or tomorrow. :D

everyone who is queued (and not a spambot) will get an account in the next day or two.

**Comment by sneak** [comment]
everyone who signs up is being added to the queue, none are lost.

**Comment by sneak** [comment]
@justinw please bias toward sending a PR versus filing an issue. copy changes are easy.

(i too started out by drafting an issue like this, then i realized that i have a text editor too)

**Comment by steevc** [comment]
@sneak thanks for the update. I can appreciate the need to deal with fake accounts. It's not an easy problem to solve. If I see anyone asking about this I'll let them know.
