### ISSUE TITLE
Scrolling on mobile has a buggy header nav

### ISSUE THREAD

**Issue by jredbeard** [steemit/condenser#1386]
When scrolling in article view on mobile, the header nav is buggy - it constantly repaints.

![image uploaded from ios 1](https://cloud.githubusercontent.com/assets/23157604/25565060/861d9c16-2d8e-11e7-9578-7d70df47af15.jpg)

**Comment by valzav** [comment]
It's a browser's bug/feature with fixed positioning, there is not much we can do about it.
