### ISSUE TITLE
Image upload instructions should be available when editing a post

### ISSUE THREAD

**Issue by jredbeard** [steemit/condenser#1403]
The 'select an image' link is only available on mobile when originally submitting a post, not when editing one.

**Comment by roadscape** [comment]
This applies to desktop too.

**Comment by quochuy** [comment]
Can't reproduce...
![Screen Shot 2019-05-10 at 9 36 13 pm](https://user-images.githubusercontent.com/310654/57524632-b95bb200-736b-11e9-82b7-3ae4bc150144.jpg)

**Comment by roadscape** [comment]
Thanks @quochuy, closing this!
