### ISSUE TITLE
Site is currently down!

### ISSUE THREAD

**Issue by TheDegenSloth** [steemit/condenser#1404]
Steemit.com is showing white pages and all indicators show its offline.

**Comment by TimCliff** [comment]
Thanks for the report. Steemit is aware and are working on it.

**Comment by TimCliff** [comment]
Looks like it is back up 😀

**Comment by TheDegenSloth** [comment]
Alright thanks for the update.

**Comment by sneak** [comment]
Fixed; sorry about that.
