### ISSUE TITLE
Resteem bug

### ISSUE THREAD

**Issue by TheDegenSloth** [steemit/condenser#1407]
As you can see it says i have resteemed this but the resteem icon is not active.
![resteem bug](https://i.gyazo.com/29ab891e960fbc34cb3946eeece52fa9.png)

After clicking the icon it gives a prompt to do it again.
![resteem bug](https://i.gyazo.com/25ce10a3245798e5245a24d47452cd5d.png)

After you click okay an error will pop up on the page telling you that you have already resteemed.

What i did to make this happen i have no clue at all.

**Comment by roadscape** [comment]
Currently resteem state is managed client-side and in some cases can be out of sync. Will fix in new APIs.
