### ISSUE TITLE
Can't login [username does not exist]

### ISSUE THREAD

**Issue by NathanAdored** [steemit/condenser#1408]
Sunday evening I created a steemit account from the webpage, where I plugged in my preferred name (which wasn't yet taken), went through cellphone verification (plug the numeric code from this SMS message into that field) and the email verification (click this link from inside the email), in that order, both of which were completed successfully.  However, every time I try to log in with the name I made, and with the randomly generated password, I get the error Username does not exist.

This is with the username nomadofnorad

Did something go wrong? oO

**Comment by TimCliff** [comment]
After you verify your email, there is still one more step. There is currently a waiting list, which may take a few days. You should receive an email letting you know your account was approved once this is done.

**Comment by valzav** [comment]
@NathanAdored, did you receive approval email with a link?

**Comment by NathanAdored** [comment]
Okay, this morning I got the following email:
----------------------->8----- cut here ----->8-----------------------
Hi again,
 
Great news, we've just approved your account.
 
You now have exclusive control over your Steem account, plus some free Steem to help you get started.
 
On Steemit you get rewarded for your curation and content according to the will of the crowd. To login, click the link below.
 
[link redacted]
 
See you on Steemit,
 
- The Steemit Team
 
 ----------------------->8----- cut here ----->8----------------------

....but the link takes me to a blank white Not Found page.  On the other hand, after I clicked on that link, and then went to the steemit main page, logging in worked.   I *think* I remember trying to log in before seeing that email (and clicking the link in it), though, and still getting Username does not exist then, but there were too many other distractions going on at the same time so I may be misremembering that from yesterday instead.  If I did, I guess clicking the link in the email sorted it.  Or something. oO

**Comment by gtkpr** [comment]
i registered yesterday. confirmed my email. got an email today saying my account was approved. but i still can't login because supposedly my username still doesn't exist?? what's going on

**Comment by valzav** [comment]
@gtkpr, did you create your account using the link in the approval email?

**Comment by gtkpr** [comment]
@valzav  i believe so!! i confirmed my email via a link in an email, but i also clicked on a link in the email that said my account was approved which brought me to a page with my password and everything.

**Comment by schweitzerb** [comment]
I'm running into the same issue. I followed all the steps pretty carefully, but get the same "Username does not exist" error. When I click the link in the approval email though I get an error that the account has already been created. See screenshot.

![image](https://user-images.githubusercontent.com/8152946/26904918-63df873a-4bb2-11e7-9ef5-1fa017f819fe.png)

**Comment by schweitzerb** [comment]
Closed but still not working?

**Comment by valzav** [comment]
@schweitzerb, it was deployed a couple of minutes ago, could you check if it fixes your issue? you need to click the link from the approval email.

**Comment by schweitzerb** [comment]
Thanks! Worked now!

**Comment by valzav** [comment]
@schweitzerb, great! Thanks for helping us to nail it down. I approved you for the second account just in case you would need the name from the screenshot too.

**Comment by gtkpr** [comment]
didn't fix my problem... :/ "username does not exist" still. it should be noted again that my account has been approved already

**Comment by gtkpr** [comment]
actually, i followed the link in the email to confirm my email, and then followed the link in the approval email, which ended up generating a new password for my account. so now instead of getting the error "username does not exist" i'm getting the error "Incorrect password". neither the old nor the new string works

**Comment by govindashwin** [comment]
i got an email which says my account is approved but when i click on the link in the email it says that my account has not been approved

**Comment by analuisafleming** [comment]
Hi valvaz i have a similar issue but the problem it i with the password. i was using my steemit account on the  google chrome web on my iphone and logged me out afer that i have tried to log in with the same result (incorrect password) i saved my master key as a print screen i made sure to be properly right and is not working.. i have read post with  log in issue on steemit with iphone but not providing any solutions my account its new but i dont want to lost it..i have not lost my master key password.. please help me out

**Comment by dotnetspec** [comment]
Hi,

My username:
fr33d0md1str0

I have similar problem. Account created 4 days ago.

Received and clicked link in - "Welcome to Steemit! Confirm Your Email"

No problems but still ...
can't login

![image](https://user-images.githubusercontent.com/27340988/28764214-8924cb2c-75f6-11e7-9a77-754e9207e645.png)

Any suggestions?
Thx

**Comment by originated** [comment]
@dotnetspec You will receive another email shortly with your final confirmation/and start link that will create your account.  Please be patient there is currently a high demand for accounts.  Thank You!

**Comment by dotnetspec** [comment]
Hi,
Thanks for that.
Just a quick note to other users. I needed to zoom out of my default zoom to see the 'create account' button. Silly, but it appeared for a moment that there was still an issue with the account creation process.
I'm using Brave browser.

**Comment by cryptojunk** [comment]
I have the same issue with my account that received the approval mail on 5th of june. username @projectzen

![steemit](https://user-images.githubusercontent.com/28138841/28997401-e178721c-7a13-11e7-81b7-36baa5563060.PNG)

**Comment by TimCliff** [comment]
@cryptojunk - please ask for help in the Steemit chat #help channel.

**Comment by habibkhadbai** [comment]
hello... i created an account on Wednesday... got verified by phone but have had no emails from steemit. I get the same response username does not exist... If i go ahead and try to create a new account my username and email shows as available but my phone number says its been used already. 

username: habibkhadbai
email: habibkhadbai@gmail.com

Can someone help?

**Comment by TimCliff** [comment]
@habibkhadbai please read the steemit.com FAQ regarding account creation.

**Comment by habibkhadbai** [comment]
@TimCliff Thanks for your message. I dont believe I ever got an email for verifying my account.

**Comment by prabinzz** [comment]
Can't i recover my username from email?? Any of the above method didn't help me ..

**Comment by habibkhadbai** [comment]
there should be a steemit helpdesk to speed this up. a promising service is turning into a poor tale.

**Comment by TimCliff** [comment]
All -  please ask for help in the steemit chat #help channel. do not ask for any account creation support in GitHub.

**Comment by sizedoesntmatter** [comment]
Hi, I made my account 1/04 and today I set up my password, but when I want to sing in it`s showning that my user name doesn`t exist. How can I deal with it?

**Comment by TimCliff** [comment]
Please ask for help in the help channel of steem chat.

**Comment by sizedoesntmatter** [comment]
I can`t sing in to chat, it`s shows that my user name doesnt exist.

**Comment by TimCliff** [comment]
Steem chat logins are completely independent of Steem blockchain / Steemit logins. You should be able to setup an account there just with an email address.

**Comment by sizedoesntmatter** [comment]
Thank you :) I`ll try again.

**Comment by xxkathaxx** [comment]
I've got the same Problem. I've created my steem account yesterday after i've got the mail "one last step to set up". After i finished all the steps i wan't to login but i get same response username does not exist. What can I do? username: xxkathaxx

**Comment by TimCliff** [comment]
Please ask for help in the help channel of steem chat.

**Comment by linglung** [comment]
why so difficult to sign up in steemit? is steemit worthed?

**Comment by TimCliff** [comment]
@linglung if you are having issues, please ask for help in the help channel of steem chat.

**Comment by linglung** [comment]
thank you @TimCliff .  your classic answer as usual. 
i don't want to spend my time just for trivial sign up in weird site.

**Comment by TimCliff** [comment]
GitHub is not the appropriate channel to discuss account issues. There are people in the help channel of steem chat who can help you if you go there. (Read the info in the pinned messages.)

**Comment by changyupkim** [comment]
The same issue. I've received the mail that Steemit verified my account on March 12. And I clicked the link in the mail to finish up.

<img width="450" alt="screen shot 2018-05-24 at 1 09 31 pm" src="https://user-images.githubusercontent.com/4415396/40464073-e36a9610-5f53-11e8-8c96-7cb4ff2e2847.png">

**Comment by TimCliff** [comment]
Please ask for help in the help channel of steem chat.

**Comment by Johackwi** [comment]
I am also facing a similar issue... In creating my account, I imputed my preferred username, then confirmed my email, afterwards I was sent an SMS code... I had a network interruption here. Coming back to continue, it gets stuck on sending another code.... And the it says my username is taken, and phone used already whenever I try creating the account allover again... Help me
