### ISSUE TITLE
Users are reporting lost posts

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1411]
There are reports from multiple users where they typed up a post, submitted, and then nothing happened. The cached version was gone, so everything was lost.

https://steemit.com/steemit/@barrydutton/post-2-went-to-submit-a-new-blog-post-for-publishing-twice-today-2-hrs-apart-clicked-submit-and-the-whole-post-vanished-and

**Comment by roadscape** [comment]
Should be fixed with https://github.com/steemit/steem/issues/1242
