### ISSUE TITLE
Current rewards message problem

### ISSUE THREAD

**Issue by ImperfectOne** [steemit/condenser#1416]
I noticed one strange thing - sometimes when I enter another user wallet, I get the message about my current rewards. I know I'm new here, but isn't that suppose to appear in my wallet along with the button to claim it? I attach the short movie to visualise the problem:

https://streamable.com/jgnjf

**Comment by noisy** [comment]
the problem is.. that when @ImperfectOne is logged in, and he is on someone else's wallet, then message should not start with "**Your** current rewards..."

I think it would be better to have "Unclaimed rewards of user XYZ:..." or something like that

**Comment by sneak** [comment]
The user's own rewards should display only on their own wallet, not anyone else's.

**Comment by roadscape** [comment]
Resolved
