### ISSUE TITLE
Prefix to resize images stored on steemitimages.com  does not work

### ISSUE THREAD

**Issue by VIM-Arcange** [steemit/condenser#1417]
When using the prefix 'https://steemitimages.com/[maxwidth]x[maxheight]/' before an image's URL in a post, it resizes the image to the specified dimension when displayed.

But, if the image is already stored on steemitimages.com, it does not work (image is displayed full size)

**Examples:**

`https://steemitimages.com/48x48/https://steemitimages.com/DQmSdpTK4dtCLJYsFjTXT44VZ3FUqSfR6gJBD1Sj5nbtTYm/image.png`
_image is not resized_

`https://steemitimages.com/48x48/https://cdn.pixabay.com/photo/2014/03/25/16/55/lightning-297608_960_720.png`
_image is resized_

**Comment by roadscape** [comment]
Bug not confirmed, but this could be a problem

**Comment by relativityboy** [comment]
@VIM-Arcange I just tried to repro using your "defective url" example and it resizes perfectly.

**Comment by relativityboy** [comment]
Doing some additional investigation. Resizing _does work_ on the proxy-end.  However, the steemit site is built to strip all proxies (to avoid loops & dead proxies), and then add  proxy with the dimensions appropriate for the environment in which the image is being displayed. Thumbs are tiny; in content they're full-sized, etc.

What @VIM-Arcange is asking for is a feature-add to steemit.com.

**Comment by VIM-Arcange** [comment]
Let me add some info on this request:

Some users use an image stored on steemitimages.com for their avatar picture (see first example above).
I want to be able to reuse this image in a post (or comment) when I mention a user (i.e. display its avatar next to its name)
Some users have an avatar image greater than the usual 48x48 format used to display avatars.
This is why I prefix the image with `https://steemitimages.com/[maxwidth]x[maxheight]/` in the post content.

To reproduce the problem, create a post (or comment) and paste the image URL provided in the above example. You will notice that the first one is not resized.

**Comment by VIM-Arcange** [comment]
While you are working on the proxy stuffs, can you give a look at the following request:
https://github.com/steemit/condenser/issues/1107

**Comment by relativityboy** [comment]
Looked. Let's get this one figured out first.

**Comment by roadscape** [comment]
Merged
