### ISSUE TITLE
Internal Server Error on /submit_mobile

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1418]
After a user enters their username, email, and phone number, the next page it takes them to is https://steemit.com/submit_mobile. When it reaches this page it gives an Internal Server Error.

![image](https://cloud.githubusercontent.com/assets/20735105/26037306/2d9ece6a-38b6-11e7-8bae-a9f162dfc3cf.png)

**Comment by roadscape** [comment]
I believe this is resolved
