### ISSUE TITLE
User Reported Issue - SMS Code Not Sending

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1426]
A user reported that during the signup process, they are not receiving a SMS message to their phone. They tried Re-send multiple times and it didn't work. The issue persisted over multiple days. I can provide the full phone number to the devs if needed via steemit.chat.

![image](https://cloud.githubusercontent.com/assets/20735105/26135936/777babc4-3a7e-11e7-8e2d-f4bebc5083e3.png)

**Comment by andrewreedy** [comment]
+1 Also having this happen for me

**Comment by Priksh** [comment]
Hi, having issues signing up, I am being told my number has been used but i have never signed up before.

Kindly tell me how i can send my number so that it can be  verified and activated

**Comment by jatsir96** [comment]
I am facing that problem from past 4 days When I try to sign up a group of members. Not a single person received any code after multiple tries. Also got the same message on steemit.chat. I can provide the phone numbers if it needed. I think it only happens to Indian numbers.

**Comment by ShikiGami** [comment]
cannot register an account from japan because of this

**Comment by TimCliff** [comment]
Signup has been converted over to faucet.

**Comment by sachinsukumaran** [comment]
Same problem. Trying to sign up from India. I reach the page where I need to enter the confirmation code, but the code never reaches my mobile. Tried with 2 different numbers - 2 different networks, but can't get the SMS.

**Comment by goktugyil** [comment]
Has anyone solved this?

**Comment by TimCliff** [comment]
The issue is being tracked here: https://github.com/steemit/faucet/issues/240
