### ISSUE TITLE
Set global default category

### ISSUE THREAD

**Issue by piotr-d** [steemit/condenser#1429]
Hi,

I'd be love to set default category for post lists (maybe in conf, ex. when category is not set then people see posts from travel category. You can set default locale and default language, but not default content :(

**Comment by TimCliff** [comment]
@piotr-d - please read the guidelines for the repository before opening issues. @sneak to close.

**Comment by piotr-d** [comment]
Maybe it's a silly question, if yes then sorry for bothering you. I cannot find any solutions, instructions, guidelines or tutorial how to set default category as a content for whole block chain :( I've been trying to change some category at PostsList.jsx and it didn't work. Please, could you tell me where can I find some stuff about modifing default content? I will be greatful.

**Comment by roadscape** [comment]
@piotr-d have you joined #dev on steemit.chat?

**Comment by piotr-d** [comment]
I've joined steemit_helpdesk_for_noobs but nobody is there :( Thanks for this channel, gonna look for answears .
