### ISSUE TITLE
Mobile signup - Cannot enter dashes for phone number

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1431]
On an iPhone 5s, when entering a phone number, it does not allow users to enter dashes. The examples make it look like this is required/necessary.

![img_0134](https://cloud.githubusercontent.com/assets/20735105/26178700/0a309adc-3b25-11e7-9212-c81998587793.PNG)

**Comment by roadscape** [comment]
Maybe add an examples number without dashes? 
Or maybe dashes need to be added automatically (annoying IMO).

**Comment by TimCliff** [comment]
Signup has been converted over to faucet.
