### ISSUE TITLE
Add Emoji Button in Editor

### ISSUE THREAD

**Issue by clayop** [steemit/condenser#1440]
Emoji is a good and fancy way to lubricate online societies. While some Steemians can use Emoji by copy-pasting from other sites, it would be better if we have Emoji button in the editor.

Here are a list of Emoji I found
http://unicode.org/emoji/charts/full-emoji-list.html

**Comment by sneak** [comment]
We're going to leave this to the OS keyboard for now - maybe one day when we revisit the editor.

(On a Mac, just hit ⌘-control-space.)

**Comment by roadscape** [comment]
With a better editor this would be trivial. Let's revisit then.
