### ISSUE TITLE
Arbitrary Rewards Issue

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/condenser#1442]
There is a cool feature within chainbb that tells me from which app a post or comment was created. I posted using beta.chainbb.com (https://beta.chainbb.com/chainbb/@cryptoctopus/why-you-should-post-on-chainbb-otherwise) but then I needed to make an edit on the post...and I did that via steemit.com

Because I did an edit using steemit, it switched the benefiaciary back to steemit.com

Can't we fix the beneficiary to the original post instead?

**Comment by roadscape** [comment]
AFAICT the beneficiary is still chainbb
