### ISSUE TITLE
Unable to reveal all user's posts on their blog site

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/condenser#1445]
Reported by `@firepower`
Example `https://steemit.com/@kevinwong`
Scrolling down eventually stops without reaching the end (beginning of the user's blog timeline)
500 limit?

_"never tried to stalk someone so hard"_ - `@trafalgar`

**Comment by roadscape** [comment]
This is a backend issue, not sure if we want to resolve it there or wait for hive

**Comment by roadscape** [comment]
Dupe of #1109
