### ISSUE TITLE
people cannot register AGAIN :(

### ISSUE THREAD

**Issue by noisy** [steemit/condenser#1446]
![selection_999 090](https://cloud.githubusercontent.com/assets/201263/26490208/b1277806-420a-11e7-8dbe-99477376dd38.png)

It looks like there is on enough funds to delegate from @steem account:
https://steemit.com/@steem/transfers

![image](https://cloud.githubusercontent.com/assets/201263/26490233/c9db0ff2-420a-11e7-9db3-64b58bd1861f.png)

This is one more time this same problem: https://github.com/steemit/condenser/issues/1340
CC: @sneak 

and I will write this one more time, as [I did previously](https://github.com/steemit/condenser/issues/1340#issuecomment-294545900):

> before this issue will be closed, at least two things could be done to better handle this kind of situation in the future:
> - error handling (this kind of error message should never be displayed to end user)
>- if the reason behind that issue was low amount of VESTS on particular account, some kind of notification system should sent high priority message to people, which could handle this before this become a real issue.

**Comment by sneak** [comment]
Thank you for reporting this; we are aware of this issue.  This tracker is for bugs in condenser, please restrict your reports to the software contained in this repo.
