### ISSUE TITLE
Post Disappears and Reappears from User's Feed

### ISSUE THREAD

**Issue by levineam** [steemit/condenser#1451]
The following post is disappearing from the user's feed and reappearing. When it doesn't appear in the feed, manually inputting the URL leads to an error  "Sorry! This page does not exist."
https://steemit.com/cryptocurrency/@digicrypt/applying-the-gold-silver-ratio-to-cryptocurrency

**Comment by roadscape** [comment]
Should be fixed with https://github.com/steemit/steem/issues/1242
