### ISSUE TITLE
Resteem failed to execute

### ISSUE THREAD

**Issue by levineam** [steemit/condenser#1452]
User reports that they resteemed a post, the resteem button is green, but the post was never resteemed on their account. Username: @cryptogee. Post they were trying to resteem: https://steemit.com/colorchallenge/@cgame/7su1tz-colorchallenge-wednesdayyellow

**Comment by roadscape** [comment]
Possibly expiring tx bug -- should be resolved in https://github.com/steemit/steem/issues/1242
