### ISSUE TITLE
Do not display pending rewards on other users' wallet pages when logged in

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1454]

**Comment by sneak** [comment]
![screen shot 2017-05-31 at 21 25 18](https://cloud.githubusercontent.com/assets/408977/26660702/acb77618-4647-11e7-8005-54bbe75aa15c.png)


(This is displayed when I'm logged in and viewing someone else's wallet with pending rewards.)

**Comment by mcifani** [comment]
Pr updates in https://github.com/steemit/condenser/pull/1460
