### ISSUE TITLE
Market - depth chart y-axis bug

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#1455]
![image](https://cloud.githubusercontent.com/assets/5168676/26681764/3b73c8c0-46ac-11e7-8bdf-7f3cc6ddcb13.png)

The `$1.50k` makes no sense here, it should be `15k` if anything. Highcharts bug?

**Comment by relativityboy** [comment]
@roadscape not Highcharts bug. A config setting... 
~~~javscript
depth_chart_config.yAxis.labels.formatter 
~~~
Turns out (10e3 != 10^3)
