### ISSUE TITLE
[feature request] saving drafts like Medium

### ISSUE THREAD

**Issue by imkimchi** [steemit/condenser#1470]
Hi, I just got into Steemit 3 days ago, I've been writing posts a lot and found some problems in editor. just in case users accidentally close a tab or have other things to get done. It would be really useful If users can save drafts so they can continue to write post just like Medium. what do you guys think?

**Comment by TimCliff** [comment]
It's a good suggestion, but the GitHub repository is not the place to make enhancement suggestions. Please read the guidelines for contributing before opening issues. @sneak to close.

**Comment by sneak** [comment]
We intend to do this eventually; we are scaling up the team at the moment to be able to accomplish more things in parallel. :)

It's an important feature and one we will absolutely get to eventually. A few other high priority projects take precedence at the moment: communities and our mobile app. 

Thank you for the feedback!

**Comment by surfyogi** [comment]
I would suggest giving a link to any alternative input system you are going
to reference.

Where are the guidelines published?

J-
