### ISSUE TITLE
6 month old posts showing near top of /created/

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1474]
I noticed that there are several 6 month old posts showing up near the top of the list when the posts are sorted by /created. It is possible this is a steemd issue.

https://steemit.com/created/witness-category

![image](https://user-images.githubusercontent.com/20735105/27016776-af64c3f8-4ee8-11e7-946e-69654d50afb3.png)

**Comment by roadscape** [comment]
I'm thinking this is same issue as https://github.com/steemit/condenser/issues/986
