### ISSUE TITLE
Accounts to add to BadActorList.js

### ISSUE THREAD

**Issue by pfunks** [steemit/condenser#1484]
Current list: https://github.com/steemit/condenser/blob/master/app/utils/BadActorList.js

New accounts to include:

polniex
poleniex
polionex
pollniex
polloniex
polnoiex
polonyex
polonied
polonixe

Additionally, `poloniexwallet` is an account I mentioned in an issue before, and was not added to this list for some reason. While technically not a bad actor, it is an address that people will lose funds to if they send them there. If there's some hang up about listing an account *technically* owned by Poloniex but not used (because it was registered by a third party and uses the Poloniex BitShares wallet private key) as a "bad actor" then rename the list to something neutral.

**Comment by originated** [comment]
Thanks @pfunks, list has been updated.
