### ISSUE TITLE
Proposal: Change "Upvote" labels to "Upsteem"

### ISSUE THREAD

**Issue by dragosroua** [steemit/condenser#1490]
- "upsteem" is closer to the name of the site, it's not voteit.com, it's steemit.com
- "upsteem" will make it easier for people to understand what's happening when they are clicking that arrow - it's not like they're electing the content in some electoral college, but they are driving away steem from the rewards pool
- since voting is such a common activity, changing the name to be closer to the site name will help with brand awareness
- it will make the site stand apart from other sites which are using appreciation input and create an identity (just like "Like" is almost a Facebook patent)
- it will give people a nice, personal touch: the self-esteem goes up

At the first glance, there are just 4-5 places in the code where this needs to be changed. I'm comfortable with using git commits / pull requests so if I get a green light on that I can do the replacement(s).

**Comment by alexvancu** [comment]
I would also change upvote to upsteem, and also maybe flaging to be renamed as downsteem

**Comment by aaroncox** [comment]
I'm opposed to this. You shouldn't rename common features - unless you just want to confuse your audience.

**Comment by Tadasu85** [comment]
I agree.

**Comment by Tadasu85** [comment]
I agree with Aaron.

**Comment by dragosroua** [comment]
Thanks for the comments. I don't think the action of _drawing steem from a daily refilled rewards pool, by using a continuously depleting amount of power_ is a common feature. It's probably the most complex part of the Steemit ecosystem and, in my humble opinion, it has a certain learning curve. I'm not sure how many members of the platform know from day one what is the action of their "vote". Changing the name to something closer to the result of the action should help with that. I agree that if you're involved with the platform for a longer time, you get adjusted and "upvote" seems valid, but, for newcomers, the current word is confusing. Add to that the potential benefits from branding.

Of course, it's just my opinion and we don't necessarily have to agree.

**Comment by roadscape** [comment]
No immediate plans to change this verbiage, I guess it's up to branding.
