### ISSUE TITLE
Oauth Open Redirect

### ISSUE THREAD

**Issue by zubairkhan930** [steemit/condenser#1491]
Recently when i visited steemit's application steemconnect i discovered a vulnreability there .
When we specify an invalid scope then the authorize url redirects to the site mentioned in redirect_uri. So, attacker can create an app and use it as open redirector to redirect victims to fake sites.
eg. Attacker can host same phishing page and hack the victims.

If you are given link like :

https://steemconnect.com/authorize/@malicious.site?redirect_url=https://malicious.site

Here you ll be Asked For Private key and password when you put  valid login you ll be redirected to malicious site.

The @variable and redirect_url are juts matched and redirects you to the site you provided .

**Comment by rayadav** [comment]
@zubairkhan930 steemconnect is not maintained by steemit. Please raise an issue here: https://github.com/busyorg/sc2/issues
