### ISSUE TITLE
Misconfigured CORS

### ISSUE THREAD

**Issue by zubairkhan930** [steemit/condenser#1492]
1) It uses Security.allowDomain("*") which is extreamly dangerous
https://steemconnect.com/profile
Security Impact of CORS Misconfig 
http://yassineaboukir.com/blog/security-impact-of-a-misconfigured-cors-implementation/

**Comment by rayadav** [comment]
@zubairkhan930 steemconnect is not maintained by steemit. Please raise an issue here: https://github.com/busyorg/sc2/issues

**Comment by roadscape** [comment]
Moved to https://github.com/busyorg/sc2/issues/34
