### ISSUE TITLE
Proposal: Crowdsourced suggestions for subunit denominators for Steem

### ISSUE THREAD

**Issue by dragosroua** [steemit/condenser#1493]
Crowdsourced proposals for smaller denominations of Steem:

Unit|	Value in USD|	@ $1 per STEEM
---|---|---
STEEM|	1|	$1
mSTEEM (milliSTEEM)	|0.001|	$0.001
μSTEEM (microSTEEM)|	0.000001|	$0.000001
see below|	0.00000001|	$0.00000001

For the 8th digit there was [a pol](https://steemit.com/steem/@dragosroua/final-pool-for-steemit-smallest-denomination-cast-your-votes-before-the-pull-request)l asking for more options, here are the results:

8th digit denominator|Proposed by|Score
---|---|---
STEEMtoshi|[@dragosroua](http://steemit.com/@dragosroua) |11
Steembit|	[@anonimnotoriu](http://steemit.com/@anonimnotoriu)| 5
Steemlet|	[@gyanibilli](http://steemit.com/@gyanibilli)|5
Heet|	[@lennstar](http://steemit.com/@lennstar)| 5
Mist|	[@nicnas](http://steemit.com/@nicnas) |4
Drop|	[@trevorlyman](http://steemit.com/@trevorlyman)|3
Gas|	[@nicnas](http://steemit.com/@nicnas) |2
Vapor|	[@trevorlyman](http://steemit.com/@trevorlyman)|2
Bubble|	[@trevorlyman](http://steemit.com/@trevorlyman)|2
Vim|	[@akrid](http://steemit.com/@akrid)| 2
Scotti|	[@steevc](http://steemit.com/@steevc)|1
Nedans|	[@steevc](http://steemit.com/@steevc)|1
Daned|	[@liberosist](http://steemit.com/@liberosist)|1
Lar|	[@rgeddes](http://steemit.com/@rgeddes)|1
Dani|	[@stephen-somers](http://steemit.com/@stephen-somers)|1
Pst	|[@girlbeforemirror](http://steemit.com/@girlbeforemirror)|1
Id	|[@girlbeforemirror](http://steemit.com/@girlbeforemirror)|1
Ned|	[@wilx](http://steemit.com/@wilx)|1
It	|[@kingofdew](http://steemit.com/@kingofdew)|1
Puff|	[@codypanama](http://steemit.com/@codypanama)|1
Nad	|[@demotruk](http://steemit.com/@demotruk)|1
Drip|	[@trevorlyman](http://steemit.com/@trevorlyman)|1
Wave|	[@trevorlyman](http://steemit.com/@trevorlyman)|1
SteemLar|	[@creatr](http://steemit.com/@creatr)| 1
Steemer| [@dhwoodland](http://steemit.com/@dhwoodland)| 1

**Comment by roadscape** [comment]
If any of these catches on, we'll use em ;)
