### ISSUE TITLE
Thumbnail not showing up

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1499]
The thumbnail for this user's post is not showing up. Multiple users see the same thing.

https://steemit.com/@mobbs
![image](https://user-images.githubusercontent.com/20735105/27314199-e6351eaa-5537-11e7-94de-354f346a1515.png)

The image URL for the top image is:
https://steemitimages.com/0x0/https://steemitimages.com/DQmRYMxoQS3JoeCz9sSNd7bhvJZhNPjEyNMs6n97RerjJ58/%23WILTW%20(3).png

Here is the json_metadata from steemd:
```	{"tags":["blog","science","life","writing","steemit"],"users":["suesa"],"image":["https://steemitimages.com/DQmRYMxoQS3JoeCz9sSNd7bhvJZhNPjEyNMs6n97RerjJ58/%23WILTW%20(3).png","https://steemitimages.com/DQmZSiUBnad9oVipAg4pwYgrEcRzGW5Tgz1RNLDhFPZmVF5/image.png","https://steemitimages.com/DQmWixodh2c5yFruWur317SEWC1AKapj9fjsrXoBbPAwDWD/image.png","https://steemitimages.com/DQmctA5QaRe9V57GZuLbWTXCRJxVYbsYsZyZXXFHtHEY8iY/image.png","https://steemitimages.com/DQmQCeKNKjPYSutpbTRXbEnHhkDEr8ec2KyaFBBDK2w8ucR/image.png","https://steemitimages.com/DQmRdNtuiy9iREK4Repj7W2akCBLWkJtzDcEEZVWzoxA2ap/image.png","https://steemitimages.com/DQmazA4PGNanPYPiNPQbMNcBhFYMxZWf2S7XHksw722NNH9/image.png","https://steemitimages.com/DQmTS7g5bMmbo3vin2we2V3bzmfSzuy2ZE1G9M2a6LYdgoy/image.png","https://steemitimages.com/DQmPSqDHoQYh9GwdN5ufqhfGJ6wUKdnZqfGozCoFaAoN2Xw/image.png"],"links":["https://steemit.com/fiction/@suesa/killed-by-the-resistance-how-we-lost-the-antibiotics","https://www.nature.com/news/resistance-to-last-ditch-antibiotic-has-spread-farther-than-anticipated-1.22140","https://www.newscientist.com/article/2133476-the-strange-cook-pine-trees-that-always-lean-towards-the-equator/","http://www.sciencemag.org/news/2017/06/china-s-quantum-satellite-achieves-spooky-action-record-distance","http://www.investopedia.com/news/how-china-became-worlds-biggest-innovator/","http://all-that-is-interesting.com/interesting-events/3","http://www.patheos.com/blogs/friendlyatheist/2017/06/18/no-breatharians-cant-live-without-food-and-neither-can-anyone-else/"],"app":"steemit/0.1","format":"markdown"}```

**Comment by rayadav** [comment]
@TimCliff not sure what the problem was, but I can see it now:
![screen shot 2017-07-05 at 19 44 07](https://user-images.githubusercontent.com/7298668/27889447-82702d76-61ba-11e7-8df8-2903e37725d5.png)

This can be closed.

**Comment by TimCliff** [comment]
I had advised the user to rename the image file and re-upload it to update the post, which is probably why it is showing up now. Multiple users have reported similar issues. I am pretty sure there are special characters (like parentheses) that cause issues if they are part of the image file name.

**Comment by roadscape** [comment]
Please reopen if this happens again

**Comment by TimCliff** [comment]
@roadscape - I cannot reopen the issue, but I think the issue is when the user uploads a file that has parentheses in it, it does not show up as the thumbnail. I've seen a lot of users reporting it, and someone just brought it up again.

![image](https://user-images.githubusercontent.com/20735105/28442130-52ddaa82-6d74-11e7-8ad4-da048e3dad4c.png)

**Comment by roadscape** [comment]
Thanks, this is a good lead.

**Comment by roadscape** [comment]
From #1590:

> Pretty simple bug: if an image filename contains an apostrophe, it breaks the post thumbnail. The image works in the post just fine though.

---

It sounds like there might be an issue when we save json_metadata (specifically, `image` array) when URLs contain special characters like parenthesis or apostrophes. Perhaps URL not being encoded properly.

**Comment by plink01001** [comment]
Is this still an issue?

**Comment by bnchdrff** [comment]
def. an issue with how we save json_metadata; we should be urlencoding

**Comment by caleblogan** [comment]
I wasn't able to reproduce this. It also looks like special chars are partially url encoded. Here is the post I used: https://steemd.com/test-category/@okc/7lwjqx-test

**Comment by TimCliff** [comment]
I tried with `#test 123 ' (4).png` and the thumbnail showed up. Not sure if any additional changes are needed.

**Comment by TimCliff** [comment]
@bnchdrff do you still see an issue with the way json_metadata is being saved? If not, I will close this issue because I am unable to reproduce the original problem that was reported.

**Comment by plink01001** [comment]
Seems resolved.
