### ISSUE TITLE
General KeyBoard Nav Improvements

### ISSUE THREAD

**Issue by originated** [steemit/condenser#1506]
https://steemit.com/steemit/@austinseraphin/steemit-com-accessibility-issues

I always tell people to try accessing their program or web site using only the keyboard to test for basic accessibility. If you can't access it with a keyboard then you'll likely have problems with other assistive technologies. Try using steemit.com just using your keyboard, and note the results. I miss a lot of controls using the tab key, and many elements report as clickable but get skipped over. Links such as the Reply links on posts and comments only respond to mouse events.

**Comment by plink01001** [comment]
Are there plans to make any changes for this issue, or should it be moved to the `enhancement-review` category?
