### ISSUE TITLE
Notification does not disappear after clicking on it

### ISSUE THREAD

**Issue by TheBenji** [steemit/condenser#1513]
If I get a notification for Feed (or any other one for that matter) it does not clear when I click on it **if I'm already on that page.**

For example I'm on my feed and get a notification for a new item on my feed so I click there to reload the feed but the notification does not clear.

If I'm on my blog tab and get a notification for a new item on the feed and I click it it does clear so it seems notifications are cleared just on an actual page change...

**Comment by mihai-asumcinei** [comment]
This looks like your side browser/network problem.

Can you send over to use:

what is your OS and version 
browser used and version

**Comment by plink01001** [comment]
Merging with https://github.com/steemit/condenser/issues/72
