### ISSUE TITLE
My edit to this comment is displaying as a diff patch

### ISSUE THREAD

**Issue by mvandeberg** [steemit/condenser#1517]
https://github.com/steemit/steem/issues/1210

**Comment by roadscape** [comment]
> @dnotestein commented 29 minutes ago
> https://steemit.com/blocktrades/@freebornangel/hello-blocktrades#@blocktrades/re-freebornangel-hello-blocktrades-20170622t031002673z

![image](https://user-images.githubusercontent.com/5168676/27452483-a3049112-5760-11e7-80cb-2cfae8242b82.png)

Here is the transaction: https://steemd.com/tx/2c86eb6d40740a73a3f0b78516c76f3288825396

There is no "original post" transaction preceding this one, which means the user's reply only existed in their local state. I didn't expect this could happen without an error. There is no sign of forking at all around this time (no missed slots, no signs of double production). When submitting an edit, only the diff patch was sent, but this tx was successful.

**Comment by roadscape** [comment]
Should be fixed with https://github.com/steemit/steem/issues/1242
