### ISSUE TITLE
Username does not exist 

### ISSUE THREAD

**Issue by bitteller** [steemit/condenser#1518]
Good day
It seems I'm having an issue.
Create account bitteller
verified phone and email
waited 24hrs, got the acceptance email. Clicked link. saved Private key. then go to login and I get "Username does not exist " if I try to signup again, username not taken, but phone and email are already in use. 

Not sure what I did wrong. I was very careful with everything.
Any help?

**Comment by bitteller** [comment]
It would seem going threw the process again fromt he last emailed link fixed it. Odd but all good now. Thanks

**Comment by aglyzov** [comment]
Thank you, going through that link helped me too. The generated password was different this time.

**Comment by startailcoon** [comment]
Could this be related to #1532, where posts does not make it into the blockchain?
If posts are sometimes missed, maybe new user registrations are to?

**Comment by roadscape** [comment]
Resolved
