### ISSUE TITLE
Mobile - Promote Page Amount entry is too small

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1520]
When viewing the promote page, the text box to enter the amount is too small. Any numbers that the user types are hidden.
https://steemit.com/devs/@justinashby/promote-post-bug-help-needed

**Comment by TimCliff** [comment]
The user who reported this is saying that it will not let them promote for any amount, and it is giving them a validation error that they do not have enough funds, even if they have more than enough SBD in their account. User is on chrome, zmax pro.

**Comment by originated** [comment]
Closing ticket, the SBD input was updated. https://github.com/steemit/condenser/issues/1520  If there is issues is still actual operation issues/with promotions please open another ticket
