### ISSUE TITLE
Make it 1 click to get from a post to a user profile

### ISSUE THREAD

**Issue by JohannesKnecht** [steemit/condenser#1525]
When I click on a post and want to visit the profile of the person why do I need to do 2 clicks ?

First on the name (then a little pop-up appears) where I can then click on the name again to get to the profile.

This is unbelievably annoying !

If you really want this info-card then let it appear when the mouse hovers over but please let me get to a profile by 1 click only !

**Comment by sneak** [comment]
Updating the user profile/account widget is in our plans, but is low-priority at the moment.  Please restrict your filing of issues in this repo to bugs in functionality per the guidelines.

https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md
