### ISSUE TITLE
Signup Issue - User is unable to click "I AGREE TO THESE TERMS"

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1526]
![image](https://user-images.githubusercontent.com/20735105/27514007-78796fe2-5942-11e7-84b4-7c9df681a4b5.png)

A user is reporting that when they click on the "I AGREE TO THESE TERMS" button, that nothing happens and it just stays stuck on that page. They say they tried in Explore, Edge, Chrome.

This is the page they see before they get to that page:
![image](https://user-images.githubusercontent.com/20735105/27514018-a69f6502-5942-11e7-97cf-8b05d18704c0.png)

**Comment by originated** [comment]
@TimCliff do they have javascript disabled in their browser?

**Comment by TimCliff** [comment]
I'll check and let you know what they say.

**Comment by TimCliff** [comment]
Closing - No additional details. Will re-open with more info if it is reported again.
