### ISSUE TITLE
Signup Issue - "Your account nas not been approved." after receiving approval email

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1527]
Multiple users are reporting receiving this error after they receive the email saying their account has been approved and they click on the link.

![image](https://user-images.githubusercontent.com/20735105/27514204-e482b9ae-5948-11e7-9ca2-2597d7f24b07.png)

**Comment by valzav** [comment]
Fixed by this commit https://github.com/steemit/condenser/pull/1528/commits/766eb578087da3dfd174d6eaaf98bc43e97200d1
