### ISSUE TITLE
Server errors when trying to make a new account

### ISSUE THREAD

**Issue by ilay1034** [steemit/condenser#1530]
I waited a few days and finally got the "your account has been approved email". I tried making a new account on a couple browsers.

**They All returned a server error**

on chrome, I keep getting an error message that says: "Couldn't create account. Server returned the following error:
Conflict

I tried edge (my only other browser), and I got the same type of error, except instead of conflict it says "Failed to read". 

![2017-06-26 17_24_52-steemit](https://user-images.githubusercontent.com/22532056/27561004-db73debc-5a72-11e7-9815-0f54f6cefc37.png)

Thanks in advance

**Comment by valzav** [comment]
@ilay1034, we think this was temporary outage, could you try to create an account one more time?
If it doesn't work again, please drop a message with account name you are trying to create to val@steemit.com. 
Thank you.

**Comment by ilay1034** [comment]
@valzav Awesome! It worked, thanks!
