### ISSUE TITLE
New blogpost never made it to the blockchain

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/condenser#1532]
Infuriating when you spend 2 hours writing something and then after you post it, it disappears from the blockchain. What's up with that guys?

**Comment by sneak** [comment]
We are currently discussing a solution to this problem - it doesn't occur very often.  For the moment, please make your posts in an external editor like TextEdit or Notepad, and paste them in when complete.

We're going to be adding a very basic draft autosave (local to the browser doing the editing only) to band-aid this bug until a proper fix is in place.  I apologize for your lost post, it must be supremely frustrating.

**Comment by startailcoon** [comment]
Another user experienced this today.

>After dotting my i (s) and crossing my t (s), I happily hit the "POST" button.  Low and behold, I guess steemit had a bug that sent my post into thin air and returned the error message below,
**Sorry! This page doesn't exist.**


https://steemit.com/gridcoin/@delordsquest/my-very-first-steemit-mistake

**Comment by roadscape** [comment]
Backend issue, should be fixed with https://github.com/steemit/steem/issues/1242
