### ISSUE TITLE
Condenser doesn't pass linting tests.

### ISSUE THREAD

**Issue by NateBrune** [steemit/condenser#1535]
Condenser should pass all prettify and eslint tests with absolutely no errors. Furthermore, linting should eventually be part of the testing suite.

**Comment by sneak** [comment]
Please break this into a series of smaller PRs.  Lint a file at a time.  `rc` is in master now so submit 1-2 linting file fixes per day, and as soon as `master` is deployed on prod, please make sure to deploy to stage, test, and then deploy to prod right after they get merged in.
