### ISSUE TITLE
Fake user: "@fyrstiken" (with single "k") imitating real user @fyrstikken (with double "kk")

### ISSUE THREAD

**Issue by LKNX** [steemit/condenser#1536]
Please put the fake user on the "bad actor" list. Thank you 👍

**Comment by Transisto** [comment]
You are posting at the wrong place, go on steemit.chat in the #steemitabuse topic

**Comment by mihai-asumcinei** [comment]
what is bad actor list?

**Comment by TimCliff** [comment]
If a user tries to do a transfer to a user in the bad actor list, the UI will give them a warning on the transfer page that they may be transferring coins to the wrong account and to check the spelling of the account name to make sure it is correct.

**Comment by roadscape** [comment]
Please submit a PR with some documentation showing why this user should be on bad actor list.
