### ISSUE TITLE
No notification when mentioned

### ISSUE THREAD

**Issue by blahbax** [steemit/condenser#1542]
I'd always assumed when mentioning a user, they'd receive a notification ... but it seems the mention just disappears into Steemit oblivion. I understand these notifications could be a little annoying for whales, but a mute button would be a much better solution than zero notifications.

**Comment by mihai-asumcinei** [comment]
Right, me and many of my followers noticed the NOTIFICATION problems so many times:

- no visual notification on steemit.com UI if someone post a comment or a reply (chrome and firefox, last version)
- no push notification on desktop, on mobile phone it works.
- no visual notification on steemit ui for mentioned username.

Weird. Anyone already working on these issues? 
I look forward to understand what's going on and maybe I can help with some coding

**Comment by finleyexp** [comment]
Since HF19, I'm only seeing notifications in "Feed" and "Wallet," but not when @ mentioned and not in "Replies."

I looked through all the other issues about notifications and this one seemed like the best thread to comment in.

**Comment by roadscape** [comment]
Restarting the notification service, please reopen if issue persists.
