### ISSUE TITLE
Enable vote slider for small SP accounts post HF19

### ISSUE THREAD

**Issue by l0k1-smirenski** [steemit/condenser#1544]
From a post back in May by @sykochika ( https://steemit.com/steem-help/@sykochica/what-s-this-slider-bar-and-vote-power-percentage-what-s-the-difference )

Once a user reaches 1 MilliVest (which right now equates to 482.398 Steem Power), they will gain access to the vote slider bar. This lets you determine how much of a vote you want to give a person. Since we have a limited number of full (100%) votes a days without it effecting our voting power, sometimes we want to give a partial votes to more people.

This is why small accounts are now voting less, and only at 100% Since even 480 SP now gives a reward of around 40 cents, this is functionality that should be available to all accounts, or, at least, it should be lowered to at least 100SP, if not blanket enabled.

**Comment by TimCliff** [comment]
If you give the vote slider to users with less than 0.25 MV of SP, then when they try to use the slider for low vote percentages they will get an insufficient bandwidth error. There is already a pull request to lower it from 1.0 to 0.25 (not approved) but it should not go lower than this.

Regardless of all that though, you are violating the rules of the repository by opening issues like this. It is not a place to submit user suggested enhancements. @sneak to close.

**Comment by l0k1-smirenski** [comment]
The bandwidth error will not exist if the witnesses increase the block size. Being that the chain has now blasted past Ethereum in transaction count, I think that the time has come to discuss increasing the block size.

This interface issue is not a feature request, it is necessary to continue the accelerated adoption that is happening. This very issue highlights the fact that the user experience for newbies is not the same as you have when you are an established user. 

I'm going to close it because of the short-sighted, sad attitude being demonstrated here, but I will be stirring up the masses to support these changes and agitate for them.

**Comment by TimCliff** [comment]
There are two different bandwidth limits. Increasing the max block size does not fix the limit that they would run into.

My attitude is not short sitedness. I was the first of the top witness to increase my max block size back to 131,072 to allow for higher bandwidth usage for new users, and I submitted the pull request to lower the threshold for the vote slider from 1.0 MV to 0.25 MV (the lowest it can go without running into bandwidth limits). 

It is purely that this is not a bug, it is an enhancement request. The existing functionality is working as per the design spec, even if you disagree with the design. To change it to something that is 'better' is an enhancement.

**Comment by TimCliff** [comment]
@l0k1-smirenski - for the record, I'm not trying to be a jerk about it. It is just I know it has been pointed out before that opening issues for this is against <a href="https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md">the guidelines for contributing</a>. In the future, it would be best if you emailed these suggestions to 'sneak at steemit.com' rather than opening issues for them.

**Comment by l0k1-smirenski** [comment]
Where is the appropriate forum to discuss serious UX issues then?
