### ISSUE TITLE
Requests to api.steemjs.com are not allowed

### ISSUE THREAD

**Issue by campje** [steemit/condenser#1545]
I want to create a greasemonkey script that call the steemjs api and display the upvote I get the last 24h.

unfortunately, the connect src just allow requests to "https://steemit.com https://api.blocktrades.us https://steemit.com wss://steemd.steemit.com https://steemitimages.com"

Please, can you allow requests to your own API.

Thanks a lot.

**Comment by jredbeard** [comment]
If you are running a local copy of condenser and wondering how to change this, the helmet directives connect source can be adjusted by setting the environment variable `SDC_HELMET_CONNECTSRC`. The default is in defaults.json. The steemjs.com site is actually not run by Steemit Inc - it is not 'our own api' right now.
