### ISSUE TITLE
Flagging in the last 12 hours

### ISSUE THREAD

**Issue by tcgirl** [steemit/condenser#1549]
@steemcleaners ran into an issue last night where a member of @steemcleaners flagged a post with 5 hours left to payout but could not remove the flag. 

While I think that flagging in the last two hours would benefit groups like @steemcleaners, I also see the potential for abuse. 

In the past, steemit has had users maliciously flagging all new users. The community was able to counter this by upvoting those posts manually and with bots. A new user having all their posts lose their rewards and hidden just before payout would be very discouraging. 
 
I did not raise this question on the site to avoid making this observation too public.

**Comment by TimCliff** [comment]
A few people have brought this up before. This is actually handled at the blockchain level, so it doesn't really belong in the condenser repository. Would be more appropriate here https://github.com/steemit/steem/issues. I don't know if it really qualifies as a variance/bug though. It may be considered more of an enhancement.

**Comment by 4Ykw** [comment]
Oh.. I see.. flagging also cost bandwidth... so it can take a while to launch a flag attack, is that right?

Otherwise I see this as a possible attack. Just like voting/unvoting.

**Comment by TimCliff** [comment]
Flagging does use bandwidth, but for a user with a larger amount of SP they likely will not be running into a bandwidth limitation.. GitHub is not really the place for these types of conversions though. If you have questions about how the platform works, you can ask in the #help channel of Steemit chat, and I or someone else will try to respond to your questions there.

**Comment by roadscape** [comment]
Backend issue https://github.com/steemit/steem/issues/1267
