### ISSUE TITLE
Issues with tags displaying with single quote and a bracket characters

### ISSUE THREAD

**Issue by recrypto** [steemit/condenser#1557]
I was browsing around Steemit.com and I saw a post that was having issues with the parsing as it contains symbolic characters such as ' and ]

![Snap 2017-07-09 at 21.08.41.png](https://steemitimages.com/DQmVGDLYifn7J69qMFRd1MAfroEqzpcD2GyDA69XyvQGRPJ/Snap%202017-07-09%20at%2021.08.41.png)

https://steemit.com/steemj/@jerrybanfield/top-cryptocurrency-services-we-can-offer-1499543073-5333757

**Comment by mihai-asumcinei** [comment]
This is not an issue related to condenser , in my opinion, but something to the software Jerry uses to submit the content to the block-chain!!

**Comment by recrypto** [comment]
Ahh, I see. Thanks for that.
