### ISSUE TITLE
DEPRECATED components

### ISSUE THREAD

**Issue by michael-asumcinei** [steemit/condenser#1560]
Hi guys

I am going to introduce some new issue , installation process, with current Github Condenser Codebase.

> npm WARN deprecated autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader
>npm WARN deprecated koa-static-cache@3.2.0: this version has critical security issue, please upgrade to >=4.1.1

ENVIRONMENT:
ubuntu 16.04
node v6.11.1
npm  3.10.10

I am going to explore the code - anyone dealing already with it?

**Comment by roadscape** [comment]
Feel free to submit a PR for this
