### ISSUE TITLE
NPM START ISSUE

### ISSUE THREAD

**Issue by michael-asumcinei** [steemit/condenser#1561]
> webpack: Compiled successfully.
application server starting, please wait.
proxying to webpack dev server at http://0.0.0.0:8081
Application started on port 8080
type `rs` in console for restarting koa application
fs.js:1445
    throw error;
    ^

Error: watch /home/michael/Documents/Projects/Web/Apps/condenser/condenser/server ENOSPC
    at exports._errnoException (util.js:1018:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at watch (/home/michael/Documents/Projects/Web/Apps/condenser/condenser/node_modules/node-watch/lib/watch.js:221:8)
    at /home/michael/Documents/Projects/Web/Apps/condenser/condenser/node_modules/node-watch/lib/watch.js:180:14
    at Array.forEach (native)
    at /home/michael/Documents/Projects/Web/Apps/condenser/condenser/node_modules/node-watch/lib/watch.js:179:13
    at ChildProcess.<anonymous> (/home/michael/Documents/Projects/Web/Apps/condenser/condenser/webpack/utils/start-koa.js:45:17)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)

npm ERR! Linux 4.8.0-58-generic
npm ERR! argv "/home/michael/.nvm/versions/node/v6.11.1/bin/node" "/home/michael/.nvm/versions/node/v6.11.1/bin/npm" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! steemit.com@1.0.0 start: `./node_modules/babel-cli/bin/babel-node.js ./webpack/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the steemit.com@1.0.0 start script './node_modules/babel-cli/bin/babel-node.js ./webpack/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the steemit.com package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/babel-cli/bin/babel-node.js ./webpack/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs steemit.com
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls steemit.com
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/michael/Documents/Projects/Web/Apps/condenser/condenser/db/npm-debug.log
michael@mich

**Comment by roadscape** [comment]
Have you tried upgrading node? Also you should be using `yarn start`

**Comment by sneak** [comment]
Please use the versions of node and package manager described in our `Dockerfile` - that is, node 7.5 and `yarn`.  We don't use node 6.x or npm.  If you are still having trouble when using the ones that match ours, please reopen this issue. :)

Best,
-jp
