### ISSUE TITLE
User Reported Issue - Share Links Missing on Chrome

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1562]
I was unable to reproduce this, but @cryptofrygirl reported in the #help channel of steemit.chat that some of the share buttons were missing when she viewed a post.

Here is a screen shot of what she saw:
![image](https://user-images.githubusercontent.com/20735105/28194012-e6309e20-6806-11e7-9e99-e3d1941ab5b0.png)

**Comment by mihai-asumcinei** [comment]
good suggestion. 

marketing materials are fundamental at this stage.

**Comment by michael-asumcinei** [comment]
I wasn't able to reproduce the error.

Can you send over:

what is your OS and version
browser used and version

Cheers
Michael Asumcinei
@digitalplayer

**Comment by roadscape** [comment]
I can't reproduce it either and haven't heard any reports since.
