### ISSUE TITLE
Logging out does not clear active vote display, causes problem when logging into other account

### ISSUE THREAD

**Issue by l0k1verloren** [steemit/condenser#1564]
This can obviously be worked around by using an incognito or other browser session, but the app has to be refreshed. This also causes issues when multiple tabs, with one logged out, the other not logged out.

It could be an issue that cannot be resolved because of browser architecture, I am not certain.

**Comment by relativityboy** [comment]
@roadscape @bnchdrff Time for groupthink - Have logout trigger page reload. It's clean && clear. Opine?
