### ISSUE TITLE
Perpetual Edit Function

### ISSUE THREAD

**Issue by kerri38846** [steemit/condenser#1565]
I just learned that there is no perpetual edit function on Steemit. This was SHOCKING to me as an experienced and successful content creator. I know that there has been a push for this and that Steemit has even stated they would allow this feature in their bylines. 

Two reasons why Steemit NEEDS this function that will not only benefit readers and content creators, but Steemit in the future: 

1) Part of Google's algorithm is pages read on a site. When I create new content, I write with the INTENTION of creating new content later that will 'interlink' with older content I've created. For instance, I might write "10 ways to clean your house faster" then later write a seperate article on each of those 10 ways, making EACH ARTICLE link to EVERY OTHER ARTICLE IN THE SERIES. 

By doing this in my own websites, I get an average of 3 pages read per visitor. This benefits me in my Google ranking in a big way. 

2) Another part of Google's algorithm is pages with dead links and outdated information. By keeping my pages 'fresh', up to date, and with current links, I have pages rank #1 on google for popular keywords for YEARS at a time! 

Steemit is INTENTIONALLY allowing something that might be popular in the search engines NOW to drop off keyword searches later by allowing content and links to become old. That is bad for Steemit, readers, and content creators. 

Thanks for listening. I hope this 'bug' gets fixed, as it REALLY is a bug. It's actually shocking to me, as a content creator, that I can't update and improve my content. It may be a 'dealbreaker' for me, as it's unacceptable to not be allowed to keep my content current and up to date, as almost everything that I write is technical and science-based. To allow my content to become dated makes me look bad and hurts my reputation as a fact-based writer. 

ADDITIONALLY, I had planned on making my Steemit page on a VERY controversial fact based topic (debunking flat earth- yes, this is a 'thing') and the ability to correct past errors I may have made is IMPERATIVE, as even ONE mistake in my math or science could literally make me a laughing stock and completely unbelievable as an authority on the topic! 

It's really a deal breaker for me to use Steemit, and I suspect it will be for many others who have 'authority' on topics. Not being able to correct past mistakes is really a horrible feature. 

Sincerely, 

Kerri Knox, RN

**Comment by TimCliff** [comment]
This is a great suggestion, but the GitHub repository is not the appropriate place to be making enhancement suggestions. Please read the guidelines for contributing. @sneak to close.

**Comment by sneak** [comment]
We appreciate the feedback and this is absolutely on our radar as something we will be fixing relatively soon; there is already backend support for it now: however it is not a bug. Please restrict your issues in this bug tracker to already-implemented functionality that is not working correctly.
