### ISSUE TITLE
Mismatching Memo for Claim Rewards in Wallet

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1566]
In my wallet transactions page, it is showed a memo from one of my transfers under the "claim rewards" line. I refreshed the page and it went away.

![image](https://user-images.githubusercontent.com/20735105/28249636-29b3845e-6a1f-11e7-90ee-5fdc4b88850e.png)

After refresh:
![image](https://user-images.githubusercontent.com/20735105/28249635-1c4a5202-6a1f-11e7-84b5-51403d2bed80.png)

**Comment by sneak** [comment]
Can you reliably reproduce it?

**Comment by TimCliff** [comment]
No. It was a one time thing.

**Comment by sneak** [comment]
Without steps to reproduce, it's unlikely we will be able to track it down.  I'm closing it for now.  Please reopen if it happens again.

**Comment by TimCliff** [comment]
Ok, will do.

**Comment by TimCliff** [comment]
It doesn't let me re-open the issue, but it has happened twice again. Both times I did a transfer with a memo, and then claimed rewards right after. The memo showed up in the "Claim Rewards" line, but then when I refreshed the page it went away.

![image](https://user-images.githubusercontent.com/20735105/28441960-3a54877a-6d73-11e7-996f-77d0372f11da.png)

**Comment by TimCliff** [comment]
Found a duplicate issue here: https://github.com/steemit/condenser/issues/1316. No need to continue the discussion here.
