### ISSUE TITLE
User Reported Issue - SBD -> STEEM Conversions are not showing up in wallet

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1569]
Multiple users have reported SBD -> STEEM conversions are not showing up in the wallet transactions, or in the SBD section.

https://steemd.com/@marcusxman?page=10
![image](https://user-images.githubusercontent.com/20735105/28299194-6c1755fe-6b3d-11e7-8d3d-489d40a3afa3.png)

https://steemit.com/@marcusxman/transfers

![image](https://user-images.githubusercontent.com/20735105/28299159-2c3d8692-6b3d-11e7-9247-ad4a3feffebd.png)

![image](https://user-images.githubusercontent.com/20735105/28299202-785fd368-6b3d-11e7-8a4b-449713022e6e.png)

**Comment by roadscape** [comment]
I don't believe it ever was shown in the steemit wallet. If it's needed, `convert_operation` should be added here: https://github.com/steemit/steem/blob/20125771e4a8b2eaa7bcbfd1ce993c4c0075e601/contrib/fullnode.config.ini#L16

**Comment by roadscape** [comment]
From @jamesashton in #1582:
> I transferred a small amount of STEEM Dollars, selecting the 'Convert to STEEM' drop down item on the menu that appears next to the STEEM Dollars balance.The STEEM dollar balance is now $0.000 but there is no evidence of the original funds anywhere.Ideally it would show some sort of 'Pending' status, or it would write an entry to the History. Or preferably both.It did say it would take 1-3 days for the transaction to complete. Which is fine, but I can have forgotten about this in 3 days, so there should be some indication that the transaction is in progress.

**Comment by TimCliff** [comment]
Adding a link to a previous issue where this was implemented/fixed before: https://github.com/steemit/condenser/issues/1246

**Comment by TimCliff** [comment]
@roadscape - I went to fix this, and realized it is already working on a fresh condenser instance. I ran the 'traditional' (non-docker) build steps in GitHub and ran in production mode.

Here is the output in the wallet for my test user with a conversion in progress:
![image](https://user-images.githubusercontent.com/20735105/29591357-c90f79b6-8763-11e7-9ece-46efed9f0365.png)

Do you know what would be different on the steemit.com instance?

Here is the code from UserWallet.jsx:

```        let conversionValue = 0;
        const currentTime = (new Date()).getTime();
        const conversions = account.get('other_history', List()).reduce( (out, item) => {
            if(item.getIn([1, 'op', 0], "") !== 'convert') return out;

            const timestamp = new Date(item.getIn([1, 'timestamp'])).getTime();
            const finishTime = timestamp + (86400000 * 3.5); // add 3.5day conversion delay
            if(finishTime < currentTime) return out;

            const amount = parseFloat(item.getIn([1, 'op', 1, 'amount']).replace(" SBD", ""));
            conversionValue += amount;

            return out.concat([
                <div key={item.get(0)}>
                    <Tooltip t={tt('userwallet_jsx.conversion_complete_tip') + ": " + new Date(finishTime).toLocaleString()}>
                        <span>(+{tt('userwallet_jsx.in_conversion', {amount: numberWithCommas('$' + amount.toFixed(3))})})</span>
                    </Tooltip>
                </div>
            ]);
        }, []);
```

**Comment by roadscape** [comment]
Probably, convert_operation needs to be added here: https://github.com/steemit/steem/blob/20125771e4a8b2eaa7bcbfd1ce993c4c0075e601/contrib/fullnode.config.ini#L16

**Comment by TimCliff** [comment]
Sorry, I see now that you knew the answer to my question before I even asked it :)

**Comment by roadscape** [comment]
The op has been added into the whitelist; this issue will be resolved w/ the next prod deploy of steemd.
