### ISSUE TITLE
@minnowbooster typo accounts to add to BadActorList

### ISSUE THREAD

**Issue by pfunks** [steemit/condenser#1573]
Attempting to profit from typos from transfers to @minnowbooster

minnowboost
minnowboster
minowbooster

https://steemd.com/@minnowboost
https://steemd.com/@minnowboster
https://steemd.com/@minowbooster

**Comment by roadscape** [comment]
Could you please submit a PR for this?

**Comment by originated** [comment]
Closing this ticket, list was updated/merged in.
