### ISSUE TITLE
New test: Sanity check, en check for translations 

### ISSUE THREAD

**Issue by originated** [steemit/condenser#1581]

**Comment by sneak** [comment]
This needs to happen ASAP - we have shipped a missing translation to prod #1611 and it's not acceptable.  Please make this your top priority.

Anywhere the code generates the translation token name via interpolation or concatenation, fix it so it doesn't, so a simple grep can get a complete list of every single translation token in use.  This is a site quality issue.

**Comment by sneak** [comment]
@NateBrune @jredbeard - please make sure this happens.  I asked for it two weeks ago and we're shipping errors today in production to thousands of people.

**Comment by sneak** [comment]
Marking this as a bug as I consider it an incomplete i18n implementation without this *build-time* check to ensure that the english strings exist for all tokens used.

**Comment by plink01001** [comment]
Is this complete?
