### ISSUE TITLE
Is this being actively maintained?

### ISSUE THREAD

**Issue by appetizermonster** [steemit/condenser#1583]
Hello,
I'm a Steemit User.
and I love the ecosystem of the Steem blockchain and Steemit.
I want to see that Steemit will continue to develop actively.
because there are so many rooms to develop in terms of UX. (e.g. WYSIWYG Post Editor)

I know Steemit, Inc is maintaining this project (condenser),
but the project seems being maintained inactively.
(too small commits per time as a company software project)

Are there are any ongoing problems on Steemit, Inc?

**Comment by roadscape** [comment]
https://github.com/steemit/condenser/pulse

Work happens in many other repos too:
https://github.com/steemit
