### ISSUE TITLE
comments body preview not showing up in certain cases

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/condenser#1586]
comments body preview not showing up in certain cases
actually I've found one such case:
https://steemit.com/@fyrstikken/comments
i.e. subject is there, body isn't

Replies works fine:
![replies](https://user-images.githubusercontent.com/6341057/28520924-cb60c1c4-7071-11e7-9571-7b7acd4f1613.png)
Comments doesn't:
![comments](https://user-images.githubusercontent.com/6341057/28520931-d2a6831a-7071-11e7-8dea-dfea7ebdd2ba.png)

**Comment by relativityboy** [comment]
Fixed
