### ISSUE TITLE
User Reported Issue - Internal Market Not Matching Orders Correctly

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1587]
A user reported that the internal market is not matching orders correctly. Details are in this post:
https://steemit.com/steemit/@rawpride/the-steemit-market-does-not-function-properly-can-be-manipulated-orders-skipped-not-a-fair-and-balanced-market

**Comment by roadscape** [comment]
This is a rounding issue which can affect tiny orders. 

It's impossible to place a dust order at $1.595/STEEM.

0.010 STEEM can only be bought for 0.015 SBD or 0.016 SBD.
