### ISSUE TITLE
Apostrophes in Image Filename Break Thumbnails

### ISSUE THREAD

**Issue by krisphelps** [steemit/condenser#1590]
Hey there,

Pretty simple bug: if an image filename contains an apostrophe, it breaks the post thumbnail. The image works in the post just fine though.

Screenshots from a test I did can be found here:

https://steemit.com/steemit/@kxp/steemit-bug-report-thumbnails-break-with-filenames-containing-apostrophes

**Comment by TimCliff** [comment]
Related to https://github.com/steemit/condenser/issues/1499 - could be combined into one issue

**Comment by roadscape** [comment]
Discussion continues in #1499
