### ISSUE TITLE
Recovering an Account

### ISSUE THREAD

**Issue by inphinitbit** [steemit/condenser#1591]
Is there any way to recover an account after my computer crashed with the password to my steemit account? It is easily verifiable using my posts, username and Facebook account so any help would be appreciated.  Thanks!

**Comment by TimCliff** [comment]
No. The only account recovery feature that exists requires you to have an owner key / master password that was used within the last 30 days.

@sneak to close

**Comment by inphinitbit** [comment]
Thanks for getting back to me TimCliff. I am just wondering how it is possible to return stolen or hacked accounts, but not get accounts with a lost password back if the identity can be verified. Thanks again!

**Comment by TimCliff** [comment]
If your account is hacked or stolen, you should still have a previous password / owner key that was used within the last 39 days (before the account was hacked). You would need that to be able to complete the stolen account recovery process.
