### ISSUE TITLE
Question: Rshare threshold for DoFollow Links

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/condenser#1592]
I discover lately that DoFollow links are activated after a certain threshold of RShare are allocated to a certain article. 

I believe we can have great demand from people who would buy SteemPower to allow their articles to have DoFollow Links on them. 

This is why I am asking this question. **What is the RShare needed for DoFollow links to be activated?**

**Comment by roadscape** [comment]
Right now it looks like `nofollow` is added to any post which has less than $10 in payout.
