### ISSUE TITLE
grammatically incorrect partially loaded page

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1594]
![screen shot 2017-07-29 at 16 24 54](https://user-images.githubusercontent.com/408977/28745142-8eb97df8-747a-11e7-8c8f-d9b013b8efe7.png)

while waiting for api calls to return, the following/followers text is incorrect.  the labels for the counts should not be displayed until the entire string is ready for display - displaying partial strings during loading is incorrect behavior.

**Comment by gl2748** [comment]
I will look at this over the weekend. Assuming you propose it simply display: ' 380 Posts' for the state you have pictured.

**Comment by sneak** [comment]
Yeah, I'd like a policy in general that we always display correct/complete messages, even during load.  There are a couple other spots I think this happens, and I will try to remember to file them as I notice.

**Comment by sneak** [comment]
I'd also be okay with small (`x` sized) loading spinners in those spots

**Comment by originated** [comment]
Yeah this shouldn't handle like that, the count and indicator should have the count state directly on the page load.  We updated this awhile ago.  I'm pretty familiar with the logic here, @gl2748 if you haven't started let me know I can take it.

**Comment by gl2748** [comment]
@originated go ahead, I've not worked on this.
