### ISSUE TITLE
Layer scrolling bug with the article popover modal on mobile.

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#1595]
### From Slack.
>  "...there is a layer scrolling bug with the article popover modal on mobile when opening an article from a list view...where sometimes it scrolls the mostly hidden list instead of the article ... maddening ... when the article modal is over the list view, sometimes scrolling will scroll the list view and not the article and the article will repaint over it enough times per second that you can see that you're scrolling the list and not the article"

**Comment by gl2748** [comment]
I am working on this over the weekend.

**Comment by gl2748** [comment]
![steem_bug](https://user-images.githubusercontent.com/3374538/28747291-64ff0250-7469-11e7-9fc1-fe5018c9b7c1.gif)

**Comment by plink01001** [comment]
Is this still an issue, or can it be closed?

**Comment by plink01001** [comment]
With the removal of modals, this should be resolved. Please re-open if it is still an issue.
