### ISSUE TITLE
Flagged posts showing negative and incorect number of votes

### ISSUE THREAD

**Issue by GoldenBoar** [steemit/condenser#1596]
I've noticed this on 2 posts now, the number of votes is showing as negative, but when you click the link to read the post it shows a different positive number of votes. Both posts I noticed like this had been flagged.

Here are some screenshots to highlight what I'm talking about:

http://i.imgur.com/qFvHHtn.png

and

http://i.imgur.com/QuvsDLE.png

That particular post can be found [here](https://steemit.com/freedom/@adsactly/a-tale-of-two-futures).

**Comment by sneak** [comment]
It's adding the upvotes and subtracting the flags.  It should show total vote count.

**Comment by relativityboy** [comment]
Fixed by @gl2748
