### ISSUE TITLE
New dropdown arrow has wierd click behavior

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1600]
When I click this:
![image](https://user-images.githubusercontent.com/20735105/28857693-e70a2794-7710-11e7-8802-fee2ec76710c.png)

It does this:
![image](https://user-images.githubusercontent.com/20735105/28857702-f2da2fc4-7710-11e7-969b-88a133a7cab3.png)

(Browser Firefox)

**Comment by steemchiller** [comment]
That's why I registered on GitHub to report this issue ;) You were a bit faster :) I think this is really important and should be fixed immediately!

**Comment by jredbeard** [comment]
Looks like this was introduced by #1533 but is already fixed on another branch soon to be merged in (the 'rc' branch with i18n fixes and performance/stability optimizations). Temporarily I will roll back steemit.com to the previous deployment.

**Comment by steemchiller** [comment]
After the rollback it seems to work again thanks!

I first have to find out how this all works here. I've never worked with GitHub, but now as I'm here, I might come up with some ideas and improvements for the UI. I'm a German developer with much experience in HTML, CSS, JS & JQuery. Maybe I will look into the Condenser World in the future. Have a nice day!

**Comment by plink01001** [comment]
Has this been addressed / can this be closed?
