### ISSUE TITLE
Integrate shop.steemit.com

### ISSUE THREAD

**Issue by Birdinc** [steemit/condenser#1602]
Edit DNS settings. 

Point A record to 23.227.38.32

Point CNAME to shops.myshopify.com

**Comment by jredbeard** [comment]
Absolutely not.

**Comment by Birdinc** [comment]
Hey, Justin.  This is something Ned wanted me to post.  We've been in talks for a few weeks and worked on setting up a store for him.  I'll touch base with him and see how best to coordinate this. 

![image](https://user-images.githubusercontent.com/1677006/28880107-016b726c-7772-11e7-8176-8153b517d359.png)

**Comment by sneak** [comment]
Sorry for the confusion.  This can't run on a subdomain of steemit.com for technical (security) reasons.  We can set up a store.steem.io or a new second-level domain for it.

**Comment by sneak** [comment]
This isn't the right repo for this - please contact justinw@steemit.com and sneak@steemit.com in private.
