### ISSUE TITLE
Recovery Fail - Help out my friend @syifaola

### ISSUE THREAD

**Issue by dejoel** [steemit/condenser#1603]
Unfortunately already tried account recovery and account recovery but it has been more 1 month steemit no response at all

**Comment by mvandeberg** [comment]
We approved the request and sent a link on May 14th to the email used to register the account. This gave your friend 10 days to recover their account (the password was changed on April 24th), which they did not. Sadly, there is nothing we can do now due to the rules of the blockchain.

**Comment by dejoel** [comment]
If the recovery address has been confirmed while the latest password does not know how to continue to hold second, because the latest password is not I change so I do recovery
