### ISSUE TITLE
I have received confirmation of account recovery but I do not know RECENT PASSWORD because I only have the first password in steemit .. 

### ISSUE THREAD

**Issue by dejoel** [steemit/condenser#1605]
Or more clearly you can see the following link
http://i.imgur.com/up9TM0v.png

**Comment by jredbeard** [comment]
Please don't open additional github issues for this - we have already responded on 3 of them. We're sorry your loss but there is simply nothing else that we can do at this point to assist.

**Comment by dejoel** [comment]
How to get back account
