### ISSUE TITLE
missing translation: en.postfull_jsx.view_the_direct_parent

### ISSUE THREAD

**Issue by ausbitbank** [steemit/condenser#1611]
![image](https://user-images.githubusercontent.com/1692203/28901074-1acb5548-7839-11e7-98f2-0cb5ae8dd0c7.png)

A recent change has broken the translation for  the "View the direct parent" prompt when viewing a nested comment.

Example: https://steemit.com/books/@thecryptofiend/re-ausbitbank-re-thecryptofiend-how-to-damage-your-reputation-using-the-dmca-a-lesson-from-mark-manson-20170730t165312987z

**Comment by sneak** [comment]
Thank you for the report!  We should have caught this during build.  It will be fixed ASAP.
