### ISSUE TITLE
The word "Private" is showing up above the Memo field on the transfer page

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1612]
![image](https://user-images.githubusercontent.com/20735105/28901664-7802f0ce-77bf-11e7-8cbc-27ccc46a422d.png)

**Comment by TheIntrnet** [comment]
Looks like this shows up depending on something - specifically:

isMemoPrivate = memo && /^#/.test(memo.value);

How should we be checking if this should be shown or not?  Or should it never be there?

**Comment by sneak** [comment]
@TheIntrnet - it should never be there.

**Comment by sneak** [comment]
@valzav - is this an artifact of any of your recent changes?  Please investigate how this occurred - I would like an explanation.

**Comment by valzav** [comment]
@sneak, my bad - I've ported this part from golos repo and missed pretty obvious bug: ternary operator should be wrapped with parentheses, see my commit that fixes it https://github.com/steemit/condenser/commit/0fb46208ed3ed64120e55247ec6dca913b04afb6
