### ISSUE TITLE
Negative vote count on top trending post

### ISSUE THREAD

**Issue by andrarchy** [steemit/condenser#1616]
Top trending post with over 1600 votes appears to have a negative vote count (~ -200) on the trending page.

https://steemit.com/introduceyourself/@hardfork-series/announcing-the-world-s-first-crypto-focused-mini-series-powered-by-steemit

<img width="985" alt="screen shot 2017-08-03 at 09 53 08" src="https://user-images.githubusercontent.com/25394365/28930197-32d15028-7840-11e7-9fb1-eb207ef19813.png">

**Comment by TimCliff** [comment]
Likely related to https://github.com/steemit/condenser/issues/1596

**Comment by andrarchy** [comment]
Yup thanks Tim
