### ISSUE TITLE
Filtering posts by tags, only shows posts from the last 7 days

### ISSUE THREAD

**Issue by kharoof** [steemit/condenser#1617]
If people create tags for competitions or specific topics the tag filter does not always show **all** their posts. 

The following two links highlight the issue
-  https://steemit.com/created/culturevulture
-  https://steemit.com/created/rickysphotochallenge

In both cases when you scroll down the page you can only see posts for the last 7 days, but there are more.

**Comment by TimCliff** [comment]
Probably the same issue as https://github.com/steemit/condenser/issues/986

**Comment by sneak** [comment]
Tag indexing is pretty janky right now but we are going to be replacing the whole implementation soon.  Tracking this issiue in #986 - closing this one as dupe.

Thank you for the report, and keep up the good work @kharoof - reports like this are extremely valuable. :)
