### ISSUE TITLE
insufficient whitespace around touch targets on vote slider

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1620]
![img_0038](https://user-images.githubusercontent.com/408977/28965825-f9b0462a-790a-11e7-8db4-74b0a7f9b852.PNG)

the handle for the slider is right next to the close button. i closed the popup when i meant to move the slider.  please make the box about 50% taller and wider and double the margins around the slider.

**Comment by sneak** [comment]
oh and align the midline of the slider with the midline of the text, the x, and the upvote button, obvs

**Comment by gl2748** [comment]
@sneak what are the steps to re-create this? I'm having trouble getting the slider to display locally or on the prod site...

**Comment by gl2748** [comment]
I am going to be addressing this issue along with the refactor of the Flag-overlay, as the slider appears there as well.
https://github.com/steemit/condenser/issues/1641

**Comment by originated** [comment]
@sneak can you please confirm this is still an issue with the new UI updates? If so will update other-wise if you could close.  Thank you
