### ISSUE TITLE
I have tried 4 times now to create an account with Steemit and still unable to login 

### ISSUE THREAD

**Issue by Mystical11** [steemit/condenser#1627]
Each time a create an account...I do the waiting and get an email telling me that I my account is approved.  I click the link to go to the login page and when I type in my username and password...it tells me that the username does not exist.  On a few occasions, I waited a week and went back and tried to login and still go the same results.  Am I missing something here...
Returning Users: Login

@mkidd11

Username does not exist 

Keep me logged in  

LoginCancel

**Comment by TimCliff** [comment]
Can you post your issue in the Steemit chat #help channel? Someone there should be able to help investigate your issue.

**Comment by Mystical11** [comment]
I am not sure how to do that.  i may just give up at this point.  i cant seem to get help and i am not sure what the problem is.  i have been trying for a month and a half now.  Forget it.

**Comment by TimCliff** [comment]
@Mystical11 - there is a link to Steemit chat in the main menu of Steemit.com. Support issues are handled through there.
