### ISSUE TITLE
Transfer confirmation modal as title "login to comment"

### ISSUE THREAD

**Issue by bonustrack** [steemit/condenser#1635]
When I do a transfer, the confirmation modal title show "Login to comment"
![image](https://user-images.githubusercontent.com/16245250/29029769-f60ec92e-7bb2-11e7-9ea3-b3ea598b621c.png)

There should be a title "Login to transfer"

**Comment by originated** [comment]
@bonustrack You shouldn't see transfer options unless your properly logged in already, unless I'm missing something.  Where are you referring this?

**Comment by bonustrack** [comment]
I'm logged on steemit.com but when i'm doing a transfer, i noticed that the title is wrong, it might be confusing for user. When i want to confirm a transfer with my username / active wif, the title is "Login to comment" see: ![login](https://user-images.githubusercontent.com/16245250/29080625-7d1aade8-7c8a-11e7-90f9-30921e4ff7d3.gif)

**Comment by originated** [comment]
Yep, thanks for the video.  Agree that could be.  Assigning to me for updates

**Comment by valzav** [comment]
When I update my Public Profile Settings it says "Login to comment" too. Maybe it should be some neutral text, let's say "Please confirm your password to proceed". What do you think?

**Comment by originated** [comment]
Yes we should update that as well.  I will be updating both here shortly

**Comment by plink01001** [comment]
Related issue: https://github.com/steemit/condenser/issues/1459

**Comment by originated** [comment]
PR with updates. User is now prompted to "confirm password" not "comment" which is incorrect on transfers. https://github.com/steemit/condenser/pull/2040
