### ISSUE TITLE
Node Security Platform should be integrated and risk should be mitigated

### ISSUE THREAD

**Issue by NateBrune** [steemit/condenser#1637]
NSP should be run every build and the build should fail if NSP finds vulnerabilities.

**Comment by plink01001** [comment]
Are there plans to make any changes for this issue, or should it be closed?

**Comment by bnchdrff** [comment]
we can follow faucet's example of how to set this up

**Comment by bnchdrff** [comment]
estimate: 1 SP

**Comment by bnchdrff** [comment]
ready to go in https://github.com/steemit/condenser/compare/1637-add-nsp - once tests can pass (i.e. we update our deps) i will open a PR

**Comment by bnchdrff** [comment]
fix was reverted in #2491
