### ISSUE TITLE
Couldn't create account. Server returned the following error: Insufficient vesting shares to delegate to new account

### ISSUE THREAD

**Issue by manuelvillar** [steemit/condenser#1638]
Couldn't create account. Server returned the following error:

10 assert_exception: Assert Exception creator.vesting_shares - creator.delegated_vesting_shares - asset( creator.to_withdraw - creator.withdrawn, VESTS_SYMBOL ) >= o.delegation: Insufficient vesting shares to delegate to new account. {"creator.vesting_shares":"10167301514.731720 VESTS","creator.delegated_vesting_shares":"10167265328.697975 VESTS","required":"57000.000000 VESTS"} th_a steem_evaluator.cpp:201 do_apply {"op":["account_create_with_delegation",{"fee":"0.500 STEEM","delegation":"57000.000000 VESTS","creator":"steem","new_account_name":"mvillar","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6AyGfk51JHNxfcxHaVspSjT8qCPLxTmMrShQppAeBhAdRpG3JP",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5Ag7su2HLoMAYXM6HCZxtXaG3zLQWzZVvcL89cSYbF8Mm3DA12",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6CNz9bVcMVdqBvwgnG5M2CrQD21TXYH9DxfhYCyPYGWs7qpVJF",1]]},"memo_key":"STM7Pm8y949wodxXgbSa5mysM2xoLjmVniHXx9b5qLg8YPf8aUeF3","json_metadata":"","extensions":[]}]} th_a database.cpp:2885 _apply_transaction {"trx":{"ref_block_num":25090,"ref_block_prefix":906275736,"expiration":"2017-08-07T21:54:48","operations":[["account_create_with_delegation",{"fee":"0.500 STEEM","delegation":"57000.000000 VESTS","creator":"steem","new_account_name":"mvillar","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6AyGfk51JHNxfcxHaVspSjT8qCPLxTmMrShQppAeBhAdRpG3JP",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5Ag7su2HLoMAYXM6HCZxtXaG3zLQWzZVvcL89cSYbF8Mm3DA12",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6CNz9bVcMVdqBvwgnG5M2CrQD21TXYH9DxfhYCyPYGWs7qpVJF",1]]},"memo_key":"STM7Pm8y949wodxXgbSa5mysM2xoLjmVniHXx9b5qLg8YPf8aUeF3","json_metadata":"","extensions":[]}]],"extensions":[],"signatures":["1f6082818aaee46ff36be415d935f146ca76d3b13dce82555576480e220dfbd40d76b7ae49847889acec1ee4873e8d5da60f4cddc4140bdc720a3ffd7b1f80d1b6"]}} th_a database.cpp:2889 _apply_transaction {"trx":{"ref_block_num":25090,"ref_block_prefix":906275736,"expiration":"2017-08-07T21:54:48","operations":[["account_create_with_delegation",{"fee":"0.500 STEEM","delegation":"57000.000000 VESTS","creator":"steem","new_account_name":"mvillar","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6AyGfk51JHNxfcxHaVspSjT8qCPLxTmMrShQppAeBhAdRpG3JP",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5Ag7su2HLoMAYXM6HCZxtXaG3zLQWzZVvcL89cSYbF8Mm3DA12",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6CNz9bVcMVdqBvwgnG5M2CrQD21TXYH9DxfhYCyPYGWs7qpVJF",1]]},"memo_key":"STM7Pm8y949wodxXgbSa5mysM2xoLjmVniHXx9b5qLg8YPf8aUeF3","json_metadata":"","extensions":[]}]],"extensions":[],"signatures":["1f6082818aaee46ff36be415d935f146ca76d3b13dce82555576480e220dfbd40d76b7ae49847889acec1ee4873e8d5da60f4cddc4140bdc720a3ffd7b1f80d1b6"]}} th_a database.cpp:660 push_transaction {"call.method":"call","call.params":[3,"broadcast_transaction_synchronous",[{"ref_block_num":25090,"ref_block_prefix":906275736,"expiration":"2017-08-07T21:54:48","operations":[["account_create_with_delegation",{"fee":"0.500 STEEM","delegation":"57000.000000 VESTS","creator":"steem","new_account_name":"mvillar","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6AyGfk51JHNxfcxHaVspSjT8qCPLxTmMrShQppAeBhAdRpG3JP",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5Ag7su2HLoMAYXM6HCZxtXaG3zLQWzZVvcL89cSYbF8Mm3DA12",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6CNz9bVcMVdqBvwgnG5M2CrQD21TXYH9DxfhYCyPYGWs7qpVJF",1]]},"memo_key":"STM7Pm8y949wodxXgbSa5mysM2xoLjmVniHXx9b5qLg8YPf8aUeF3","json_metadata":"","extensions":[]}]],"extensions":[],"signatures":["1f6082818aaee46ff36be415d935f146ca76d3b13dce82555576480e220dfbd40d76b7ae49847889acec1ee4873e8d5da60f4cddc4140bdc720a3ffd7b1f80d1b6"]}]]} th_a websocket_api.cpp:124 on_message (see err.payload for the full error payload)

**Comment by manuelvillar** [comment]
This has happened before but all the issues are closed and locked now.

**Comment by netuoso** [comment]
This is expected behavior, @manuelvillar. Why is this an issue you are creating on Condenser repo? if anything this would belong on the Steemd repo.

```
{"creator.vesting_shares":"10167301514.731720 VESTS","creator.delegated_vesting_shares":"10167265328.697975 VESTS","required":"57000.000000 VESTS"}
```

Total Vests | Delegated Vests | Available Vests
------------------------------------------------
10167301514.731720 | 10167265328.697975 | 36186.033745

Required Available Vests for creating account with delegation = 57000

36186 < 57000

Therefore you do not have enough Available Vests to delegate to a new account.

**Comment by sneak** [comment]
@manuelvillar Please give it another shot.  This wasn't a condenser bug, just that the creation account needed more SP to delegate (it had run out from creating so many accounts).

**Comment by manuelvillar** [comment]
It worked, thanks

**Comment by slimyangy** [comment]
i just ran into this issue

**Comment by punkr0ck** [comment]
Same problem for me:

```
Couldn't create account. Server returned the following error:

4100000 plugin_exception: plugin exception Account: steem bandwidth limit exceeded. Please wait to transact or power up STEEM. 
```
