### ISSUE TITLE
User Reported Issue - Wallet page loads Blog content, not Wallet

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1646]
I have worked with the user @janusface to try and debug an issue, where their wallet page will not load. When they are logged in, if they click on the link to their wallet, it loads with their blog content instead of their wallet:

![image](https://user-images.githubusercontent.com/20735105/29150221-bb7703ca-7d3e-11e7-8b2d-9a07f200ede4.png)

If they are not logged in, the wallet page does load, but it doesn't let them do anything (since they are not logged in).

I had him try going to an external site (Google.com) and then going directly to the https://steemit.com/@janusface/transfers URL. The same issue occurred.

I gave him the username/password for one of my test accounts and had him try that. He was able to access the wallet page, when logged in with my test account.

He tried with both Safari and Chrome, and got the same issue.

**Comment by plink01001** [comment]
Has this been addressed / can this be closed?

**Comment by TimCliff** [comment]
the user has not followed up and I haven't seen any new instances of it
