### ISSUE TITLE
Auto converting the tags that a user enters to lower case, rather than giving a validation error

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1647]
This is an enhancement issue to track a community developer task.

**Comment by TAMustafa** [comment]
It looks like the code change need to happen in the following file:
src/app/components/cards/`CategorySelector.jsx`

At Line 84:
`cats.find(c => /[A-Z]/.test(c))      ? tt('category_selector_jsx.use_only_lowercase_letters') :`

Can the result of the input be passed to a function that uses the **toLowerCase()** method?

*//Function to convert tags into LowerCase*
```
function toLower(tag){
 return tag.toLowerCase();
}
```

*//And use .map method to apply array to toLower function*
`var tagToLower = c.map(toLower);`

I try to get condenser running to test this approach.

**Comment by voorash** [comment]
I think the code at line 84 is only testing that the tag is all lowercase. It needs to be converted to lower case before the validation is run.

**Comment by voorash** [comment]
So, changing this
```
const impProps = {...this.props}
```
to
```
const impProps = {...this.props, value: this.props.value.toLowerCase()}
```
fixes the issue but the validation runs before this code so one additional change handles that but I need a better way to do this without modifying that const.  Too late tonight so I will look at that tomorrow.
```
const ns = nextState
ns.category.value = ns.category.value.toLowerCase()
```

**Comment by voorash** [comment]
Making these two changes fixes the issue. My only issue was I wasn't sure if it was ok to make that change directly to the event or if I needed to make a copy and then change that and then pass it to onChange.

```
this.categoryInputOnChange = (e) => {
          e.preventDefault()
          e.target.value = e.target.value.toLowerCase()
          this.props.onChange(e)
        }

const categoryInput =
          <input type="text" {...cleanReduxInput(impProps)} ref="categoryRef" tabIndex={tabIndex} disabled={disabled} onChange={this.categoryInputOnChange}/>
```

**Comment by voorash** [comment]
Oh and that first function is added to the CategorySelector constructor right after categorySelectOnChange

**Comment by stephanmullerNL** [comment]
Ha that's exactly the solution I came up with, but then the "no uppercase" validation warning still remains even though it's converted? 

I don't think modifying the event should be a problem by the way.

**Comment by voorash** [comment]
I don't get the error message anymore with that change

**Comment by voorash** [comment]
hmm, the extra space removal is a good idea

**Comment by stephanmullerNL** [comment]
Alright, will do!

I got the error because I didn't use `e.preventDefault()` by the way, so that explains :)

**Comment by plink01001** [comment]
Closing in favor of https://github.com/steemit/condenser/issues/2061
