### ISSUE TITLE
looking at wallet crashes my browser

### ISSUE THREAD

**Issue by Siko91** [steemit/condenser#1649]
On my desktop, I am using Firefox 44.0.2 on Windows 8.1. (I do not want to update my browser)
On my phone, I also use Firefox, but it is the newest version for Android.

On both devices I have problems when looking at the wallet page of steemIt profiles.

On my computer, the browser sometimes crashes.
On my phone - it freezes and asks me if I want to stop some slow JavaScript, or let it run.

Basically - one of the scripts on that page is probably not performing well.

**Comment by TimCliff** [comment]
Possible related issue https://github.com/steemit/condenser/issues/1646

**Comment by plink01001** [comment]
Is this still an issue?

**Comment by plink01001** [comment]
Please re-open if this is still an issue.
