### ISSUE TITLE
Comments have resteem Buttons that do nothing.

### ISSUE THREAD

**Issue by Siko91** [steemit/condenser#1653]
Look at the image bellow. These are replies on a SteemIt profile.
There is a ReSteem button on each one. When pressed, it shows me a message "only top-level posts can be resteemed".
The button should be removed/hidden.

![img](https://s23.postimg.org/55kggeusb/Capture.png)
https://s23.postimg.org/55kggeusb/Capture.png

**Comment by originated** [comment]
Yes, we should filter the resteem in these cases.

**Comment by originated** [comment]
solution pushed in PR https://github.com/steemit/condenser/pull/1680
