### ISSUE TITLE
Create account allows user to proceed without re-entering password

### ISSUE THREAD

**Issue by nkgokul** [steemit/condenser#1654]
Aftter clicking on https://steemit.com/start/[hashcode] in the Welcome mail from Steemit user is redirected to https://steemit.com/create_account where he needs to reenter the password. 

The submit button should not be enabled until the RE-ENTER GENERATED PASSWORD field is filled. 

If the user submits the form without entering this is there is no warning or error message which can be confusing the users

**Comment by plink01001** [comment]
Is this still an issue?

**Comment by plink01001** [comment]
Closing issue, as all signup functionality has been converted to the new https://github.com/steemit/faucet.
