### ISSUE TITLE
Add full "og" tags to blog/profile pages

### ISSUE THREAD

**Issue by kellyjanderson** [steemit/condenser#1666]
Right now if you share the link to your blog/profile on Facebook the preview is only text and titled Steemit.

This should have the title "User Name - Steemit" at least and should pick a reasonable image for Facebook.

![screen shot 2017-08-16 at 11 09 31 am](https://user-images.githubusercontent.com/643583/29378483-1e3e47a4-8274-11e7-9d71-494ca1280ef9.png)

**Comment by plink01001** [comment]
Are there plans to make any changes for this issue, or should it be moved to the `enhancement-review` category?

**Comment by originated** [comment]
I just address this issue, the naming declaration on the facebook OG tags was not correct. Closing. PR https://github.com/steemit/condenser/pull/2024
