### ISSUE TITLE
Cover image size hint

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#1676]
Let users know what the ideal cover image size is.

We may want to check other frontends too and see if we need to make some compromise. 

For the current condenser UI the ideal size is `2048x256`. Currently any specified URL is constrained to `2048x512` just to preserve some quality in case the image is not 1:8 aspect ratio.

**Comment by relativityboy** [comment]
Facebook's crop-positioning works well. If we did that, the hint (image quality) would be more viscerally apparent than some kind of fancy hint (though that might be worth doing too)

**Comment by plink01001** [comment]
There is info on this in the FAQ now. Are further changes needed, or can this be closed?
