### ISSUE TITLE
User Reported Issue - Internal Market Reports Sell order as Buy

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1683]
If a user places a "sell" order above the current market price, the order shows up in the market orders at the bottom of the page as a "buy".

I reproduced with this transaction:
![image](https://user-images.githubusercontent.com/20735105/29738462-a0d1f668-89e8-11e7-8803-ba4410fc1fc7.png)

Here is the order on steemd.com:
![image](https://user-images.githubusercontent.com/20735105/29738455-8bcfdba4-89e8-11e7-9aa8-64f5cb379158.png)

Here is what is shown on the internal market:
![image](https://user-images.githubusercontent.com/20735105/29738468-bd12424c-89e8-11e7-821d-b882b2be5a4b.png)

**Comment by bnchdrff** [comment]
example of an action to receive open orders:

```js
{
  type: 'market/RECEIVE_OPEN_ORDERS',
  payload: [
    {
      id: 2,
      created: '2017-10-02T12:40:33',
      expiration: '1969-12-31T23:59:59',
      seller: 'foo',
      orderid: 1506948025,
      for_sale: 10000,
      sell_price: {
        base: '10.000 STEEM',
        quote: '10.000 SBD'
      },
      real_price: '1.00000000000000000',
      rewarded: false
    },
    {
      id: 5,
      created: '2017-10-02T12:49:21',
      expiration: '1969-12-31T23:59:59',
      seller: 'foo',
      orderid: 1506948557,
      for_sale: 5000,
      sell_price: {
        base: '5.000 STEEM',
        quote: '5.000 SBD'
      },
      real_price: '1.00000000000000000',
      rewarded: false
    }
  ]
}

the bug is here: https://github.com/steemit/condenser/blob/master/src/app/components/pages/Market.jsx#L250 -- `g.ask` isn't meant to be a translatable string, it's checking an attribute of the incoming order book payload.. fixing now :)
```
