### ISSUE TITLE
Enhancement: Add voting power information to user account page

### ISSUE THREAD

**Issue by dragosroua** [steemit/condenser#1687]
Suggestion: near the reputation number, using a simplified pie chart icon. Hovering over the icon should reveal the number in percentages (72.45%).

It's an issue that appears quite often in users requests.

<img width="737" alt="screen shot 2017-08-29 at 12 56 30 pm" src="https://user-images.githubusercontent.com/1648447/29815859-cb1fa90e-8cba-11e7-9861-5596620653c3.png">

**Comment by SpiderSprog** [comment]
It would be useful to see voting power decay/recovery rates in the hibernation event too.

**Comment by sneak** [comment]
We have discussed this before and have decided against adding any indicators that would cause hesitation around taking interactions on the site. While voting power is a scarce resource, we do not wish to expose it as such to users.

That said, we have a plan to put in a hidden cheat code menu that may expose certain things like this.
