### ISSUE TITLE
Warning about sending STEEM and SBD to @bloctrades instead of @blocktrades

### ISSUE THREAD

**Issue by Team-Steem** [steemit/condenser#1691]
This @bloctrades account just got created 21 days ago. 

If I remember this correctly warning have been added about other opportunist accounts of the type. 

I know this github might not exactly be the right place for this but I didn't know elsewhere to address this. 

Someone erroneously send 230 SBD to that account yesterday.

**Comment by originated** [comment]
Thanks @Team-Steem, has been added to our warning list https://github.com/steemit/condenser/pull/1692/files
