### ISSUE TITLE
Feed/Following Issue

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/condenser#1696]
Hey guys, I've cleaned up the list of people that I am following from 100+ to around 30...but my feed didn't change. I cleared my cookies and tried in private mode too but still doesn't work.

What's up?

**Comment by roadscape** [comment]
This is a known quirk with the backend follows system -- actions are not retroactive.

So a new account which instantly follows 20 people will still have an empty feed.

We have a replacement service in the works.
