### ISSUE TITLE
Incorrect text when user has SP delegated

### ISSUE THREAD

**Issue by dragosroua** [steemit/condenser#1697]
Currently, when a user has some SP delegated to somebody else, the explanatory copy goes like this:
`Part of your STEEM POWER is currently delegated to you. Delegation is donated for influence or to help new users perform actions on steemit. Your delegation amount can fluctuate.`

I think it should change `to` to `by`. See attached image for proof.

<img width="1241" alt="screen shot 2017-09-01 at 9 42 03 am" src="https://user-images.githubusercontent.com/1648447/29958725-dd782a24-8efc-11e7-885e-2b0867e5d447.png">

**Comment by originated** [comment]
This has been improved with different verbiage and including username if delegation https://github.com/steemit/condenser/pull/1705
