### ISSUE TITLE
wallet/transfers page missing translation asset

### ISSUE THREAD

**Issue by markhu** [steemit/condenser#1703]
Example URL https://steemit.com/@steemit/transfers

> SAVINGS
> Balance subject to 3 day withdraw waiting period,missing translation: ***en.asset_currently_collecting***

The problem is either in https://github.com/steemit/condenser/blob/master/src/app/locales/en.json
or https://github.com/steemit/condenser/blob/master/src/app/locales/en.json
but I am not familiar with the code or libs to be able to submit a fix PR myself at this time.

**Comment by sneak** [comment]
@valzav - please write a test for missing translations.

**Comment by plink01001** [comment]
This should be resolved. Please re-open if still an issue.
