### ISSUE TITLE
Images not displayed in Safari / Mac

### ISSUE THREAD

**Issue by dragosroua** [steemit/condenser#1704]
This issue seems to be related to the proxy or server settings of the image hosting instances on EC3. Here's a sceenshot of an image link on my mac.
![screen shot 2017-09-04 at 11 01 16 am](https://user-images.githubusercontent.com/1648447/30017126-93ddaa40-9160-11e7-8dd2-c50a3fcda94a.png)

On Chrome is working ok.

**Comment by jnordberg** [comment]
Can you provide the url to the image you're having problems with

**Comment by dragosroua** [comment]
IT behave like this with all images, and not only the ones references from steemit.com. I pull some JSON metadata for [steem.supply](http://steem.supply) to display the user avatar stored in the blockchain and it behaves exactly the same: image not displayed, and when I right click and "open image in a new window / tab" I see a message similar with the one above.

**Comment by jnordberg** [comment]
I'm unable to reproduce that in Safari so unless you can provide more details I'm inclined to think this is a problem on your end.

**Comment by dragosroua** [comment]
Ok. Will try to look more into this.

**Comment by dragosroua** [comment]
Was a local issue.
