### ISSUE TITLE
Ability to un-resteem posts

### ISSUE THREAD

**Issue by joshuadanpeterson** [steemit/condenser#1713]
It doesn't look like the ability to un-resteem a post exists, but this would be a super useful feature for curators. I noticed this issue when I recently attempted to un-resteem a post when I noticed that it violated community guidelines for plagiarism. Because the feature doesn't exist, however, I instead downvoted/flagged the post and commented defending the action: https://steemit.com/photography/@olivia0001/humming-bird-in-rain#@joshpeterson/re-olivia0001-humming-bird-in-rain-20170905t233025847z

Unfortunately, the post still exists resteemed on my blog, making it look like I support it, unless someone clicks through and sees my comment.

**Comment by joshuadanpeterson** [comment]
Here is my post further articulating my idea: https://steemit.com/steemit/@joshpeterson/steemit-needs-an-un-resteem-option

**Comment by roadscape** [comment]
This is a limitation of our current backend. It's on our radar; un-resteeming is being implemented in a new service.

**Comment by joshuadanpeterson** [comment]
Sounds good, thanks!
