### ISSUE TITLE
Missing translation in Wallet page

### ISSUE THREAD

**Issue by feruzm** [steemit/condenser#1722]
![2017-09-06_17-23-50](https://user-images.githubusercontent.com/3015990/30208088-a01d2ef6-949a-11e7-998c-e60345d176e9.png)

**Comment by valzav** [comment]
It's already fixed in`fix-some-i18n-issues` branch

**Comment by plink01001** [comment]
Has this been addressed / can this be closed?

**Comment by plink01001** [comment]
This should be resolved. Please re-open if it is still an issue.
