### ISSUE TITLE
amount of SBD in "convert to steem" is not fully validated

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/condenser#1731]
When you go convert your SBD you can enter non-valid amount.
Validation is clearly different from one used for transfers as for the same value it shows `Use only 3 digits of precison ` message.
![convert_validation](https://user-images.githubusercontent.com/6341057/30332382-6e65387a-97da-11e7-90d0-cad941994a11.png)

**Comment by plink01001** [comment]
Convert to Steem has been removed from the condenser UI.
