### ISSUE TITLE
When Upvoting From A Page Not Fully Downloaded

### ISSUE THREAD

**Issue by Team-Steem** [steemit/condenser#1753]
When upvoting a post from a page that isn't fully loaded the page is scroll back up at the top of the page. It should just do nothing or even better memorize our upvote and process it when the page ends up loading.

**Comment by plink01001** [comment]
Is this still an issue?

**Comment by plink01001** [comment]
Closing for no response. If this is still an issue, please re-open with steps to reproduce.
