### ISSUE TITLE
orders to *sell* steem on the internal market are falsely listed as `Buy` in the list view of open orders

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1754]
It should also probably show "Sell STEEM" or "Buy STEEM" to be perfectly clear.

**Comment by sneak** [comment]
<img width="1110" alt="screen shot 2017-09-24 at 08 56 04" src="https://user-images.githubusercontent.com/408977/30782754-4aa01a92-a106-11e7-8816-854624ca7e61.png">

**Comment by TimCliff** [comment]
Duplicate issue: https://github.com/steemit/condenser/issues/1683

**Comment by sneak** [comment]
closing dupe
