### ISSUE TITLE
Navigation to transaction page is way too slow

### ISSUE THREAD

**Issue by Siko91** [steemit/condenser#1772]
When a users want to transfer some STEEM, they have to go to the wallet page and then to choose a transaction option from the drop-down.
This is a big UX problem because on slower internet the wallet can take way too much time to open.
I often use SteemIt on the move with my phone. However cellular internet is way too slow to actually display the whole wallet page... Or maybe it's my phone's processing power that's weak. Anyway. I don't know what the bottleneck is, but it exists.

> If the problem is the internet speed, then the problem is even more serious. My country has a pretty decent cellular internet speeds, and my plan specifically is one of the better ones, and yet I can't open wallets with many transactions. Imagine how it would be for people with worse connection speeds. There are also areas in the world where people don't have any other type of connection. Would they be able to use their wallets at all?
Of course, the problem is probably less

My point is that we shouldn't really need to open the wallet in order to send money.
This extra step is not necessary if the purpose is transferring.

There should be a separate send/receive button, that loads a quick and simple page.

**Comment by plink01001** [comment]
Is this still an issue?

**Comment by plink01001** [comment]
Closed for no response. Please re-open if this is still an issue.
