### ISSUE TITLE
warn before transfer to negative rep account

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#1781]
suggestion from @blocktrades:
> have you guys considered giving a warning when sending to someone with a negative rep? That would allow anyone to flag accounts as potential phishing accounts.

**Comment by steevc** [comment]
I think the transfer screen should also indicate if we follow that person. We're more likely to transfer to those we know.

**Comment by sneak** [comment]
I think the warning should be any account with zero posts or a negative rep.

Then, we can suggest that exchanges make a single terse post, which makes them potentially flaggable, which “legitimizes” them in the transfer dialog.

**Comment by bnchdrff** [comment]
more ideas here: https://steemit.com/witness-category/@dragosroua/more-spam-fighting-improvements-are-coming-to-condenser-steemit-ui-that-is

pr WIP here: #1964

**Comment by abitmore** [comment]
> Then, we can suggest that exchanges make a single terse post, which makes them potentially flaggable, which “legitimizes” them in the transfer dialog.

I guess most exchanges won't do this. We can use a white-list for known exchanges.

**Comment by abitmore** [comment]
IIRC rep won't change after the post has been paid out. The proposed approach doesn't prevent phishing accounts from posting something then self-voting before start phishing via transfer memos, or using account names like poloneix which are similar to the real exchange account names.

**Comment by sneak** [comment]
Rep is nonconsensus and I consider it a bug that flags don’t alter rep post-payout.

**Comment by roadscape** [comment]
Closing as outdated
