### ISSUE TITLE
Missing Nav Elements for Mobile

### ISSUE THREAD

**Issue by inertia186** [steemit/condenser#1784]
When looking at one's own `/feed`, the navigation elements next to the logo are missing, when browsing on a small screen.

![image](https://user-images.githubusercontent.com/494368/31205629-77ea460c-a927-11e7-951e-8990d54d247a.png)

On a larger screen, they are present:

![image](https://user-images.githubusercontent.com/494368/31205652-a2b6c040-a927-11e7-9227-bef42a88337d.png)

**Comment by plink01001** [comment]
Is this still an issue?

**Comment by inertia186** [comment]
Fix confirmed.
