### ISSUE TITLE
performance issue: scroll event listener without debounce

### ISSUE THREAD

**Issue by trashhalo** [steemit/condenser#1799]
There are two scroll listeners in condenser. One is debounced one is not. I recommend you add debounce to the second one. Scroll events fire like crazy and the header scroll showed up in the firefox performance monitor, I suspect thats whats causing the site to drop below 60 fps in firefox while scrolling. 

# No debounce
https://github.com/steemit/condenser/blob/7cae6d9ce8e50ed7e2b28d3ff55e6fbe3f3240da/src/app/components/modules/Header.jsx#L35

# Has debounce
https://github.com/steemit/condenser/blob/107f116029b45bf651f46296586cf30d9a3bb785/src/app/components/cards/PostsList.jsx#L136

**Comment by plink01001** [comment]
Is this still an issue?
