### ISSUE TITLE
Re-use cell phone for account verification

### ISSUE THREAD

**Issue by jfolta** [steemit/condenser#1809]
I want to re-use my cell phone with a new user name but can't because "that number is already in use".  How can I stop using the old account (don't care about deleting it or its posts) and use my cell phone for verification with a new account/new user name?  Thx.

**Comment by TimCliff** [comment]
What you are requesting is not supported. There is more information in the FAQ on Steemit.com.

**Comment by jfolta** [comment]
TimCliff, are you sure?  I don't care about deleting the old account or the old posts.  Whatever.  I just want to be able to use my cell phone for a new account so I can create a better username.  Are you sure?

**Comment by TimCliff** [comment]
Steemit pays the account creation fee for one new account per user. If you want additional accounts created, you will be responsible for funding them with the Steem Power necessary to interact with the blockchain. It is not required to provide your cell phone number to create the additional account(s) using this method though. There is more info in the FAQ.

**Comment by jfolta** [comment]
TimCliff - thanks for the clarification.  I appreciate your effort and expertise.  Thanks again.
