### ISSUE TITLE
Frequent long delays on posts, comments, and votes, as well as lost transactions

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1818]
Over the past week, there have been several periods of time when submit activity (posting, commenting, upvoting, etc.) takes a really long time. The website just hangs after an action is taken, and the loading/processing icon just spins. This has happened before the past week too, but it seems to have gotten a lot worse recently.

A lot of times after voting on a post/comment and waiting around 20 seconds, if you upvote something again, it says you cannot upvote twice within 3 seconds.

I replied to a comment, and the page just kept spinning. After about 20 seconds, I refreshed the page and my comment was still there in the UI (unposted). I clicked the submit button again, and it said that I could not comment twice within 20 seconds. I checked the blockchain and the comment was not there. I refreshed a third time and submitted the comment, and that time it went through.

There are also many reports from users where they have commented, posted, upvoted, etc. and the UI shows the action has successfully completed, but then the action is never recorded on the blockchain. After successfully submitting a post, it goes to the created/new page and shows the post there, but then after refreshing a few seconds later, the post is gone.

**Comment by lukestokes** [comment]
Can we please get an update on this? The site has been almost unusable lately. I'm constantly seeing 5XX errors, long load times, lost comments, lost posts, votes not working, console errors on login... it's bad.

This is really discouraging. It's even more discouraging to not have any communication from the steemit team, no site down page, and no status page explaining the issues or what's being done to mitigate them. I want to believe this is a professionally run web service company which takes these issues seriously and cares about the usability of their product and how it's perceived within the community. Please give me reason to believe that.

Could we get some updates from steemitblog or steemitdev? Is the team aware of how bad things are right now with the site? If not, can they please use the site more so they can share in the experience of their users? If so, can they please communicate about it regularly to restore some confidence?

**Comment by TimCliff** [comment]
Luke - the dev team is aware of the issue and and is actively working on addressing it. There have been some discussions in other (steem) GitHub threads, and it looks like some related changes were checked in as pull requests. I can't speak for their communication part of it, or their ETA on a fix, but I know they are actively working on it.

**Comment by lukestokes** [comment]
Thanks @TimCliff. I know this stuff is hard as I've been running my own SaaS for ten+ years. The lack of communication is what concerns me most. I hope they prioritize that.

**Comment by inertia186** [comment]
![](https://media1.tenor.com/images/3d06d6ac5a22d245bce66d453f2fad7c/tenor.gif?itemid=4810969)

**Comment by TimCliff** [comment]
Seems fixed
