### ISSUE TITLE
Missing Posting Authority

### ISSUE THREAD

**Issue by oflyhigh** [steemit/condenser#1820]
From earlier today, we can't post any text which ***contains Chinese characters*** on steemit.com.

We got "Missing Posting Authority" message once we submit post or reply.

![image](https://user-images.githubusercontent.com/25529332/31644700-462e098e-b32a-11e7-816c-6adec984a0ce.png)

**Comment by TimCliff** [comment]
@oflyhigh - the Missing Posting Authority error is unrelated to Chinese characters. Can you log out and then back in and see if you get the same error?

**Comment by TimCliff** [comment]
I discussed with @oflyhigh and was able to reproduce using a test account. It did not let me create a post with ` 哈哈哈` as the subject and body.

**Comment by oflyhigh** [comment]
Thank you @TimCliff 

And this also effect other NO pure English language, such as Korean，Japanese.
So I think it's BUG related to character encoding or String serialization.

**Comment by tcgirl** [comment]
I have the same problems. The posts were created in google docs & hackmd.io. No special characters. 

![selection_092](https://user-images.githubusercontent.com/25617507/31646973-d85e7ec0-b2ca-11e7-9c11-4b3f89e9e92a.png)

![selection_093](https://user-images.githubusercontent.com/25617507/31647031-215da6aa-b2cb-11e7-85c1-26f098dde8c2.png)

I was able to do a short post with 'test' for the title, body & tags. 

https://steemd.com/tx/df0c49d045234afd350811466cd0d59e90156a64

**Comment by bobinson** [comment]
RPC issues ?

**Comment by plink01001** [comment]
Has this been addressed / can this be closed?

**Comment by plink01001** [comment]
This should be addressed. Please re-open if it is still an issue.
