### ISSUE TITLE
Attempt to create account failed with "unexpected token" error

### ISSUE THREAD

**Issue by kbsizer** [steemit/condenser#1823]
![image](https://user-images.githubusercontent.com/7295827/31776459-9755a570-b4b9-11e7-89e2-47b5fa5618cf.png)

**Comment by plink01001** [comment]
Has this been addressed / can this be closed?

**Comment by plink01001** [comment]
Please re-open if this is still an issue.

**Comment by kbsizer** [comment]
Not sure whether "it's fixed" or "I got past it", but it is no longer
blocking me. :-)
