### ISSUE TITLE
New STEEMIT layout POST buttons are very confusing

### ISSUE THREAD

**Issue by alexpmorris** [steemit/condenser#1832]
I recently authored a new STEEMIT post, and kept clicking POST button on the upper-right side to "POST", then tried doing it from a new browser window, etc. before realizing I had to click the lower POST button that was no longer clearly visible by the time I was ready to send my post, especially since **both buttons look nearly identical** to one another.  

As such, I would suggest making it clearer that the toolbar POST button is for going to the "Create a Post" page, and the lower POST button should be used to actually POST your new content.  

Perhaps even better, the toolbar POST button could detect that it's already on the POST page and ask the user "Would you like to submit your POST?"

![image](https://user-images.githubusercontent.com/5326789/31847695-6dc0c40c-b5ee-11e7-9459-260d28634d11.png)

**Comment by originated** [comment]
@alexpmorris Thank you, this is a good suggestion and will be implementing an update

**Comment by 4leem** [comment]
It would be better if we can disable the upper right 'post' button when the post submission page is active.

**Comment by originated** [comment]
Thanks @4leem @alexpmorris a solution has been pushed, this will help with the confusion of double post buttons when posting new content. Closing ticket https://github.com/steemit/condenser/pull/1997
