### ISSUE TITLE
Completed SBD conversion still showing in wallet

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1834]
There is a user who initiated two SBD conversions within the last 4 days. One of them has completed; the other is in progress. The steemit.com wallet page still shows both transactions.

![image](https://user-images.githubusercontent.com/20735105/31852734-8b50a95c-b642-11e7-8c3c-0a7a36a45709.png)

![image](https://user-images.githubusercontent.com/20735105/31852684-929ce83e-b641-11e7-92b5-95443af39a43.png)

![image](https://user-images.githubusercontent.com/20735105/31852709-ee478090-b641-11e7-8b32-5cceac6d63e1.png)

![image](https://user-images.githubusercontent.com/20735105/31852688-a6f4781a-b641-11e7-85e6-54fd5588c9ff.png)

![image](https://user-images.githubusercontent.com/20735105/31852712-fad17cd0-b641-11e7-8396-afb316a90e31.png)

![image](https://user-images.githubusercontent.com/20735105/31852706-da69a972-b641-11e7-89da-1bffedb991a0.png)

**Comment by plink01001** [comment]
Unable to reproduce. Please re-open if happens again.
