### ISSUE TITLE
Stuck on Loading... after comment

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1837]
It happened to me a few times today where I made a comment, and steemit.com never displayed it. It was stuck on "Loading...". In both cases, the comment did make it to the blockchain.

![image](https://user-images.githubusercontent.com/20735105/31857460-fac5b9d2-b6a4-11e7-8d46-f1285b739ed1.png)

**Comment by plink01001** [comment]
Unable to reproduce. Please re-open if it occurs again.
