### ISSUE TITLE
image thumbnails in new UI scale using “fill” instead of “fit longest edge”

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1852]
c.f. https://steemit.com/steemit/@nspart/thanks-steemit-you-just-cropped-the-head-off-most-of-my-models-in-my-thumbnails

**Comment by pkattera** [comment]
Right now, all the previews go 100% width, centered vertically. I think it's not a bad solution for now, but the ideal solution is to let

**Comment by roadscape** [comment]
IIRC, there used to be a 20% north gravity on the centering to help prevent chopping heads.
