### ISSUE TITLE
Make links not able to be clicked for low rep accounts

### ISSUE THREAD

**Issue by FUBAR-BDHR** [steemit/condenser#1854]
With the recent rash of phishing posts and now some malware links to boot it seems like a bit more protection is in order on steemit.  There is already a proposal #1835 but since then the phisher has changed tactics and is now using short links.  Low rep accounts already hide images so why not extend that to links as well.  This could be done by enclosing the links in ` so that markdown converts them to inline when displayed.  Thus the links are not censored and can still be seen just not easily clicked on.  Anyone wanting to go to one can highlight and open that way.  

In addition to low rep a blacklist of known phishing sites should be created.  Any links to know phishing sites would also be hid no matter the rep.  This would no only help block links from compromised high rep accounts but also prevent accidental clicking on posts about phishing attack.  Although people making them mean well many include a link to the phishing page.

**Comment by TimCliff** [comment]
Could this be handled by applying the same link formatting (not having it as a hyperlink and turning it red) if the author has a negative reputation, or if the post/comment has been downvoted? This would be similar to how images are hidden as well.

**Comment by roadscape** [comment]
Thanks for the report. There's been a few measures to prevent problems like this since the issue was filed. If there are any deficiencies in the logic please open a new issue.
