### ISSUE TITLE
yo: change shown to seen

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#1867]
the verdict is in. `mark_shown` should `mark_seen`, etc

**Comment by relativityboy** [comment]
After some discussion we've re-opened issue 48 in yo, and are closing this one.
https://github.com/steemit/yo/issues/48

**Comment by bnchdrff** [comment]
"works for me" does not work for me, still! https://www.youtube.com/watch?v=--wUUJivsk4

i'll work on a fix for this

**Comment by bnchdrff** [comment]
oops wrong issue !
