### ISSUE TITLE
yo: off-screen notifications are marked as shown

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#1868]
if i have 30 unread notifications, and i click on the dropdown, only a few of them are shown in the viewport
 
expected: only the visible notificaionts should be marked as seen.

actual: all 30 of them are marked as seen.

**Comment by relativityboy** [comment]
@bnchdrff - I haven't been able to reproduce this locally when connecting to local yo running branch https://github.com/steemit/yo/tree/mock_api_varied_notifs/

**Comment by bnchdrff** [comment]
"works for me" does not work for me, still! https://www.youtube.com/watch?v=--wUUJivsk4

i'll work on a fix for this

**Comment by bnchdrff** [comment]
possible solution: use react-virtualized or a similar system to render notifications

**Comment by bnchdrff** [comment]
a related issue: if un-shown notifications are loaded by the infinite scroll, they are not marked as shown.

to reproduce:

restart yo & condenser, and go directly to `/@user/notifications/wallet` or some other category

you'll see that the initial batch of notifs are loaded w/ unshown state, and then marked as shown

if you scroll to the bottom of the page, more will load - they have the red dot initially. they are not marked as shown, though, because `markDisplayedShownWithDelay` is only called on mount

**Comment by bnchdrff** [comment]
even if we don't use a virtualized display system immediately, i think we should connect the mark-as-shown action to individual `Notification`s
