### ISSUE TITLE
Add password security notes in the approval email template

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/condenser#1877]
This is not the right repo for this issue and I can't make tickets in steempunks. I'm writing it here following @sneak's recommendation.

Very often we see cases of users losing their password for various reasons: PC crash, stolen
account, no backup, mistyping, etc. Some have even lost their password minutes after activating their new account! I propose to include a detailed explanation about the importance of the password and the different keys. This should be included in the approval email, so users can be better prepared before activating their account.

Here's my draft:
>During your first login, you will be asked to generate a new password. This password (or Owner Key) is the main key to your account which will be holding your funds and earnings. It's the key to your wallet, do not lose it! Because of the strict security measures of Steem, if you lose your password there is no way to recover it and you will be locked out of your account with no access to your funds, permanently!

>Back up your password immediately in an offline storage. Copy it into a plain text file, encrypted preferably, and save it on a USB key. Multiple USB keys are even better. Avoid using a word processor as they may change the character encoding in some rare cases and cause copy/paste problems when trying to log into your account. Do not send your password in emails, because those can often be compromised. The password starts with P5, is 52 characters long and is case-sensitive. The password is case-sensitive. If you write it down on a piece of paper, double check all the characters have the correct case.

>Your account has different keys with different permissions. Please refer to the FAQ's section to learn about the different keys https://steemit.com/faq.html#What_are_my_different_keys_for. We highly recommend you always login with the Posting Key because of its limited permissions to your account, in case you're compromised.

>To retrieve your key set (Active, Posting, Memo):
- Log in with your Owner Key (Password)
- Go to your Wallet, click "Permissions", then click on "Show Private Key" or "Login to Show". Notice that by default, the PUBLIC keys are shown. You need to backup the PRIVATE keys, which all start with 5 (except the Owner Key which starts with P5).
>Never share your private keys with anyone, especially the Owner Key or Active Key. Public keys are safe to share, if needed.
>Good luck and have fun on Steemit.

**Comment by plink01001** [comment]
An issue has been opened in the steempunks repo.
