### ISSUE TITLE
payout amount and vote count are wrapping to the next line sometimes

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1880]
![screen shot 2017-10-28 at 05 34 50](https://user-images.githubusercontent.com/408977/32133220-ca395466-bba1-11e7-8886-65f3184e465f.png)

https://steemit.com/agoric-challenge/@agoric.systems/what-is-the-agoric-challenge

**Comment by originated** [comment]
Adjusted, here is new without wrapping. Closing. PR https://github.com/steemit/condenser/pull/2025

**Comment by originated** [comment]
<img width="626" alt="screen shot 2017-11-17 at 11 33 06 pm" src="https://user-images.githubusercontent.com/1158463/32978137-e3b31d78-cbf0-11e7-8b71-2dbc8e54f8d4.png">
