### ISSUE TITLE
Login fails on Internet Explorer

### ISSUE THREAD

**Issue by VIM-Arcange** [steemit/condenser#1881]
Since the last update, login fails when using Internet Explorer 11

![image](https://user-images.githubusercontent.com/21260036/32134700-30db2932-bbf3-11e7-8b33-55a7c8724ec7.png)

After hitting the login button, page got stuck with "loading ..."

![image](https://user-images.githubusercontent.com/21260036/32134705-361c6f5a-bbf3-11e7-8d8a-d421e36f0b37.png)

**Comment by jnordberg** [comment]
Could you copy the output from the developer console (opens by pressing F12 if I don't misremember). That would help us track this issue down

**Comment by VIM-Arcange** [comment]
![image](https://user-images.githubusercontent.com/21260036/32135138-52c8fb3a-bbfa-11e7-9987-08960a7eed25.png)

**Comment by bnchdrff** [comment]
we're using `Object.assign` rather than the es2015 object spread, which babel will polyfill, rather than use Object.assign directly.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility <-- `Object.assign` is not ie compatible

**Comment by Jolly-Pirate** [comment]
I confirm that bug on IE 11.0.9600 too (Windows 7 64bit).

**Comment by VIM-Arcange** [comment]
Do you plan to fix it or does it mean IE won't be supported anymore?

**Comment by plink01001** [comment]
Is this still an issue?

**Comment by VIM-Arcange** [comment]
@plink01001 Yes, the problem has not been fixed and I didn't got any answer to my last question.

**Comment by plink01001** [comment]
We will review.

**Comment by plink01001** [comment]
This does not seem to cause an issue with the Edge browser.

**Comment by plink01001** [comment]
@bnchdrff was this fixed as part of https://github.com/steemit/condenser/pull/2494 ?

**Comment by VIM-Arcange** [comment]
I testes login with IE11 (v10.0.51 and v10.0.52) on different windows OS (W8, W10, WS2008, WS2012 and  WS2016) and I confirm login is now working.
