### ISSUE TITLE
Multiple URLs aren't clickable in the same paragraph

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/condenser#1885]
When adding more than one URL in the same paragraph, only the first one shows up as clickable, but not the rest. I have to use markdown on all the links to work around that issue.

![bug-linkable urls](https://user-images.githubusercontent.com/4613678/32138773-fce2a6be-bc06-11e7-8937-a1fa9b5b3186.png)

**Comment by bnchdrff** [comment]
just reproduced this locally; verified it isn't a regression caused by https://github.com/steemit/condenser/pull/1839

working on a fix
