### ISSUE TITLE
Followers/ Following page takes long time to load based on number of followers

### ISSUE THREAD

**Issue by hephesthesis** [steemit/condenser#1887]
**Issue**
Followers/ Following page takes long time to load based on number of followers
If the followers / following list is high the page takes very long.
![image](https://user-images.githubusercontent.com/8221343/32145567-eabb40d2-bcf0-11e7-9289-d7edb424eabf.png)

**reason:** 
It takes all the followers or following profiles on page load.
if i am following 10000 people and when i open my following page it takes all the 10000 list on load itself and untill this is done the list is not displayed. 
![image](https://user-images.githubusercontent.com/8221343/32145588-2abdb61a-bcf1-11e7-8c6f-65d41db14c36.png)

**solution:**
Can use pagination for fetching the profiles instead of fetching all the data at first, can fetch only the first page data and if next button is clicked next set of data can be fetched.

**Comment by originated** [comment]
Am reviewing and testing issue

**Comment by roadscape** [comment]
Made some efficiency improvements since this was filed; more to come when we upgrade API
