### ISSUE TITLE
The images hijack script hijacks img data urls causing image display fail.

### ISSUE THREAD

**Issue by muksihs** [steemit/condenser#1888]
The image hijack script on steemit.com (also busy.org and chainbb.com) redirects data src urls for images to steemitimages.com which does not process data urls. Such images display correcty via the esteem app.

Possible fixes:

a) Update the script to not hijack img src urls that start with "data:"

b) Add data url processing to the backend for steemitimages.com.

Start of an example img src url (after hijack) which causes image display failure:

https://steemitimages.com/0x0/data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD ...

**Comment by sneak** [comment]
data URLs are not supported on steemit.com. if anything we will update condenser to simply strip those tags from the doc.

**Comment by aaroncox** [comment]
Curious to know why the lack of support (not that I'm objecting). Is there a security risk involved or should we just not encourage that sort of bloat on the blockchain?

**Comment by plink01001** [comment]
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).
