### ISSUE TITLE
Using https://api.steemit.com for connection result an errors.

### ISSUE THREAD

**Issue by KINGdotNET** [steemit/condenser#1889]
As suggested by steemitdev (https://yehey.org/steemitdev/@steemitdev/update-your-steem-apps-big-changes-coming-for-3rd-party-developers), we should start using the endpoint/url to https://api.steemit.com from the older wss://steemd.steemit.com.

I did, but I see this "/api/v1/csp_violation" in the error logs. Here's what it looks like.

[ Europe - Yehey.org server ]
  <-- POST /api/v1/page_view 2d2bb8e00b64d68bbd85fd3b82
-- /page_view --> ip=2600:8806:600:2c70:ed83:5c3a:4542:a06f uid=2d2bb8e00b64d68bbd85fd3b82 page=/pick_account
  <-- POST /api/v1/csp_violation 2d2bb8e00b64d68bbd85fd3b82
-- /csp_violation --> https://yehey.org/pick_account : https://api.steemit.com/ -- Mozilla/5.0 (Windows 
NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
  --> POST /api/v1/csp_violation 200 5ms 0B 2d2bb8e00b64d68bbd85fd3b82
  --> POST /api/v1/page_view 200 34ms 12B 2d2bb8e00b64d68bbd85fd3b82

Right now, I put it back to wss://steemd.steemit.com and no errors.

Let me know how to correct this issue so I can test it again.
Thank you,
EM

**Comment by Jolly-Pirate** [comment]
add `api.steemit.com` to the `connectSrc` list in default.json, and restart condenser.

**Comment by KINGdotNET** [comment]
That's do the trick. Thank you sir.

Closed!
