### ISSUE TITLE
Added Albums Feature on steemit.com

### ISSUE THREAD

**Issue by podanrj** [steemit/condenser#1896]
![header new.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509465886/sflw9csybht5anef2epi.png)

hi everyone, after three months I became an active **steemit** user, and this needs some good idea refine for **steemit** development.

in fact, my idea is not much different from the one already on **steemit**. however, my idea is to make it easier for users to access **steemit.**

always on the fact, every thing needs **favorite** access. on this access will make us easier to find what the other users desire.

on this occasion, I will give an idea for **steemit** to add **favorite** feature in place of **resteem** feature. but **resteem** feature will be inside.

# Fitur Idea

![fitur.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509460251/axhatuwh9a4nmj1hi9id.gif)

![line podan.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509461210/ejehztmdtmuutfbl2yx1.png)

and this will be visible on the **Profile Page**. and see before and after **Display**.

![tampilan halaman profile.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509460394/cxtk7heudzbyt9fshyue.png)

![line podan.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509461210/ejehztmdtmuutfbl2yx1.png)

then this will be visible in the Feed page.

![tampilan halaman feed.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509460524/acirmplnbvdj3o3g9zwh.png)

![line podan.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509461210/ejehztmdtmuutfbl2yx1.png)

## Added

ok, then what is the virtue of this feature.?
this feature will allow the user to see the **post** only on post added, on **post added** just look post that in enter by the user. view image.

![post added.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509461065/ba28ck70zepp5h9vcayo.png)

when post **added** in klick, then the only visible post that entered by the user.

![line podan.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509461210/ejehztmdtmuutfbl2yx1.png)

## Resteem

then, on **resteem** feature there will be post from other user in **resteem** by user. on this feature will load all post **resteem**. So do not disturb post **resteem** and added by user.

![resteem.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509461601/hxwgx6srwdor8adytbgz.png)

![line podan.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509461210/ejehztmdtmuutfbl2yx1.png)

## Albums

then, on the **album** feature, this will load all the favorite post that the user adds to facilitate the search. does not have to store links in **Notepad** and does not have to **bookmark** in the browser again.

![album.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509462462/enbfld1zxetzujektkw0.png)

![line podan.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509461210/ejehztmdtmuutfbl2yx1.png)

## Example

so how do you think, so easy.? and very well organized in profile page. if by now, the user post is just a mess and mixes with the **resteem** post. so with the idea of this feature I hope it can be a benchmark to provide comfort and development to the user.

![example.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509463583/lfo2jni5dmwgtcf2b9d8.gif)

Ok, maybe this is just what I can explain, hopefully the image that I enter can give easy to be able to understand about how this idea.  there is another idea that I will load, for **steemit**, **utopian**, **wordpress**, etc. It will take time to give the visuals,

I always expect feedback, so feelfree for feedback. regards

![FOOTER.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509464363/zxo7pczx5tm8fpi6cowh.png)

<br /><hr/><em>Open Source Contribution posted via https://utopian.io</em><hr/>

**Comment by TimCliff** [comment]
While this is a good suggestion, the GitHub repository is not the place to make these types of enhancement suggestions. Please review the guidelines for continuing before submitting issues. @sneak to close.

**Comment by podanrj** [comment]
what u mean about ? "Please review the guidelines for continuing before submitting issues"

any link to review..?

**Comment by TimCliff** [comment]
Here is the link:
https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md

It shows up at the top of the page when you go to create a new issue.

**Comment by sneak** [comment]
Please submit feature requests as posts on the blockchain for community discussion. GitHub issues are our task queue.
