### ISSUE TITLE
Using new condenser, not able to upload image.

### ISSUE THREAD

**Issue by KINGdotNET** [steemit/condenser#1899]
When I drag and drop an image, seems it is uploading but when it finished the image is not showing up.
Is this a new bug or I missed something in my config file. 

Anyone?

**Comment by netuoso** [comment]
Should probably clarify if the issue is on your local instance or SteemIt.com As you as questioning about your config, I will make a logical leap and assume you mean local.

You should change the `upload_image` value in the config to `https://steemitimages.com/`

**Comment by KINGdotNET** [comment]
Hi Netuoso,
I have that value on my default.json config file.

**Comment by KINGdotNET** [comment]
This is local instance. 
I have the following settings.

 "img_proxy_prefix": "https://steemitimages.com/",
and
  "upload_image": false, // default
//  "upload_image": "https://steemitimages.com/",  // when I used this setting, it is not even allowing to attach/drag an image.

**Comment by netuoso** [comment]
Then idk what to tell you.

The value `upload_image` is a URL for the [imagehoster](https://github.com/steemit/imagehoster) application. You can see its use here https://github.com/steemit/condenser/blob/107f116029b45bf651f46296586cf30d9a3bb785/src/app/redux/UserSaga.js#L447

It should be https://steemitimages.com

You should also ensure that `https://steemitimages.com` is in the `connectSrc` to allow it to be connected to. Along with the RPC node you use.

This isn't a bug

**Comment by KINGdotNET** [comment]
Thank you sir.
The solution is to change my connectSrc from steemitimages.com to https://steemitimages.com.

Fixed. This is not a bug, but a configuration setting issue.
