### ISSUE TITLE
Dark mode decimal numbers are the wrong shade

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1901]
![298b73c2-cea2-4f21-a44a-b4bc3076b70a](https://user-images.githubusercontent.com/20735105/32262479-cde928ce-becc-11e7-983c-0a95380bef18.png)

**Comment by valzav** [comment]
Hmm.. everything looks good to me. What shade they should be if we want to deemphasize them a little bit?

**Comment by TimCliff** [comment]
Oh, I didn’t know the intent was to deemphasize them. They were a gray shade instead of the white, as shown in the screenshot. I thought it was a bug 🙂. If this is working as expected, it is fine to close.
