### ISSUE TITLE
Steemit Design Update - A 'Borderline' Idea!

### ISSUE THREAD

**Issue by deveerei** [steemit/condenser#1902]
![Untitled-1.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509502054/pqzsoj5jzlry9stlgesa.gif)

I have [posted about the updates](https://steemit.com/steemit/@deveerei/new-steemit-look-spotted-in-steemitstage-1509407806-181477) on Steemitstage recently and it didn't take them long to update Steemit.com with those new updates and even more.

They have revealed the new Logo and color scheme. We also have night mode on top of it!

<center>
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509499468/pqohi9q4htav9z3qkyht.png)
<sub>Steemit.com Night Mode</sub>
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509499490/s2mwroqzg0r2mfpuauyr.png)
<sub>Steemit.com Day/Normal Mode</sub>
</center>

***

I was surprised about the Night Mode - that made me like the whole new look of Steemit. I must say that they did a splendid job in this update. It made me like almost everything that has been updated. There's just one thing that I think needs fixing. This made me come up with an **"Idea"**.

<center> ![Light On_96px.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509499723/tuzist0esq9fkfrpsfg9.png)</center>

Notice the colored shadow on the right side of the content box:

<center> ![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509499787/x5oqsyzrlc2gb1raivxu.png)</center>

It matches that of the **"Post"** button to Create a New Post:

<center>
![post.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509502169/v2tngfxw8tydqhuhv2rl.png)
</center>

It does look good but it looks weird, reason being: TOO ASYMMETRICAL . Once you scroll down, it just looks like a weird line on the side, it doesn't look like a shadow for the content box:

<center> ![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509499912/vuyggvtbtudsdvqdfy0s.png)</center>

# <center> Here comes the Lightbulb: </center> <h1>

<center>![22222222222222.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509500977/ugcdoh9sgmto7dbxpcib.png)</center>

Instead of a shadow, why not just make a border go around the content area. I have played around a bit with Photoshop and made a mock-up of how it would(or should) look like if that were the case.

#### <center> Day/Normal Mode: </center> <h4>

<center> ![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509500275/l7krth5qvjcgdkldgaoe.png)</center>

#### <center> Night Mode: </center> <h4>

<center> ![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509500346/oofjgrestedubrarxxeq.png)</center>

Here is another set of mock-ups to show you how it looks like when you scroll down in a list of posts. It looks more symmetrical and this design makes a lot more sense rather than having a weird line on one side being lonely and all:

#### <center> Day/Normal Mode: </center> <h4>

<center> ![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509500591/xly52kinism4szumesnm.png)</center>

#### <center> Night Mode: </center> <h4>

<center> ![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509500755/yco85qfo1wyj0havx0ge.png)</center>

***

Do you see the difference between having just one of those bright bars and having two of them? 

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@deveerei/steemit-design-update-a-borderline-idea">Utopian.io</a></em><hr/>

**Comment by sneak** [comment]
Your images aren't showing up, and this isn't the place to discuss feature suggestions; this is a bug tracker for things that *must* be fixed.

**Comment by sneak** [comment]
For making feature suggestions, please make the suggestions via posts on the blockchain.

**Comment by deveerei** [comment]
Hi, sorry about that. I did the post using Utopian.io. It seems it's being synced.

https://utopian.io/utopian-io/@deveerei/steemit-design-update-a-borderline-idea
