### ISSUE TITLE
payout and vote count still wrapping when they shouldn't be

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1904]
<img width="1455" alt="screen shot 2017-11-01 at 08 22 42" src="https://user-images.githubusercontent.com/408977/32266144-24c43754-bede-11e7-84f5-07939b9dedea.png">

**Comment by valzav** [comment]
Why they shouldn't' be wrapping? We cannot fit everything into a single line so something should wrapp..

**Comment by originated** [comment]
This has been resolved in PR https://github.com/steemit/condenser/pull/2025, closing ticket.
