### ISSUE TITLE
Favicon and Power Up Logo Not Changed

### ISSUE THREAD

**Issue by codingdefined** [steemit/condenser#1905]
Edit: It looks like the favicon is fixed, but the Power Up Logo still unchanged

![](https://steemitimages.com/DQmaXbb6FLurVHJoDpV5z5jvxSWDwi7z3jbCzMx4JG31ztL/image.png)

<hr>

Just a little while back Steemit has changed its logo from Blue to Green. But the Favicon as well as the Power Up, button Logo has not been changed on the trending or hot page and even from the Blog section.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509502584/pxj1alq5f4dfyyp8xejr.png)

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509502479/yraluyreruxdcnemn7uv.png) 

When you open the Post you can see the change on the Power up logo.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509502673/ybqrgki716iztpe8l2ni.png)<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@codingdefined/favicon-and-power-up-logo-not-changed">Utopian.io</a></em><hr/>

**Comment by sneak** [comment]
This is working as intended. The post receives Steem Power.

**Comment by gopesh-sharma** [comment]
@sneak My question was why there is two logo in two places. When you open up the Blog post which is Power Up it shows other logo, whereas when you open any feed it shows other logo.

**Comment by codingdefined** [comment]
@sneak  My question was why there is two logo in two places. When you open up the Blog post which is Power Up it shows other logo, whereas when you open any feed it shows other logo.
