### ISSUE TITLE
New Steemit Language parameter: saving new language bug

### ISSUE THREAD

**Issue by stoodkev** [steemit/condenser#1907]
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509520351/tgzootqfgm8v6ybbcv0n.png)

The new Steemit interface is here and brings cool features such as a night mode and translations in French, Spanish, Russian, Italian:

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509520486/uwrp1k1f2uvqgrrxx9cx.png)

That is a tiny bug I found out but it is one of these little annoying things that disturb the user experience.
Upon changing the language, you cannot immediately save your changes.

In this example, I just changed the language from French to English and this is what I get:

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509520692/dsinyxftlr3dn7j7jgd7.png)

As you can see, the Update button is disabled, I need to change something to another input of the form in order to have it enabled which is quite annoying. That would be really easy to fix that by adding a listener for changes of languages and enabling this button in the listener.

Hope this helps. If it is not fixed soon, I might propose a Pull Request when I have time.
Enjoy your SteemFest!<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@stoodkev/new-steemit-language-parameter-saving-new-language-bug">Utopian.io</a></em><hr/>

**Comment by plink01001** [comment]
When you update the language setting in the settings, it automatically saves. There is no need to click the "Update" button unless you are updating your public profile settings.
