### ISSUE TITLE
Old logo still appears in the blog post feed (meta info level)

### ISSUE THREAD

**Issue by surfermarly** [steemit/condenser#1908]
<img width="361" alt="logo" src="https://user-images.githubusercontent.com/33285318/32275102-d2838930-bf01-11e7-8643-41e08e0d2f9a.png">

<p>Screenshot was taken in my own blog steemit.com/@surfermarly on 1st of Nov 12:40 (UTC-1)</p>

**Comment by pkattera** [comment]
@surfermarly This is actually intentional for now. We've kept the 'Steem' logo to denote that the post is 100% powered up (which was the icon that we used previously).

Ideally, we need to design a new icon (something like the '100' emoji 💯 ) to indicate that a post is 100% powered up.
