### ISSUE TITLE
Bug Report for SteemIt : Mobile Page Design error

### ISSUE THREAD

**Issue by landlove** [steemit/condenser#1911]
###  Bug Report for SteemIt

1. You connect https://steemit.com on your cell phone
2. If you go down to the bottom of the contents, you will see the screen below.
3. The contents shown in the red box are contents that should not come out originally.
4.  However, it is displayed due to incorrect css design.
     This error is currently found on the iPhone and Android.

![2.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509523611/huzaqioj7azf1chuds7x.png)

Environment
Model : Lg-G5
Browser: Google Chrome 62.0.3202.62 (64-bit)
OS:  android 7.0

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@jungs/bug-report-for-steemit-mobile-page-design-error">Utopian.io</a></em><hr/>

**Comment by bnchdrff** [comment]
to clarify, this happens when you:

* go to steemit.com
* click on a post title (it opens in an overlay)
* scroll to bottom of post

the overlay odes not extend to 100% of document height and leaves a transparent portion at the bottom, where the non-overlay part of the page is visible

**Comment by roadscape** [comment]
Not using the overlay so is now a non-issue
