### ISSUE TITLE
Bug Hunting: Steemit Editor Irritating Problem Found Using Android Chrome | utopian-io Contribution #01

### ISSUE THREAD

**Issue by philiparniebinag** [steemit/condenser#1913]
![Screenshot_20171102_124514.png](https://steemitimages.com/DQmUFisQmjLDox8dzaG6D4oECGGfGMyWyf5bKa3RwoiZxXF/Screenshot_20171102_124514.png)

Hello Steemians, this is my fist #utopian-io contribution under the category of **Bug Hunting**.

Posting directly from steemit using editor is somehow the best choice for all the beginners in blogging. In my case, I'm not really fan in markdown and html method that's why almost of my articles posted in steemit is relying to much from editor method.

Lately, I've been encountered many problem using editor. Here is list of the problem I've been encounter so far using android chrome:
1. The second word in every stanza will automatically capitalize the first letter. Instead you will write **"This is"**, but in editor it will automatically capitalize the letter **"I"** in word **"is"**, so the result will be **"This Is"** and not **"This is"**
2. If you insert a word in between two words, the inserted word will just delete itself. If you only wrote **"This the"**, then you want to insert **"is"** in between the two words to make it **"This is the"**, the word **"is"** will automatically erase itself if you directly write it in between the space that separated the two words.
3. Data will not update if the spacing after written word is not applied. If you wrote **"This is the"**, the **"the"** word will erase itself if you click another word without hitting space after the word **"the"**.

#### To continue, I will share to all of you the alternatives method how to deal the problem found.
Just a reminder only that this method I will share to all of you is just only an alternative. It is best if the problem will be solved itself.

![Screenshot_20171101_191034.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509542920/rkmswq6ejscmeftwbddk.png)

#### So, here are methods I found useful:
1. In every stanza, the 2nd word of the sentence will automatically capitalize itself. Like for example, if you write **"This is"**, the letter **"I"** of word **"is"** will automatically become capital when you hit space for the next word. So, the resulted text will become **"This Is"**. This method will be solve by writing the two words connected, like this **"Thisis"**, then hit the space button. Go back to the connected words then separate it by spacing. From **"Thisis"** to **"This is"**.
2. When you want to write **"This is the"**, but you missed **"is"** and just wrote only **"This the"**. If you insert the word **"is"** directly between **"This _ the"**, that won't work as the inserted word will just erase itself when you go to another word after. The best thing to do in this case is to insert the word **"is"** connected before the last word, like this, **"This _the"**. So, the sentence will become **"This isthe"**. Just apply the first alternative to separate the connected words.
3. If you write **"See you."** without hitting the space after period of **"you."** word. The text will not update and instead the **"you."** word will be erase automatically. Therefore, the best method in this problem is to hit space always after written words.

That's all for now. This is my first contribution to #utopian-io and I hope you'll find this article helpful. I will give my full effort to contribute more useful information that can help the Steemit community. If I found any bug, I will inform you all right away.

Note: This problem I encountered using android chrome browser, with 19 mbps wifi connection and android marshmallow version.

Best regards,
@philiparniebinag

![](https://steemit-production-imageproxy-upload.s3.amazonaws.com/DQmPxTPVFf3T5WiU46rycx14QgUdHg9FaENTDcbc5ELySdd)<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@philiparniebinag/bug-hunting-steemit-editor-irritating-problem-found-using-android-chrome-or-utopian-io-contribution-01">Utopian.io</a></em><hr/>

**Comment by sirrius-a-b** [comment]
I really tried to replicate these bugs but I was not able to. I tested on Linux Mint 18.1 and Nexus 7(2013).

**Comment by roadscape** [comment]
Thanks for the feedback @philiparniebinag. We will try to address these issues with a new editor.
