### ISSUE TITLE
Tags are not showing in Mobile Night Mode View on Steemit

### ISSUE THREAD

**Issue by codingdefined** [steemit/condenser#1915]
When I load the Steemit Page in the mobile browser and toggle it to the Night mode, the tags are not showing. A blank white screen is shown. I am using screen 414 X 736.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509612746/omfdqfyrceuzrjn2nhhf.png)

Tags are working fine in the normal mode

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509613130/l5ce92qoitekpybcxsox.png)

### Expected Behaviour

The tags should be shown like below where I can see trending, hot, new and promoted.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509612987/ypj50xqqqaecdfjoyoyp.png)

### Steps to Reproduce

1. Open Steemit.com in the mobile browser.
2. Toggle the View to Night Mode
3. Click on All tags.

The tags will not be shown whether you are in home, hot, trending or new.

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@codingdefined/tags-are-not-showing-in-mobile-night-mode-view-on-steemit">Utopian.io</a></em><hr/>

**Comment by plink01001** [comment]
This appears to have been solved in https://github.com/steemit/condenser/pull/1935. Please re-open if it is still an issue.
