### ISSUE TITLE
Several issues with the new layout on IE11

### ISSUE THREAD

**Issue by JefPatat** [steemit/condenser#1922]
Today I tried to use new layout of the new steemit interface for the first time and there are several issues on IE 11.

I switched to IE11 because of some other issues I was having an noticed the site is not really supported on IE11. 

#### Issue 1
The top bar overflows the columns beneath.
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509695884/xdofrwxho9zudx7rt2em.png)<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@jefpatat/several-issues-with-the-new-layout">Utopian.io</a></em><hr/>

#### Issue 2
The posts images also don't show in the overview. See image above.

#### Issue 3
The signin page is empty:
![](https://steemitimages.com/DQme7VeNtmPBfEGjpNH8aQeLqEv6qy5NZoEHBqU6QXdPJgq/image.png)

#### Issue 4
Clicking signup makes the whole title bar empty
![](https://steemitimages.com/DQmT2Nffc8ieLAwaFhZJXt6xwWkaPAaFHtyqCX58BcVQSf9/image.png)

#### Issue 5
Clicking the menu button does not work, nothing happens
![](https://steemitimages.com/DQmcDB7MMqvXoypSoBYpSCfU3sCGR8ygpcFErk3mVosm8Yt/image.png)

**Comment by plink01001** [comment]
@bnchdrff was this addressed in https://github.com/steemit/condenser/pull/2494 ?

**Comment by roadscape** [comment]
I believe these issues have been resolved; if not, please reopen this issue.
