### ISSUE TITLE
Bug: Highlighted Comments In Steemit's NightMode Have Low Contrast & Are Unreadable

### ISSUE THREAD

**Issue by propertunist** [steemit/condenser#1923]
When a URL is followed directly to a reply on Steemit, a page is displayed with shows the comment and also a link to 'view full context' for the reply. When that link is clicked, the full page of the original post is displayed and the relevant reply is highlighted with a coloured background. The new night mode of steemit has not been updated to recolour this highlighted background area so that the white text of the night mode remains visible.

The background colour needs to be changed for this situation so that it is darker and so that the text component of the reply is readable.

1. activate night mode in Steemit.com.
1. open a URL that points to a specific reply (such as: https://steemit.com/tag/@elear/re-ura-soul-idea-for-dtube-direct-import-of-videos-from-youtube-channels-playlists-20171103t091949935z)
1. click 'view the full context'.
1. the incorrectly coloured background is visible for the relevant comment.

OS: Linux Fedora
Browser: Firefox

![comment highlight](https://i.imgur.com/Jm6dQVf.png)
<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@ura-soul/bug-highlighted-comments-in-steemit-s-nightmode-have-low-contrast-and-are-unreadable">Utopian.io</a></em><hr/>

**Comment by relativityboy** [comment]
@pkattera

**Comment by steevc** [comment]
I get this in Chrome too. I really like night mode apart from this

**Comment by plink01001** [comment]
Has this been addressed / can this be closed?

**Comment by sirrius-a-b** [comment]
I could not replicate this issue.

**Comment by TimCliff** [comment]
This was fixed in https://github.com/steemit/condenser/pull/1935 which has been applied to production. The issue should be closed.
