### ISSUE TITLE
scrolling too far down is possible in post modal overlay

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1925]
![screen shot 2017-11-04 at 04 21 40](https://user-images.githubusercontent.com/408977/32402252-c4fd55ee-c117-11e7-9bef-58cf30550b55.png)

![screen shot 2017-11-04 at 04 21 46](https://user-images.githubusercontent.com/408977/32402253-ca47a266-c117-11e7-993c-c30e270c65fc.png)

**Comment by sneak** [comment]
![screen shot 2017-11-04 at 05 00 08](https://user-images.githubusercontent.com/408977/32402489-17a84e02-c11d-11e7-9cc0-dca6f09d2121.png)

not just modal, might be a recent regression for the downvote dialog overflow fix?

**Comment by relativityboy** [comment]
Thankfully the overlay is dead.

**Comment by sneak** [comment]
You killed the overlay without fixing the underlying bug that lead to its existence in the first place.
