### ISSUE TITLE
Transfer history length varies between accounts

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/condenser#1928]
The transfer/wallet history seems incomplete and highly variable between accounts. When looking at my own history, it goes back to 2 months (although I've been transacting since 4 months!). When checking other accounts history, it can vary from a few days up to months.

Examples:
"carlobelgado" (spammer account) goes back to 2 months, with a lot of transactions
"dan" goes back 4 months
"gandalf" has a few transactions and goes back to 4 months
"sneak" goes back to 9 months
"bittrex", 20 days (lots of transactions)
etc...

**Comment by plink01001** [comment]
The wallet transaction history does not show an unlimited history. The amount of historic transactions that are shown for a particular account depends on the account history. This is not considered a bug, although could be improved upon with a future enhancement. Closing for now, as there are no immediate plans to change this.
