### ISSUE TITLE
Bug at promotion text box. using Mobile phone.

### ISSUE THREAD

**Issue by ruahtheking** [steemit/condenser#1930]
# Bug at promotion text box. using Mobile phone.
While promoting one of my posts. in steemit using my mobile phone I encounter a small but issuable bug.
I think it's need to be fixed as soon as possible for mobile users that always using this features.
![Screenshot_2017-11-05-14-50-40.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509950504/imizesxon0a0hdffcwot.png)
the text box width is too narrow. I guess the text box needed a specific width and not sizeable. so when using mobile its width is fixed. 

To change the width of the textbox you need to enable your screen rotation and rotate it to make it wider. 
![Screenshot_2017-11-05-14-51-24.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509950646/zyzgciwca6mjxozklvr1.png)

While confirming the promotion and rotate it to its original. heres the screenshot.
![Screenshot_2017-11-05-14-52-00.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509950706/z7t4uhpgowqfrcoisyru.png)

To fix this box, you can change its width into fixed state and not auto.
Device : Samsung Note 3
Browser : Chrome for Android. Ver. 56.0.2924.87
<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@ruah/bug-at-promotion-text-box-using-mobile-phone">Utopian.io</a></em><hr/>

**Comment by TimCliff** [comment]
Duplicate issue: https://github.com/steemit/condenser/issues/1520

**Comment by plink01001** [comment]
Closing duplicate
