### ISSUE TITLE
Image upload results in Bad Request 400 error

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/condenser#1931]
Pasting an image URL in a Post or Comment results in Bad Request 400 error and a broken image link in the preview box. Happens on steemit.com and in a separate condenser instance.

![image upload bug](https://user-images.githubusercontent.com/4613678/32451374-a06066ee-c2e4-11e7-9316-a3600c47fe81.png)

**Comment by plink01001** [comment]
Is this still an issue?

**Comment by netuoso** [comment]
Willing to bet the `imagehoster` was having intermittent issues. Can not reproduce.

**Comment by plink01001** [comment]
Closed for no response. Please re-open if this is still an issue.
