### ISSUE TITLE
Bug: Condenser website kills my browser when loading a post with huge number of comments

### ISSUE THREAD

**Issue by ianpark** [steemit/condenser#1933]
## Problem:
Condenser website cannot open a post with huge number of comments. An obvious example is:
https://steemit.com/poctest2/@philipnbrown/genesis-poctest2

![Screen Shot 2017-11-06 at 16.46.16.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509987134/qyixsnbqamv6lxxtjsu1.png)

On Chrome:
Chrome opens the post and hangs for long time, and then it fails to recover from the infinite loop in the script, then crash.
On Firefox:
Forefox opens the post and hangs for long time, and shows the dialog to choose to stop the script or close the window.

## How to reproduce:
1. Open the URL below using Chrome or Firefox
https://steemit.com/poctest2/@philipnbrown/genesis-poctest2
2. Your browser will hang and you will encounter the situation that were explained above.

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@asbear/bug-condenser-website-kills-my-browser-when-loading-a-post-with-huge-number-of-comments-1932">Utopian.io</a></em><hr/>

**Comment by bnchdrff** [comment]
leaving this open til it's completely solved

**Comment by relativityboy** [comment]
I suggest creating new issues for improvements to initial fixes. Re-using issues is a lot like re-using facial tissues.

**Comment by roadscape** [comment]
Would be solved by https://github.com/steemit/condenser/issues/3194
