### ISSUE TITLE
"Beta" word should always be present with steemit logo on top bar

### ISSUE THREAD

**Issue by thrize** [steemit/condenser#1939]
There seems to be 4 adaptive top bar styles which depend on screen width:

.1. Wide has everything
![steemit_wide](https://user-images.githubusercontent.com/25388336/32489027-8d1e3468-c3a6-11e7-8fbf-b4a453f5d817.png)
.2. Medium size drops the beta under steemit logo
![steemit_medium](https://user-images.githubusercontent.com/25388336/32489033-93e16ad6-c3a6-11e7-9b02-812be860df07.png)
.3. Short size drops trending, new, hot, promoted
![steemit_short](https://user-images.githubusercontent.com/25388336/32489038-9787975a-c3a6-11e7-9a53-9fd745be6d14.png)
.4. Very short size (mobile) goes into mobile mode
![steemit_mobile](https://user-images.githubusercontent.com/25388336/32489052-a08f1e68-c3a6-11e7-9fca-bf2d7ca7a2fc.png)

New new website is great for the adaptive sizing and styling. But you should always have the word "beta" present here when in beta, it should not be an optional bit of information. Really it should be incorporated into the logo itself and switched out with an updated logo when out of beta.

I bring this up in part because some people have been talking and think it's out of beta, probably because they have small screens or use mobile. It's misleading.

**Comment by steevc** [comment]
On mobile we just have the logo. Should that have 'beta' too?

**Comment by thrize** [comment]
Yes I definitely think so. Making the screen size smaller does not promote the web app out of beta, that's the logic I'm following. It's important information.

**Comment by relativityboy** [comment]
We've been progressively moving away from 'beta' branding. Condenser (like most software these days) is an evolving thing, with new features and new challenges popping up on a somewhat frequent basis.

Expect the remaining beta tags to disappear in the coming months.

**Comment by thrize** [comment]
I know it's not high priority, but you're not using good reasoning. Have it consistently or don't have it at all, that's simply the point. Just because it will at some point not be in beta is no excuse.
