### ISSUE TITLE
Steemit FAQ and Welcome page : some links don't work 

### ISSUE THREAD

**Issue by inoue-a** [steemit/condenser#1940]
Currently some links of FAQ and welcome page don't work.
Maybe it happened after design change.

This is a list of inactive links:
### FAQ
- On the contents table, 2 lines from the bottom of each section (except Accounts and Disclaimer) cannot work.
For example, in **General**
![](https://s20.postimg.org/6sy6h1qd9/image1.png)

- All of ^ links which placed in bottom of each subsection (except Disclaimer).
![](https://s20.postimg.org/l37qsytzh/image2.png)

- On each subsection, links on the bottom line cannot work.
For example in "How long does the account approval process take?", steemit chat link does not work (#help link is active).
![](https://s20.postimg.org/h9eajmpgd/image3.png)

#### Welcome page

-  A link of FAQ page in foreword
![](https://s20.postimg.org/4xbe5wwe5/image4.png)

- All of ^ links which placed in bottom of each subsection (except Third Party References).

- On each subsection, links on the bottom line cannot work.

I think all causes are the same.
But I couldn't find the cause in their source file.

----

These are my environment.
PC1:
OS: Windows 7 64bit
Web Browser: Google Chrome (62.0.3202.75), Internet Explore (11.0.9600.18816) and Firefox (56.0.2) 

PC2:
OS: Windows 10 64bit
Web Browser: Google Chrome (62.0.3202.75), Microsoft Edge (40.15063.674.0) and Firefox (56.0.2)
<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@inoue/steemit-faq-and-welcome-page-some-links-don-t-work">Utopian.io</a></em><hr/>

**Comment by TimCliff** [comment]
I will review these.

**Comment by plink01001** [comment]
Closed via https://github.com/steemit/condenser/pull/2049 (still waiting to be approved and merged)

**Comment by relativityboy** [comment]
@plink01001 - issues should not be closed until resolving code is in master and on the way to production.

**Comment by bnchdrff** [comment]
i just edited the description -- u have the power to do that too i think
