### ISSUE TITLE
White Screen Bug Under Steemit Post

### ISSUE THREAD

**Issue by arietm** [steemit/condenser#1941]
![2017-11-07 at 21-24-05.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510064932/ebalb4pkekwsutkyh4yt.png)

Hello everyone
I found some bugs that happened on page post in steemit. sometimes bugs like that. when we open a friend post one of the steemit, I see there is a white screen below.

you can see and open the steemit and try with night mode, you can see bugs sometimes happen like that. I feel there is still a shortage in the steemit view for the post.

And I also suspect if the white screen under it is a column for comments. and that's where bugs look

This also I have tried in my own page that apparently experienced the same thing. you can see the gif image I gave below

<center>
![ezgif.com-video-to-gif (3).gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510075368/rte4n0eyebexb5zvee0n.gif)
</center>

Hopefully this report can be useful and can be completed as soon as possible. that's the bug I see today when I open the steemit with desktop and via chrome.

<center>Author : @arie.steem
Adsactly & Utopian-io</center>

Communite With Us In
Discord ADSactly :https://discordapp.com/invite/6jAXNuu
Discord utopian.io :https://discord.gg/72bPmxk
<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@arie.steem/white-screen-bug-under-steemit-post">Utopian.io</a></em><hr/>

**Comment by roadscape** [comment]
This should no longer be an issue; otherwise please re-open this ticket
