### ISSUE TITLE
User Reported Issue - Pictures not showing up in old posts

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1944]
A user reported an issue where a lot of images from their old posts are not showing up.

Here is an example post:
https://steemit.com/travel/@catwomanteresa/travel-with-catwoman-teresa-2-bangkok-chocolate-ville-2

Here is an example of one of the images that is not showing up:
![image](https://user-images.githubusercontent.com/20735105/32522200-059779f6-c3dc-11e7-890f-6c7548062147.png)

The image URL for that image is:
`https://img1.steemit.com/1000x1000/https://steemitimages.com/DQmYcBcePJA2j12sCGT7qPSrxiifeQcsJCze5ouLoVuGt3T/728.jpg`

**Comment by roadscape** [comment]
We can't do anything about this. Issue seems to be that users are referencing the resolved/time-sensitive direct image URLs
