### ISSUE TITLE
The UI should encourage comments to be meaningful

### ISSUE THREAD

**Issue by relativityboy** [steemit/condenser#1945]
After conversations with content creators in steem and users of steemit at SF2, it's apparent that comments like "nice" or "yay" do not meaningfully add to the conversation, and can cause reader fatigue.

Add a minimum character limit on posts in the UI of steemit.

**Comment by TimCliff** [comment]
I have run into a few situations where short comments have been useful. A simple example is replying yes/no to a question. Would it be possible to handle this by setting up an array of patterns that would get blocked, instead of just basing it entirely off length?

**Comment by sneak** [comment]
algorithm/heuristic suggested in #1966, closing this one in favor of that one
