### ISSUE TITLE
Some short commented post in Steemit have white marks below using night mode

### ISSUE THREAD

**Issue by robin-ho** [steemit/condenser#1949]
There are some steemit articles that have white marks on the lowest corner, if you scroll down the lower part section.

Testing :
Operating System : Windows 7
Browser : Google Chrome

![robin-ho.JPG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510196855/xavj5c2qozfim5s90gje.jpg)

![robin-ho2.JPG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510197319/n3c8ohxzitnbg1zb40rg.jpg)

Link of the post that have problem : https://steemit.com/family/@robin-ho/treasured-memories-buwan-ng-wika

Other sample  post that have errors :
https://steemit.com/plants/@robin-ho/my-province-life-i-like-this-kind-of-plant
https://steemit.com/travel/@robin-ho/treasured-memories-kirk-beach-resort
https://steemit.com/minnowbooster/@robin-ho/i-got-myself-a-minnowbooster-selfgoat

This could be minor error but we are happy that this would be fixed.
Thank you. 
Note : This error is applicable to all new post with less comments.

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@robin-ho/some-short-commented-post-in-steemit-have-white-marks-below-using-night-mode">Utopian.io</a></em><hr/>

**Comment by sirrius-a-b** [comment]
This was already reported here: #1941

**Comment by plink01001** [comment]
Closing duplicate
