### ISSUE TITLE
Common Steemit Minor Bugs and Errors we usually ignore

### ISSUE THREAD

**Issue by mind-blast** [steemit/condenser#1950]
Here are some following minor common errors that i have found :

**CATEGORY TAG INPUT**

Minor Bug or Error :

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510187929/kvxthito9mqaaya0w3dx.png)

When inputting a space accidentally on tag section , an error message appear .Message should not be "Please use only 5 categories" instead it should be "space entry invalid" or equivalent.

Suggested Solution :

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510188420/ephshpox18knvqnxszvb.png)

I think it is more appropriate to have accurate error message so the user will know what should be changed and what to be deleted.

**SPACING MESSAGE ERRORS**

How to replicate : 

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510188759/uwkl9p3kga4rlzxtmqsh.png)

Once you have flagged the person and you want to revert your action , the confirmation modal shows incorrect spacing .

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510189130/bondosojwxdxzqjo0unx.png)

Incorrect spacing message error "Removing your votewill reset your curation rewards for this post"

Suggested Solution :

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510189308/njcil6z49jchwmisrlfq.png)

Spacing should be in correct format "Removing your vote will reset your curation rewards for this post"

**SWITCHING EDITOR ERROR**

This error has been long before i started , i usually used Raw HTML and Editor sometimes but if you mixed it you will probably get an error.

Replication of the Problem :
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510190206/bo3vwi3hdjbhuyzarq21.png)

You created a sample image like heart using Editor (WYSIWYG)(What you see is what you get)

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510190251/fw1suo4ppeodx0gxcwer.png)

Now you switch back to raw html to have some modification on the html

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510190295/lafi1jp5rldheehp23pc.png)

After that you switch back again to the WYSIWYG Editor and you will found out that center alignment is being ignored.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510190504/tbu5udfpxcgfmidpxlnq.png)

Switching back to raw html and adding image via drag-and-drop or browsing image from your local folder.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510190544/fh2bdhqdawqchershou1.png)

After that when you switch back to WYSIWYG Editor , you will see that the code itself is displayed instead of the image .

**My Suggestion**

It would be better if both WYSIWYG and Raw HTML are usable vice-versa at the same time , there should be some code translation when you change interfaces.<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@robin-ho/common-steemit-minor-bugs-and-errors-we-usually-ignore">Utopian.io</a></em><hr/>

**Comment by originated** [comment]
Thanks, spacing issue on flag, and voting operations, has been resolved in a recent PR. (Can be removed from this list)

**Comment by roadscape** [comment]
Some of these issues have been addressed; please create a new issue for any items which remain. Thanks!
