### ISSUE TITLE
No action Bottoms are functioning on Mobile Device(Steemit)- Bug Reporting

### ISSUE THREAD

**Issue by katteasis** [steemit/condenser#1959]
Hello everybody, I have just encountered another big problem with steemit on my phone’s default browser.
I had just reported a bug about not showing the action bottom on the normal screen but it can be seen when we rotate a mobile to widescreen.

https://steemitimages.com/0x0/https://steemitimages.com/DQmTuxB9dnsWujPXgnGoaPCHR64mqHyQTHUn9TKsZVWgiQD/image.png

Yes, I found the bottoms, then I clicked on sign-in the bottom. But it didn’t take to the login page, instead, it was all loading for a longer time than expected so I tried touching other bottoms. Then I found that none of the bottoms are functioning on a mobile browser.
I tried every bottom available there (only while on widescreen). But only the search bottom open the new page. Other bottoms, namely sign up, sign in, and Menu (icon) doesn’t work. When I click on those icons they show respective url of Login/ logout and post bottoms but they don't open at all.

## See the screenshots below, Non of the action Bottoms are working.

![IMG_20171110_095544.jpg](https://steemitimages.com/DQmZd4dBTNVwfTR5Uhz7314j7qNYsKWRggY77RDfZ2TUmqZ/IMG_20171110_095544.jpg)

**Which means we simply can't use steemit.com on our mobile phone.Well, in my opinion, this is really bad thing. People are shifting to mobile devices and they perform most of the actions from mobile devices nowadays. How frustrating is it for a user can't be able to browse anything on his/her mobile device?**

![IMG_20171110_095609.jpg](https://steemitimages.com/DQmVcdaruEmjgi5KRs5AmPdVRHb7QsuHmfKfquo9ugby7Te/IMG_20171110_095609.jpg)

## I hope this video Explains more about the issue/bug

https://youtu.be/39wRUxgTUvc

## Hardware/Software Information

```
Model: colorsx114
Android Version: 4.4.2
Browser: Android Default
````
____

# Thank You.!!!

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@katteasis/no-action-bottoms-are-functioning-on-mobile-device-steemit-bug-reporting">Utopian.io</a></em><hr/>

**Comment by plink01001** [comment]
Combine with https://github.com/steemit/condenser/issues/1961
