### ISSUE TITLE
Condenser allows copypasta spam

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1966]
Please implement a heuristic-based blacklist of comment bodies that cannot be posted using condenser.

The rule:  Comments under 20 characters that include "nice" or "great" or "good" or "follow".

I suggest giving an error, and redirecting the user to a new FAQ item that says not to post tiny, content free comments consisting of "nice post" or "good information" or such.  For that, direct them to upvote the post instead.

**Comment by relativityboy** [comment]
Came here to create this issue. Well done.

**Comment by bnchdrff** [comment]
wait ... i'm working on this though??!

**Comment by dragosroua** [comment]
Suggestion: include reputation as a parameter in heuristics?

(from here, where I tried to pick the brains of my followers about this this: https://steemit.com/witness-category/@dragosroua/more-spam-fighting-improvements-are-coming-to-condenser-steemit-ui-that-is)
