### ISSUE TITLE
Nsfw content showing even though I have options set to always hide

### ISSUE THREAD

**Issue by codename-littleboy** [steemit/condenser#1968]
Nsfw stands for not safe for work. Generally, it refers to porn and other disruptive content (violent death photos or similar things). Steemit has an option to always hide this type of content, that are posted in the nsfw tag. I have it set to always hide. Here's a screenshot of my preferences:

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510422485/otitd1tturanbnhoho3d.png)

But I am still seeing such content show up when I visit the feeds of people who have resteemed such content.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510422201/xlxxm6tdww17gf3swd8k.png)

I hope steemit developers will work on this and fix it.

## Actual behaviour

Nsfw content appear even when preferences are set to always hide them.

## Expected behaviour

All nsfw content posted in the nsfw tag are hidden to users who have choose to hide them.

## How to reproduce

The first screenshot is from [@littleboy/settings](https://steemit.com/@littleboy/settings). Visiting the page with always hide set in preference.

The second screeshot is from [this page](https://steemit.com/@sportic).

OS: Windows 7 

Browser: Chrome 60

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@littleboy/nsfw-content-showing-even-though-i-have-options-set-to-always-hide">Utopian.io</a></em><hr/>

**Comment by sneak** [comment]
Those are hidden behind the clickwall. This is working as intended. “Hide” in this sense means “don’t show the thumbnail or title”, not “remove from the list”.

**Comment by sneak** [comment]
The alignment is all off for NSFW clickwall boxes, though. :/
