### ISSUE TITLE
night mode problem

### ISSUE THREAD

**Issue by bitcoiners** [steemit/condenser#1978]
Night theme has a problem displaying text in tables. White on white is hard to see. 
![steem-night-mode](https://user-images.githubusercontent.com/38520/32732268-9532e92e-c8be-11e7-9817-aead8a892238.png)

**Comment by pkattera** [comment]
Hi @bitcoiners – I'm unable to replicate this bug on Mac (Chrome, Safari, Firefox or Opera). Can you please let me know what OS, browser and version you're using? Also, just to confirm, this is on the

**Comment by bitcoiners** [comment]
Ubuntu 17.10, 
chrome 
Version 62.0.3202.89 (Official Build) (64-bit)
wallet page

**Comment by bitcoiners** [comment]
Same issue in Firefox or Yandex browser!

**Comment by Kiaazad** [comment]
This is caused by "Steemit More Info" addon, if you disable the addon the colors will show correctly.

**Comment by bitcoiners** [comment]
Oh, so this is not a condenser problem, but "Steemit More Info"?  I will have to report it to it's github repo. Thanks.

**Comment by Kiaazad** [comment]
already sent a pull request to fix it, but another report might speed up the change
