### ISSUE TITLE
condenser still seems to be slow serving static files

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1980]
<img width="891" alt="screen shot 2017-11-13 at 19 44 19" src="https://user-images.githubusercontent.com/408977/32748214-1c1a7e0c-c8ab-11e7-830c-8b626e9c4014.png">

Please test and benchmark and troubleshoot.

**Comment by bnchdrff** [comment]
xposting from slack:

try testing with some parallel requests: ``for i in {1..15}; do (curl -w "%{time_total}\n" -so/dev/null -H 'pragma: no-cache' -H 'accept-encoding: gzip, deflate, br' -H 'cache-control: no-cache' --compressed https://steemit.com/favicons/favicon-16x16.png &) ; done`

notice that steemit.com slows down bit by bit:

```
0.502
0.621
0.886
2.618
2.621
4.759
5.787
5.857
6.015
6.057
7.799
7.866
9.861
12.010
15.934
```

but running `yarn run production` and hitting that server locally doesn't choke like that:

```
0.024
0.029
0.023
0.027
0.042
0.022
0.053
0.012
0.046
0.021
0.013
0.032
0.010
0.024
0.011
```

**Comment by sneak** [comment]
Why don't we get condenser out of the business of serving static files?

**Comment by bnchdrff** [comment]
ideally we'd have a static asset only subdomain `static.steemit*.com` and serve everything in `/static/` from there, optionally

immediately we can configure sdc-frontend to serve everything in `static/` with the practices outlined at https://www.nginx.com/resources/admin-guide/serving-static-content/ rather than passing the requests to condenser. @Gandalf-the-Grey @jnordberg

**Comment by bnchdrff** [comment]
@Gandalf-the-Grey @jnordberg should i take a stab at implementing these nginx config changes in sdc-frontend?

**Comment by sneak** [comment]
Not yet; the koa webserver should first and foremost be a lot more performant than it is; fixing the static files issue in the frontend will mask that.  This could be a performance issue that is affecting other parts of the site (then again, it might not and it's just that serving static files from a dynamic webapp is dumb).

Could you please find out which it is, first?  The solution you propose (serving static files via nginx) is obviously the correct one, but we need to understand the problem fully first.

http://catb.org/jargon/html/magic-story.html

**Comment by bnchdrff** [comment]
word, i'll do some profiling. agree that it'd be best if the performance issue was fixed on the koa layer so that local dev can benefit also.

**Comment by jnordberg** [comment]
I think what you're seeing is the burst rate limiting in nginx kicking in on steemit.com

**Comment by jnordberg** [comment]
https://github.com/steemit/sdc-frontend/blob/master/site.conf.template#L675

**Comment by bnchdrff** [comment]
ah yup that'd do it :) glad i didn't start fishing for red herrings in koa

**Comment by bnchdrff** [comment]
should we make a different zone for static files?

**Comment by sneak** [comment]
Not yet, it hoses our whole build process, and favicon needs to be served from the root of the same domain.

Let’s tune the rate limits on sdc-frontend so I don’t encounter them in normal site usage, eh?

**Comment by jnordberg** [comment]
https://github.com/steemit/sdc-frontend/issues/22

(sneak you where the one who picked the limits ;)
