### ISSUE TITLE
Only show share buttons after a user interaction

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#1990]
Avoid loading the Facebook SDK or showing the share buttons until the user shows some sort of intention to use them.

**Comment by goldibex** [comment]
@bnchdrff what do we need to do to accomplish this?

**Comment by bnchdrff** [comment]
the blessing of a PM & a few spare hours

**Comment by bnchdrff** [comment]
( i'm on it :) )

**Comment by bnchdrff** [comment]
looks like we used to lazyload fb and then switched to not doing it: https://github.com/steemit/condenser/commit/4b989a2b274cecbfdeb872603476f368e405e33f
