### ISSUE TITLE
White Screen Columns Edit Post Move

### ISSUE THREAD

**Issue by arietm** [steemit/condenser#1991]
![Capture_2017_11_15_02_06_56_694.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510687084/riwhju4jr8pf33mik5za.png)

Bugs are very disturbing to us in the activity on a website, I want to report a bug that often happens when I want to do activities like want to reply to a comment or want to make a post.

This bug occurs when the resize for the write column in the steemit, there is a sign below the line next to the right to adjust the size we want, but there is an irregular white screen bug in the position.

<center>![ezgif.com-video-to-gif (8).gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510686925/bku32bizbdufmauhkncr.gif)</center>

I hope this bug can be fixed so we do not have to repeat the post or refresh page. because at the time it has happened like that I have to refresh page as before

Hopefully this information I provide can be useful for all of us who have experienced something like this.

Browser : Google Chrome
Windows 10
No Extensions

<center>
Author : @arie.steem
Adsactly & Utopian-io
</center>

Communite With Us In
Discord ADSactly :https://discordapp.com/invite/6jAXNuu
Discord utopian.io :https://discord.gg/72bPmxk/n/n

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@arie.steem/white-screen-columns-edit-post-move">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by plink01001** [comment]
Possibly the same bug as https://github.com/steemit/condenser/issues/1941

**Comment by roadscape** [comment]
Hi, if this is still a problem please open a new issue. Thanks!
