### ISSUE TITLE
add minnnowbooster and it's associates to BadActorList

### ISSUE THREAD

**Issue by inquiringtimes** [steemit/condenser#2004]
# Issue
minnowbooster is an upvotebot on steem.  minnnowbooster is a typo squatter that has been taking advantage of simple mistakes. connected with this account are:

minnowbooste
booste
randwhale
minnowboooster
blockrades
blocktraades
blocktradse 
randwhale
minnnowbooster create account openledgerdex (show details)
minnnowbooster create account bittresx (show details)
minnnowbooster create account polobiex (show details)
minnnowbooster create account hitbtcexchange (show details)
minnnowbooster create account livecoinnet (show details)
minnnowbooster create account polonoiex (show details)
minnnowbooster create account bbittrex (show details)
minnnowbooster create account changellly (show details)
minnnowbooster create account pololniex (show details)
minnnowbooster create account btitrex (show details)
minnnowbooster create account minnowwbooster (show details)
minnnowbooster create account poloniew (show details)
minnnowbooster create account livecoin.com (show details)

![](http://imgur.com/85htFvol.png)

probably beyond the scope... but it seems this account is fond of @starke 

# Solution

Add the accounts typo squatting to the BadActorList for warning.

# Summary

Minnnowbooster is surrounded by a host of typosquatters.

@minnowbooster is an actual service that users send money to. Some users are making typo mistakes and sending money to a scam or inactive account. There are also a number of other typosquatting accounts associated with the minnnowbooster account. This change adds the violating users to the BadActorList so the sending user is warned before burning their SBD.

**Comment by originated** [comment]
Thanks @inquiringtimes updates will be out shortly, closing ticket.

**Comment by inquiringtimes** [comment]
awesome... I realised some of those might already be on the list and came back to edit it to make your job easier... that was super quick.
