### ISSUE TITLE
Typo in the flag popup

### ISSUE THREAD

**Issue by codename-littleboy** [steemit/condenser#2008]
When I click flag in a post I have already flagged, a popup appears that says, "Removing your **votewill** reset curation rewards for this post". There is a typo in it and it is in the words vote and will. There is supposed to be a space between the two words.

After the flag is removed, if I click on the flag button again, this message is shown:

>Changing to a down-votewill reset curation rewards for this post

Another similar typo I guess. This is shown in the below gif image:

![4. Typo in the flag popup 17.11.2017.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510859898/qncxmitrb2izybgvaztl.gif)

Expected behaviour:

Their should be no typo in the popup that appears after you click downvote on a downvoted post.

Actual behaviour:

There are typos in the popup that appears after you click downvote on a downvoted post.

How to reproduce:

1. Go to a post page. 
2. Click on flag.
3. Remove flag.
4. Again click on flag.

OS: Windows 7
Browser: Chrome 58
<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@littleboy/typo-in-the-flag-popup">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by originated** [comment]
Thanks @codename-littleboy, this error was actually happening on various voting operations as well not just flagging. It's been fixed. Closing. PR https://github.com/steemit/condenser/pull/2017
