### ISSUE TITLE
The page doesn't focus on the comment when browsing to a comment link

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/condenser#2011]
When browsing to a comment link, for example https://steemit.com/roadmap2018/@steemitblog/steemit-roadmap-2018-community-input-requested#@drakos/re-steemitblog-steemit-roadmap-2018-community-input-requested-20171116t210955021z, the page doesn't focus on the comment but stays at the top. 

In the previous condenser version (from october), this works fine. For example https://yehey.org/roadmap2018/@steemitblog/steemit-roadmap-2018-community-input-requested#@drakos/re-steemitblog-steemit-roadmap-2018-community-input-requested-20171116t210955021z

**Comment by TimCliff** [comment]
Duplicate of https://github.com/steemit/condenser/issues/1946. A PR has already been created/merged.

**Comment by plink01001** [comment]
Closing duplicate.
