### ISSUE TITLE
Scam Account Impersonating A Known Exchange 

### ISSUE THREAD

**Issue by Team-Steem** [steemit/condenser#2012]
@openledgerdex = Scam Account
@openledger-dex = Known Exchange

https://steemit.com/@openledgerdex/transfers 
https://steemit.com/@openledger-dex/transfers

I know it's not a bug but I thought I would mention it anyway.

**Comment by TimCliff** [comment]
@Team-Steem - is it something you can create a PR for? Here is a similar example: https://github.com/steemit/condenser/pull/2006

**Comment by Team-Steem** [comment]
I'll contact you in private for more precision on how to pull this off. Pun intended.

**Comment by originated** [comment]
I've handled this, all set. Closing. PR https://github.com/steemit/condenser/pull/2016
