### ISSUE TITLE
User "scroll up" impossible for a few seconds after following some hash links

### ISSUE THREAD

**Issue by relativityboy** [steemit/condenser#2013]
If the user follows a hash link where the target element is located on the page such that the element cannot be scrolled so to the top of the viewport, it is impossible for the user to scroll 'up' for a few seconds.

The user should be able to scroll up immediately after clicking on such a link.

**Comment by bnchdrff** [comment]
i'm having trouble reproducing this behavior; can you give an example link?

**Comment by bnchdrff** [comment]
@relativityboy how can i reproduce this bug?

**Comment by relativityboy** [comment]
Whoa. Didn't see you chatting there. 

Surf directly to any post page using `#<some comment>` link on a high-performing condenser instance. There needs to be enough content on the page that scrolling up is possible when at that link, but not so much that scrolling down is possible (aka, the attempted scroll location should not _actually_ be able to hit the top of the viewport)

Perf-wise - The page need to auto scroll to the link within a second or less. 

As soon as you hit the page, attempt to scroll 'up' the page will fight you for a couple seconds.
