### ISSUE TITLE
Steemit shows error page before post loads

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2015]
When I type in a Steemit URL directly, or click on it from an external chat page such as steemit.chat or slack, it shows this page briefly before the page loads:
![image](https://user-images.githubusercontent.com/20735105/32924180-f87fb842-cb00-11e7-8420-32a6b4de3695.png)

**Comment by TimCliff** [comment]
Users in the help channel of steemit.chat are also reporting that the issue occurs when Steemit links are shared in Facebook.

**Comment by Jolly-Pirate** [comment]
Happens also when refreshing the page.
