### ISSUE TITLE
Hash links not scrolling, very slow load time on refresh, IE11 buggy

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/condenser#2022]
- Clinking hash links (comments/replies) or visiting them from external sources doesn't scroll to them; the page remains at the top. The scroll occurs **after** refreshing the page (F5) [Firefox, Chrome].
- Refreshing the page is very slow (too much avatars and images to load), before it scrolls to the hash link.
- IE11 doesn't scroll hash links at all, even after refreshing.

**Comment by bnchdrff** [comment]
thanks for reporting & providing clear testable cases! we will be working on a comprehensive fix for these scroll bugs.

**Comment by relativityboy** [comment]
@Jolly-Pirate - I've been unable to reproduce your bug in Chrome or Firefox when coming-in from external sources and being sure to wait a second or three.
example urls: 
* https://steemit.com/steem/@davidpakman/great-interview-with-steemit-s-andrew-levine-talked-cryptos-and-steemit#@andrarchy/re-artwatch-re-davidpakman-great-interview-with-steemit-s-andrew-levine-talked-cryptos-and-steemit-20171120t222508375z
* https://steemit.com/steem/@davidpakman/great-interview-with-steemit-s-andrew-levine-talked-cryptos-and-steemit#comments

We've implemented a 'better' scrolling solution that attempts to take into account scrolling behavior on previous pages within the site. When the the servers are experiencing heavier traffic and take a while to respond, it can result in a slightly longer delay that was experienced previously, but this difference is temporary, as we're actively working issues to improve server performance under those conditions. 

If you can provide urls that regularly reproduce this problem in chrome and FF latest, I'd be happy to take another look.

**Comment by relativityboy** [comment]
@bnchdrff - Something noticed when in-page & cold typing what might be an expected hash link 
ex: `#comments` the router doesn't pickup the change. (the url that works is `##comments` ugh) We'd previously decided to stay with using `#` as the prefix for hash-linkable ids, because someone had made that decision a while ago and it was the path of least resistance. But I think it's really time for us to follow a consistent standard. We should replace the hash with a short string, or eliminate it entirely. Opine?

**Comment by Jolly-Pirate** [comment]
@relativityboy, you can try with any page, for example in the /recent-replies of any account, click on the replies links and see. Either they take too long to scroll to the hash, or not scroll at all.

**Comment by plink01001** [comment]
@Jolly-Pirate several updates have been made for IE 11. Can you please report back the latest status of the items listed in this issue?

**Comment by roadscape** [comment]
If issues persist please reopen.
