### ISSUE TITLE
Adding new line in code block

### ISSUE THREAD

**Issue by WhiteRaidho** [steemit/condenser#2027]
## Issue
During writing post in Steemit I added Code Block:
![bug1.PNG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1511052066/tlwakulxkoakg3uvseos.png)

Next, I'm going to Raw HTML editor to do some changes.
![bug2.PNG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1511052165/nlqnnnpgui17qdbeacvi.png)
###### *(In second line you can see \<br>, I don't add this. It was added automatically.)*

Return to Editor mode causes that you have one new line between in your code.
![bug3.PNG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1511052900/xox0yti7f7w0ksyi6c0v.png)

It doesn't happen if you have not clicked to this code before going to Raw HTML.

I am using Google Chrome v62.0.3209.94 (64-bit) on Windows 10.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@raidho/adding-new-line-in-code-block">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by roadscape** [comment]
The editor needs a complete overhaul
