### ISSUE TITLE
Views count is slow to update with hundreds of views

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/condenser#2041]
With posts that have a lot of views (e.g. ~1000), the views counter takes about 10 seconds to appear after a refresh.
For example: https://steemit.com/cryptocurrency/@sonny.dharmawan/the-cryptocurrency-tax-fairness-act.

To reproduce: browse to the post, scroll down to the views area, press F5.

**Before**
![1000-views-before](https://user-images.githubusercontent.com/4613678/33107496-8da1e99c-cf05-11e7-9888-39275812385e.png)
**After ~10 seconds**
![1000-views-after](https://user-images.githubusercontent.com/4613678/33107500-90b69ee8-cf05-11e7-9519-f5f28f59cb60.png)

**Comment by roadscape** [comment]
Views count is gone
