### ISSUE TITLE
Bug on Steemit Mobile - Failed to redirect the notification to destination page on google chrome for android.

### ISSUE THREAD

**Issue by adlyjailani** [steemit/condenser#2048]
![](https://itsblockchain.com/wp-content/uploads/2017/11/Untitled-design-9.jpg)
Illustration: Steemit Mobile | [Image Source](https://itsblockchain.com/steemfest-update-steemit/)

## Issue
I got a problem with Steemit Mobile on my Android Smartphone. The case is when I click the notification on the top of the main screen, I was redirect to the wrong destination page. 

For example, I was notified by a comment from @joanstewart via this link > https://steemit.com/life/@joanstewart/4tceus-thank-you-steemianshttps://steemit.com/life/@joanstewart/4tceus-thank-you-steemians, but when I click on the notification I was redirect to this link https://steemit.com/@adly.jailani/feed.

And the problem always happen like that.

FYI, I'm using Google Chrome for Android Mobile (v. 62.0.3202.84). But the problem doesn't happen on another web page, only on @steemit mobile.
![Screenshot_20171122-231336.jpg](https://steemitimages.com/DQmRbu9JF7MSG7vcrqViVuUbhQJBZ7j6mPuc1CSGgSKLqpz/Screenshot_20171122-231336.jpg)
*Link Source (Notification).*

![Screenshot_20171122-225058.jpg](https://steemitimages.com/DQmPd61YUyHVccsDfZsYYE5HLGRcRjiVDLmLigG9wAhmR4j/Screenshot_20171122-225058.jpg)
*Destination of the direction.*

## Additional Information
To make the analysis process can be easier to do, here are some additional information for Google Chrome Dev. Team.

* Smartphone Type / Device Name: Samsung Galaxy J7+ ;
* Model Number : SM-C710F/DS ;
* OS Version : Android Nougat version 7.1.1.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@adly.jailani/bug-on-steemit-mobile-failed-to-redirect-the-notification-to-destination-page-on-google-chrome-for-android">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by roadscape** [comment]
Notifications are currently disabled
