### ISSUE TITLE
Voting slider doesn't appear when changing from upvote to downvote

### ISSUE THREAD

**Issue by littleboy0k** [steemit/condenser#2051]
If I try to downvote a post I upvoted before, the warning message appears and asks me to confirm. Confirming by clicking ok will smash a 100% downvote. This is shown in the gif image below:

![Voting slider doesn't appear when changing from upvote to downvote](https://res.cloudinary.com/hpiynhbhq/image/upload/v1511495957/o90apddnqs8mn4htuysq.gif)

As you can see in the image, the voting slider is not appearing. -_-

Expected behaviour: 

The voting slider for downvote should appear if a user is trying to change from upvote to downvote.

Actual behaviour: 

The slider doesn't appear. -_-

How to reproduce:

1. Visit a steemit post and upvote it.
2. Click flag.
3. Confirm by pressing ok in the warning message for changing to downvote.

OS: Windows
Browser: Google Chrome	61.0.3163.91 (Official Build) (64-bit)
JavaScript: V8 6.1.534.37
User Agent:	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@littleboy/voting-slider-doesn-t-appear-when-changing-from-upvote-to-downvote">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by roadscape** [comment]
Is this still an issue?

**Comment by littleboy0k** [comment]
> Is this still an issue?

No. I am closing it.
