### ISSUE TITLE
[#SteemitBugs] Thumbnail image appears randomly, not the top image on a post.

### ISSUE THREAD

**Issue by adlyjailani** [steemit/condenser#2055]
![](https://image.shutterstock.com/z/stock-photo-video-hosting-website-movie-streaming-service-digital-photo-album-709087018.jpg)
Illustration of Image Thumbnail | [Image Source](https://www.shutterstock.com/image-photo/video-hosting-website-movie-streaming-service-709087018?irgwc=1&utm_medium=Affiliate&utm_campaign=Hans%20Braxmeier%20und%20Simon%20Steinberger%20GbR&utm_source=44814&utm_term=)

## Issue
A common problem that has been often occurred in @steemit is: We expect that the top picture in our post will be as default thumbnail image in the post list, but which appear after instead of another image.

I guess it's a bug that should be fixed soon by steemit dev team, because it wasn't happen always but sometimes.

## Bug Summary
For example, just point your cursor to this address: https://steemit.com/@adly.jailani. Then you will see the tumbnail of the post that's titled [[#roadmap2018 - part 2] Adding Follower Feeds Menu on Steemit.com ](https://steemit.com/utopian-io/@adly.jailani/roadmap2018-part-2-adding-follower-feeds-menu-on-steemit-com) as shown below:
![Bugs on steemit thumbnail.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1511670754/ylby4xwd7yqmy1bv6qpt.jpg)

You know that in the post I have put 3 image, and I hoped the image that appear as its thumbnail isn't it, but the first (top) image. See the screenshot as described below:
![Bugs on steemit thumbnail 1.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1511671393/wsxl5muij52dkszpgdqw.jpg)

It should be remembered that thumbnails have an important role to the attractiveness of an article. Sometimes the blog visitors wouldn't open a post link, just because the thumbnail isn't match with the title of the post.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@adly.jailani/steemitbugs-thumbnail-image-appears-randomly-not-the-top-image-on-a-post">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by roadscape** [comment]
Should be resolved, please open a new issue if this is not the case.
