### ISSUE TITLE
BADACTORSLIST Add Request - Disable SBD Transfers to @bellyrub - Bot no longer active and taking all funds off Steem

### ISSUE THREAD

**Issue by mikepm74** [steemit/condenser#2063]
<h3>Issue</h3>

The Voting Bot @Bellyrub has gone rogue, been transferred, or otherwise become a SBD suck on the platform.  While various users are attempting to get the word out for people to stop sending funds to this account in hopes of an upvote from the bot.  While the bot may still be functioning (I am unwilling to send it money to test) the delegation which was granted from @freedom has been withdrawn and the maximum upvote is only $0.09 when the minimum fee for the upvote is $1.00 SBD.  

<h3>Solution</h3>
Please disable payments going to the Bellyrub account to protect users who may not have seen any of the posts regarding the bot no longer functioning as promised until and unless the current and rightful owner of the @bellyrub account comes forward and makes amends for the last 48 hours of issues.

<h3>Summary</h3>
Until such time as @zeartul or the supposed @bellyrub Buyer steps forward with a proposal to pay off all debts and make all bellyrub votes as promised, the @bellyrub account should be restricted from receipt of any transfer of STEEM or SBD.  

Thank you!

**Comment by TimCliff** [comment]
I submitted a pull request for this. 

If it is accepted, it will **not** prevent users from sending funds to the account, but it will give them a warning:
![image](https://user-images.githubusercontent.com/20735105/33357918-01861eac-d48b-11e7-8fa3-d0f34a3679d4.png)
