### ISSUE TITLE
for logged in users, only open the comment reply box once

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#2074]
"if you click ‘Cancel’ it disappears; cast a vote, and it reappears"

**Comment by neander-squirrel** [comment]
On android the page automatically jumps to reply box as it gets focus once the post loaded.
Why do you have to open the reply box without touching "reply"?

**Comment by bnchdrff** [comment]
we're reverting some buggy code, sorry about that @neander-squirrel

**Comment by originated** [comment]
@bnchdrff The default/show reply was implemented from another ticket request, the idea was to improve engagement(Comment engagement has gone up) - This can be tweaked more. I agree with the above, but if your viewing a different post I believe those rules shouldn't apply. Thoughts?

**Comment by sneak** [comment]
Comment boxes shouldn’t disappear once they have appeared.

**Comment by pkattera** [comment]
@sneak The whole open / close comment box is an unnecessary interaction. Also, the 'reply' link is kinda hidden amongst a bunch of other links and icons. 

Let's leave the comment box open by default and remove the ability to compress it.

Also, a few other visual tweaks:

<img width="1540" alt="screen shot 2017-12-14 at 10 19 42 am" src="https://user-images.githubusercontent.com/1121139/34002614-aa3f2c58-e0b8-11e7-9fb7-595fda0c2c19.png">

Thoughts?

**Comment by pkattera** [comment]
Regarding the autofocus bug on Android, is it possible to do something like add a hidden form field to the top of the page to avoid the page automatically scrolling down? Or we could tab-index="-1" on the comment box until a user starts scrolling down the page?

**Comment by originated** [comment]
Thanks @pkattera definitely agree. I'll update your style suggestions & android issue.

**Comment by roadscape** [comment]
Closing as outdated
