### ISSUE TITLE
"Reveal this post" text gradient change is backwards

### ISSUE THREAD

**Issue by realnedscott** [steemit/condenser#2077]
![snip20171130_7](https://user-images.githubusercontent.com/18314477/33450247-c1bc7e28-d5d0-11e7-8595-d09e17be1204.png)

**Comment by roadscape** [comment]
Seems to be resolved :+1:

**Comment by jredbeard** [comment]
This currently looks like this:

![Screen Shot 2019-04-25 at 2 48 57 PM](https://user-images.githubusercontent.com/23157604/56760667-b35db280-6769-11e9-8e9d-cd8d7a3afd67.png)

Or in non-dark-mode:

![Screen Shot 2019-04-25 at 2 52 37 PM](https://user-images.githubusercontent.com/23157604/56760720-ca040980-6769-11e9-8f3e-4cdcbe2d6e8f.png)
