### ISSUE TITLE
use "prettier" to automatically format codebase

### ISSUE THREAD

**Issue by goldibex** [steemit/condenser#2081]
Code formatting in condenser consumes an unhealthy amount of developer cognitive burden. Therefore we should do the following work:

1: ADD PRETTIER
- [x] add prettier to devDependencies
- [x] set up prettier with some reasonable conventions
- [x] create a new npm script called "fmt" that runs prettier

2: RUN PRETTIER
- [x] run Prettier over the codebase
- [x] Make sure Prettier doesn't break anything
- [x] make Prettier a precommit hook

After 2, all existing pull requests will be conflicted out.

BUT to resolve the merge conflicts we only need to fast-forward each branch to 1 and run prettier. We could even do this automatically for all outstanding PRs.

**Comment by bnchdrff** [comment]
additional step for `2: RUN PRETTIER` can be
- [ ] sync up eslint rules with what prettier does, and add it back to pre-commit hook
