### ISSUE TITLE
first letter of username is truncated in title

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#2107]
![screen shot 2017-12-06 at 17 48 09](https://user-images.githubusercontent.com/408977/33689527-d05fa84c-daad-11e7-8858-21da06e875e9.png)

**Comment by originated** [comment]
@sneak can you please double check this?
<img width="860" alt="screen shot 2017-12-13 at 6 49 27 pm" src="https://user-images.githubusercontent.com/1158463/33973209-7f39e84a-e036-11e7-91dd-f7e595ddbaf3.png">
 I can't seem to reproduce see screenshot of what i'm seeing.

**Comment by sneak** [comment]
I can't reproduce this because the new url scheme branch isn't deployed on dev
