### ISSUE TITLE
blogPost is not a valid schema type

### ISSUE THREAD

**Issue by DennisAlund** [steemit/condenser#2118]
The blog post articles are marked up with the Schema.org type `blogPost` which is not a valid type. The correct one should be `Blog`.

# Error
![blogPost is not a schema type](https://user-images.githubusercontent.com/2051607/33750102-96763cee-dc0c-11e7-9d24-d31aeb53035d.png)

# No Errors
![Blog is a valid schema type](https://user-images.githubusercontent.com/2051607/33750060-5ccb27b6-dc0c-11e7-9a23-fb105a378242.png)

**Comment by bnchdrff** [comment]
closed by #2119 -- thanks so much @DennisAlund !
