### ISSUE TITLE
Unable to reach comments that are nested more than 7 levels by clicking link

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2135]
When I get a reply to a comment chain that is more than 7 levels deep, I am unable to get to the comment by clicking the link. 

Example can be found here:
https://steemit.com/witness-category/@timcliff/timcliff-s-updated-witness-application#@dialsamai/re-timcliff-re-dialsamai-re-timcliff-re-dialsamai-re-timcliff-re-dialsamai-re-timcliff-re-dialsamai-re-timcliff-timcliff-s-updated-witness-application-20171206t030128224z

Also, I know the default behavior is to take the user to the fully loaded page and jump to the comment, but there is another way it is implemented here. If you open the link, it takes you to a page where the comment itself is the top level of the page, and the user has the option to either view the "direct parent" or the "full context".
https://steemit.com/witness-category/@dialsamai/re-timcliff-re-dialsamai-re-timcliff-re-dialsamai-re-timcliff-timcliff-s-updated-witness-application-20171204t034208285z

This seems to be inconsistent behavior. I'm not sure which way you want to use, but it should probably work the same throughout the site. My personal preference is to have it work the way where it only loads the comment, and the user has the option to view more. It seems more efficient than loading the whole page, and it also doesn't run into the issue reported here: https://github.com/steemit/condenser/issues/2098.

**Comment by bnchdrff** [comment]
i think the magic number is actually 7: https://github.com/steemit/condenser/blob/master/src/app/components/cards/Comment.jsx#L321

**Comment by relativityboy** [comment]
@TimCliff - as @bnchdrff mentioned && linked above, the magic number is '7', and was most likely chosen for performance and anti-spam reasons.

As to the two links you posted, they're two completely different links; different ways of viewing content. One is a "hash link" for deep-linking in a post's comment section, and the other is a "perma-link" for viewing (or sharing) a very specific comment. 

If there _use_ somewhere on the site is not good, our could be better, please describe that.

**Comment by TimCliff** [comment]
The main issue is with the first link. That is the link from my reply tab, and when I click on it, it doesn’t take me to the comment.

The second link was provided as an example of how maybe it could be implemented. If there is an alternate way to fix the issue with the first URL, I’m fine with that.

**Comment by TimCliff** [comment]
This was addressed by https://github.com/steemit/condenser/pull/2676
