### ISSUE TITLE
Steemit cant login after verification

### ISSUE THREAD

**Issue by niquid** [steemit/condenser#2138]
Hello i created a account called niquid. I verified with sms. i then verified with email. I still can not login into steemit this seems like a great idea and hope this gets fixed.

**Comment by TimCliff** [comment]
Please ask for help in the “help” channel of Steemit chat.

**Comment by olo2552** [comment]
@niquid  I don't think it's condencer problem - even if your bug is valid it seems more like a system backend bug. Condencer is only a layer beetween steem system and a user - a form of presenting data, not the logic itself.  
Can someone draft of close this issue?

**Comment by plink01001** [comment]
Closing issue, as all signup functionality has been converted to the new https://github.com/steemit/faucet.
