### ISSUE TITLE
MarkNotificationRead probably shouldn't be a component

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2139]
https://github.com/steemit/condenser/blob/master/src/app/components/elements/MarkNotificationRead.jsx

A funny lil component, basically uses the componentDidMount lifecycle hook to dispatch an action but has no visual component ...

**Comment by gl2748** [comment]
Will probably be removed when old notification system is removed.

**Comment by bnchdrff** [comment]
see #2103; this issue can be closed
