### ISSUE TITLE
User settings Update button becomes spinner before appropriate

### ISSUE THREAD

**Issue by relativityboy** [steemit/condenser#2142]
The Update button on the user settings page becomes a loading spinner after the user clicks it and after a pwd modal opens but before the update call is actually made. That's bad UI.

Worse - if the user decides not to input their password but instead closes the modal update button remains a spinner. A page reload is required to get it back.

An interim solution was proposed in #2030 but does not cover the case where a user closes the modal with a mouse click.

<img width="689" alt="screen shot 2017-12-12 at 5 03 36 pm" src="https://user-images.githubusercontent.com/599528/33913228-94349ba6-df5e-11e7-933e-fb0166bdf913.png">

**Comment by roadscape** [comment]
Settings now live on wallet, closing
