### ISSUE TITLE
Load forever upvote button on error

### ISSUE THREAD

**Issue by alex-osman** [steemit/condenser#2150]
## Upvote button loads forever
When encountering an error upvoting, there is no feedback to the user and the upvote button loads forever.
![out.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513138191/vjosnfqjrw5ppzewfclb.gif)
In this case the error was: 
```javascript
{
  code: 10,
  message: "Assertion Error",
  name: "assertion error",
  stack: Array(6)
}
```
The error in the stack is:
```
"_db.head_block_time() < comment.cashout_time - STEEMIT_UPVOTE_LOCKOUT_HF17:
Cannot increase payout within last twelve hours before payout."
```
This is shown in the console but is not shown on the frontend.  Therefore a user doesn't know why this is loading forever.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513138580/xcrlup93ed7nm1wvidup.png)

There must be some error handling added to account for this.

This was encountered in Google Chrome

## To Reproduce:
To reproduce this error you must encounter an error.  An easy way is to try and like a comment within 12-hours before its payout date.  For example, if a comment says "Payout in 15 hours", you will not encounter the bug.  If a comment says "Payout in 8 hours" - you will encounter this bug.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@walnut1/load-forever-upvote-button-on-error">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by pkattera** [comment]
Please follow @sneak's suggestion above.

For completeness, I just wanted to document another solution to this that we may be able to do in the future:

- The upvote button could be directly associated with an upvote counter.
- Any time after the 12 hour period starts (including after the payout period), when a user hits the upvote button, the upvote counter could be incremented, along with a contextual message stating that the upvote didn't affect payout

![upvote](https://user-images.githubusercontent.com/1121139/33963264-00f34696-e01a-11e7-9769-677850663d40.png)

**Comment by alex-osman** [comment]
@pkattera is this a limitation put on by steemit, or is this a limitation of the STEEM blockchain?  (Just curious, as I see @relativityboy is on it :) )

**Comment by pkattera** [comment]
@alex-osman This is not my area of expertise, but my understanding is:
During the 12 hour period, upvotes are not included on the Steem Blockchain. We could increase the vote counter on the front-end, but if the user refreshed the page, it would not be saved.

In my ideal world, people would still be able to upvote during once the 12 hour period starts, but it would't count towards the rewards payout in a similar fashion to voting on a post from months ago.

**Comment by roadscape** [comment]
Resolved; no vote lockout anymore
