### ISSUE TITLE
top bar search input overlaps signup link & makes it unclickable

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#2153]
to reproduce, open up a browser window that's ~877px wide, and try clicking on the sign up button -- you'll see that your click focuses the search text input.

![screenshot from 2017-12-13 16-47-57](https://user-images.githubusercontent.com/99194/33964223-bbadded2-e025-11e7-95c3-0dea745c4f58.png)

**Comment by gl2748** [comment]
Ooof, will fix.
