### ISSUE TITLE
Create Tests for the Reducers.

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2160]
Why test?

- Because the business relies on the site being operational and bug free.

- So that we can add new features to the App (e.g. communities) and have confidence we have not broken something when we do.

- So that we can understand how the app works and think about improving it / simplifying it.

- So that when we are working we only have to worry about one thing at a time - the task at hand and not the wider context.

# Reducers.

- [x] App Reducer. -  #2156
- [x] Global Reducer. - #2232
- [ ] Market Reducer. - #2230 
- [x] Offchain Reducer. - #2147
- [ ] Root Reducer.
- [ ] Transaction Reducer.
- [ ] User Reducer.

**Comment by relativityboy** [comment]
Unless we create child stories for each item we'll be auto-closing this and re-opening with each merge. (Child stories are not necessarily a bad thing) @goldibex please weigh in on this. I don't mind making one-line stories, but it may be too much process for some. What does your experience and training tell you? Where will we get our greatest benefit?

**Comment by bnchdrff** [comment]
let's keep on doing sub-issues... some of the reducers & sagas merit more discussion anyways

**Comment by gl2748** [comment]
Global reducer is in progress - https://github.com/steemit/condenser/tree/test-GlobalReducer
