### ISSUE TITLE
Steemit Account registration bug i detected 

### ISSUE THREAD

**Issue by Michaelnaija** [steemit/condenser#2163]
In this video, i covered how i couldn't register a new user on his mobile google chrome website. i had to use click on the desktop view before i saw the account creation button. please kindly fix the bug 

![Screenshot_20171215-003019.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513298524/p6ulsvgsf26unfaltiky.png)
     [screenshot from my recorded video showing the newbie mobile phone we used to create the account]

![Screenshot_20171215-002854.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513298990/imvdidjilbmxovfizouh.png)
                                 [screenshot image]

This is not the first time i have experienced account creation issue. the  button is always invisible till i click the browers menu to view desktop page

# See video here 
https://youtu.be/By4XBYLaM8o

See videos of lasts night error when i was trying to create an account for @bana58 on his Samsung galaxy phone 
Same bug erros has occurred on my F103 pro Gionee (Android version 6) phone and also my friends Techno M6 Phone (v5)

I have to go outside to meet up every newbie so i could complete their registration. 

 
![IMG_20171214_111033[1].jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513251736/ce82uslf1viestrhjt8x.jpg)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@michaelcj/steemit-account-registration-bug-i-detected">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by boomverzorging** [comment]
Dear originate, sorry to trouble you, but the door is locked? 
https://github.com/steemit/condenser/issues/2268
Cheers

**Comment by boomverzorging** [comment]
Thank you for unlocking it. Cheers

**Comment by relativityboy** [comment]
1pt
