### ISSUE TITLE
Embedded videos from Twitch "Unsupported" though same post works on busy.org

### ISSUE THREAD

**Issue by debrayc** [steemit/condenser#2168]
I recently wrote a post and attempted to share the embed code from a Twitch livestream video. While writing the article, the embed code worked perfectly (I wrote the post on busy.org), but after submitting the post and visiting the page on steemit.com I saw an error stating that the player was unsupported.

![Screen Shot 2017-12-15 at 11.45.19 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513368658/g6edlhk0dyurcyy4jmvg.png)

However, the same post on busy.org works perfectly fine which makes me conclude that it has to be an issue with steemit/condenser.

![unsupportedonsteemit.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513369860/wobef6qy5qor7s4nxjkq.gif)

In order to reproduce the error, copy an embed code from a Twitch stream and paste it into a new Steemit blogpost on steemit.com and the error should appear in the preview section. If you paste that same embed code into a new post on busy.org, you will see that it works.

Otherwise, you can visit [https://steemit.com/netneutrality/@debraycodes/livestream-video-recording-or-althea-mesh-x-oakland-blockchain-developers-or-decentralizing-isps-to-preserve-net-neutrality](https://steemit.com/netneutrality/@debraycodes/livestream-video-recording-or-althea-mesh-x-oakland-blockchain-developers-or-decentralizing-isps-to-preserve-net-neutrality) to see the non-working post on Steemit.com and you can visit [https://busy.org/netneutrality/@debraycodes/livestream-video-recording-or-althea-mesh-x-oakland-blockchain-developers-or-decentralizing-isps-to-preserve-net-neutrality](https://busy.org/netneutrality/@debraycodes/livestream-video-recording-or-althea-mesh-x-oakland-blockchain-developers-or-decentralizing-isps-to-preserve-net-neutrality) to see the working post on busy.org.

URL to Twitch video: [https://www.twitch.tv/videos/209632378?collection=87cPIXJfABU9Cg](https://www.twitch.tv/videos/209632378?collection=87cPIXJfABU9Cg)

Embed Code for Twitch video: 
```<iframe src="https://player.twitch.tv/?autoplay=false&video=v209632378" frameborder="0" allowfullscreen="true" scrolling="no" height="378" width="620"></iframe>```

Link to (not working) post on Steemit: ```https://steemit.com/netneutrality/@debraycodes/livestream-video-recording-or-althea-mesh-x-oakland-blockchain-developers-or-decentralizing-isps-to-preserve-net-neutrality```

Link to (working) post on Busy:
```https://busy.org/netneutrality/@debraycodes/livestream-video-recording-or-althea-mesh-x-oakland-blockchain-developers-or-decentralizing-isps-to-preserve-net-neutrality```

*My Computer* - **Mac Mini Server (Late 2012) 2.6 GHz Intel Core i7**
*My Browser:* - **Google Chrome Version 63.0.3239.84 (Official Build) (64-bit)**

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@debraycodes/embedded-videos-from-twitch-unsupported-though-same-post-works-on-busy-org">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by sneak** [comment]
This is by design. Steemit does not currently support embedding videos from Twitch.
