### ISSUE TITLE
Performance and Load Time Improvements needed

### ISSUE THREAD

**Issue by mvandeberg** [steemit/condenser#2174]
From steemit/steem#1921

> I did a Performance and Load time Audit today and found that there is a lot of room for improvements. Please refer to the post for details :
> 
> https://steemit.com/steemit/@funnyman/steemit-audit
> 
> If it cannot be improved considering the current scenario. Let's add some tweaks like
> https://clasifika.com Add some loading screen on the screen to help user understand the UX and UI.

**Comment by roadscape** [comment]
There's still room for improvement but we've made some progress here in the last 18 months.
