### ISSUE TITLE
htmlready test error needs explanation

### ISSUE THREAD

**Issue by relativityboy** [steemit/condenser#2178]
HtmlReady generates an error when tests are being run against it. 
`TypeError: Cannot read property 'prefix' of null`

This thrown error needs to be accounted for; with a test that triggers it and explains why it's 'ok', or the error needs to be eliminated.

**Comment by bnchdrff** [comment]
i cannot remember why i added the test that triggers this error (it makes sure that non-html content will be returned unmodified) so i'm looking into if this matters at all

**Comment by bnchdrff** [comment]
ok we're in good shape -- HtmlReady never receives non-html content; audited `src/app/utils/ExtractContent.js` `src/app/components/elements/ReplyEditor.jsx` and `src/app/components/cards/MarkdownViewer.jsx`

i'll do a quick PR to remove this test

**Comment by bnchdrff** [comment]
as discussed at https://github.com/steemit/condenser/pull/2192#issuecomment-353692430 the real solution here is to throw a real error (not `console.error`) when we catch a parser error, and not output any html to the caller. i'll do a new PR for this.
