### ISSUE TITLE
Extend Storybook reach

### ISSUE THREAD

**Issue by relativityboy** [steemit/condenser#2182]
Expands on the storybook components integrated from issue #2165 / pr #2146

### Progress
- [x] TimeAgoWrapper: 12
- [x] Keys: 4
- [x] Follow: 4
- [x] WalletSubMenu: 3
- [x] TransactionError: 3
- [x] Reputation: 3
- [x] Reblog: 3
- [x] ChangePassword: 3

**Comment by gl2748** [comment]
The remaining components are only used once or twice and the usefulness of having a story for each is dubious, the work in #2401 is a solid basis for our new component work as it illustrates the bulk of our commonly used 'atomic' components.

Remaining components without stories.
- [ ] VotesAndComments: 2
- [ ] QrReader: 2
- [ ] PageViewsCounter: 2
- [ ] OrderbookRow: 2
- [ ] HelpContent: 2
- [ ] GeneratedPasswordInput: 2
- [ ] YoutubePreview: 1
- [ ] UserNames: 1
- [ ] UserKeys: 1
- [ ] SuggestPassword: 1
- [ ] SidebarStats: 1
- [ ] SidebarNewUsers: 1
- [ ] SidebarLinks: 1
- [ ] ShareMenu: 1
- [ ] SavingsWithdrawHistory: 1
- [ ] QrKeyView: 1
- [ ] PasswordReset: 1
- [ ] OrderHistory: 1
- [ ] HorizontalMenu: 1
- [ ] FormattedAsset: 1
- [ ] DepthChart: 1
- [ ] DateJoinWrapper: 1
- [ ] CountryCode: 1
- [ ] ConvertToSteem: 1
- [ ] CheckLoginOwner: 1
- [ ] AuthorDropdown: 1
- [ ] Template: 0
- [ ] SlateEditor: 0
- [ ] SignupProgressBar: 0
- [ ] SaveLogin: 0
- [ ] ReplyEditor: 0
- [ ] OrderhistoryRow: 0
- [ ] LocalizedCurrency: 0
- [ ] ExperimentWrapper: 0

**Comment by goldibex** [comment]
@gl2748 if this is done, can you mark as closed plz? annoying that gh didn't do that for you
