### ISSUE TITLE
Warning to Input Memo When Sending to Exchanges is Not Displaying

### ISSUE THREAD

**Issue by eastmaels** [steemit/condenser#2189]
I'm not sure if this was intended or a bug, but I think it's the latter. Just now, I transferred some SBDs to bittrex and didn't see the warning that when transferring to exchanges, I should include a memo. 

## Expected Behavior

**"You must include a memo for your exchange transfer."** error message should display below the **memo** field.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513689916/vel00bstaowenggdfclh.png)

## Actual Behavior

**"You must include a memo for your exchange transfer."** did not display below the **memo** field.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513689055/zkblexekiug2tsklmmq8.png)

## Replication

1. Go to your **Wallet**
1. Click on **Transfer STEEM** or **Transfer Steem Dollars**
1. Select an exchange account (e.g., **bittrex**) in the **To** field

## Result

![steemit-wallet-transfer-to-exchanges.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513689155/xjcqaaxniegkqsf1mwns.gif)

## Others

I also checked the latest codes from `steemit/condenser`'s `master` branch and the validation is still there.

* `condenser\src\app\utils\ChainValidation.js`

This is where the validation is coded.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513690452/uud1vhm5k0rbyibuo3iv.png)

* `condenser\src\app\locales\en.json`

This is where the error message is defined

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513690526/m3js0adznsfldwpg4w05.png)

* `src\app\components\modules\Transfer.jsx`

I also see no intention to disable/skip the validation. 

The commit that may have caused this is this - [Enable auto suggestion for transfer input based off of users own transfer history](https://github.com/steemit/condenser/commit/c85983352509f504a78997cf6e747054d530deaf).

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513690610/qqe3gaewpdvujnoiuj1f.png)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@eastmael/suggestion-to-return-warning-to-input-memo-when-sending-to-exchanges">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by bnchdrff** [comment]
yup, the change in #1964 is not compatible with `src/app/utils/ReactForm.js` validation -- i'm working on a fix now
