### ISSUE TITLE
Add Husky to automatically run prettier as a pre-commit hook

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2190]
Propose automating our Prettier run with Husky.
https://medium.com/@bartwijnants/using-prettier-and-husky-to-make-your-commits-save-2960f55cd351

**Comment by goldibex** [comment]
make it happen. we already have it in whistle.

**Comment by bnchdrff** [comment]
it's already there! https://github.com/steemit/condenser/blob/master/package.json#L173 https://github.com/steemit/condenser/blob/master/package.json#L18

**Comment by bnchdrff** [comment]
if it isn't running for you, try removing `.git/hooks/pre-commit` and re-running `yarn install`

**Comment by gl2748** [comment]
Ah thanks Ben, It's only because I was seeing `run fmt` type commit messages and now understand that this was because of old  PRs.
