### ISSUE TITLE
Test components

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#2203]
Figure out how to test components, and set up some examples.

**Comment by gl2748** [comment]
This is good for snapshot tests of components:
https://github.com/storybooks/storybook/tree/master/addons/storyshots
Within each test for each story we can also include unit tests in jest for components that have logic...
Snapshot tests are interesting, the JSDOM output from the tests is committed to the repo.

**Comment by bnchdrff** [comment]
fix was reverted
