### ISSUE TITLE
Bug hunting : my blog is showing Account Unknown (See Video) 

### ISSUE THREAD

**Issue by Michaelnaija** [steemit/condenser#2204]
Good day Utopians, its good to be here again and i want to point out an issue that i have seen on steemit open source for a while now. 

When ever you click a username, it will show you **Unknown Account**

I believe i am not the only one that has seen this error but its most time scary to find out your account is **Unknown** especially when you just made a fund transaction to the count that you see unknown. 
***
 
![unknown account bug.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513578487/lxxxjo1veadzclb5i0py.png)

***
It comes back after refreshing your page again which i just did in this video you are about to watch. 
***
After some hours posting this video, it reoccured on my mobile phone which I quickly Screengrabbed below 
![Screenshot_20171218-224600.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513657426/thcg41udrvdoi5o9km68.png)
****

# **Proof of Video**
https://youtu.be/xKwXlJaUuqs
**Video Length :  1:8mins**
Don't mind the audio because i am still learning how to use my screen recorder

I hope this error can be fix to avoid tension from open source users. Thank you very much 

#  Device details 
Laptop : Dell latitude 
Mobile phone : Infinix hot pro 4 

I don't really need to write too much here because I believe it happens to most people on this platform. 

Well it's @michaelcj Just keeping it real 
 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@michaelcj/bug-hunting-my-blog-is-showing-account-unknown-see-video">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by roadscape** [comment]
Should be resolved; please reopen if not the case.
