### ISSUE TITLE
Eliminate 3 day averaging of estimated steem account value in wallet view

### ISSUE THREAD

**Issue by dnotestein** [steemit/condenser#2205]
Motivation: whenever there's an increase in the price of Steem, it's likely to attract new buyers. But after they buy, they experience buyer's remorse because condenser reports a 3 day average of the price which is naturally lower than the actual price. Please replace this with a more timely value estimate, or remove it entirely. I strongly favor using a more accurate price versus removal, by the way.

**Comment by roadscape** [comment]
I haven't looked into it but the `get_feed_history` API call might be able to provide us with the latest witness feed price. It should only be lagging by a few hours max, vs. a few days.

**Comment by dnotestein** [comment]
Sounds like a good source to me

**Comment by originated** [comment]
The https://api.steemjs.com/get_feed_history quote looks identical to the get.state quote, can we can confirm there should be a price difference? @jnordberg

**Comment by jnordberg** [comment]
I'm not that familiar with how the price is calculated but it looks like `get_feed_history` `get_current_median_history_price` and `get_state` all share the same source for price data.

Isn't the averaging part of the protocol?

**Comment by sneak** [comment]
use `price_history[0]`

**Comment by jnordberg** [comment]
@originated where's the PR for this?

**Comment by roadscape** [comment]
https://github.com/steemit/condenser/pull/2736
