### ISSUE TITLE
default trending page very stale

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#2207]
I suspect there's a feedback loop with trending content; we should consider using hot instead, it cycles faster and generally looks more welcoming to guest users.

![image](https://user-images.githubusercontent.com/5168676/34305857-c89761ea-e705-11e7-8eff-db091ef34287.png)

![image](https://user-images.githubusercontent.com/5168676/34305863-cb4ecd7e-e705-11e7-969f-334d99b8eb2c.png)

**Comment by roadscape** [comment]
Hot cycles too fast; trending too slow. Addressing this later w/ hive integration.

**Comment by mahdiyari** [comment]
Why not apply this now?
6 months passed and we are waiting for hive while trending page is under attack of shit posts!
it can be a temporary fix!
(already tested in https://github.com/mahdiyari/condenser branch: changed_sort_to_hot)

**Comment by KINGdotNET** [comment]
I agree with Madhiyari, we have real issue seeing the Trending page with low quality content.
Let see this improvement now.
