### ISSUE TITLE
My account page 404s and post page 500s after posting a incorrectly formed post

### ISSUE THREAD

**Issue by Smittyvb** [steemit/condenser#2215]
I posted a post that had a few irregularities in it:
- It was a root post, but the ```parent_permlink``` wasn't one of the tags
- The tag list had more than 5 tags
- The tag list had values that weren't strings
Going to [the post page](https://steemit.com/hihi/@smitop/testing-testing-123) gives me a error 500:
[![Error 500](https://vgy.me/yIeQga.png)](https://steemit.com/hihi/@smitop/testing-testing-123)
And [my profile page](https://steemit.com/@smitop) gives me a 404:
[![Error 404](https://vgy.me/5MAgO8.png)](https://steemit.com/@smitop)

Viewing the [post data](https://steemd.com/tx/002338a17b52fa32db2df56bf2bd9bbf71748821) might help.

**Comment by sneak** [comment]
Good bug!  We'll sort this out, thank you for reporting it!

To whomever works this: please write a failing test first.  We should be catching this sort of stuff.
