### ISSUE TITLE
eSteem App - pressing the names in autosuggest dropdown field wont automatically fill in the "To" Field under Wallet tab > Transfer

### ISSUE THREAD

**Issue by dranem** [steemit/condenser#2220]
Model : iPhone SE
Version : 11.2
Browser : Safari

Note: Im using iPhone not a PC unit. see above. 

Location : Wallet tab > Transfer

When I try to press the name from the dropdown autosuggest "To" field, it wont fill in automatically the input field. Tried also pressing the done many times button and nothing happened. 

Expected result:

When pressing the selected name, the name will automatically fill in the "To" field just like how the web browser for non-mobile. 

Please see video below:

<iframe width="560" height="315" src="https://www.youtube.com/embed/a0Thsqqrk80" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@an0na/esteem-app-bug-problem-choosing-autosuggest-to-field">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Smittyvb** [comment]
This repo is for bugs with steemit.com, not eSteem. You can post your issue here: https://github.com/eSteemApp/esteem/issues
