### ISSUE TITLE
include git revision in error messages

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#2223]
as a developer fixing frontend bugs, in order to log errors better (#2152), i want to include the git revision (output of `git rev-parse HEAD`) in our error messages.

i think the best way of doing this would be to dynamically include the revision in our config and then provide it in `$STM_Config`, via the `config` module, or maybe via webpack.

**Comment by sneak** [comment]
I think we are already writing the git revision to the filesystem on docker build, so this could easily be picked up by condenser on startup.  @jredbeard did some work around this AFAIR.
