### ISSUE TITLE
Phishing URL should not be clickable

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2226]
In this comment:
https://steemit.com/art/@woodywood143/3h9695-fractals#@hellcow/re-woodywood143-3h9695-fractals-20171226t212749177z

There is a phishing link that displays the URL:
www.steemit.com/@daniell/3h9695-fractals

When the user clicks it, it takes them to:
http://bit.ly/2Dj5T3r

![93ef9859-b47e-4156-b2fa-543544907451](https://user-images.githubusercontent.com/20735105/34366022-eae1497e-ea5b-11e7-997f-f853ef800744.png)

**Comment by bnchdrff** [comment]
see #1839 for original antiphishing thing; i'll broaden it to include protocol-less link text

**Comment by bnchdrff** [comment]
fixed on staging, deploying to prod now:

![screenshot from 2017-12-27 14-45-24](https://user-images.githubusercontent.com/99194/34391599-9fdd2f1a-eb14-11e7-9205-eec6f3cbc360.png)
