### ISSUE TITLE
New layout for component files

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#2237]
Our component directories are getting gigantic; what if we switched to a structure where each component has its own subdirectory with an `index.jsx` entrypoint for the component itself, and `style.scss` for its associated styles?

**Comment by gl2748** [comment]
propose:
```
Button
  index.jsx
  story.jsx
  spec.js
  styles.css
  __snapshots__
    index.snap
```

**Comment by relativityboy** [comment]
I'm in favor.

**Comment by bnchdrff** [comment]
it's in the mix: https://github.com/steemit/condenser/commit/b62fe9a3342ef7ea2ea7c64fcc81e17400c0f315#diff-04c780eb1842aabffdec5424d964ace0

**Comment by bnchdrff** [comment]
we should add this recommendation to the README,and also give a brief outline of how to add tests
