### ISSUE TITLE
Transfer of 0 steem allowed in error and has strange error message

### ISSUE THREAD

**Issue by h4ck3rm1k3** [steemit/condenser#2241]
If you have a balance of 0 steem, you should not be allowed to initiate a transfer. 
![Screenshot from 2017-12-27 06-35-37.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514374755/abur6tyd557d3p99idjy.png)

If you try to do it you are allowed to submit, this is a bug because it can easily be checked that the value is zero in javascript.
After you do it, the error message is not even well formed and says "stealing)", which is a bug. 
![Screenshot from 2017-12-27 06-36-01.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514374742/rbkuhc10rrrkbe7onqyb.png)

The submit button should be greyed out and or the error message should be improved.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@h4ck3rm1k3st33m/transfer-of-0-steem-allowed-in-error-and-has-strange-error-message">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by roadscape** [comment]
Thanks for the report! If it's still an issue would you mind moving it over to: https://github.com/steemit/wallet/issues

**Comment by h4ck3rm1k3** [comment]
Hi there I am not really using this system right now, took quite some time for you to get back to me.
