### ISSUE TITLE
Add endpoint to create users

### ISSUE THREAD

**Issue by jnordberg** [steemit/condenser#2243]
The endpoint should be password protected (set in env var) and take username email and insert it into the database to be used by the old account recovery system until it is replaced.

**Comment by bnchdrff** [comment]
WIP at https://github.com/steemit/condenser/compare/2243-create-user-endpoint?expand=1

@jnordberg should we ensure that both the username and email are unique as pre-conditions for inserting the record?

**Comment by jnordberg** [comment]
@bnchdrff No that will be verified by faucet
