### ISSUE TITLE
Unable to get active key in wallet

### ISSUE THREAD

**Issue by relativityboy** [steemit/condenser#2245]
For some users -

When a user tries to get their active key, they complete the login modal that's shown on "login to see". At this point that button "locks up" and becomes unresponsive.

Issue appears to be occasional(I was not able to reproduce) and browser independent on Mac: Chrome, Safari and Firefox have been tried.

Addl info:
* User was able to get them successfully previously, later changed them.
* Same behavior happens when attempting to show the posting key
* User attempted on Linux after this issue was create and
    * reproduced the error in Chrome
    * was able to get their keys using firefox
* User cited [this post](https://steemit.com/steemit/@thecryptofiend/anyone-else-having-trouble-viewing-their-private-active-key) as describing the same issue.

**Comment by roadscape** [comment]
This functionality moved to wallet. If anyone is still experiencing this issue please report it at https://github.com/steemit/wallet/issues
