### ISSUE TITLE
Can't access a user's posts

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/condenser#2246]
This particular user's posts cannot be accessed via steemit.com https://steemit.com/@skywalker2506
It gives an error:
```
Sorry.
Looks like something went wrong on our end.
Head back to Steemit homepage.
```
User said it started to happen 3-4 days ago. His posts are fine on an older version of condenser. Tested on Firefox and Chrome.

**Comment by bnchdrff** [comment]
thanks for the report @Jolly-Pirate -- we recently made a change to our html processor so that it throws errors more eagerly when an input causes a parser error -- i'll look into what is causing this error

**Comment by bnchdrff** [comment]
see https://github.com/steemit/condenser/commit/fb66e5a79f77f8345b028de46d6d6145709398f0

**Comment by Jolly-Pirate** [comment]
The user says his posting modal isn't working neither.

**Comment by TimCliff** [comment]
More links that are not working:
https://steemit.com/openmic/@steembirds/steemit-open-mic-week-65-bots-bots-bots-bots-original-songs 
https://steemit.com/openmic/@steembirds/steemit-open-mic-week-64-making-steem-let-it-snow-parody
https://steemit.com/steemit-101/@dan-atstarlite/steemit-101-everything-you-need-to-know-about-your-steem-wallet

**Comment by bnchdrff** [comment]
i was able to reproduce this bug by pasting this iframe in the non-rich-text editor and then posting it  `<iframe width="560" height="315" src="https://www.youtube.com/embed/Zl8KeAIwCDU" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>` - post is on testnet at `/@foo`'s blog

**Comment by bnchdrff** [comment]
the change in #2260 may have caused a performance issue; re-opening until we fix this

**Comment by relativityboy** [comment]
#2260 has been resolved, and the links in the comments above are working.
