### ISSUE TITLE
Possible discrepancy between maximum post size (maxKB) and Steem maximum_block_size

### ISSUE THREAD

**Issue by jamzed** [steemit/condenser#2247]
Condenser allows to create posts up to 65kB and disable **POST** button when story exceeds the size of maxKB (defined in `src/app/components/elements/ReplyEditor.jsx`). But there is no any mechanism to prevent posting story >64kB which causes the exception on steemd side due to exceeded max block size.

![condender_steemd_error](https://user-images.githubusercontent.com/198428/34464148-02d4bc52-ee74-11e7-9d91-d13ae310dc1b.png)

```
fc::raw::pack_size(trx) <= (get_dynamic_global_properties().maximum_block_size - 256):
```

Steps to reproduce:
- create a new story with length >64kB <65kB

**Comment by gl2748** [comment]
@jamzed thanks for this.

**Comment by roadscape** [comment]
Is this still an issue?

**Comment by gl2748** [comment]
refs #3717

**Comment by roadscape** [comment]
https://github.com/steemit/condenser/pull/3726 merged
