### ISSUE TITLE
Add BlockTrades to the list of alternate signup methods in the FAQ

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2249]
Add to question: What are other ways to create an account on the blockchain besides using Steemit.com?

https://steemit.com/blocktrades/@blocktrades/buy-steem-accounts-with-pre-loaded-steem-from-blocktrades

I will be working on this.

**Comment by gl2748** [comment]
@TimCliff please submit a PR referencing this issue if you have not done so already. We'd love to include this work.

**Comment by TimCliff** [comment]
PR: https://github.com/steemit/condenser/pull/2250
