### ISSUE TITLE
Welcome Page Updates

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2251]
I am planning to make several updates to the "Welcome" page. I will create a branch for this on my fork.

1. Move the "To Do List" above the "Quick Start Guide" so it is the first thing users see.
2. Add more items to the "To Do List".
3. Add information on the bluepaper.
4. Remove some of the information from the "Quick Start Guide" section, so it is a quicker read.
5. Review and update the links in the "Helpful Posts from Steemit Users" section.

**Comment by TimCliff** [comment]
There is a `2251-welcome-updates` branch on my local fork with these changes. Let me know if I should submit a pull request.

**Comment by gl2748** [comment]
@TimCliff Yes please submit a PR for this work. Ideally with before and after screenshots describing the changes. Thanks.

**Comment by TimCliff** [comment]
PR: https://github.com/steemit/condenser/pull/2335
