### ISSUE TITLE
Add new question to FAQ for which exchanges STEEM and SBD are listed on

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2252]
Add a new question to the FAQ:
_Which exchanges are STEEM and SBD listed on?_

Answer:
BitShares	https://wallet.bitshares.org
Bittrex	https://bittrex.com
BlockTrades	https://blocktrades.us/
Changelly	https://changelly.com/
HitBTC	https://hitbtc.com
Poloniex	https://poloniex.com
ShapeShift	https://shapeshift.io/
UpBit	https://upbit.com/

**Comment by gl2748** [comment]
Hi @TimCliff we'd love to include this work. Please submit a PR with these changes. The relevant file to be edited is here:
https://github.com/steemit/condenser/blob/master/src/app/help/en/faq.md

**Comment by plink01001** [comment]
Will address in https://github.com/steemit/condenser/issues/2486
