### ISSUE TITLE
Remove  react-foundation-components and write voting mechanism test

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2253]
Currently blocking upgrade to React-16 and poorly maintained lib.

https://github.com/aruberto/react-foundation-components

**Comment by bnchdrff** [comment]
estimate: 1 SP

**Comment by bnchdrff** [comment]
reverted in https://github.com/steemit/condenser/commit/076f8518570fc664a79e9b6064a67a1693c547a1

**Comment by pkattera** [comment]
Remove all foundation components, EXCEPT for the voting components.

**Comment by bnchdrff** [comment]
@gl2748 this is closed right?
