### ISSUE TITLE
Use of <iframe> tag as html in post makes post editing unaccesable. 

### ISSUE THREAD

**Issue by sicarii-13** [steemit/condenser#2255]
I summed it up here, https://steemit.com/steemit/@joeridamian/i-found-a-bug-that-can-make-your-steemit-experience-very-unpleasent 

What I tried to do was to figure out the syntax I have to use the speceficly publish something I have on mixcloud. 

So after pasting in 

`<iframe width="100%" height="120" src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&feed=%2Fjoeridamianjungschlager%2Fdioxide-3-promomix%2F" frameborder="0" ></iframe>`

Steemit froze, and navagating to the publish a post page, has become impossible. On the specefic machine I tried to post it on. 

I reproduced the error on Linux + opera, same thing happened. I can't get back to the post and I have to delete my cookies to get back at it. This could be a markdown issue or a steemit issue not sure.

**Comment by bnchdrff** [comment]
This is a known issue and will be fixed when https://github.com/steemit/condenser/pull/2248 is merged. Thanks for the report!
