### ISSUE TITLE
can't log in to my account ''Incorrect password''

### ISSUE THREAD

**Issue by sawadeekrap** [steemit/condenser#2257]
I have not logged in my steemit accoun @sawadeekrap for at least a year and a half....i am now trying and they won't let me even tho i know i am using the good password...i also cannot use the ''recover'' my account option since it says my account never changed ownership....please i can easily prove that i am the account owner of the account....i just need some help from a steemit mod 
thanks
Jean

**Comment by TimCliff** [comment]
Please ask for help in the help channel of steemit.chat.

**Comment by TimCliff** [comment]
Please ask for help in the help channel of steemit.chat.
