### ISSUE TITLE
Change flag to downvote

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2258]
There has been a lot of discussion in the community on how to combat various forms of voting abuse, and unless there are significant changes made to the rewards algorithm, the consensus seems to be that the solution is for stakeholders to **downvote** content that is over valued. 

There was a lot of discussion on the idea (and other proposals) in [this post](https://steemit.com/downvoting/@timcliff/let-s-make-downvoting-great-again).

Here are a few examples:
![image](https://user-images.githubusercontent.com/20735105/34476745-0bd7b698-ef59-11e7-9d0f-92e07870f902.png)

![image](https://user-images.githubusercontent.com/20735105/34476766-500dd450-ef59-11e7-9f19-cd45b203650d.png)

![image](https://user-images.githubusercontent.com/20735105/34476823-da813e42-ef59-11e7-8c3e-9b6bdb152bcb.png)

Not everything is abuse either. There are a lot of cases where users get added to auto-vote bots and keep receiving rewards, even if the quality of their content goes down. Sometimes, users just receive large amounts of upvotes that other stakeholders disagree with. In a lot of cases, stakeholders feel it is appropriate to downvote content, so there are more rewards left in the rewards pool for more deserving content.

The current condenser/steemit.com UI creates a horrible user experience for users who are downvoted, because downvotes are labeled as "flags". Even though the user did not necessarily do anything wrong, they interpret it this way because of the connotation of flags. Many users do not use downvotes when they should, because they are under the impression that they are flags - and should only be used for abuse.

The UI should change 'flags' to 'downvotes' to align with the purpose that they serve at the blockchain level, and users can be properly educated as to their appropriate use.

A PR with changes for this was created a while ago:
https://github.com/steemit/condenser/pull/1270

**Comment by gl2748** [comment]
I have been thinking about the inconsistent UI when flagging, that touches on this issue.

Currently there is a mix  of dropdown and modals for user flagging actions.
# Before.
### 1. User flags a post they are presented with a dropdown:
![screenshot from 2018-01-08 09-32-27](https://user-images.githubusercontent.com/3374538/34675487-cba28b8a-f457-11e7-85b7-ce5b7b2a6d2d.png)
### 2. Subsequent voting/flagging actions result in a modal display:
![screenshot from 2018-01-05 15-01-58](https://user-images.githubusercontent.com/3374538/34675520-e00682d4-f457-11e7-816e-a9acc6eefe27.png)

I propose using modals for all user flagging / downvoting actions... 

# After
### 1. User  clicks 'Downvote' button on a piece of content.
![screenshot from 2018-01-08 09-37-25](https://user-images.githubusercontent.com/3374538/34675628-35d42220-f458-11e7-908b-28b8d733e7a1.png)

### 2. Subsequent voting  actions on that piece of content...
![screenshot from 2018-01-05 15-01-58](https://user-images.githubusercontent.com/3374538/34675665-57fe8444-f458-11e7-9d17-7ee8f408b851.png)

**Comment by roadscape** [comment]
PR: https://github.com/steemit/condenser/pull/1270

**Comment by roadscape** [comment]
Resolved in https://github.com/steemit/condenser/pull/3307
