### ISSUE TITLE
The <iframe> tag will cause the page to crash on steemit.com

### ISSUE THREAD

**Issue by ety001** [steemit/condenser#2262]
# The issue
I found that the `iframe` tag will cause the page to crash on steemit.com.

# Error page
<https://steemit.com/cn/@ety001/5uoniw>

# Steps

1. Open the post page and input this code `<iframe width="560" height="315" src="https://www.youtube.com/embed/MbNRZ3KhWkI" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>`. You can find that the preview is empty.

2. Press the Update Post button. The post is published but no response.

3. Open the post I just published and got this page:

![error_page](https://i.loli.net/2017/12/30/5a46fe2cded15.png)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@ety001/the-iframe-tag-will-cause-the-page-to-crash-on-steemit-com">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mktcode** [comment]
duplcate of https://github.com/steemit/condenser/issues/2260

Sorry, we reviewed this contribution a bit late.
