### ISSUE TITLE
Comment sorting changes don't apply until refresh

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2264]
As a user, I want to be able to sort comments for a post by: 
-  'trending'
-  'votes'
- 'age'.

To do this I navigate to the comment thread on a `Post` and then in the upper right hand corner select the sort order I desire. After I have selected a sort order the order of the displayed comments should update accordingly.

Right now this does not happen. Upon selecting a sort order, the argument is simply added as a URL param and the user must manually refresh the page for the comment order to update.

Likely a bug in the state management.

![screenshot from 2018-01-02 15-04-17](https://user-images.githubusercontent.com/3374538/34498254-d6554a0a-efce-11e7-9b8a-f93305143047.png)

**Comment by Jolly-Pirate** [comment]
I've had that same problem for a while, forgot to open an issue.
