### ISSUE TITLE
Bug On  Profile Pictures For Steemit Search Engine Results 

### ISSUE THREAD

**Issue by realrufans** [steemit/condenser#2265]
One awesome feature of [Steemit Custom Google Search](https://steemit.com/static/search.html) is the ability to only  search for anything that has been posted on Steem blockchain. And also search for user's profile easily.
The search feature don't just search but it also suggest similar enquiry while the user is typing.

 ![image](https://img.esteem.ws/acxvgwn97h.jpg)

<Hr>

I haven't been able to use Steemit search button for a long time. So I tried searching my self to get into  my profile with few clicks. It was then I noticed there are bugs with the search engine. Which needs urgent attention.

#### The Bug 

 After I tried searching my name "rufans" I got the exact link to my profile  but with a wrong profile picture.
The profile picture showing along side my name via the Google Custom Search page isn't me. The profile pictures shows a white man.

<Hr>

*Check the screenshots below  which compares the **fake Profile picture** shown on Google custom search page and my  **real Steemit profile picture***.
* Fake Profile Picture

 ![image](https://img.esteem.ws/ekmyor9y7g.jpg)

<Hr>

* Real Profile Picture

 ![image](https://img.esteem.ws/bljsk0ja7f.jpg)

<Hr>

I searched for another user . Same bug.

* Fake Profile Picture
 ![image](https://img.esteem.ws/rc7i9bcz6c.jpg)

<Hr>

* Real Profile Picture

 ![image](https://img.esteem.ws/byxq4mfjr6.jpg)

<Hr>

I initially thought it's just an error on my profile picture or some selected profiles. I went ahead to search for other users . The bug even got worst here. After searching for some users , Google custom search result gave them no profile picture.
Check the below screenshots 

* Google custom search [no profile picture]
 ![image](https://img.esteem.ws/rzkqh7b0ha.jpg)

<Hr>

* Steemit profile picture
 ![image](https://img.esteem.ws/d8ikqk9ln1.jpg)

<Hr>

#### How to Reproduce bug

![videotogif_2017.12.30_10.37.51.gif](https://steemitimages.com/DQmQNDevJTJTvcuWJSTmXHWJ6CCaJyw6rosGvsQM61YwaHu/videotogif_2017.12.30_10.37.51.gif)

#### Phone And Browser Used

 ![image](https://img.esteem.ws/tbhyzv4don.jpg)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@rufans/bug-on-profile-pictures-for-steemit-search-engine-results">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by gl2748** [comment]
Hi @realrufans I have not been able to reproduce.
![screenshot 2018-01-06 at 5 33 22 pm](https://user-images.githubusercontent.com/3374538/34644605-bb00a15a-f307-11e7-9dea-b21528a64d40.png)

**Comment by realrufans** [comment]
Hi , I'm surprised it worked over there .
After I got notification  ,that the issue  is closed, I tried reproducing the bug .I still found out it still exist. But this time , no more  fake Profile pictures  , search results brings no profile picture for every user searched.
I guess it's a mobile bug . Try it on mobile. Thanks
