### ISSUE TITLE
Comment with <?php crashes steemit.com

### ISSUE THREAD

**Issue by DoctorLai** [steemit/condenser#2266]
I was trying to place a comment that contains a PHP code:

```
<?php
  echo base64_decode("GVsbG8gQ29sZEhhaXJ+"); 
```

and on steemit.com  it keeps loading, after 1 minute, I refresh the page, and the steemit.com crashes  https://steemit.com/cn-stats/@dailychina/cn--2017-12-31

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514720803/azj4h0daefza0svhxydx.png)

And if I open busy.org  it can load, but the comment displays as:

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514720836/xiy5lzn5rymr5s9ssysx.png)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@justyy/comment-with-php-crash-the-steemit-com">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by netuoso** [comment]
https://github.com/steemit/condenser/pull/2275

**Comment by bnchdrff** [comment]
fixed in #2277
