### ISSUE TITLE
Couldn't create account. Server returned the following error

### ISSUE THREAD

**Issue by WilliamWhispell** [steemit/condenser#2268]
4100000 plugin_exception: plugin exception
Account: steem bandwidth limit exceeded. Please wait to transact or power up STEEM.
    {"account":"steem","account_vshares":"488420593089","account_average_bandwidth":"6962636088297","max_virtual_bandwidth":"3905222627819520000","total_vesting_shares":"404625810200280457"}
    th_a  witness_plugin.cpp:409 update_account_bandwidth

...

The transaction list goes on, but I think a number of things should be changed here:

1) If we expect the main steem account to limit account creations that have already been approved by email, then we should provide a more user friendly feedback. "Steemit is busy, please try again later."
2) We should always allow people to finish creating their accounts once the email has been sent that they are approved.. I think setting the password/WIF should be done for the user, then when they come to "finish" creating the account it is displayed the first time. As of now, each time I click the link which came in my approval email: https://steemit.com/start/XXXXXXXXXX, it generates a new WIF for me. However, then when I click Create Account, I'm given the steem bandwidth limit exceeded feedback.
3) If it is my individual account that needs more steem or to have it powered up, then the feedback should display that and tell me how to do it... I have a few hundred STEEM on the exchange, so I can send them to my account if needed, but as of now, I don't have an account that I know of, I've just been approved to finish creating it.

**Comment by sneak** [comment]
Temporary issue that should, in theory, never happen.  We dropped the ball for a moment due to the volume of signups we've had in the last few days.  It should be resolved permanently now.

**Comment by sneak** [comment]
Regarding 3, it isn't your individual account - it's the account `@steem` that creates your individual account.  It ran out of Steem Power to perform the create account transaction, but it's been powered up with additional Steem Power now.

**Comment by thecotne** [comment]
@sneak i am having this issue now

**Comment by pranishg** [comment]
Same Problem Right NOW

**Comment by pranishg** [comment]
4100000 plugin_exception: plugin exception Account: steem bandwidth limit exceeded. Please wait to transact or power up STEEM. {"account":"steem","account_vshares":"939236279575","account_average_bandwidth":"8886894394994","max_virtual_bandwidth":"3618273912422400000","total_vesting_shares":"405615648593053634"} th_a witness_plugin.cpp:409 update_account_bandwidth {"trx":{"ref_block_num":56203,"ref_block_prefix":3082200487,"expiration":"2018-01-08T14:03:48","operations":[["account_create_with_delegation",{"fee":"0.500 STEEM","delegation":"57000.000000 VESTS","creator":"steem","new_account_name":"upvotebaby","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6dLDdyUSMSUCaX6C8c6bkWcLvKWoARrAZUk9QNWxUyDVcfm6mn",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6S7CY63US47WxhVPYFEZf5bdRJtUr1zdLXjSnGkjPM33ZjZ6jx",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7FcPKfhRxSGhQM1M5anRaUhT9kK1nW9Dc8CFLbjvqcQniCJTnz",1]]},"memo_key":"STM6oF7DDKQHn49zkZM3nDwhWWa4Y1fbkbfizunhghZM3HPQ2yeHg","json_metadata":"","extensions":[]}]],"extensions":[],"signatures":["2065a7c7fe97f62163f6461fa52bc61da78a01d755b901a8afdd51b70cb93e9c880d3ac431b3984dc2bfd7ac5366fdef6a8be452fee9620fb1004591ab4aca5ed8"]}} th_a database.cpp:2896 _apply_transaction {"trx":{"ref_block_num":56203,"ref_block_prefix":3082200487,"expiration":"2018-01-08T14:03:48","operations":[["account_create_with_delegation",{"fee":"0.500 STEEM","delegation":"57000.000000 VESTS","creator":"steem","new_account_name":"upvotebaby","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6dLDdyUSMSUCaX6C8c6bkWcLvKWoARrAZUk9QNWxUyDVcfm6mn",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6S7CY63US47WxhVPYFEZf5bdRJtUr1zdLXjSnGkjPM33ZjZ6jx",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7FcPKfhRxSGhQM1M5anRaUhT9kK1nW9Dc8CFLbjvqcQniCJTnz",1]]},"memo_key":"STM6oF7DDKQHn49zkZM3nDwhWWa4Y1fbkbfizunhghZM3HPQ2yeHg","json_metadata":"","extensions":[]}]],"extensions":[],"signatures":["2065a7c7fe97f62163f6461fa52bc61da78a01d755b901a8afdd51b70cb93e9c880d3ac431b3984dc2bfd7ac5366fdef6a8be452fee9620fb1004591ab4aca5ed8"]}} th_a database.cpp:660 push_transaction {"call.method":"call","call.params":["network_broadcast_api","broadcast_transaction_synchronous",[{"ref_block_num":56203,"ref_block_prefix":3082200487,"expiration":"2018-01-08T14:03:48","operations":[["account_create_with_delegation",{"fee":"0.500 STEEM","delegation":"57000.000000 VESTS","creator":"steem","new_account_name":"upvotebaby","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6dLDdyUSMSUCaX6C8c6bkWcLvKWoARrAZUk9QNWxUyDVcfm6mn",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6S7CY63US47WxhVPYFEZf5bdRJtUr1zdLXjSnGkjPM33ZjZ6jx",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7FcPKfhRxSGhQM1M5anRaUhT9kK1nW9Dc8CFLbjvqcQniCJTnz",1]]},"memo_key":"STM6oF7DDKQHn49zkZM3nDwhWWa4Y1fbkbfizunhghZM3HPQ2yeHg","json_metadata":"","extensions":[]}]],"extensions":[],"signatures":["2065a7c7fe97f62163f6461fa52bc61da78a01d755b901a8afdd51b70cb93e9c880d3ac431b3984dc2bfd7ac5366fdef6a8be452fee9620fb1004591ab4aca5ed8"]}]]} th_a websocket_api.cpp:124 on_message

**Comment by cerealBoxx** [comment]
Same here.

**Comment by pranishg** [comment]
what might be the problem

**Comment by dredson1983** [comment]
Same here. Tried many times.

**Comment by boomverzorging** [comment]
Same here in Belgium, spent an hour looking for info, found stuff on buying Steem, nothing in the Steemfaqs

**Comment by ruistan** [comment]
Same here. Can steemit be more user-unfriendly?

**Comment by quangbm** [comment]
got this problem right now

**Comment by WilliamWhispell** [comment]
I think a proper solution is to hold off emailing the user until the account is created. The password should be solidified at this point to ensure that a lack of steem bandwidth can not cause this issue. Instead of simply upping the steem on the account as band-aid, you should design the system so that bandwidth cannot halt signups. The user is already waiting days for the account to get approved, so it should simply wait however long more to ensure the account is created, then it should inform the user that their account is ready to use. You can have the password/WIF displayed on the page when they click the link, then after the first login, have that link no longer display the WIF. I'd curious as to what happened this time that sneak's theory that this could not happen again was broken. Please let me know if I can help.

**Comment by boomverzorging** [comment]
Update: just tried again and got in.
Must have been some heavy traffic, or the West coast just woke up :-)

**Comment by ruistan** [comment]
*Yeah I got in too. Thank everyone.*

**Comment by ryantyre** [comment]
Same issue currently

**Comment by charlieb** [comment]
Me too fwiw

**Comment by codehobbit** [comment]
Same here. :)

**Comment by oalsing** [comment]
Also experiencing this!

**Comment by stmoreau** [comment]
Also experiencing this!

Hoping that when it gets resolved we'll be able to create our account and not get blocked due to some weird loophole.

**Comment by DonnieBae** [comment]
There is expiration date+time. Hope it will resolve after that given time

**Comment by stmoreau** [comment]
@DonnieBae expiration date+time === ?

**Comment by DonnieBae** [comment]
@stmoreau for the guy up there,  it says  ""expiration":"2018-01-08T14:03:48","

Mine said 10th (today)  15:03:10   ,  so after 3 hours, it might resolve for me..?

**Comment by stmoreau** [comment]
I am guessing that this is probably the date + time when the link itself will expire. Might be wrong but this is my guess.. That's why I asked if we will get access, or we will get blocked from creating an account.

**Comment by snow961** [comment]
Unfortunately same problem 
what should I do?

**Comment by DonnieBae** [comment]
I made a new issue thread. Please check and comment to raise the issue

**Comment by snow961** [comment]
@DonnieBae 
How to solve this problem?

**Comment by DonnieBae** [comment]
Nah I have the same issue xD

**Comment by stmoreau** [comment]
Please comment here to raise the issue as @DonnieBae proposed  https://github.com/steemit/condenser/issues/2315

**Comment by snow961** [comment]
@stmoreau  ok

**Comment by csuno** [comment]
i've same issue

**Comment by josclementes** [comment]
me esta pasando a mi que hago?

**Comment by josclementes** [comment]
I have the same problem the link came to me 3 goras ago

**Comment by krischik** [comment]
Asking for a friend which has the same problem:

When will this be fixed? Failing on signup is about the worse thing hat can happen!

**Comment by D3luxee** [comment]
Issue does still exist, same here.

**Comment by AngelicaPerduta** [comment]
I read the terms and conditions and clicked to accept, but I get the same error message. Tried again a few hours later making sure to use the e-mail link that said my application was approved, a different password was generated but the same bandwidth limit message was returned.

**Comment by krischik** [comment]
There is an open ticket on the same problem #2315.
