### ISSUE TITLE
Informative message on the account page about the bandwidth feature

### ISSUE THREAD

**Issue by dragosroua** [steemit/condenser#2272]
If a user has insufficient Steem Power, he may run into bandwidth related problems relatively quick. At this moment, there is no information about that, so I suggest to add a quick message, if a "newbie" condition is met. Something like:

```
if (user.SteemPower <= 30)
{
 echo "Please be aware that in Steemit there is a bandwidth mechanism to prevent spamming. Post, comment and vote responsibly, until your Steem Power increases. Thank you.";
}
```

**Comment by h4ck3rm1k3** [comment]
Good idea! https://steemit.com/utopian-io/@h4ck3rm1k3st33m/error-handling-in-transfer-funds-panic-no-callback-registered-to-handle-error-bandwidth-limit-exceeded-please-wait-to-transact there also needs to be better error handling on this.

**Comment by plink01001** [comment]
Moving discussion to issue https://github.com/steemit/condenser/issues/2569
