### ISSUE TITLE
Memo field in transfer dialog gets slower and slower

### ISSUE THREAD

**Issue by h4ck3rm1k3** [steemit/condenser#2282]
There is something going on in the memo field.
I noticed this before, if you type a long memo field it gets slower and slower as you type.
![slow3.gif](https://steemitimages.com/DQmPdy6dbQ8k35wcgBPTDi5GhtoVt9kbgoZarMVUGJA2iwA/slow3.gif)

Second demo
![slow2.gif](https://steemitimages.com/DQmWTAHkifRMrVgbtWzcKKkmHM28bkwD6fNdwNw2vFA5LP9/slow2.gif)

The cpu profiler shows some time spent in one section 
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514982139/vpgydfkfgg6fbnfizodu.png)

Putting a breakpoint I get this being called many times :
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514982224/kcmgrl6fbbml349c4q27.png)

```
value (vendor.018876a8…ormatted:11103)
a (app.018876a897e71d4c1f78.js:1)
validation (app.018876a897e71d4c1f78.js:1)
a (app.018876a897e71d4c1f78.js:1)
(anonymous) (app.018876a897e71d4c1f78.js:1)
t.notifyAll (vendor.018876a8…ormatted:18624)
close (vendor.018876a8…formatted:7046)
closeAll (vendor.018876a8…ormatted:11226)
perform (vendor.018876a8…ormatted:11199)
perform (vendor.018876a8…formatted:7062)
S (vendor.018876a8…formatted:7070)
closeAll (vendor.018876a8…ormatted:11226)
perform (vendor.018876a8…ormatted:11199)
batchedUpdates (vendor.018876a8…ormatted:19228)
o (vendor.018876a8…formatted:6979)
dispatchEvent (vendor.018876a8…ormatted:33284)
```

```
 {
                key: "toPublicKey",
                value: function() {
                    return this.toPublic()
                }
            }
```

The more text I have the more this breakpoint fires.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@h4ck3rm1k3st33m/memo-field-in-transfer-dialog-gets-slower-and-slower">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by gl2748** [comment]
thanks @h4ck3rm1k3 this is odd, I'll take a look. Thanks.

**Comment by h4ck3rm1k3** [comment]
That is great because It really gets on my nerves. I am using chromium57  on debian  but it really appears to be a code issue
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36

**Comment by relativityboy** [comment]
We do a lot of expensive validation on the memo field to let users know if they're a key of some kind in there.

Field validation happens on keypress. We can solve this by adding a debounce of 400ms or so.
