### ISSUE TITLE
about page is down

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2283]
https://steemit.com/about.html

**Comment by bnchdrff** [comment]
the link in the sidebar goes to steem.io now; are there any existing links to the old about page?

**Comment by gl2748** [comment]
Not sure, we still have route and component associated with it so that should be removed if we don't want it... assuming there are still links to this on the internet somewhere.

**Comment by gl2748** [comment]
@sneak @pon, can we rip out the 'About' page and associated routes?

**Comment by sneak** [comment]
Looks like it, anything else we do will be on steem.io/steem.com
