### ISSUE TITLE
code div css should scroll

### ISSUE THREAD

**Issue by not-a-bird** [steemit/condenser#2290]
The code div blocks shouldn't clip the background, instead they should be set to overflow: scroll

I've made this change in my local copy of the condenser, but I don't know what a new_grass label is or how to "tag @sneak" so I'm just going to leave this here...

https://github.com/not-a-bird/condenser/commit/d8aaea60c146624717278eebe1b03a378cef4382

**Comment by gl2748** [comment]
Hi @not-a-bird, can you open up a pull-request with before and after screenshots to describe your contribution, we'd love to be able to include it.

**Comment by not-a-bird** [comment]
Cool.  Will do!
