### ISSUE TITLE
Too large post error message is cryptic "fc::raw::pack_size(trx) <= (get_dynamic_global_properties().maximum_block_size - 256):"

### ISSUE THREAD

**Issue by Transisto** [steemit/condenser#2291]
![image](https://user-images.githubusercontent.com/388716/34637505-466cad88-f286-11e7-9ff9-d6be0881d801.png)

deleting 1 character to make it smaller and this is what I get when trying to post.

![image](https://user-images.githubusercontent.com/388716/34637508-637bc4ea-f286-11e7-839f-e566fca61c2f.png)

`fc::raw::pack_size(trx) <= (get_dynamic_global_properties().maximum_block_size - 256):`

**Comment by gl2748** [comment]
Duplicate of #2247
