### ISSUE TITLE
White space removed from beginning of posts, but not in preview

### ISSUE THREAD

**Issue by scottyeager** [steemit/condenser#2292]
For example, on Steemit, this doesn't work

Steemit strips spaces and line breaks from the beginning of posts. This produces an inconsistency between the preview pane and what is actually rendered when posting.

Use case: want to make a post that is one monospaced "code" block (or begins with one). This can only be achieved by indenting all lines with spaces, as far as I know. The preview shows the code block as expected:

![deepinscreenshot_select-area_20180106133057](https://user-images.githubusercontent.com/17682591/34644152-eebf1e4e-f2e5-11e7-9ead-ebd74524a570.png)

But upon posting, the spaces are removed from the beginning of the first line and it is not included in the block. Adding a blank line above the first line doesn't help; it is removed too. Adding a horizontal rule as the first line provides a decent workaround. However, the discrepancy between the preview pane and the actual post is frustrating, and this restriction doesn't exist in other Markdown environments like here on Github.

**Comment by gl2748** [comment]
Hi Scotty. I Agree that might be quite frustrating. Have you tried adding three back-ticks before and after your code block?
```
Hello World
```

**Comment by gl2748** [comment]
I am going to close this as MD is behaving as expected.

**Comment by bnchdrff** [comment]
but why is there a difference between our preview & what is posted? are we trimming leading/trailing whitespace somewhere? if we are, we should modify our markdown renderer to reflect this.

**Comment by scottyeager** [comment]
@gl2748 Thanks, the triple backtick form was what I was looking for. I seemed to remember using quote marks for this in another markdown implementation, and the Github markdown reference only shows this in the context of syntax highlighting which isn't super obvious.

@bnchdrff That's my main point: they should be consistent. Also, while I understand that every markdown implementation is different, Steemit ostensibly uses the Github flavor, and Github doesn't behave this way.
