### ISSUE TITLE
Night mode toggle no longer persists

### ISSUE THREAD

**Issue by jnordberg** [steemit/condenser#2294]
To reproduce toggle night mode and reload page

**Comment by bnchdrff** [comment]
yup this was broken in commit:1ade1bf6 -- see https://github.com/steemit/condenser/issues/2185 / https://github.com/steemit/condenser/pull/2156#discussion_r157743086

@gl2748 which PR can fix this? i think there's a pending fix

**Comment by gl2748** [comment]
@bnchdrff 
https://github.com/steemit/condenser/pull/2186

**Comment by bnchdrff** [comment]
the fix was reverted; reopening
