### ISSUE TITLE
Community - Add information on bandwidth to FAQ

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2298]
I will work on this

**Comment by TimCliff** [comment]
Proposed text for FAQ update. Let me know if this looks good (or if there are any proposed changes). I can submit a PR once the text is approved.

## How does bandwidth work?

Everything action that you take on the blockchain will consume a small amount of bandwidth. This includes posting, commenting, voting, transferring tokens, etc. Viewing content does not consume bandwidth.

Every user has a limited amount of bandwidth to use each week. The more transactions a user does, the less bandwidth they will have left (until it recharges). Users with more Steem Power will have a higher bandwidth allowance.

Normally everyone's bandwidth allowance is quite high, and users are able to use the network freely without any interruptions. Sometimes when the blockchain becomes busy however (due to heavy use), everyone's individual allowances may go down until the network becomes less busy.

You can check how much bandwidth you currently have based on the current limit at:
https://steemd.com/@youraccount

If users are below their bandwidth limit, they will be unable to transact with the blockchain until their bandwidth recharges or their limit is raised.

If you get an error that you have exceeded your bandwidth allowance, it is normally best to just wait and try again later (when it is less busy). Usually if you wait and try again later, the transaction should go through.

If you are unable to transact for extended periods of time,  or you are frequently running into bandwidth limits, then you will either need to reduce your usage to stay within your limit, or purchase more Steem Power for your account through a third-party exchange such as BlockTrades.us.

**Comment by plink01001** [comment]
Will address in https://github.com/steemit/condenser/issues/2486
