### ISSUE TITLE
Receiving "Unhandled rejection Error: connect ETIMEDOUT" error

### ISSUE THREAD

**Issue by randytorres** [steemit/condenser#2299]
I just installed this repo following the instructions and everything builds correctly but I'm receiving these timeout errors when trying to view http://localhost:8080/. Doesn't matter whether I try dev or production mode. The errors are pointing to steem-js.
  
Dev mode errors - https://gist.github.com/randytorres/846024e4e7e62d098f99eb90e8557ca4

Production mode errors - 
`Unhandled rejection Error: connect ETIMEDOUT 54.86.108.212:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)`

**Comment by farrukhhameed-fistix** [comment]
i am also facing same issue

**Comment by bnchdrff** [comment]
this should get fixed by https://github.com/steemit/condenser/pull/2195
