### ISSUE TITLE
Could not create account, closed issue now reoccurring 

### ISSUE THREAD

**Issue by sactheskydiver** [steemit/condenser#2300]
I saw this in the closed issues section and wanted to post that it is still ongoing. 

4100000 plugin_exception: plugin exception
Account: steem bandwidth limit exceeded. Please wait to transact or power up STEEM.
{"account":"steem","account_vshares":"488420593089","account_average_bandwidth":"6962636088297","max_virtual_bandwidth":"3905222627819520000","total_vesting_shares":"404625810200280457"}
th_a witness_plugin.cpp:409 update_account_bandwidth

**Comment by regharding** [comment]
I have same issue

**Comment by codehobbit** [comment]
I get this issue, too. Clicked on the link in the email and tried to create the account. It shows up as soon as you submit the password on account creation.

**Comment by stmoreau** [comment]
Also experiencing this!

Hoping that when it gets resolved we'll be able to create our account and not get blocked due to some weird loophole.

**Comment by plink01001** [comment]
This has been resolved.
