### ISSUE TITLE
remove version ranges from package.json

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#2301]
in order to have a more deterministic build, remove version ranges (^, ~, *, etc) from our package.json so that the installer will install only exact versions.

**Comment by gl2748** [comment]
We should also consider:
`yarn install --flat` if deterministic is our goal...

**Comment by bnchdrff** [comment]
we're already doing `--frozen-lockfile` which is what we want

**Comment by bnchdrff** [comment]
update? this is a prerequisite of #1637

**Comment by bnchdrff** [comment]
handy trick: `function whichver { grep '"version"' node_modules/$1/package.json | sed -e 's/.*"\([0-9.]*\)",$/\1/'; };`
