### ISSUE TITLE
Top level dropdowns do not accept theme-ing.

### ISSUE THREAD

**Issue by relativityboy** [steemit/condenser#2303]
Condenser's current top-level dropdowns exist outside the theming context. They cannot respond to 'night mode' theme changes (or any others for that matter)

Though theme-dark is set, the dropdown exists outside the regular tree.
![screen shot 2018-01-08 at 2 51 19 pm](https://user-images.githubusercontent.com/599528/34691896-c568dffe-f483-11e7-8e9a-8d52bbb2f73a.png)

Two possible solutions (of many) add the theme class to either the `<body>` tag, or the root of the tree that holds the dropdown.

body:
![screen shot 2018-01-08 at 2 53 06 pm](https://user-images.githubusercontent.com/599528/34691974-0cfecd74-f484-11e7-8049-e14e7cdca5e5.png)
dropdown root:
![screen shot 2018-01-08 at 2 50 52 pm](https://user-images.githubusercontent.com/599528/34691987-1bc08f50-f484-11e7-953f-570077830615.png)

**Comment by gl2748** [comment]
Hey I actually have this comprehensively solved on this branch, I'm one dropdown away from leaving react-foundation-components for good:

https://github.com/steemit/condenser/compare/2253-remove-react-foundation-components?expand=1

refs #2253
