### ISSUE TITLE
Reputation wrong and cover photo missing from wallet 

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2306]
![aef42d2e-16e0-492f-9e52-2ce8265c9b10](https://user-images.githubusercontent.com/20735105/34708013-51b9f7b6-f4d6-11e7-9042-47b374933aa5.png)

When I click on my wallet, it shows reputation 25 and my cover photo is missing:

**Comment by dragosroua** [comment]
As far as I can see, this affects only the account page, as the rep in the posts and comments is shown correctly.
<img width="655" alt="screen shot 2018-01-09 at 11 15 31 am" src="https://user-images.githubusercontent.com/1648447/34713300-8080b2ee-f52e-11e7-8760-2b0385d411a4.png">

**Comment by Pipiczech** [comment]
Same problem in Rewards:

![image](https://user-images.githubusercontent.com/35335650/34826048-5828469c-f6d5-11e7-9dfc-286452f9a50e.png)

**Comment by roadscape** [comment]
#2244 would resolve this issue

**Comment by NickDavison** [comment]
*changes his pants* then notices its a known bug :)

**Comment by pkattera** [comment]
Looks like there are three issues:

1. Reputation defaulting to 25
2. No cover image
3. Profile photo also not displaying (both for the logged in user and on other user profile pages)

Rather than showing a wrong default of 25, I'd prefer to show no reputation until the real score has loaded.

**Comment by roadscape** [comment]
The wallet page get_state request goes to account-history node which does not have follow plugin enabled (so no rep). Easiest solution is to not show rep on wallet page. Medium-term solution is still #2244

**Comment by bnchdrff** [comment]
fixed in commit:136e951d4fccef3c9a523bb9752851929f995bdb along with work to address #2397
