### ISSUE TITLE
Steem reputation score not accurate

### ISSUE THREAD

**Issue by postandbeam82** [steemit/condenser#2307]
My Steem reputation score is different in my blog (47) than when I'm in my wallet (25).  I'm worried this is affecting my influence or payouts.

User name is postandbeam82

**Comment by bnchdrff** [comment]
Duplicate of #2306

Hi postandbeam82, thanks for the bug report -- this is a known issue and a fix is in the works!

**Comment by postandbeam82** [comment]
Awesome thanks!
