### ISSUE TITLE
Profile header broken on the wallet page

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/condenser#2312]
Browsing to the /transfers page is breaking the profile settings and reputation. It requires a refresh to show up correctly.

![wallet bug](https://user-images.githubusercontent.com/4613678/34736908-8797e070-f542-11e7-9cd6-22c69317372a.png)

**Comment by TimCliff** [comment]
Duplicate: https://github.com/steemit/condenser/issues/2306
