### ISSUE TITLE
Settings are not being saved!

### ISSUE THREAD

**Issue by feruzm** [steemit/condenser#2337]
Reported by user:

`And maybe you know what can I do to fix steemit.com is always resetting my settings to default. I mean language, night mode and all that.`

`It started a week ago in all the browsers with new login. When I am changing settings after refreshing the page they are gone`

**Comment by fildunsky** [comment]
This happenes on each and every new logins in all the different browsers and different internet connections on any device. Old logins are keeping settings fine but new ones are resetting to default immideately after page refresh.

**Comment by pfunks** [comment]
Related issue #2319

**Comment by bnchdrff** [comment]
fixed in 31fb893d3cec6aa50851f4875e123d0d0c4c89ed - thanks for your report!

**Comment by rsrafael84** [comment]
I am sorry but you can't simply close this ticket and send us to another one that has just a bunch of code line to be added in whatever what. This is a very basic error in the UX perspective, I have just paid the steemwallet to have direct access to an account to gain time, now I do not even have ability to update my basic settings such as header, logo image etc. When I try to look for help the only thing I came across is this closed ticket linking to another one with some ludicrous step by step. Please indicate how we can get this fixed.
