### ISSUE TITLE
Steemit - Needs to refresh page in order to see a post update

### ISSUE THREAD

**Issue by jayserdny** [steemit/condenser#2345]
#### Expected behavior
***
Once you update one of your post, you should be able to see the changes without refreshing the page (just by changing from one section to another in the front-end). 

#### Actual behavior
***
When you update a post, you can go to you feed and go back to your profile and you will not see the changes in the post list if you have not refreshed the website.

#### How to reproduce
***
Supposing you are logged in:

1) Open two tabs. In tab 1, open your blog page and in tab two, open one of your post.
2) In tab 2, edit your post and change the title.
3) Back in tab 1, click on your profile photo (in the header) and move to another section of the page. Then, click again in the profile picture and go back to your blog.
4) Old title of the edited post is still there.
5) Refresh the page and the new title will appear.

#### Current Environment
***
* Browser:  Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
* Operating system: macOS High Sierra 

#### Recording Of The Bug
Here is a visual reproduction of the bug

![steemitbug.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516008562/tcgdayxcagdb625xhn4z.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@jaysermendez/steemit-needs-to-refresh-page-in-order-to-see-a-post-update">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by roadscape** [comment]
Thanks for the report. Opening two tabs can indeed cause inconsistent state. However condenser is designed to be a single page app and this use case should be fairly rare
