### ISSUE TITLE
Error: Invalid reponse id: undefined

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/condenser#2350]
I got this `Error: Invalid reponse id: undefined` when replying to a comment. Reposting the comment went ok.

![invalid response id](https://user-images.githubusercontent.com/4613678/34968176-ccf89e6e-fa35-11e7-9fcd-70b85bfa580c.png)

**Comment by inertia186** [comment]
I saw it earlier today as well.

**Comment by roadscape** [comment]
Any more occurrences of this issue?

**Comment by inertia186** [comment]
I have not observed this lately.

**Comment by roadscape** [comment]
Ok this may have been a hiccup with the backend. If it reoccurs please reopen the issue. Thanks!
