### ISSUE TITLE
Missing Reference to reputation on /transfers page

### ISSUE THREAD

**Issue by Hatchi-San** [steemit/condenser#2357]
The reputation is proper on other pages;
![steemit-1](https://user-images.githubusercontent.com/16407472/35059073-cc5d468c-fb6e-11e7-9360-360de9f652fb.JPG)

The Reputation on the /transfers page is set to the default 25;
![steemit-2](https://user-images.githubusercontent.com/16407472/35059088-e4364074-fb6e-11e7-9083-e608bbb2c363.JPG)

I would have liked to fix this myself as I am a developer, but after searching I could not find the transfers .html page to add the reference.

regards, 
https://steemit.com/@hatchi

**Comment by TimCliff** [comment]
Same issue as: https://github.com/steemit/condenser/issues/2306

**Comment by Hatchi-San** [comment]
Fixed, thanks Developer!
