### ISSUE TITLE
Search function not working

### ISSUE THREAD

**Issue by aparrales** [steemit/condenser#2359]
Using search box on steemit homepage yields a blank page regardless the string entered.
Tried on Firefox 52.5.0 64bit and Chrome 63.0.3239.132 (Official Build) (64-bit), both running on Debian GNU/Linux 9 (stretch) 64-bit.
Screenshots below:
![firefox screenshot](https://user-images.githubusercontent.com/7762695/35067860-bd570eec-fbab-11e7-89b9-37673ad32514.png)
![chrome screenshot](https://user-images.githubusercontent.com/7762695/35067874-c63f9556-fbab-11e7-913c-927b792a8645.png)

**Comment by plink01001** [comment]
Unable to reproduce. Please re-open if this is still an issue.
