### ISSUE TITLE
The "following" element on Personal Steemit Page does not display well

### ISSUE THREAD

**Issue by AngelaWenjing** [steemit/condenser#2360]
#### Expected behavior
I was supposed to see the list of Steeminians I followed under the _**following**_ element on my own Steemit page.

#### Actual behavior

When I browsed the page of my Steemit friend friend @angelina6688, I found that the **_follow_** button on her page showed that I haven’t followed her yet. It is weird since I followed her long time ago. Anyway, I clicked the **_follow_** button again and went back to my page. Then I clicked the **_following_** element under my username and noticed that I only have one followed which is @angelina6688. However, as you can see from the following image, I have followed 221 Steeminians. 

#### How to reproduce
All you have to do is clicking the **_following_** element under your Steemit user ID on your cover image.

* Browser: Chrome (Version 63.0.3239.132)
* Operating system: Windows 10

#### Recording Of The Bug

![1.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516082859/avfipqa6r9yl6kltfqox.gif)

_________________________________

© Copyright 文字图片均为原创，转载请注明出处。感谢阅读！| All texts and images are created by @wangwenjing.  All rights reserved. Thanks for your time.

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@wangwenjing/the-following-element-on-personal-steemit-page-does-not-display-well">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by roadscape** [comment]
Thanks for the report, this should no longer be an issue
