### ISSUE TITLE
Allow positioning of images in posts

### ISSUE THREAD

**Issue by relativityboy** [steemit/condenser#2361]
Users want the ability to float images left, right, and center, (with widths of ~50%) on large enough screens.

**Comment by pkattera** [comment]
@relativityboy Giving users more control over how their images are displayed is really important. In addition to the positions you mentioned, let's add the ability to stretch an images 100% width center-aligned.

But first, how do you propose for users to be able to do this via the markdown editor? My understanding is that our markdown editor will strip out CSS styles for security?

e.g. If a user enters this via the markdown editor:

`<img style="float: right;" src="image.jpg">`

Will the `style="float: right"` be stripped out? Is it dangerous for us to allow some styles but not others?

For the WYSIWYG editor, we could introduce new UI like this:

<img width="744" alt="screen shot 2018-01-18 at 1 58 29 pm" src="https://user-images.githubusercontent.com/1121139/35118808-a737a970-fc58-11e7-9fd9-837690bc87f5.png">

**Comment by relativityboy** [comment]
@pkattera we wouldn't want to use `style=""` or any html / css directly.

A beta (evolving) standard set of tags would be more appropriate. Tags like `med_left` `med_right` `med_center`...

 So you might have `<img med_left src="image.jpg">`

And our parser would translate that into appropriate styling. This: 
* makes the user's desired layout less brittle
*  frees us from security vulnerabilities,
*  frees us from the need to support specific css classes over time.

We'd likely keep it to embedded html tags for now; I'd expect that to be relatively easy for people who want that level of control.

**Comment by relativityboy** [comment]
@pkattera I had a conversation with @roadscape about layouts. While I think supporting custom html tags for this kind of thing is a more robust solution we currently have some of this image layout support with the following white-listed css classes (you can put `class="${classname}"`) for `<div>` elements. Users can wrap images in divs, or we could potentially add a subset of this whitelist to `<img>` tags as well
* 'pull-right',
* 'pull-left',
* 'text-justify',
* 'text-rtl',
* 'text-center',
* 'text-right',
* 'videoWrapper',
* 'phishy'

**Comment by roadscape** [comment]
Right now we allow `pull-right` and `pull-left` for images. A future wysiwyg editor will make using them simple
