### ISSUE TITLE
Able to delete a post by turning it into a comment using XSS evasion test

### ISSUE THREAD

**Issue by jayserdny** [steemit/condenser#2367]
#### Expected behavior
***
Posts in the Steemit should not be deleted. Only comments can be deleted.

#### Actual behavior
***
By using XSS evasion techniques, a post can turn into a comment and allow the user to delete it.

#### How to reproduce
***
1) Add a new post
2) Add any content you want
3) Edit the post
4) In content, add the following:

```bash
<BR SIZE="&{alert('XSS')}">
```
5) Post it with the self upvoted
6) Unvoted
7) Delete

#### Environment
***
* Browser: Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
* Operating system: macOS High Sierra

#### Visual Reproduction of the bug
***
![deleteposts.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516352139/nugp1ufekfnujubrahak.gif)

#### Proof of transactions
***
![Screen Shot 2018-01-19 at 3.57.29 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516352281/dwcc9m0picnnjcdgrqxt.png)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@jaysermendez/able-to-delete-a-post-by-turning-it-into-a-comment-using-xss-evasion-test">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by roadscape** [comment]
Thanks for the report, but the blockchain (and frontend) allow deleting any post/comment which meets the following criteria:
1) the post has no children
2) the post does not have positive net_rshares
3) the post has not been paid out

**Comment by jayserdny** [comment]
So I think it worth to be included into the FAQ 👍  Thanks
