### ISSUE TITLE
Upvote broken

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/condenser#2368]
Upvoting is broken, the upvote button goes into an infinite circle without a UI feedback.

- On steemit.com, the browser console gives this error:
`Uncaught (in promise) Error: PANIC: no callback registered to handle error Transaction broadcast error.`

On an older condenser (b73032b3c0d9369d4cacf505b709b0564ab68d7d):
- Using wss://rpc.buildteam.io
`Transaction failed: !check_max_block_age( _max_block_age ): DISMISS`
- Using https://api.steemit.com, the upvote goes through, or sometimes gives this error:
`Error: Invalid response id: undefined Dismiss`

**Comment by sneak** [comment]
This is a jussi issue, not condenser - closing thereby.
