### ISSUE TITLE
Community - Change default deposit/withdrawal coins on blocktrades to ETH (currently BTC)

### ISSUE THREAD

**Issue by dnotestein** [steemit/condenser#2369]
Motivation: some customers are getting LTC/BTC/BCH addresses confused. The typical error is they get a bitcoin address and then try to send LTC or BCH to it (or send to a BTC address when they mean to send to one of the others). I think the simplest solution is to set the default BlockTrades URLs to ETH (ETH addresses are incompatible with the other coins). Then the user will be forced to pick the appropriate coin type.

For example, changing: 

https://blocktrades.us/unregistered_trade/steem/btc to https://blocktrades.us/unregistered_trade/steem/eth

**Comment by relativityboy** [comment]
Hi @dnotestein - This is a nicely documented request, we've updated the [contribution guidelines](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md#how-to-contribute). Future issues may be closed if they don't follow the guidelines.

(Hint: look at item 6 in detail, prefixing)

I'll bring it up to the team.
