### ISSUE TITLE
Not able to show posting key in Spanish interface

### ISSUE THREAD

**Issue by bruce-forks** [steemit/condenser#2372]
Copied from [this](https://utopian.io/utopian-io/@suesa/not-able-to-show-posting-key-in-spanish-interface) bug report on Utopian.io:

Expected behavior
Clicking on the "show" button next to the posting key (while logged in) shows posting key, when using Steemit in Spanish.

Actual behavior
Clicking on the "show" button next to the posting key (while logged in) doesn't show the posting key, only when the user chose "Spanish" as language. All other languages function as they're supposed to.

How to reproduce
Switch your language in the settings to "Spanish". Go to the permissions tab and click the button to show the posting key. Nothing will happen.

Browser: Chrome and Firefox
Operating system: ??? (probably Windows, was by a different user) and Windows 10

**Comment by bnchdrff** [comment]
fixed in #2373
