### ISSUE TITLE
SteemIt Bug: Dragging any Texts into the Comments or Post TextBox Fails with `Image upload : Please insert only image files.`

### ISSUE THREAD

**Issue by DoctorLai** [steemit/condenser#2378]
#### Expected behavior
Dragging a piece of text into a textbox should insert the text to the textbox at the current cursor position

#### Actual behavior
The SteemIt.com will report error: `Image upload : Please insert only image files.` 

#### How to reproduce
1. Open any post
2. Click `Reply`
3. Select any text in the page (post)
4. Drag the text onto the comment textbox.

Comment:
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516580641/py3oyta9elpjotoh5wxh.png)

Post
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516580649/qkgxmk4wngg8drr8qi7p.png)

* Browser:  Chrome v63
* Operating system: Win 10 64 -bit

Please note that it happens for both comments and posts. Basically, anything dragging to the textbox will be considered as 'images'. 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@justyy/steemit-bug-dragging-any-texts-into-the-comments-or-post-textbox-fails-with-image-upload-please-insert-only-image-files">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by relativityboy** [comment]
This is a really nicely documented request, but you need to follow the [contribution guidelines](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md#how-to-contribute). 

(Hint: look at item 6 in detail)
