### ISSUE TITLE
select community when posting

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2382]
As a user, I want to be able to post in a community (and be sure that I'm posting in the right place).

----

After tapping the 'Post' button within a community, I should be taken to the 'Post Editor' which clearly displays that I'll be posting within the same community that I just came from. 

In the example below, I've tapped on post button within the 'Today I learned' community.

![screen shot 2018-01-22 at 3 42 44 pm](https://user-images.githubusercontent.com/1121139/35250367-16bfaa7e-ff8b-11e7-9300-c1f8d4962eeb.png)

If I tap on the 'Post' icon within the **primary navigation**, it will continue to default to my personal blog (even if that button is pressed while on a community page)

![screen shot 2018-01-22 at 3 43 56 pm](https://user-images.githubusercontent.com/1121139/35250375-1f7fd9a4-ff8b-11e7-9a5e-2a5769c4b3b9.png)

On desktop, the new element which shows where the post will live is displayed similarly to the mobile layout:

![screen shot 2018-01-22 at 3 48 31 pm](https://user-images.githubusercontent.com/1121139/35250527-e258d52a-ff8b-11e7-8f18-5b61c042f504.png)

*(Note the orange dots in the UI indicate where the user taps)*

**Comment by roadscape** [comment]
Replaced by #3531
