### ISSUE TITLE
auto-tag posts nsfw

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2385]
If a community which I'm posting in has been designated as a #NSFW community by the admins, the first tag should be pre-populated as #NSFW. This tag should be editable, so that I can choose to delete the tag if I believe that my post is not #NSFW. I can also choose to add other tags as usual. 

![screen shot 2018-01-22 at 4 10 22 pm](https://user-images.githubusercontent.com/1121139/35251170-cce5667e-ff8e-11e7-9536-2bb994588e13.png)

*Please disregard the orange dot – it's just there to show you where the #NSFW tag will be pre-populated*

**Comment by roadscape** [comment]
Merged #3645
