### ISSUE TITLE
Password input delay

### ISSUE THREAD

**Issue by jnordberg** [steemit/condenser#2387]
Since a week or so the login modal has a annoying delay after password is entered until button goes green, this breaks password managers with autofill.

**Comment by bnchdrff** [comment]
this is a side effect of https://github.com/steemit/condenser/pull/2347

i think we should change that code to work as i suggested before: debounce the actual validation, not the `setState`

@relativityboy

**Comment by relativityboy** [comment]
Adding async  to all our form validations is an involved proposition. That's the only graceful, uniform way I see to do individual element debouncing within our current framework.

@bnchdrff - is there another good, but lower effort approach that comes to mind?

**Comment by bnchdrff** [comment]
we could separate the form-value-state-setting and validation parts of what's currently `ReactForm.setFormState`. form-value-state-setting happens first: updating the value aside from its error state. then the validation can be run async & debounced.

**Comment by gl2748** [comment]
Lodash has a debounce.
React Redux Form will also be important for communities features so this is an opportunity to make some decisions about form validation.
