### ISSUE TITLE
Include the full logotype on mobile

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2391]
**The problem**
Currently, we do not show the full logotype within the mobile primary navigation. This means we're missing an important branding opportunity when new users come from a google search or social link.

![screen shot 2018-01-23 at 11 16 03 am](https://user-images.githubusercontent.com/1121139/35295746-d4c1d0b2-002e-11e8-96b8-32eeef278106.png)

**The solution**
Display the full steemit logotype for all screen sizes both for authenticated and non-authenticated users.

![screen shot 2018-01-23 at 11 19 31 am](https://user-images.githubusercontent.com/1121139/35295890-5154abae-002f-11e8-803a-e688ed325048.png)

_Home page_

To implement this, we'll need to remove the content filter within the primary navigation on the home page. Instead, we'll add a dropdown to the page title. 

![screen shot 2018-01-23 at 11 19 20 am](https://user-images.githubusercontent.com/1121139/35295994-983db948-002f-11e8-9589-a96d8aafaf25.png)

----

Other elements and icons also need to be updated but I'll create another ticket for that.

**Comment by lmiller1990** [comment]
I am interested in contributing. Maybe I can look into this one?

**Comment by pkattera** [comment]
Thanks @lmiller1990 – I'm happy for you to take this on. This will be a good discrete task to look under the hood and contribute.

**Comment by gl2748** [comment]
Hey @lmiller1990 by all means take a look. If you have any questions or would like some direction please reach out.

**Comment by pkattera** [comment]
Also for clarity, the dropdown is not connected to the primary navigation. It's connected to the title of the feed.

For example, see how it will appear on the unauthenticated state (where the dropdown is removed from the primary nav and placed within the feed).

<img width="437" alt="screen shot 2018-01-24 at 9 02 05 am" src="https://user-images.githubusercontent.com/1121139/35345756-468a4dda-00e5-11e8-85aa-7008ec183667.png">

**Comment by lmiller1990** [comment]
Ok, thanks for the clarification  @pkattera (and fast reply, woah!).

I'll start by looking around and finding the file(s) I have to work on, and trying to display the full logo for all size screen.

**Comment by lmiller1990** [comment]
Hopefully have this done in the next few hours. I'm more of a Vue guy, so not sure of the norm for React, but I noticed the component `Header.jsx` is pretty lengthy, almost 400 lines. Are you interested in refactor the component to be a little more modular?

**Comment by lmiller1990** [comment]
I notice we have the logo.svg in assets/icons - am I able to import and use that one instead of the existing inlined svg?

**Comment by lmiller1990** [comment]
Actually, that can wait. At the moment, the pencil like icon (ew post) and the hamburger are in the same component `TopRightMenu`, but the mockup shows them split. The thing I think I should do first is split those into two components. Do you think this is a good place to start from?

Thanks for your help.

**Comment by pkattera** [comment]
@lmiller1990 Regarding the logo.svg – ideally the logo should be inline SVG so that we have flexibility to style it for hover states (which isn't possible if you just reference it from within an `img` tag). 

Regarding the hamburger navigation and `TopRightMenu` issue, I like your approach. However, I want to keep this issue scoped only to replacing the logo with the logotype (to keep this issue as simple as possible). 

I'll create another issue to update the other icons and placement of them.

**Comment by bnchdrff** [comment]
estimate: 2SP

**Comment by gl2748** [comment]
Moving Sort order into redux store - Will help if this is something we are going to be setting from Hive - discussed here - change default sort to hot - #2208.

**Comment by gl2748** [comment]
![screenshot from 2018-02-07 16-41-13](https://user-images.githubusercontent.com/3374538/35935471-82482bfe-0c38-11e8-81cb-5eeb13cc37d2.png)

![screenshot from 2018-02-07 16-41-07](https://user-images.githubusercontent.com/3374538/35935457-7d674e58-0c38-11e8-9705-242cc30376dc.png)

**Comment by bnchdrff** [comment]
based on our discussion today with pon, changes to dropdown:

let's try to add some material-ui-like behavior to our dropdown; namely centering the select list on the active item.

we should try out the various MUI react implementations and see if any of them allow you to pull in specific components (for example in the case of [material-ui-next](https://material-ui-next.com/demos/selects/#native-select), we'd use native select and simple select).

on mobile devices, use native option/select

let's try rendering both the native `<select>` as well as a fancy one designed by us & then conditionally displaying one or the other via css media queries

**Comment by bnchdrff** [comment]
re-opened by #2621 / 5e9eb7d79bcc9057c6fdf4a106db7c0d798da8d8
