### ISSUE TITLE
thumbnail image is broken if url includes an ampersand

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#2392]
see https://steemit.com/travel/@purepinay/el-nido-palawan-philippines-what-a-trip (find a page that lists this post to see the broken url

```
<picture class="articles__feature-img"><source srcset="https://steemitimages.com/256x512/https://scontent.fceb2-2.fna.fbcdn.net/v/t31.0-8/10505138_10206817529536181_4547281922455566840_o.jpg?oh=1e5bf2828d8e67dece93b9defb53f916&amp;amp;oe=5AE91EEC" media="(min-width: 1000px)"><img srcset="https://steemitimages.com/640x480/https://scontent.fceb2-2.fna.fbcdn.net/v/t31.0-8/10505138_10206817529536181_4547281922455566840_o.jpg?oh=1e5bf2828d8e67dece93b9defb53f916&amp;amp;oe=5AE91EEC"></picture>
```

generated url is `https://steemitimages.com/256x512/https://scontent.fceb2-2.fna.fbcdn.net/v/t31.0-8/10505138_10206817529536181_4547281922455566840_o.jpg?oh=1e5bf2828d8e67dece93b9defb53f916&amp;oe=5AE91EEC`

should be `https://steemitimages.com/256x512/https://scontent.fceb2-2.fna.fbcdn.net/v/t31.0-8/10505138_10206817529536181_4547281922455566840_o.jpg?oh=1e5bf2828d8e67dece93b9defb53f916&oe=5AE91EEC`

**Comment by bnchdrff** [comment]
the `image_link` in this posts contains an html encoded ampersand. a quick fix is to do

```diff
diff --git a/src/app/components/cards/PostSummary.jsx b/src/app/components/cards/PostSummary.jsx
index 49b8b21..1ddafae 100644
--- a/src/app/components/cards/PostSummary.jsx
+++ b/src/app/components/cards/PostSummary.jsx
@@ -299,7 +299,7 @@ class PostSummary extends React.Component {
             const blogSize = proxifyImageUrl(p.image_link, '640x480').replace(
                 / /g,
                 '%20'
-            );
+            ).replace(/&amp;/g, '&');
 
             if (this.props.blogmode) {
                 thumb = (
```

... but will a url ever intentionally include an ampersand? in this post, the `image_link` is coming from the json metadata (as decided in [ExtractContent](https://github.com/steemit/condenser/blob/master/src/app/utils/ExtractContent.js#L47-L52)) so the issue here is with the content supplied by our api.

i'm not confident that doing the replace at the view layer is the right solution for this bug.

**Comment by gl2748** [comment]
Can we update the validation of the user_profile image form to check for ampersands?

**Comment by bnchdrff** [comment]
this isn't the user_profile image; it's the post thumbnail image

**Comment by relativityboy** [comment]
I was hoping this is/was an "initial state" client side transport layer bug, but it looks like SSR also has this problem.

Unless the `json_metadata` being parsed by the ExtractContent [code mentioned above](https://github.com/steemit/condenser/blob/master/src/app/utils/ExtractContent.js#L47-L52) is being generated at query time (aka it doesn't exist on the chain) what we have here is a chain-transaction artifact. I don't want to call it a bug, but why anyone would html-encode a url going onto the chain is beyond me.

We need to determine if the urls exist this way on chain. If they do, then view layer may be where it belongs. Otherwise, we fix the src of the json_metadata.

I wish we could have a HF that went back in time and re-computed some of the information on the chain to make it consistent with current practices... @theoreticalbts any input on if that json_metadata is on chain or computed?

**Comment by bnchdrff** [comment]
honestly i think we're pretty safe in replacing html encoded ampersands in these urls as a quick fix for this issue

**Comment by relativityboy** [comment]
Yes. I was moving forward with your deeper question. Is it the ..
> ... the right solution for this bug
?

**Comment by bnchdrff** [comment]
did some cursory checks to see if posts end up with html-encoded ampersands in their image urls; couldn't find any:

```js
import { api } from '@steemit/steem-js';

api.getStateAsync('trending')
  // Get some images
  .then(res => Object.keys(res.content).reduce((acc, url) => {
    const p = JSON.parse(res.content[url].json_metadata);

    if (p.app === 'steemit/0.1' && p.image.length > 0) {
      const images = p.image.map(img => ({ url, img }));
      return [ ...acc, ...images];
    }
    return acc;
  }, []))
  // Find ones with &amp;
  .then(images => {
    console.log(images.reduce((acc, image) => {
      if (image.img.indexOf('&amp;') > -1) {
        return [ ...acc, image ];
      }
      return acc;
    }, []));
  })
  .catch((error) => console.error({ error }));
```

**Comment by TimCliff** [comment]
This is probably the same issue as https://github.com/steemit/condenser/issues/1499. In 1498 it looked like parentheses and quotes were causing issues too.

**Comment by bnchdrff** [comment]
yes it's the same issue; moving #1499 up the list
