### ISSUE TITLE
steemit.com page display bug

### ISSUE THREAD

**Issue by huizhao1983** [steemit/condenser#2396]
#### Expected behavior
I want to switch my website to night mode for easy night time reading.

#### Actual behavior
I want to switch the site to night mode, but there is a white patch at the bottom of the page that affects my reading experience.

#### How to reproduce
I find two bugs.
1. I want to switch the site to night mode, but there is a white patch at the bottom of the page that affects my reading experience.
2. When I switch to night mode, I think the "Toggle Night Mode" button should be "Toggle Day Mode" but it does not change

* Browser: Chrome  63.0.3239.132 x86
* Operating system: Windows 7 Sp1

#### Recording Of The Bug
![demo.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516778699/xdgjdjalwse6dtv6euq0.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@hui.zhao/steemit-com-page-display-bug">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by bnchdrff** [comment]
i like the nightmode toggle in [docker docs](https://docs.docker.com): 
![screenshot from 2018-01-25 09-09-49](https://user-images.githubusercontent.com/99194/35392433-dbb31bce-01af-11e8-96f8-9b25471ccb03.png)

**Comment by pkattera** [comment]
@bnchdrff There are a bunch of nice ones on Codepen too:

**Comment by gl2748** [comment]
The white dropdown menus appearing in 'nightmode' issue is addressed here - #2399
