### ISSUE TITLE
when viewing transfers page for a user that is not you, or logged out, memos from users with low/negative rep should be clickwalled

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#2397]
We don't want to be showing spam links to logged out users, or to third-party viewers (not the sender or the recipient of the memo).

**Comment by roadscape** [comment]
Related: https://github.com/steemit/condenser/issues/2206

**Comment by pkattera** [comment]
We added a clickwall for known bad actors in #2206. 

Is it easy to do a clickwall based on reputation score? My understanding is that this will be better done with Hive?

**Comment by sneak** [comment]
This is separate from #2206, and should perhaps be a superset encompassing the known bad actors too - bad actors and rep under 10 users memos should not be shown on any not-your wallet page, and should not be shown at all if logged out.

**Comment by bnchdrff** [comment]
we can use getAccounts (or a similar dedicated call just for rep) -- if it's a specific call note it here so @roadscape can add it to hive

**Comment by roadscape** [comment]
The follow plugin has the following call
```
vector< account_reputation > get_account_reputations( string lower_bound_name, uint32_t limit = 1000 )const;
```

It looks like `get_accounts` will be faster because `get_account_reputations` only retrieves in alphabetic order

**Comment by bnchdrff** [comment]
should we hide the memo when either party has a bad reputation, or just the sender?

should the test be `reputation < 0`?

**Comment by sneak** [comment]
reputation < 10. Just the sender.
