### ISSUE TITLE
Account never created

### ISSUE THREAD

**Issue by rjgcomputers** [steemit/condenser#2398]
Is there some extremely long delay when creating new accounts? I registered a new account and verified my email on the 16th Dec 2017, it's now 25th Jan 2018, and I still don't have my account created.

This is the email I received:

Hey there,
Looks like this was the right email. :)
Next, please confirm your email address by clicking on the link below.
(link redacted)
And that's it! You're that much closer to your Steemit account.
See you there,
- The Steemit Team

Could someone please create my account? I'd like to use the platform and have been waiting over a month for it to be created.

Also this seems like it could put potential new members off using the Steemit.com website as the time to wait for an account to be created is overly long.

Hope this issue can be fixed. My username on Steemit should be Phanes, and the email used is my username here with @aol.co.uk on the end. 

Thanks,
Richard

**Comment by pkattera** [comment]
@rjgcomputers Ah, that's no good.

Unfortunately, we don't offer official support but the best place to get to the bottom of this and get assistance is within the 'help' channel within steemit.chat: https://steemit.chat/channel/help 

Hope you're able to sort it out. I'm going to close this issue for now.
