### ISSUE TITLE
Profile information in community setup

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2403]
As a user, I want to create a new community. First step, I need to enter basic profile information details about the community. 

---

There are three required fields in this step. 

- A community name (which doesn't have to be unique)
- A community URL (which must be unique and cannot be changed later once registered)
- An about field (a short blurb about the community. Text only. No markdown allowed.)

---

**Mobile layout**

![screen shot 2018-01-25 at 4 20 34 pm](https://user-images.githubusercontent.com/1121139/35419252-ca827cdc-01eb-11e8-92c8-6ca1bbae09a1.png)

**Desktop layout**

![screen shot 2018-01-25 at 4 22 16 pm](https://user-images.githubusercontent.com/1121139/35419280-f461fbfe-01eb-11e8-8d3f-35334fc47837.png)

---

**Details** 

_'Community name' field_

- Restricted to 32 characters

_'Community URL' field_

- On focus, additional hint text appears below the field: `Choose wisely, this URL will be permanent`
- If the user choose a name already taken, there will be an error message `This URL has already been taken`
- The field is automatically populated by the text entered into the 'Community name' field (with special characters removed and spaces replaced by hyphens. Users can choose to edit the URL as they wish.
- Only allow characters which may be used within URLs. Prevent a user from entering characters in this field if it is not allowed as a URL character. e.g. If a user enters a `*`, do not display it and keep the cursor in the same position.

_'About' field_
- Text only. Restricted to 512 characters.

_'Next' button_
- Starts disabled with 20% opacity. Becomes enabled with 100% opacity when all required fields are correctly input.
- Tapping this button leads the user to #2404

---

For more information about communities - see the [spec](https://github.com/steemit/condenser/wiki/Community-Spec-%5BDRAFT%5D).

**Comment by gl2748** [comment]
There was a suggestion that initially we work to divide this into individual 'dumb' components, unified by a consistent approach to forms throughout the site.

This would invovle:
 - unifying form state styling - e.g. 'Valid', 'invalid', 'hint', 'auto-complete' etc...
- Deciding on a flexible tool for building forms in React (different from the original).
- Identifying and implementing other elements described here:
  - Progress List. - mobile and desktop.
  - Top Nav
    - Forward / back button

**Comment by relativityboy** [comment]
Deceptively simple.
We'll need a spike for form validation.

**Comment by Smittyvb** [comment]
Why doesn't the desktop version have dots in the top right? Is this intentional?
