### ISSUE TITLE
Content settings in community set up

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2404]
While creating a community, when I tap "Next" from _Step 1: Profile information_ (#2403), I should see the '_Step 2: Content settings_ form'. 

This allows me to set up who can post and comment, the primary language and #NSFW settings of the community.

---

**Mobile layout**

![screen shot 2018-01-25 at 4 48 03 pm](https://user-images.githubusercontent.com/1121139/35419915-8aae0dde-01ef-11e8-9ee6-f43969ea6b33.png)

**Desktop layout**

![screen shot 2018-01-25 at 4 50 37 pm](https://user-images.githubusercontent.com/1121139/35419982-e7223004-01ef-11e8-98c8-7136918e2971.png)

---

**Details** 

_'Next' button_
- Tapping this button leads the user to #2405

See the [spec](https://github.com/steemit/condenser/wiki/Community-Spec-%5BDRAFT%5D) for more info on communities.

**Comment by goldibex** [comment]
there are 3 types of communities: anybody can post and comment, or restricted in a couple of ways about who can post and comment etc.

- for "who can post", the choices are "anyone" and "approved members only"
- if I choose "approved members only", the field "who can comment" is enabled and the choices there are "anyone" or "approved members only".

**Comment by bnchdrff** [comment]
state coming in:

who can post: `anyone` or `approved members only`
if `approved members only` is selected, who can comment is enabled, and choices are `anyone` or `approved members only`
language: array of lang/id pairs
nsfw: bool

data in/out can be split into another issue

**Comment by relativityboy** [comment]
Presets and configuration values and their source will be handled in a different issue.

**Comment by gl2748** [comment]
I would  envisage a dumb component:
```
<Dropdown 
  options = {['anyone', 'approved only' ]}
  enabled = {true}
  onClick = {() => Update container component 'enabled fields list' here.}
/>
```

With the onClick function in the container deciding which subsequent form-fields are enabled / disabled.
