### ISSUE TITLE
Select a management team in community set up

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2405]
While creating a community, when I tap "Next" from Step 2: Content settings (#2404), I should see the 'Step 3: Management team' form.

This step allows me to select my team members and set their roles including owners, admins and moderators.

---

**Mobile layout**

![management-team](https://user-images.githubusercontent.com/1121139/35420337-d0405bac-01f1-11e8-9850-fb25d7db460d.png)

**Desktop layout**

![slice 3](https://user-images.githubusercontent.com/1121139/35420362-f244bba8-01f1-11e8-9377-f12e9b977aa2.png)

**Details**

_'Next' button_
- Tapping this button leads the user to #2407

**Comment by goldibex** [comment]
- autocomplete to use the same recommendation system as transfers for this issue

**Comment by goldibex** [comment]
may want to request a Hive API endpoint for this as Hive can cache reputation

**Comment by relativityboy** [comment]
We may want to ask for a hive api endpoint for autocomplete of users (esp for caching reputation)

**Comment by relativityboy** [comment]
Checkmarks in table should be supplied by hive generated artifact.
