### ISSUE TITLE
Unable to Complete Phone # Account Creation

### ISSUE THREAD

**Issue by Kakerate** [steemit/condenser#2406]
Steemit isn't very future-proof if somebody who used to have your phone number can deny you access to an account. Am I fucked until I get a new phone number?

**Comment by pkattera** [comment]
@Kakerate Just to clarify your issue: Are you unable to sign up because, a former owner of your phone number has also previously signed up to Steemit with that number?

**Comment by Kakerate** [comment]
No, was only bringing that up as a potential issue in the future. I was actually able to find my steemit key on my old computer

**Comment by adyscorpius** [comment]
Hi,

Unable to sign up. Even after resend, I cannot verify my phone number. 

Registering from India here...

**Comment by plink01001** [comment]
Closing issue, as all signup functionality has been converted to the new https://github.com/steemit/faucet.
