### ISSUE TITLE
Review and pay to set up a community

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2407]
While creating a community, when I tap "Next" from Step 3: Management team (#2405), I should see the 'Step 4: Review' form.

This step enables me to check all of the information I've provided and confirm that I haven't made any mistakes before paying to set up a community.

---

**Mobile layout**

![review](https://user-images.githubusercontent.com/1121139/35421498-63c533f6-01f8-11e8-9220-34231cd7c216.png)

**Desktop layout**

The desktop layout hasn't been designed but follows the layout conventions displayed in #2405 #2404 #2403 regarding padding etc.

**Comment by bnchdrff** [comment]
the user should press the back arrow (or use history.back in the browser) to edit these things -- the actual fields are readonly / don't link to anything

**Comment by bnchdrff** [comment]
the blue step-indicator dots do not have a click action assigned to them
