### ISSUE TITLE
Update homepage welcome banner

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2408]
Update the homepage 'welcome banner' for unauthenticated first time users.

---

As per Ned's directive, let's update the banner.

**Mobile layout**

![screen shot 2018-01-25 at 6 55 37 pm](https://user-images.githubusercontent.com/1121139/35423178-624b0736-0201-11e8-8e92-23768e6da554.png)

**Desktop layout**

![screen shot 2018-01-25 at 6 55 42 pm](https://user-images.githubusercontent.com/1121139/35423176-61023818-0201-11e8-9f68-8774b47c45b8.png)

**Details** 

Headline copy: `Your voice is worth something`

Body copy: `Get paid for good content. Post and upvote articles on Steemit to get your share of the daily rewards pool.`

The 'learn more' button should link to https://steemit.com/faq.html (Yes, I know, it's not the loveliest page on the site but it provides useful info – hopefully we'll improve it soon).

**Hero image**

I've attached a zip file with the hero image in .webp and .png format. To keep this performant as possible, please use a technique like below to serve the smaller sized webp image to capable browsers (mainly Chrome for now but that represents most of our traffic).

`<img src="hero.webp" onerror="this.onerror=null; this.src='hero.png'">`

[hero-image.zip](https://github.com/steemit/condenser/files/1666468/hero-image.zip)

**Comment by bnchdrff** [comment]
estimate: 1 SP

**Comment by imwatsi** [comment]
I must say that I like this new banner's content. It's more to the point and easier to understand for new users. Not to mention easier to promote. The reference to "get a share of the daily rewards pool" creates a call-to-action I like. Great work!

**Comment by relativityboy** [comment]
We've decided to not add webp support in this issue. #2440 has been created to guide work on that.

**Comment by gl2748** [comment]
Tested, LGTM, A rebase down to one commit would be nice ... :
![overlay](https://user-images.githubusercontent.com/3374538/35659972-9b6cc12a-06c6-11e8-8272-e03957732d6f.gif)
