### ISSUE TITLE
get DTube thumbnail images larger

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2409]
**The problem**

The images that we're pulling from DTube videos are too small. This makes them look awkward in blog posts. 

_An example of a DTube video in a blog post._

![screen shot 2018-01-25 at 10 48 19 pm](https://user-images.githubusercontent.com/1121139/35428108-27e1ce74-0222-11e8-8797-6c7471ad9b28.png)

---

_An example in the feed within the card layout_

![screen shot 2018-01-25 at 10 48 45 pm](https://user-images.githubusercontent.com/1121139/35428143-5ab0666c-0222-11e8-842f-7c75cd2c4a7f.png)

---

**Potential solutions**

Are we able to pull and display a larger image from DTube? I notice that busy.org is able to display larger images for DTube posts.

**Comment by roadscape** [comment]
(Can this be fixed on dtube's side?)

**Comment by bonustrack** [comment]
Been talking with Adrien from DTube, he is gonna look for a fix on his side.

**Comment by skzap** [comment]
It was already planned to resize these pictures as 200x200 is the minimum for Facebook open graph data (and getting the pic to display in a Facebook feed basically).

Facebook specifies minimum sizes, does steemit do that too?

Anyway fixing on our side doesn’t fix it on yours. If you think this is looking too bad, you should probably just hide like fb.

**Comment by bonustrack** [comment]
@skzap I suggest a minimum size of 640 width with a 4/3 aspect ratio, this way the preview image would always appear fullscreen on steemit.com.

**Comment by skzap** [comment]
Our images are 16/9 resolution because that's the most mainstream video format and it just makes sense for us. That would end up in 640x360, seems good.

**Comment by pkattera** [comment]
640x360 at 16/9 is fine for us. 
@bonustrack Is there any additional work for us to do, or should this just render nicely once @skzap returns these images at 640x360?

**Comment by bonustrack** [comment]
@pkattera no additional work so far to do on condenser, we just need to wait. @skzap told me this will be fixed on the next DTube release (v0.7).
