### ISSUE TITLE
Get translations working with storybooks.

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2410]
# Currently:
![screenshot from 2018-01-26 08-24-17](https://user-images.githubusercontent.com/3374538/35446554-56b763d0-0272-11e8-97bd-0e78d7b057cd.png)

**Comment by bnchdrff** [comment]
it'd be really cool to be able to toggle sample text in RTL and various unicode samples, also

**Comment by gl2748** [comment]
Estimate: 4SP.

**Comment by bnchdrff** [comment]
see https://github.com/steemit/condenser/pull/2280 for an example of how we'd like to get translations working in our enzyme tests

**Comment by gl2748** [comment]
# After:
![translated](https://user-images.githubusercontent.com/3374538/35977423-07a83f76-0cdb-11e8-9102-a1c92e7b666b.gif)
