### ISSUE TITLE
Community settings page

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2411]
As a community owner, admin or moderator, I want to be able to review and update the settings of the community. 

---

A setting page should contain all the information entered during community set up. In addition there should be few other sections, like a place to block / mute users. 

**Mobile layout**

![screen shot 2018-01-26 at 8 12 20 am](https://user-images.githubusercontent.com/1121139/35449046-c2338f14-0270-11e8-9d5d-0335ed303799.png)

**Desktop layout**

![communities](https://user-images.githubusercontent.com/1121139/35449061-cb89a63e-0270-11e8-8225-6624cc97df66.png)

**Comment by roadscape** [comment]
Replaced by #3493
