### ISSUE TITLE
Collapsible sidebar component

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2412]
As a user, I want more context around the main content. For example, a place to see trending communities, trending tags, top authors etc.

---

**Example desktop layout**

![sidebar](https://user-images.githubusercontent.com/1121139/35450201-1fd12264-0274-11e8-930a-52ec5d47b80e.png)

**Details**

- Sidebar components should have the option to be expandable and collapsible.  The system should remember the state that the user last selected (e.g. stay collapsed if the user has previously minimized it).
- Not all sidebar components need the ability to do the second level expansion (via a 'view more' link).
- All link items will transition to the accent color on hover.
- All changes in color and movement (expand and collapse) should use an ease-in-out function.

e.g. `transition: all 0.3s ease-in-out`

**Comment by goldibex** [comment]
Team would like to split into the "dumb component" and the user state management

**Comment by goldibex** [comment]
And there's already a sidebar component that this would replace

**Comment by gl2748** [comment]
Regarding implementing consistent animations across a project I have used this with some success:
https://github.com/chenglou/react-motion

**Comment by relativityboy** [comment]
Component will be stateless.

**Comment by gl2748** [comment]
Example of the Exisiting Dropdown component:
http://www.iainmaitland.com/condenser/?knob-tooltip%20text=a%20helpful%20lil%20tip&knob-Currently%20Selected=power%20up&selectedKind=Elements&selectedStory=DropdownMenu&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs

**Comment by bnchdrff** [comment]
this sidebar component will have 0 or many sidebar blocks. each block will have a component to render, a title, boolean isExpandable, boolean viewMoreLess

**Comment by bnchdrff** [comment]
todo: split the state management part into a new issue
