### ISSUE TITLE
Divide Screenshots into components.

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2413]
Identify all the components that we need to make.
-Spec out props, and prop shape.

---
## HeaderNav
![screenshot from 2018-01-29 13-44-57](https://user-images.githubusercontent.com/3374538/35534294-4a73164a-04fd-11e8-8cb8-b6cd95eb3d0f.png)

- [ ] HeaderNav

  - `title: String`
  - `onClick: Function`

---
## ProgressDots
![screenshot from 2018-01-29 13-45-03](https://user-images.githubusercontent.com/3374538/35534310-552c20cc-04fd-11e8-979e-5ffde393420e.png)
- [ ] ProgressDots
  - `total: Number`
  - `current: Number`
---
## WizardContainer
![screenshot from 2018-01-29 13-45-12](https://user-images.githubusercontent.com/3374538/35534772-c49a73cc-04fe-11e8-88c2-383adfaaf285.png)

- [ ] WizardContainer
  - `children`
---
### Default
![screenshot from 2018-01-29 13-45-41](https://user-images.githubusercontent.com/3374538/35535948-81d3d390-0502-11e8-9976-be9a4c3cec6e.png)

- [ ] InputText
---
### Default
![screenshot from 2018-01-29 13-45-56](https://user-images.githubusercontent.com/3374538/35534842-efd51e2a-04fe-11e8-98dd-cc7e61213b64.png)

### Invalid
![screenshot from 2018-01-29 13-52-02](https://user-images.githubusercontent.com/3374538/35535763-e181921a-0501-11e8-8ef7-2318d2251d83.png)

### Suggestion
![screenshot from 2018-01-29 13-51-57](https://user-images.githubusercontent.com/3374538/35535701-abf0de4e-0501-11e8-9072-49a0a7fbd780.png)

- [ ]  InputUrl
---
### Default
![screenshot from 2018-01-29 13-46-08](https://user-images.githubusercontent.com/3374538/35534873-1292b6b6-04ff-11e8-9586-5ca49bd7deda.png)

### Suggestion
![screenshot from 2018-01-29 13-52-19](https://user-images.githubusercontent.com/3374538/35535875-3fedc8b4-0502-11e8-9df9-f2d9a054ba87.png)

- [ ] InputTextArea
---
### Enabled
![screenshot from 2018-01-29 13-51-45](https://user-images.githubusercontent.com/3374538/35535686-9a8ca6ba-0501-11e8-9005-c9e0c8dfd937.png)

### Disabled
![screenshot from 2018-01-29 13-46-16](https://user-images.githubusercontent.com/3374538/35534899-26f429f0-04ff-11e8-856d-51a16d734ca2.png)

- [ ] Button

---
## ProgressList
![screenshot from 2018-01-29 13-46-25](https://user-images.githubusercontent.com/3374538/35534936-3b0020b6-04ff-11e8-9a49-6551d37dbe98.png)
- [ ] ProgressList

---
### Enabled
![screenshot from 2018-01-29 13-46-50](https://user-images.githubusercontent.com/3374538/35535250-37371998-0500-11e8-91f8-87982f02140f.png)

### Disabled
![screenshot from 2018-01-29 13-46-37](https://user-images.githubusercontent.com/3374538/35535209-220740ca-0500-11e8-9d94-19c50a0599c7.png)

- [ ] DropDown 
---
## CheckBox
![screenshot from 2018-01-29 13-46-56](https://user-images.githubusercontent.com/3374538/35535282-4d7c93c2-0500-11e8-9023-0b034246c8c8.png)

- [ ] CheckBox
---
## UserAccessTable
![screenshot from 2018-01-29 13-47-08](https://user-images.githubusercontent.com/3374538/35535303-5876aa7e-0500-11e8-8af3-8d752a65b16e.png)
- [ ] UserAccessTable 

---
### Empty
![screenshot from 2018-01-29 13-47-18](https://user-images.githubusercontent.com/3374538/35535565-32b670fc-0501-11e8-93b4-abf12086fab8.png)

### Locked
![screenshot from 2018-01-29 13-47-27](https://user-images.githubusercontent.com/3374538/35535599-48286b66-0501-11e8-9011-5cadd12becbc.png)
- [ ] SelectUser
---
## ReceiptTearOff
![screenshot from 2018-01-29 13-47-40](https://user-images.githubusercontent.com/3374538/35535659-7a410d42-0501-11e8-92fb-a8700948db7c.png)

- [ ] ReceiptTearOff
---
## UserInfo
![screenshot from 2018-01-29 13-47-50](https://user-images.githubusercontent.com/3374538/35535667-87bd4b98-0501-11e8-998c-f138346ff0ff.png)

- [ ] UserInfo
---

**Comment by gl2748** [comment]
2 SP

**Comment by gl2748** [comment]
see #2428

**Comment by bnchdrff** [comment]
this is done -- the result is #2428
