### ISSUE TITLE
Outline State MGMT for the communities creation wizard.

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2414]
Outline all Requirements.

3SP.

**Comment by gl2748** [comment]
"This is a spike - i.e. the specs are big and we need to do discovery tasks to figure out what work needs to be done."

**Comment by bnchdrff** [comment]
my notes are here: https://docs.google.com/document/d/11MiHzrNqITm1tG6wuL8ujcPLQsxdr1t5YlVs7zOzeY4/edit

**Comment by bnchdrff** [comment]
done: see notes :)
