### ISSUE TITLE
Community - Remove one half-sentence in the signup request for Steemit

### ISSUE THREAD

**Issue by doodle-bear** [steemit/condenser#2419]
Hi,

there is the big issue of new users having to wait one week or more, until their accounts is confirmed. Too many users waiting for their approval are therefore complaining in the help channel of the Steemit Chat - it clogs up the entire system and frustrates the mods there. I believe the most of the complaints can be avoided if the following file is modified:

https://github.com/steemit/condenser/blob/1842b43aef55d58a089f7e2e735fd2c4c0885f31/src/app/components/pages/PickAccount.jsx

The line in question is number 205 where it states:

> Signup requests can take up to 7 days to be processed, but usually complete in a day or two.

The second half of sentence should be removed so that the new statement says:

> Signup requests can take up to 7 days to be processed, please be patient.

There was an intense debate about it in the [witness-social channel](https://steemit.chat/channel/witness-social) of the Steemit chat. The discussion was on Jan28 2018 between @doodlbear (me), @drakos, @yehey and @ats.david and at least @drakos isa very active mod in the help channel.

If you would like to discuss this with me or the others, please reply to me here, or [contact me on Steemit](https://steemit.com/@doodlebear) or in the [Steemit Chat](https://steemit.chat/direct/doodlebear).

In advance, Thanks a lot!

@doodle-bear/@doodlebear

**Comment by doodle-bear** [comment]
@roadscape: What is "community-pr-welcome"?

**Comment by roadscape** [comment]
@doodle-bear It means anyone in the community who wants to submit a Pull Request for this issue is welcome to do so

**Comment by plink01001** [comment]
I will address this in #2486
