### ISSUE TITLE
Going to other user's feed, page title says "My Feed" should say "${account}'s feed"

### ISSUE THREAD

**Issue by relativityboy** [steemit/condenser#2420]
Title says it all, but here's a screenshot of user 'valuproposition' browsing to user 'lovejoy' 's feed page.
<img width="682" alt="screen shot 2018-01-28 at 9 47 20 pm" src="https://user-images.githubusercontent.com/599528/35492897-1a25f3dc-0475-11e8-80ec-8bfd25529801.png">

**Comment by roadscape** [comment]
Browsing others' feeds is an undocumented feature; a PR would be welcome for such a tweak but closing the issue for now.
