### ISSUE TITLE
Community - TOS Update

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2431]
Based on info from ned this email address needs to be updated:

_20. Copyright Complaints_

_Steemit respects the intellectual property of others by not reading infringed content from the Steem blockchain. If you believe that your work has been copied in a way that constitutes copyright infringement, you may notify Steemit’ s Designated Agent by contacting:_

_contact@steemit.com_

The email should be changed to: 
Copyright@steemit.com

https://github.com/steemit/condenser/blob/57946d0efc65d43e027499f1f839785e87965d25/src/app/components/modules/TermsAgree.jsx#L951

**Comment by imwatsi** [comment]
All in lower case letters :)

copyright@steemit.com

**Comment by plink01001** [comment]
PR has been merged
