### ISSUE TITLE
Pick account page poorly formatted when visited by logged-in user.

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2433]
As a logged in user, if I navigate to: https://steemit.com/pick_account I expect to see a dialog instructing me to log-out before creating a new account.

Currently this dialog is hidden by the top-nav due to CSS rules.

![screenshot from 2018-01-30 15-22-05](https://user-images.githubusercontent.com/3374538/35594779-997f5116-05d1-11e8-8b35-e39e8e1f0fbb.png)

**Comment by pkattera** [comment]
It also looks like there is too much vertical padding within the navigation on that screenshot compared to the size of the normal desktop header...

**Comment by plink01001** [comment]
Closing issue, as all signup functionality has been converted to the new https://github.com/steemit/faucet.
