### ISSUE TITLE
improve tag editor component so that users aren't confused about what tags they are about to use

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#2437]
A brand new user doesn't know what the tag delimiter characters are (space? tab? comma?)

I'd love to see us migrate to a component like the following:

https://github.com/NdYAG/react-tageditor

demo:  https://ndyag.github.io/react-tageditor/

It disambiguates what is and isn't a tag boundary by creating a new subcomponent when you hit tab.  I think we should expand this set of keys to create a new subcomponent when you hit tab or space or comma, so any of those common tag delimiters clearly indicate to the user what set of tags they have chosen.

**Comment by roadscape** [comment]
#2061
