### ISSUE TITLE
nsfw display preference should be stored in preferences (conveyor)

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#2439]

**Comment by bnchdrff** [comment]
how about *all* preferences? any reason not to persist them all in conveyor?

**Comment by sneak** [comment]
yes, that's the idea. other than night mode and nsfw, what other prefs are there?

**Comment by bnchdrff** [comment]
language

**Comment by sneak** [comment]
Ahh yeah, that too (although I think we are vastly overestimating the importance of the language selector and associated preference, as 99% of users will never need to change/set it as simply setting the UI language to the same language as the browser will serve them).
