### ISSUE TITLE
Community Reported Issue - Promoted post not showing up as expected

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2444]
A user promoted this post for $8 SBD:
https://steemit.com/travel/@ella-kay/my-beloved-riga-latvia-history-timeline-historic-st-peter-s-church-and-tower-and-many-other-beautiful-places

It has five tags: travel history photography steemchurch adsactly
![image](https://user-images.githubusercontent.com/20735105/35655963-3bb0948e-06ba-11e8-8c63-1097a9e6581a.png)

When viewing the promoted 'adsactly` posts, it does not show up as expected:
https://steemit.com/promoted/adsactly

![image](https://user-images.githubusercontent.com/20735105/35655999-742161b8-06ba-11e8-802f-50721f48a02e.png)

**Comment by gl2748** [comment]
I am seeing this as promoted on Travel (i.e. the first tag) but not on subsequent tags. Is this not the expected behavior? i.e. would one expect a promoted post to appear as promoted across multiple tags?

**Comment by TimCliff** [comment]
@gl2748 afaik it should be promoting for all tags. Here is an example of a post that is being prompted for the other tags: https://steemit.com/cryptocurrency/@kriptonoob/comfort-safety-and-confidence-for-you-and-your-data-loomia

**Comment by roadscape** [comment]
This may have been due to steem API issues. Steemit.com is now powered by hive API's; please reopen if issue persists.
