### ISSUE TITLE
Steemit.com Fails to Remember Login after Refreshing the Page

### ISSUE THREAD

**Issue by DoctorLai** [steemit/condenser#2445]
#### Expected behavior
After login, the session of steemit.com should stay logged in even after refreshing the pages

#### Actual behavior
After login, it keeps asking for user login details from time to time on page reloads. I have ctrl+F5 to clear the cache many times.

#### How to reproduce
Login, refresh the page on users' profile page.

* Browser:  Chrome V63
* Operating system: Win 10 64-bit

#### Recording Of The Bug
https://youtu.be/PKbdIh48fu4

If you press F12 in Chrome, you will see
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517064514/hwad4ffllrysgjdoz3ps.png)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@justyy/steemit-com-fails-to-remember-login-after-refreshing-the-page">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by gl2748** [comment]
I believe this is a feature rather than a bug. The feature is here:
https://github.com/steemit/condenser/blob/master/src/app/redux/UserReducer.js#L103-L121
