### ISSUE TITLE
Post Editor Does Not Allow URL Link To Be Attached to Image

### ISSUE THREAD

**Issue by Zaivlys** [steemit/condenser#2449]
Hi -

This is my first time reporting a bug. Please bear with me if it does not completely fall in line with your rules. Thanks!

#### Expected behavior
I added an image to a new post and wanted to link a URL to it. 

#### Actual behavior
I added an image, highlighted it, clicked on 'link' icon and typed in the URL.  The image disappeared once I clicked the 'check' button.

#### How to reproduce
Please follow the steps below:
1. Start a new post and add a image. Here is an example of mine:
![1.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517269067/cwbgyuqrk2yaiueckhlc.jpg)

2. Highlight the image and click on the 'link' button:
![2.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517269331/od8tbsoytqjldw3iel4m.jpg)

3. Type in URL:
![3.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517269375/enmsj4ah6aadm1txpmfr.jpg)

4. The image is gone:
![4.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517269405/gqey0a1v78ib7c3tsenr.jpg)

5. I checked the HTML of the post. Looks like the URL replaced the image URL address.

* Browser: 
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

* Operating system:
Mac OS X Version 10.9.5

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@itsok/post-editor-does-not-allow-url-link-to-be-attached-to-image">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by roadscape** [comment]
Hi, thanks for the report! The editor does not currently support this functionality and we hope to replace it altogether
