### ISSUE TITLE
Check for Plagiarism on Post Creation

### ISSUE THREAD

**Issue by digitalplayer-steemit** [steemit/condenser#2452]
Hello everyone

I am a web developer I would like to create a new feature: check for plagiarism on post creation and block the post submit if plagiarism has been detected, the block could be temporary, permanent or just a friendly warning.

Before I go deeper into this I have 2 questions for active developers:

1. Is there anybody working already on a similar feature?
2. Would you like to see such a feature?

Best Regards
Michael Asumcinei
@digitalplayer

**Comment by TimCliff** [comment]
There is a third party organization - SteemCleaners that already handles this type of stuff. You should get in contact with them. IMO, condenser is not really an appropriate place to handle this.

**Comment by digitalplayer-steemit** [comment]
SteemCleaners works well but my approach is different, it's about cheching content before submission and doing so there are some benefits:

- mitigate or even eliminate the duplicated content on the blockchain before submission, saving memory and increasing the overall performance.

- increase search engine rating: the se crawlers scan every part of steemit.com even those duplicate just before SteemCleaners flags it and even after the flag.

- long term user education to original content

> IMO, condenser is not really an appropriate place to handle this.

I was thinking about it and I have a proposal to solve this issue which is create an external engine that performs the heavy work for content duplication check, with API to be used on Condenser side on submission.

Best Regards
Michael Asumcinei
