### ISSUE TITLE
Bug: hedge.whale account name pre-filled on Steemit login screen 

### ISSUE THREAD

**Issue by blahbax** [steemit/condenser#2458]
Over the past few weeks, when I log out of my primary account on Steemit and go to change accounts (Click Avatar -> Logout -> Login), the account name on the login screen is pre-filled with the username *hedge.whale*:

![](https://steemitimages.com/DQmVSYCFGhTNmhedtv9HzjvMpqQtarqywfCTv9eoS5bynrn/image.png)

This account has no association with me - I do not hold the keys and have never attempted to log into it. I have experienced this on three different PC's, on three different networks at two separate locations. Clearing browser and form history has no effect - the login is not stored in Chrome or my password manager.

Other users in my network have reported the same issue.

**Comment by sneak** [comment]
dupe #2466 - thank you for reporting this!  let's track it over at the other issue number.

**Comment by blahbax** [comment]
Thanks Sneak, apologies for the dupe!
