### ISSUE TITLE
condenser is leaking state between sessions

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#2466]
Brand new incognito window, click login, receive this:

<img width="1582" alt="screen shot 2018-02-05 at 07 45 54" src="https://user-images.githubusercontent.com/408977/35824386-53a83832-0a78-11e8-8a64-8003b68fb6eb.png">

**Comment by valzav** [comment]
I cannot replicate this. It might be a browser's automatic forms fill up feature.

**Comment by bnchdrff** [comment]
why would it fill in these random usernames though? so strange!! i want to get a redux store dump of this in the wild :(

**Comment by valzav** [comment]
It tries to suggest a user name from the current url, see urlAccountName(). I don't know who and why added it. I think we need to remove it.

**Comment by bnchdrff** [comment]
we should keep `#account=usethisname` so we can prefill usernames when redirecting from the new faucet. it could be limited to only being used at the `login.html` route

**Comment by gl2748** [comment]
I think this issue was a Full DB issue. Suggest close.

**Comment by bnchdrff** [comment]
how would a full database have caused this issue?

**Comment by gl2748** [comment]
Mis-understood this issue. My bad.

**Comment by bnchdrff** [comment]
see https://github.com/steemit/condenser/issues/2614
