### ISSUE TITLE
Is there a developers forum or mailing list? 

### ISSUE THREAD

**Issue by lonnieOST** [steemit/condenser#2474]
Sorry if this is not the correct place to ask this question as I did not know if here or SteemChat would be best.

Is there a developers forum or mailing list?  

I would like to try and find a developer to work with on a related fork project as Steem seem to be exactly what I need but do not have the experience in working with it.

**Comment by sneak** [comment]
Please do not open issues in the condenser repo for platform questions or support inquiries.

To answer your question directly, your best bet is to use steemit.com - it is the forum used by the platform's developers.

**Comment by lonnieOST** [comment]
Thanks, and apologies once again.
