### ISSUE TITLE
Use A different Slider component

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2480]
Old discussion @TimCliff @valzav  were both involved there:
https://github.com/steemit/condenser/issues/938

Currently our slider is the same for 'Voting' as it is for 'Flagging'. I.e. 'Green' and sliding from left to right. While the actions are in fact diametrically opposite - one 'adds' weight to a voting action, the other 'subtracts' weight.

The component we use: https://github.com/whoisandy/react-rangeslider has some shortcomings for our purposes.
- Have to hack it to accept negative values.

This leads to some confusion / discontinuity when adjusting vote weight either up or down. 

Ideally the slider we use would describe these two actions as part of a continuous spectrum. 
For example by using colors and/or by orientating the slider direction to describe the movement up or down.

# Currently - after this PR https://github.com/steemit/condenser/pull/2434 is merged
## UP:
![screenshot from 2018-02-07 13-23-22](https://user-images.githubusercontent.com/3374538/35918558-25caf484-0c0a-11e8-9f65-38fd8ce3e890.png)

## DOWN:
![screenshot from 2018-02-07 13-23-35](https://user-images.githubusercontent.com/3374538/35918561-27b27f24-0c0a-11e8-9070-a34f4a999495.png)

**Comment by TimCliff** [comment]
Related discussion: https://github.com/steemit/condenser/issues/2258
