### ISSUE TITLE
Improve IE support.

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2492]
If you use Steemit.com on Internet Explorer. The header is too big -  and makes some important user interactions impossible / not clear...

## e.g. 
- cannot close welcome banner
- once welcome banner is closed cannot select sort order etc..
- Sign up is painful...
- Posting is impossible.
![screenshot from 2018-02-09 11-46-37](https://user-images.githubusercontent.com/3374538/36026428-f11bebfe-0d8e-11e8-9257-55a46ebe23ef.png)
![iain_004](https://user-images.githubusercontent.com/3374538/36026503-49139dde-0d8f-11e8-8ed4-61666cfea0ae.jpg)

**Comment by bnchdrff** [comment]
what version of ie is that? here it is in 11:

![screenshot from 2018-02-09 14-50-29](https://user-images.githubusercontent.com/99194/36046960-a79ac972-0da8-11e8-8916-b0d076128d11.png)

**Comment by gl2748** [comment]
![screenshot from 2018-02-09 19-53-30](https://user-images.githubusercontent.com/3374538/36047091-fa96d024-0dd2-11e8-8651-42d998d2862e.png)

**Comment by bnchdrff** [comment]
i'm mistaken; i was testing the fixed branch. ha.

yes that looks bad :)

**Comment by TimCliff** [comment]
Here are some other (possibly related) IE 11 issues:
https://github.com/steemit/condenser/issues/2484
https://github.com/steemit/condenser/issues/1922
https://github.com/steemit/condenser/issues/1881
