### ISSUE TITLE
TimeAgo Component needs to retain utility

### ISSUE THREAD

**Issue by relativityboy** [steemit/condenser#2497]
The "TimeAgo" component loses precision too quickly. The "Last year" described posting date is nice to read, but was it january or december of last year? (or two years ago)

Implement one of the following ways to show exact date and time of post while retaining the current "nice read" version  (UTC || GMT || Local)
1. A title attribute with the actual date and time it was posted 
2. A pop over/under on click
3. A subscript once the date and time main-text is no longer precise to the hour.

**Comment by roadscape** [comment]
There is a tooltip on hover showing exact date
