### ISSUE TITLE
phone number registration fails because it is longer than 10 digits

### ISSUE THREAD

**Issue by davidak** [steemit/condenser#2499]
Error: `Phone number invalid`

I got a new phone number and actually tried to sign up, but it fails because it has 11 digits!

**Comment by LadyFuzztail** [comment]
My own phone number is 8 digits long, not including the area code, and that is counted as invalid.

**Comment by CF84** [comment]
Same problem here. My number is 12 digits long (Germany, +49), but i can only enter up to 10 digits.

**Comment by steemthink** [comment]
me too

**Comment by Nogas** [comment]
Here in Brasil, now, all mobile numbers are nine digits PLUS two area code digits.
That makes eleven digits.

**Comment by jnordberg** [comment]
We are aware of this issue and working on a fix, thanks for the reports.

Refs https://github.com/steemit/faucet/issues/195

**Comment by jnordberg** [comment]
This should be fixed now, let me know if the problem persists

**Comment by davidak** [comment]
Problem solved for me. Thanks!
