### ISSUE TITLE
sign up error (yayayay I found my first bug look at me!)

### ISSUE THREAD

**Issue by lanmower** [steemit/condenser#2500]
https://signup.steemit.com/

![image](https://user-images.githubusercontent.com/657315/36072687-7f3a7e0c-0f2c-11e8-8316-5c46e0c4afbd.png)

starting your username with a captial produces the wrong error message

a user would expect it to handle the casing automatically

steemit.com/@lanmower :)

**Comment by jnordberg** [comment]
Please direct any bug reports for signup to https://github.com/steemit/faucet

Thanks
