### ISSUE TITLE
Editing files when developing locally

### ISSUE THREAD

**Issue by jm2242** [steemit/condenser#2502]
I am having trouble developing locally. As per the readme, I have the docker container running with 
`docker run -it -p 8080:8080 steemit/condenser` and can run the site locally. However, I don't believe I have configured the ability to edit files on my local machine and for those to get synced to the container. I imagine others have a way to do this, without having to edit directly on the container. Is there a link/resource on how to properly do this?

Happy to add this to the readme if someone can list out their development steps!

**Comment by sneak** [comment]
`docker build -t steemit/condenser .` in the root will rebuild the steemit/condenser container on your docker instance.

for interactive dev work, it's best to just `yarn start` in the root (dev server), then rebuild the container to do a final test.
