### ISSUE TITLE
 Steemit BUG | Settings Visibly no (other users') but have Access link.

### ISSUE THREAD

**Issue by yasayanoluler** [steemit/condenser#2503]
#### Expected behavior
I think it's a very important mistake.Exit the profile , the SETTINGS section is still active....
it is not normal for any profile images(link) to appear...

- If the settings do not appear visually in the menu row.I think there is a mistake here. It is a bug to get there by giving a link - 

*steemit.com/username/settings*

#### Actual behavior
And thanks to this bug, all images become visible to other users.The bug need fix quickly.
- The other users visible the profile :
PROFILE PICTURE URL
COVER IMAGE URL

#### How to reproduce
* Browser:  Chrome
* Operating system: Windows 7
It just needs to be fixed ....

#### Here are 2 questions

1. Why other users do not see settings ?
![settingnotfound.jpg](https://steemitimages.com/DQmVkqn1aaHunEHzakZn94HWBttcta3xUFsVntkrPptozhs/settingnotfound.jpg)

2. If this is normal why do not have button(not show settings ,does not see other users) ?
![setting link.jpg](https://steemitimages.com/DQme7bjHi5DHvskc3HvDc5gFi1vMPZ56iLoh7SCnSdRu6UK/setting%20link.jpg)

#### Recording Of The Bug
<iframe width="560" height="315" src="https://www.youtube.com/embed/yWiykIMcgeA" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@yasayanoluler/steemit-bug-or-settings-visibly-no-other-users-but-have-access-link">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Smittyvb** [comment]
It doesn't appear there are any issues. Profile/cover image URLs were always visible on the blockchain, and the update button is greyed out.

**Comment by roadscape** [comment]
Should be resolved on `wallet`
