### ISSUE TITLE
community - canonical links via the app tag in json_metadata for the popular dapps

### ISSUE THREAD

**Issue by drov0** [steemit/condenser#2505]
Hello, 

This issue has been discussed on steemit here : https://steemit.com/steemdev/@howo/steem-improvement-proposal-canonical-links

The canonical tag idea has been dropped because if we let an user edit the canonical tag this will lead to domain-wide abuse which will nuke steemit.com's seo.

Hence this is my revised proposal  for a new standard : 

## Canonical links for the popular dapps 

The front ends would keep a list of dapps with their url and their url scheme.

So that if the "app" tag is recognized (aka it's in that list) then the front end automatically generate the canonical link. 

For example :  

```
{
  "author": "jesta",
  "permlink": "test-post",
  "category": "test",
  "json_metadata": {
	"app": "busy/0.1"
  }
}
```

From that the front end know that it orginated from busy, and thanks to the list it can do busy -> https://busy.org and recover the url scheme. 

In the case of busy.org it's 

`@{username}/{permlink}` 

it can easily recreate the cannonical link : 

`https://busy.org/@jesta/test-post`

and add it in the header :

`<link rel="canonical" href="https://busy.org/@jesta/test-post">`

Which allows us to prevent steemit.com from hurting the seo of other dapps while having no cost whatsoever in storage space in the blockchain. 

Of course this means that there is a need for a list of the most popular dapps to be hardcoded on the front ends, but it's not like there are tons of them and anyone can submit a pull request to have his new dapp added to the list of the frontends.

What do you think of that final proposal ? Is it implementable ?

**Comment by bonustrack** [comment]
Related #336

**Comment by bonustrack** [comment]
I think app url scheme should be stored with the full url. 

I created a list of app with their url scheme, this is something we can use and let developer pull request if some change are required https://github.com/busyorg/steemscript/blob/master/apps.json

**Comment by drov0** [comment]
> I think app url scheme should be stored with the full url.

Agreed, I talked about it in the initial proposal.

> I created a list of app with their url scheme

This is awesome ! It'll definitely help me implement this :D

**Comment by relativityboy** [comment]
@drov0 - I appreciate the creativity.

The `app` tag as described here is not good juju. See: https://steemit.com/steemdev/@valuproposition/re-jesta-re-howo-steem-improvement-proposal-canonical-links-20180217t054225178z

I'm closing this issue as #336 is closer to a first step at a solution, and was reopened recently by @roadscape
