### ISSUE TITLE
research a blackbox / selenium test suite

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#2507]
create a quick set of selenium scripts to test loading the homepage, finding certain important content items, ensuring no js errors happen, logging in on testnet, posting, upvoting, logging out.

**Comment by sneak** [comment]
re-scoping this issue to simply creating a test suite, excluding any tests within that suite yet. empty test suite should be added to ci for done-ness.

**Comment by bnchdrff** [comment]
got the selenium / chromedriver test runner all set up to go, along with an example test that loads the home page & checks for console errors

i'm not quite sure how to orchestrate this to run in CI, since we currently just rely on ci doing a docker build -- we'll want to do a docker build, run the image, and then execute this new test runner... is this possible?

**Comment by jnordberg** [comment]
Circle ci 2.0 can have multiple workflows that can have dependencies, I think it could be setup so that the first job builds the image, then a second one spins it up as a test server and the third runs the tests against it

**Comment by bnchdrff** [comment]
started on a circlci 2 config file in [2507-blackboxtests](https://github.com/steemit/condenser/compare/master...2507-blackboxtests#diff-29944324a3cbf9f4bd0162dfe3975d88)
