### ISSUE TITLE
[Steemit] - Settings are not shown when navigating from wallet

### ISSUE THREAD

**Issue by jayserdny** [steemit/condenser#2511]
#### Expected behavior
***
When you navigate from wallet to settings, settings should show the current values in the fields.

#### Actual behavior
***
When you switch from wallet to settings, all fields are empty.

#### How to reproduce
***
Here is an easy guide on how to reproduce this issue:

- Go to your Steemit profile
- Click on Wallet tab
- Click on Settings tab

#### Current Environment
***
* Browser: Google Chrome Version 64.0.3282.140 (Official Build) (64-bit)
* Operating system: macOS High Sierra

#### Recording Of The Bug
***
![steemitbug.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518319873/pukwn3kmujxu71vr3r7q.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@jaysermendez/steemit-settings-are-not-shown-when-navigating-from-wallet">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by roadscape** [comment]
Non-issue after wallet split. 👍
