### ISSUE TITLE
Make New Select List Component.

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2519]
Changes required by #2391 necessitate a new select dropdown component, illustrated:
![](https://user-images.githubusercontent.com/3374538/35935457-7d674e58-0c38-11e8-9705-242cc30376dc.png)

Propose doing something like this:
https://material-ui-next.com/demos/selects/

Must have native support.
Also propose using:
https://github.com/rtsao/styletron

**Comment by bnchdrff** [comment]
where is the code for this that we can review?

**Comment by jnordberg** [comment]
Ping @gl2748

**Comment by gl2748** [comment]
Apologies @bnchdrff @jnordberg 

This is incorporated into the work on the header and here is the component:

https://github.com/steemit/condenser/tree/master/src/app/components/elements/NativeSelect
