### ISSUE TITLE
Welcome page banner is using the old logo

### ISSUE THREAD

**Issue by bonustrack** [steemit/condenser#2530]
The welcome page has Steemit old logo in banner image https://steemit.com/welcome
![image](https://user-images.githubusercontent.com/16245250/36331994-d31b34c4-13a2-11e8-84bf-88a45f93d3f2.png)
It may confuse some users.

**Comment by TimCliff** [comment]
Dupe: https://github.com/steemit/condenser/issues/2493

**Comment by bonustrack** [comment]
Oops
