### ISSUE TITLE
Remove Savings accounts

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2541]
As a new user, the sheer number of token types and actions on the wallets page are overwhelming. 

----

Savings functionality on Condenser is being phased out (due to the additional complexity, the usual 0% interest and concerns around it still being vulnerable to attack with a relatively small 3 day time lock).

The work:

1. If a user has a zero balance in either their STEEM Savings or SBD Savings, remove it from being listed in their wallet view. This means that new users who join the platform after this change will not initially see Savings accounts. 

2. Remove the 'Transfer to Savings' options from the dropdowns of the STEEM and SBD balance (see below).

![screen shot 2018-02-18 at 5 09 55 pm](https://user-images.githubusercontent.com/1121139/36359524-1c686316-14d1-11e8-972b-5edea127a40a.png)

Notes:

- If a user has a Savings balance, we'll continue to display it and enable them to withdraw it out of Savings.
- Although Savings are being removed from Condenser, the functionality will continue to work and may be utilized by other Steem interfaces and applications. 
- Since people can use other Steem apps to add to Savings, we'll continue to display any Savings balances (and add it to their estimated total USD balance).

**Comment by roadscape** [comment]
Now that we have a dedicated app for wallet we could leave this feature in.
