### ISSUE TITLE
Minor UI updates to Settings

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2542]
Some UI and structural cleanup for the Settings page, enabling us to add future user preferences, like rewards preferences.

![slice 2](https://user-images.githubusercontent.com/1121139/36365899-5c6c7f40-1500-11e8-89f6-e191e7cabb18.png)

**Comment by gl2748** [comment]
Confine to this page.

**Comment by originated** [comment]
Please see PR https://github.com/steemit/condenser/pull/2589
