### ISSUE TITLE
The 'Search' Icon Directly Overlaps The 'Create new post' Icon When Viewing Promoted/Trending post.

### ISSUE THREAD

**Issue by bluishjane** [steemit/condenser#2549]
###### N.B :This bug was noticed while using the mobile interface.

The two icons mentioned are usually separated by a significant gap, hence it is possible to use each of them without the conflict of choosing one when you mean to choose another.
The search option looks like a magnifying glass icon, while the 'creat new post' option is represented by a pen icon.. and post are situated at the top of the pages.

#### Actual behavior
When viewng trending or promoted post, both icon somehow breach the gap and meet in a way that the search icon overlaps the 'create new post' icon.

#### How to reproduce
* Visit www.steemit.com
*  Follow a particular tag and view it's trending or promoted section.
* There you will find that the search icon had moved to now overlap the 'create new post' icon

* Browser:  EKSTAR BROWSER V15.0
* Operating system: ANDROID NOUGAT, VERSION 7.0

#### Recording Of The Bug
![PicsArt_02-18-08.52.21.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518941502/gqroodmggpgbizgom0cy.jpg)
........
![PicsArt_02-18-08.51.28.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518941531/e53umw1yw1sc3mlcr2ch.jpg)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@bluishjane/the-search-icon-directly-overlaps-the-create-new-post-icon-when-viewing-promoted-trending-post">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by roadscape** [comment]
Thanksd for the report. This issue should be resolved now
