### ISSUE TITLE
Received both welcome + approved account mail, but doesn't work

### ISSUE THREAD

**Issue by meeposki** [steemit/condenser#2550]
Hello, I registered on steemit few weeks ago, and since I didn't know how long it would take to be approved, I forgot about it until few days ago, I clicked on the "your account has been approved" mail's link, but when I do so i get this message:

"This is not a valid sign up code. Please click the link in your welcome email."

and when I click on the link in my welcome email, this one:

"confirmation code not found".

now my phone is pegged to this account and when I try to make another one, they say "this phone number is already used".

What can I do? 

Thank you by advance!

**Comment by TimCliff** [comment]
@meeposki please ask for help in the help channel of steemit chat.

**Comment by meeposki** [comment]
@TimCliff where can I find that sir?

**Comment by TimCliff** [comment]
Main menu on steemit.com

**Comment by meeposki** [comment]
Well, i registered using two emails and never received mail confirmation on neither of them :(

**Comment by TimCliff** [comment]
Message me here on discord chat. I will reply within 24 hours.
https://discord.gg/HYj4yvw
