### ISSUE TITLE
Can´t login

### ISSUE THREAD

**Issue by AdrianL8** [steemit/condenser#2554]
Dear Steem Team,

I have registered me about five days ago. I got a sms with my steem verification code but i didn´t get a verification email. Is it usually that it tooks relatively long or did I made an error?

Thanks for helping

**Comment by TimCliff** [comment]
Please review the steemit.com FAQ

**Comment by CF84** [comment]
I registered on February 12th and still haven't received a verification email. If I want to register again, I get the message that my phone number is already in use. Also, I cannot register with steemit.chat. I don't get an e-mail there either. I checked the spam folder.

**Comment by TimCliff** [comment]
CF84 steemit chat registrations should be fixed. Can you please give it another try?

**Comment by CF84** [comment]
Yes, it worked now. Thank you.

**Comment by kutrysfour** [comment]
Hello, I have same problem, when I put my phone number, it will show that number us already verified. I am already waiting 3 weeks for some news from steem, email support didnt respond yet. Could you please anyone help me what can I to resolve this and finally get signed. Thank you, Lukas

**Comment by TimCliff** [comment]
Please ask for help in the help channel of steemit chat.

**Comment by kutrysfour** [comment]
Ok, I’ll do it. Thanks
