### ISSUE TITLE
comment URLs can get munged in render

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#2556]
A valid URL to a comment gets transformed into a broken link.

```
https://steemit.com/spam/@test-safari/34gfex-december-spam#@test-safari/re-test-safari-34gfex-december-spam-20180110t234627522z
```

Rendered as:

![image](https://user-images.githubusercontent.com/5168676/36504002-add1bf60-1714-11e8-9322-62c10e142f0d.png)

-------

## Minimal failing test case

Seems as though `#` followed by `@` causes it

```
https://steemit.com/foo#bar

https://steemit.com/foo#@bar
```

![image](https://user-images.githubusercontent.com/5168676/36504057-d66ec88c-1714-11e8-8e2c-1edeab6a32c1.png)

## To reproduce

Paste the valid comment URL `https://steemit.com/spam/@test-safari/34gfex-december-spam#@test-safari/re-test-safari-34gfex-december-spam-20180110t234627522z` into https://steemit.com/submit.html

**Comment by roadscape** [comment]
ben states:

> has been broken at least since feb 8 / 75d5772a33f6af099bacaa4678c6b12a93f297da
> it worked at e643f10964321465791114d3549c115dd4c83d63
> didn't do a full bisect, though

**Comment by bnchdrff** [comment]
worked at 57706605ccc176af4953fe4aba2698aecec43548 (dec 4 2017)

**Comment by bnchdrff** [comment]
regression caused by the mention linking changes in 4d9ac106c1e75f5a2391a53b11abb1e7dbc08504
