### ISSUE TITLE
tag previous condenser-signed-up users in conveyor tagging database

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#2559]
As a user who signed up via the old condenser signup system, it is important to steemit that my previous TOS agreement is recorded in the conveyor tagging database, and that I am not prompted in the future to agree to the same version of the TOS.

**Comment by goldibex** [comment]
Get the list of users who signed up on condenser before we changed over to faucet signups and mark them in conveyor as having agreed to the TOS.
