### ISSUE TITLE
Account Recovery issues

### ISSUE THREAD

**Issue by r351574nc3** [steemit/condenser#2561]
I am trying to recover an account with the following:

```typescript
    return steem.broadcast.requestAccountRecoveryAsync(wif, user, accountToRecover, newOwnerAuthority, [])
        .then((results: any) => {
            console.log("Results %s", JSON.stringify(results));
        },
        (error: any) => {
            console.log("Unable to request recovery 1 %s", JSON.stringify(error));
        });
```

The result is the following:

```
{"cause":{},"isOperational":true}
```

How do I get my account into `isOperational: false`?

**Comment by bnchdrff** [comment]
hey, sorry for putting you on a wild goose chase but i didn't realize this is within your own app... this is really a steem-js issue. maybe someone can just address it here, though.

**Comment by r351574nc3** [comment]
@bnchdrff that's ok. I really think it's a steem issue. In the FAQ, it's only for hijacked accounts and I think that's what the `isOperational` is for. I think it means that my account isn't hijacked, so it can't recovery it. 

The idea is that the account was created with `steem.broadcast.accountCreate` by a third party and the keys were never sent or lost, but there is a recovery account. I would think then, that the recovery account should be able to recover accounts that the keys were never given or were lost to, correct?

The trouble is that if the API has a built-in countermeasure that states only hijacked accounts can be recovered, can anything be done?

**Comment by bnchdrff** [comment]
i'm pretty sure that the `isOperational` symbol you're seeing is related to a bluebirdjs library error -- maybe post a stack trace & someone can help more

**Comment by r351574nc3** [comment]
Ok. I'll post in steemjs.

**Comment by r351574nc3** [comment]
steemit/steem-js#351
