### ISSUE TITLE
Feed layout is not well aligned while loading

### ISSUE THREAD

**Issue by bonustrack** [steemit/condenser#2565]
When a feed is loading, the layout is aligned to left. It feel a bit off because once it's loaded it appear centered.
![image](https://user-images.githubusercontent.com/16245250/36639950-69d83a54-1a49-11e8-9e8e-f22cc41198f9.png)
![image](https://user-images.githubusercontent.com/16245250/36639972-e293a0dc-1a49-11e8-9936-0e582d6b81ab.png)
It's not visually pleasant and a bit annoying if you want to interact with the right sidebar when the layout is moving like that.

**Comment by roadscape** [comment]
Unable to replicate, closing for now.
