### ISSUE TITLE
Include paid sign up options 

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2568]
As a user, I want to sign up for a Steem account instantly. 

-----

Let's provide options on signup.steemit.com for users to be able to signup instantly via paid options, including Blocktrades and AnonSteem.

**Comment by goldibex** [comment]
- [ ] Add links to Blocktrades and AnonSteem's relevant "pay-for" signups

**Comment by bnchdrff** [comment]
moved to https://github.com/steemit/faucet/issues/245
