### ISSUE TITLE
New bandwidth error modal UI with 'Buy Steem' button

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2569]
As a user, when I perform an action that fails due to a lack of bandwidth, I need to see actionable items that help me resolve the issue, so I can continue interacting on Steemit. 

----

When a user interaction fails due to a lack of bandwidth, let's display a modal window which explains the issue clearly and provide buttons, prompting them to buy Steem or power up to Steem Power.

_Notes:_ 

- This will only be displayed to users when they're prevented from doing an interaction / transaction. 
- We'll continue to research better medium term options around solving bandwidth issues.

**Comment by TimCliff** [comment]
@pkattera - one thing to be aware of is that if they are out of bandwidth, they can not power up liquid STEEM - as this requires bandwidth to do. The only real option in this regard is to purchase “Steem Power” via the BlockTrades interface, which actually lets them buy it directly as Steem Power, so it arrives in their account powered up.

**Comment by pkattera** [comment]
@TimCliff Good point! So let's only include one button to 'Buy Steem Power' and link it to Blocktrades. 

Regarding the blocktrades link, are we happy to push it to:

**Comment by TimCliff** [comment]
Lgtm

**Comment by plink01001** [comment]
Related issue: https://github.com/steemit/condenser/issues/2443

**Comment by pkattera** [comment]
Lightbox / modal to be displayed when a user performs an action that triggers a bandwidth error:

![screen shot 2018-03-18 at 10 18 07 pm](https://user-images.githubusercontent.com/1121139/37579224-4ba964ec-2afa-11e8-8b87-27603fcf96f9.png)

Text:

> **Your [post] failed to process**
> 
> **Why? You've run out of bandwidth.**
> 
> Actions such as posting and voting use computing resources placing a real cost on the community members who run the Steem blockchain for everyone.
> 
> To keep things free, Steem intelligently allocates bandwidth to each user based on their Steem Power holdings, their recent usage and overall network demand. This system prioritizes actions by good community members while limiting spam.
> 
> To keep interacting on Steemit:
>   1. Buy and hold more Steem Power
>   2. Wait until your bandwidth recharges
>   3. Wait until the network usage decreases

The 'Buy Steem Power' link will take the user to Blocktrades with their user name prepopulated and 'Ether' to 'Steem Power' selected.

**Comment by gl2748** [comment]
Error is being thrown here:
https://github.com/steemit/condenser/blob/a0a293ea8f912387a0fcc78c3f5fa689b4b52f09/src/app/redux/TransactionReducer.js#L143

**Comment by gl2748** [comment]
![modal](https://user-images.githubusercontent.com/3374538/37738954-a6c3970c-2d26-11e8-812e-e1ec44c2fdbb.gif)

**Comment by pkattera** [comment]
Nice work @gl2748 – is it possible to replace 'transaction' in the heading with the specific action the person was trying to do? For example, in the vote example, it could read `Your up vote failed to process'. We could do it for the following items, with 'transaction' as the fallback. 

- Posts: 'post'
- Comment: 'comment'
- Upvote: 'up vote'
- Downvote: 'down vote'
- Transfer: 'transfer'
- Power up: 'power up'
- Power down 'power down'
- Rewards claim: 'claim'
- For anything else (like market purchases, savings transfers etc.), use: 'transaction'
