### ISSUE TITLE
user should not be able to post mostly similar comments in sequence via condenser

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#2572]
For comments under a certain size, condenser should prohibit the user from posting mostly-similar comments to comments a user has recently posted in their history, to cut down on repetitive spam comments.  Something like a hamming distance or diff from n recent comments, thresholded.

**Comment by abitmore** [comment]
I don't think this makes sense. a) It's hard to identify similar comments, spammers are usually better at getting around the restrictions. b) There may be false positives that may drive legit users away. c) Most spams are done by bots.

**Comment by sneak** [comment]
It's not technically difficult at all.  False positives would still be content that isn't very beneficial, and we can provide a good UX around this. The third issue you raised isn't an argument against cutting down on condenser-originated spam.

There are other spam-fighting measures in the works, but I think that in the short term this would cut down on a lot of copypasta drive-bys.

**Comment by roadscape** [comment]
This would be great but no implementation and no immediate plans
