### ISSUE TITLE
clicking a comment from the replies page does not scroll down to the anchor

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#2580]
The URL has an anchor on it, and the comment is highlighted, but the user must scroll down to find it.  The page should scroll directly to it.

**Comment by caleblogan** [comment]
It seems to be working for me. Do you have any more details on this? One thing I noticed is the comment is only highlighted on refresh. Is that the intended behavior or should it be highlight on click as well?

**Comment by TimCliff** [comment]
It is most noticeable on posts that have a very large number of comments.

**Comment by bnchdrff** [comment]
proposed fix: change comment deep links to point at the comment & children to avoid this issue

**Comment by roadscape** [comment]
The associated PR helps to alleviate the problem by linking comments to their parent, instead of the root. Thus for depth-1 comments, this means no change; for anything deeper the experience is improved.
