### ISSUE TITLE
SBD disappeared?

### ISSUE THREAD

**Issue by DesignPixelZ** [steemit/condenser#2581]
So I got 50 SBD from someone, I went to market to sell that for steem.
Seccounds after that I was getting this message:

```
Sorry.
Looks like something went wrong on our end.
Head back to Steemit homepage.
```

Now, my 50 SBD is gone!!! Guys, I'm freaking out.
![image](https://user-images.githubusercontent.com/11901639/36816085-72532a6a-1ce5-11e8-94e5-74a9850f249d.png)
![image](https://user-images.githubusercontent.com/11901639/36816106-7d8c0a50-1ce5-11e8-8927-330d80b357f1.png)
![image](https://user-images.githubusercontent.com/11901639/36816132-940d07e8-1ce5-11e8-9e45-b043c996bfc6.png)
Account: https://steemit.com/@mup/transfers

**Comment by TimCliff** [comment]
Check what happened on the block explorer: steemd.com/@youraccount. Nothing should be lost, but the GUI may not be rendering the data properly.

**Comment by DesignPixelZ** [comment]
I did, but is not loading / working.

**Comment by TimCliff** [comment]
Unfortunately the block explorer is down, but I checked and the blockchain has a record of your order. What happens if you refresh the order page? Also, what browser are you on?

**Comment by DesignPixelZ** [comment]
I don't see anything my order or anything. But if I click on "market" from the SBD dropdown nothing will load.

**Comment by TimCliff** [comment]
Can you close out then refresh, and take a full page screenshot of the market page, as well as your wallet?

**Comment by DesignPixelZ** [comment]
![2018-03-01-00-31-steemit com 1](https://user-images.githubusercontent.com/11901639/36816893-f633b8a2-1ce7-11e8-85d2-b4ba4dec408f.png)
![2018-03-01-00-31-steemit com 2](https://user-images.githubusercontent.com/11901639/36816894-f654c3a8-1ce7-11e8-91d0-9457dc3b4ba0.png)

**Comment by TimCliff** [comment]
At this point I am fairly confident that it is just a display issue, and your coins are not actually missing. Still digging into it to see what is causing it though.

**Comment by DesignPixelZ** [comment]
Same thing happens on firefox too. I saw the blockchain record now and I'm a bit reassured, but still scared. Bug or not, this is really scary.

**Comment by mvandeberg** [comment]
Your SBD is still there. It is a problem with the steemd API.

**Comment by mvandeberg** [comment]
Steem issue steemit/steem#2172

**Comment by DesignPixelZ** [comment]
Now everything is working again. :+1:
