### ISSUE TITLE
Create a steemit/dtube account without a cell phone

### ISSUE THREAD

**Issue by GThib** [steemit/condenser#2583]
Greetings,

I have got no and never will a cell phone.

How can I create a steemit/dtube account then?

Thank you in advance.

**Comment by TimCliff** [comment]
There is info for alternative signup methods in the steemit.com FAQ.

**Comment by GThib** [comment]
Thank you.

As far as I discovered one has to pay about 45 USD to open an account without a cell phone confirmation.
Is this right?

**Comment by TimCliff** [comment]
It depends on which service you use. I’ll there ayany further questions on this, please contact me on steemit chat. GitHub is not the appropriate place for this discussion.

**Comment by GThib** [comment]
Thank you, I will try to find you there.
