### ISSUE TITLE
default to english translation if another language is not found

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#2592]
we can do this by wrapping calls to counterpart. this will make the site more usable when new translated strings are added but the non-english translation sets are not immediately updated.

**Comment by caleblogan** [comment]
Doesn't this do that already https://github.com/steemit/condenser/blob/master/src/app/Translator.js#L42 ?
Or do you mean something else?

**Comment by bnchdrff** [comment]
you are totally correct & i completely overlooked it since it doesn't apply to my dev env :upside_down_face: !
