### ISSUE TITLE
Unable to change any settings/profile images since before Christmas

### ISSUE THREAD

**Issue by mobbs2** [steemit/condenser#2593]
Account: @mobbs

I've been stuck with my christmas theme for months now. any attempt to change simply gives me the error 'Server returned error' - no other information. 

Timcliff and I have tried numerous variations; Chrome, Explorer, Firefox on Windows. Tried on another device; android phone, all of these with and without VPN. Attempted to change and clear all details in the boxes, various types of URLs to the images - all simply 'server returned error'

The same URLs work on both a friends account and my second account. It seems it's specifically my account that holds an issue. It's not limited to the URLs, *any* change comes with 'server returned error'
![image](https://user-images.githubusercontent.com/36998976/36914625-dfa3c044-1e88-11e8-958f-08dc509061e6.png)

**Comment by caleblogan** [comment]
Have you checked the console for more info about the error?

**Comment by mobbs2** [comment]
Sorry I'm not computer savvy - The console in the inspector shows a whole load of errors that I don't understand mostly boiling down to these repeating errors:

h: uncaught TypeError: Cannot read property 'toString' of undefined

c: uncaught Error: Account not found

**Comment by eonwarped** [comment]
@mobbs2 :  I think I know this error now that I was investigating another error that had to do with "Account not found". By any chance are you using a suffix like  /active  to login with a username? I believe I have a fix for this situation. Now that I have an issue that's out I can reference this as well.

**Comment by eonwarped** [comment]
(If that is the case, the workaround is to not login with the /active  attached to the end of the username and drop the suffix, using the active private key as the password)
