### ISSUE TITLE
transaction confirmation modal

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2599]
When I do a transfer to another user, it shows a 'standard' login page. It would be very useful if this page showed a summary of what was about to be signed, such as "sending X STEEM tokens to @user; memo: xyz" (or something like that). It also seems unnecessary to have the "Sign up. Get STEEM" option at the bottom, since a user who is already logged in and sending tokens already has an account.

![image](https://user-images.githubusercontent.com/20735105/36929391-8fef9a60-1e55-11e8-9062-399913a3688e.png)

**Comment by gl2748** [comment]
On this screen:
'Use your active/owner key to confirm this transaction',
Also potentially add a step to the transfer process ... where the transfer is summarized prior being confirmed.

@roadscape also notes there is something on the market page that does something similar.

**Comment by roadscape** [comment]
Relevant implementation on Market page: https://github.com/steemit/condenser/blob/master/src/app/components/pages/Market.jsx#L1054-L1095

**Comment by gl2748** [comment]
There is a newer looking modal described in this issue, perhaps its implementation can be used here:
https://github.com/steemit/condenser/issues/2569

**Comment by pkattera** [comment]
Currently on the authorization screen, the password field is the only relevant piece of information. Everything else is a distraction and not required.

![screen shot 2018-03-21 at 3 16 20 pm](https://user-images.githubusercontent.com/1121139/37740407-d5ec85fe-2d1a-11e8-9b40-f271a78edcef.png)

As @TimCliff mentioned, the main issue is that users do need see a confirmation screen before authorizing the transaction. Ideally, the user would be able to authorize and visually confirm the transaction at the same time.

### When authorization required

Let's create a new confirmation screen which shows user's the details of their intended transaction and an input for their Active Key / Master password. This enables a user to check the transaction and authorize all at once.

For example:

![posting](https://user-images.githubusercontent.com/1121139/37750531-d2cc22d2-2d4a-11e8-868e-9cac9d144b21.png)

The logic for the copy under the 'transfer to' username (which reads 'Following' in the screenshot):
```
if transactions between the users is >= 1 { copy is '[X] past transfers' }
else if logged in user follows the person they are transferring to { copy is 'Following' }
else { copy is 'Member since 03/2018' }
```

### When no authorization is required

If no key is required to authorize the transaction, e.g. when a user recently provided their active key / master password, simply exclude the 'key' input and show the rest of the confirmation details. e.g. 

![active](https://user-images.githubusercontent.com/1121139/37751254-947134e2-2d4e-11e8-9d27-6718d709d3f4.png)


### Additional states

#### Once a user has put in a valid key

The button becomes enabled.

![posting2](https://user-images.githubusercontent.com/1121139/37751222-76a00380-2d4e-11e8-9149-caebb0348e31.png)

#### Error states

![posting3](https://user-images.githubusercontent.com/1121139/37751231-7ea3cfda-2d4e-11e8-9cc7-1d8d422a027d.png)

---

Note: If someone builds out the elements of confirm screen, I'm happy to help with the css styling.

**Comment by gl2748** [comment]
@pkattera what does the back button do? close the modal?

**Comment by pkattera** [comment]
The back arrow would go back to the input screen:

![screen shot 2018-03-22 at 3 58 26 pm](https://user-images.githubusercontent.com/1121139/37802993-eb9a2cce-2de9-11e8-8093-09ae19e5dfd1.png)

(or a future version like this)

![posting](https://user-images.githubusercontent.com/1121139/37803029-17e46196-2dea-11e8-8a34-a010c0988690.png)
