### ISSUE TITLE
Phone number and eMail contest and recovery

### ISSUE THREAD

**Issue by krischik** [steemit/condenser#2603]
#### Problem
I friend of mine recently wanted the create a steemit account but was denied with the following error message:

![image](https://user-images.githubusercontent.com/685853/36947573-258e16d6-1fce-11e8-8a7b-df5a92c71cf6.png)

<p>We don't know if this is because of a previous attempt to create an account or because someone with that similar phone number made a registration request. Either way: I can see several problems with phone numbers as registration requirement.</p>
<ol>
<li>Phone numbers are not a live long property. You can loose a phone number by getting a new contract with a different company. Especially if you move to another country. The number can also be assigned to a new user which then won't be able to register.</li>
<li>People might make a typo when trying to register. Unlike a typo in an e-Mail the mistyped number will most likely still be a valid phone number. If the true owner of that number wants to register he or she will be denied service.</li>
<li>Speaking of denied service: a malicious person could start and abandon a registration with someone else phone number in a deny of service attack. This is also valid for E-Mails.</li>
</ol>

#### Proposal
<p>Adding a requirement for  phone numbers, and in lesser degree EMail, without a recovery process seems to be a mayor design flaw top me. I suggest that the follwowing two features are added to the system:</p>
<ol>
<li>Registrations expiry: a registration attempt should expire after a short while freeing the number and Email for a new user.</li>
<li>Number and eMail contest and recovery: A user should be able to contest the use of an eMail or phone number by another user as false.</li>
</ol>
<p>Both options should be placed at an easy to find location in the GUI as they are mostly needed by new users which can't be expected to know there way around the system<p>

#### Benefits
More news users make it though the registration process. Less fraught.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@krischik/phone-number-and-email-contest-and-recovery">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by TimCliff** [comment]
The only purpose of the phone number is to prevent users from creating multiple accounts. If “Registrations expiry: a registration attempt should expire after a short while freeing the number and Email for a new user.” is implemented, then users would just use this to create multiple accounts.

It will not be marked as “in use” unless/until they verify the SMS, so there is no potential for a DoS against users’ phone numbers unless the attacker has the ability to verify the phone number via SMS.

The signup method is _a_ way for users to get accounts on the Steem blockchain, but it is not the *only* way. If a user gets a new phone number, and the previous owner had already used the number to create an account - they can still use any of the alternate signup methods listed in the steemit.com FAQ.

Also, this issue should be closed as the signup system is not maintained in the condenser repository. It has it’s own repository: faucet.

**Comment by krischik** [comment]
@TimCliff Oh, I did not know about the facet part. I repost there.

**Comment by krischik** [comment]
There is already a report https://github.com/steemit/faucet :

https://github.com/steemit/faucet/issues/243

I close as duplicate.
