### ISSUE TITLE
Error scrolling to the bottom of /payout page

### ISSUE THREAD

**Issue by inertia186** [steemit/condenser#2604]
#### Expected behavior

When scrolling down to the bottom of steemit.com/payout, I expect the posts to load continuously.

#### Actual behavior

It stops loading at the bottom of the first page and we can only see the spinning gif icon indicating that it's still loading, but it never does.

#### How to reproduce

Browse to https://steemit.com/payout and scroll to the bottom.

* Browser: Chrome Version 64.0.3282.186 (Official Build) (64-bit)
* Operating system: macOS High Sierra 10.13.3

#### Screen Capture Of The Bug

![](https://steemitimages.com/DQmRVDZCAZHQbdhjfq1EY2h2GxxmduEBRTppgrfyi6kzxi4/image.png)

Looking at the JavaScript console, we see:

```
Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
```

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@inertia/error-scrolling-to-the-bottom-of-payout-page">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by inertia186** [comment]
Same behavior for `https://steemit.com/payout_comments`

**Comment by roadscape** [comment]
This is strange, the pagination response seems to come through just fine.
