### ISSUE TITLE
Wrap new notification system in feature flags

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#2613]
Ensure only users with the `new notifications` feature flag set to true experience the new notifications system by wrapping all related components (and even saga fetches) in a feature flag test.

**Comment by sneak** [comment]
let’s use an integer for anything like this instead of relative terms like “new” - perhaps “notifications2pretest”.

**Comment by bnchdrff** [comment]
using feature flags to determine whether or not to run notification related sagas implemeted in https://github.com/steemit/condenser/tree/notification-ui-rebased-squashed-merged

wrapping the actual components is not done; pending work following https://github.com/steemit/condenser/issues/2928 - this part is simple though :)

**Comment by bnchdrff** [comment]
closed by pending work in the aforementioned branch
