### ISSUE TITLE
Add blacklist for phishing sites (replace link with warning)

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/condenser#2616]
Lately we have a lot of scam sites that are used to steal people passwords, by impersonating Steemit, Steemconnect or just luring people to log in with their Steem credentials.

We need to be able to put list of such domains on a blacklist and then replace links to such sites with a warning and do not allow people to follow such links etc.

For example:
`[click here](http://therealsteemit.com/enteryourpassword)`
adding 'therealsteemit.com' to the blacklist should get rid of above link
plus variants like:
`https://therealsteemit.com/`
`http://signup.therealsteemit.com/`
etc.

**Comment by bnchdrff** [comment]
create a static list like BadActors and reference it during HtmlReady to either hide links behind clickwall or just unlink them (render as plain text)

**Comment by roadscape** [comment]
I'd recommend simply unlinking them; do we just discard the link text, if any?

**Comment by bnchdrff** [comment]
i just found this set of related work https://github.com/steemit/condenser/pull/1515

**Comment by bnchdrff** [comment]
design the bad actor check in a way that would work async (so if we eventually ask network services we can use this same system)

**Comment by bnchdrff** [comment]
rather than requesting the phishing list at render we could eventually load it at the beginning of the session -- no need for it do work async actually
