### ISSUE TITLE
clicking #-tag in body exceeding 1169 chars triggers a "502 Bad Gateway"

### ISSUE THREAD

**Issue by crokkon** [steemit/condenser#2618]
#### Expected behavior
Clicking a `#[tag]` in the body of a contribution in Condenser should show trending posts with the the given tag on `steemit.com/trending/[tag]` or none.

![01_1169chartag.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520325408/xmi8cao7zmo75fkx8qmo.png)

#### Actual behavior
If a tag has more than 1169 chars, a click on the tag results in a "502 - Bad Gateway" nginx error

![01_1170chartag.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520325457/nktsyi3uwgfxgcgtdwqt.png)

#### How to reproduce

Here's an example post with two tags:
https://steemit.com/python/@stmdev/testing--tags---mentions
* tag with 1169 chars after the "#" -> working
* tag with 1170 chars after the "#" -> 502 Bad gateway

Environment:
Most likely independent from OS/Browser, tested with Firefox + Chrome on Linux

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@stmdev/clicking-tag-in-body-exceeding-1169-chars-triggers-a-502-bad-gateway">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by roadscape** [comment]
Need to cap tags at some reasonable length. Check what hivemind supports... 16? 32?

**Comment by quochuy** [comment]
@roadscape  The 1170 char tag in the example post are not showing 502 anymore.
Capping tags in the Condenser won't prevent longer tags to come from other dapps.

**Comment by roadscape** [comment]
Excellent, thanks, closing. Also confirmed hivemind caps all tags to 32 chars, which would help mitigate issues.
