### ISSUE TITLE
Cant login to steemit

### ISSUE THREAD

**Issue by domnoble** [steemit/condenser#2624]
So i created an account, i chose a username, gave it an email and a phone number, i got the SMS verification but nothing ended up in my email account, now i do use dkim, dmarc and spf to stop spam, anyway so i cannot login to steemit with that email or the account username i created, if i go to try and create another account with a microsoft email instead it says the username is still available but it wont let me use the same phone number so i cant sort out the SMS verification

**Comment by TimCliff** [comment]
Please request help in the steem chat #help channel.
