### ISSUE TITLE
Header - issues and tweaks

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2633]
- [x]  #2631 - Signin option appears in hamburger menu as an authenticated user on mobile.

- [x]  As an authenticated user, navigating from 'my feed' to 'trending' is not possible in one-step / if it is possible it is not clear.
##### propose
<img width="665" alt="screen shot 2018-03-08 at 12 17 54 am" src="https://user-images.githubusercontent.com/3374538/37152752-6161188e-22a8-11e8-8147-0d362026b06e.png">

- [x] - As an authenticated user, when I log-in and am on 'my feed' the tag-select dropdown displays 'All Tags'.

**Comment by pkattera** [comment]
The first bug to fix:

When you log in on mobile, the default page is "My Feed", however the dropdown incorrectly shows "All tags". Then when you select 'All tags' or 'My feed', the page doesn't change.

**Comment by pkattera** [comment]
I think we can solve the issue around users not being able to find trending by:

1. Fixing the bug the dropdown bug on 'My feed' (as I mentioned above)
2. Adding the disabled dropdown state with sort order set to 'New'
3. For the mobile select only, changing the option name from 'All tags' to 'All content'

**Comment by bnchdrff** [comment]
As a logged in user on a desktop screen, when I go to the homepage, select a sort order ("Hot") and then click on an article, I expect to either not see any underlined sort orders in the header, or I expect to see "Hot" (my last selectd sort order state) underlined.

**Comment by gl2748** [comment]
@bnchdrff  Addressed here: https://github.com/steemit/condenser/pull/2636/commits/1382109bd2799a5ba0ffb9648c09d18385f47e40
