### ISSUE TITLE
Header turns black after click on mobile (active state)

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#2639]

**Comment by gl2748** [comment]
^ At this point using CSS media queries level 4 is not supported by all browsers:
https://caniuse.com/#feat=css-media-interaction
It does cover the vast majority of our bases.
The alternative solution of  conditionally add a "can-touch" CSS class to the document root element might be over-kill for this issue. Per: http://www.javascriptkit.com/dhtmltutors/sticky-hover-issue-solutions.shtml

**Comment by bnchdrff** [comment]
let's remove the hover effect for now.

**Comment by gl2748** [comment]
That's what this does... and keeps it if the user's device supports the hover event.

**Comment by bnchdrff** [comment]
but we're missing ie/ff support for that "feature"

**Comment by gl2748** [comment]
In browsers that do not support that media query no hover effect will be applied.

**Comment by bnchdrff** [comment]
cool, sounds good to me
