### ISSUE TITLE
Steemit preview looks right but when I post my pictures are scrambled

### ISSUE THREAD

**Issue by Beekerst** [steemit/condenser#2646]
Below is the code that works in preview....I've messed with it so much I may have it hopelessly messed up.

So, I made this post.....it looks correct in preview but when I post it the pictures I have lined up three in a row no longer align ?????

<center>https://steemitimages.com/DQmPWoVSkzmka9ux7kMXe8R8CSxgQhxM7ce5VJtpzMzgSkt/IMG_1213.jpg</center>

This morning the Missus woke me up and said, "Let's go buy some plants, it's springtime and I want to plant the flower bed in front of the house."

Now boys, I don't have to tell you, when the little Lady says, "I want to plant something," that is wife speak for, "you are fixing to go to work boy!"

So, we jump in her car and head up to the big town of Alexandria, LA where the Home Depot is.  They've had their spring flora out for about two weeks and the plants haven't been too picked over yet. 

Anyway, I headed off to the tool aisle while she looked over the merchandise.

After a while, she comes to find me and makes me put back the _**Seven Piece Cordless Tool Set with FREE Palm Sander**_ included.

I followed her back to the flowers and we loaded up a couple of small pallets of _**Impatiens Walleriana**_ aka _**Bizzy Lizzy's**_ if you happen to be from Great Britain. (Ain't I smart?  I looked that up on Wikipedia so as to impress you folks!) 

So, after that, we had to go look at dresses and shoes and purses and perfumes and whatnot, before we could go to the sporting goods store for a small pack of perch hooks, on account of it's getting about warm enough to drown a worm!

Then we went to an _**all-you-can-eat**_ Chinese Buffet where she ate three shrimp, a slice of cucumber, and a piece of cantaloup.  I think I sampled a little bit of everything. She started clucking and frowning after the third plate full.  

"Well," I says, "this is gonna cost us $24.95 plus a 20% tip, I figure I'm gonna get our money's worth, by golly! No, help from you of course!"

She giggled and sipped her unsweetened tea. "Your going to get fat!" she replied. 

"Am not," I said, "This here just happens to be a diet drink!"  I took another swill from my third glass.

Back at the ranch, I was sent out to the barn to get a shovel, a yard rake, a hoe, a garden rake, a hand trowel, a pitch fork  and various other implements of destruction, (a little Arlo Guthrie right there) and was set to my task, under her watchful eye,of course.

<p><div class="pull-left">https://steemitimages.com/DQmYx6fG8G2iUhKn3pyCWhBCFKrxNi52CCWe8VewcCd5JrV/IMG_1180.jpg</div>
I used a shovel to spade up the old bed and snagged a few weeds out with a garden rake.  When the soil was broken up to her liking, she placed the plants where she wanted them and handed me a hand trowel.

"Now hold up there Missy," I said, "I fixed  the bed, don't you think someone else can plant it?"

"Bending over upsets my Lumbago!" she said.

Now I didn't know what Lumbago was but I didn't let on. I've since looked it up and I think I'll use it for an excuse myself sometime!

I snatched the trowel out of her hand and started digging holes where she pointed  and placed the plants in the holes and packed them down.
<p><div class="pull-left">https://steemitimages.com/DQmWjq1CYGdUjb1DSFDFWGyqmmbAihQXQonuofCU53U3qRc/IMG_1182.jpg</div>
<p><div class="pull-right"> https://steemitimages.com/DQmaTpmVcGmDvgTVV8sm9GVvFtd1UF352vKF8WnMaHneuXN/IMG_1185.jpg</div> 
I'd like to point out right here that my good friend @eibemmchen gave me some HTML pointers and I figured out how to get this text to position between these two pictures!  Isn't that neat?  I'm going to have to make an HTML post about all these new tricks I'm learning.  If any of you have found a neat thing to do with HTML code that you think I'd like to add to my list, please leave it in the comments. I'm collecting tricks and useful sites to share with others when I make a how-to post again.

Check out this [post](https://steemit.com/deutsch/@eibemmchen/holzring-birke-woodenring-birch-02-2018-de-en) that @eibemmchen made about making a ring from a piece of birch.  English translation is to the right of his native German.

After she was satisfied with her flowers, we took a ride around the yard. 

The thumbnail picture of this post is one of the first azaleas that we found blooming.  

<br><center>https://steemitimages.com/DQmfJb9VDT9B3PLXPSvosjvCcqHxuMSTwgJsRTvGbAa8Bkb/IMG_1192.jpg</center>
<center>Hydrangeas are Popping Out</center><br>

We had snow about six weeks ago.....IMAGINE THAT.... snow in central Louisiana! It was super cold, at least for us, for about four straight days. 

<p><div class="pull-left"> https://steemitimages.com/DQmTn4SqBNuzjr7BZ75gTZZ4jXFX4Z4vcfyGMk14nCEhYxK/IMG_1197.jpg</div> 

My poor citrus trees got hammered!  This satsuma tree should keep it's leaves all year but the hard freeze killed all the foliage. I think it may survive, the little buds are green and it may even bloom. I doubt if I get any fruit this year though. First comment that says 0.5 SBD in the comments is a winner. We stopped in the vineyard and got out to check the vines. 
My little wiener dog, Molly, kept the mule safe for us.

<p><div class="pull-right">https://steemitimages.com/DQmUxhgq2YeEKrBv8jt3UmESJtZ5CedcdxLxNpNos355ms3/IMG_1187.jpg</div>

She likes to ride!  She can be laid out in her favorite sunny spot, and if someone says,"Molly, you want to go for a ride?" She is ready!
In the vineyard ,I found the Concord and Spanish Black vines were putting on leaves! Most of the Muscadines were dripping sap from the ends of the pruning scars.  This is normal and means spring has sprung and things are cranking up in that big circle of life! 
 I took this opportunity to set out one of my bee swarm traps. That's it hanging in the tree below. I built seven of these this year and it may be too early, but I'm like a kid at Christmas, I wanna play with my toys. Besides, I think the bees will scope it out and remember it come swarm time.....I wonder if a bee remembers?

<p><div class="pull-left">https://steemitimages.com/DQmRLUXd2qfRR6oT7AoqP5X762HwRVzgBMx1xhG2tHzptnQ/IMG_1198.jpg</div>
<div class="pull-right">https://steemitimages.com/DQmdiy4hc1hS27eUKmZH78w2p5D3BoWLWrbqTnq5GeRc6sQ/IMG_1202.jpg</div>
https://steemitimages.com/DQmeiYeMxy6DG6m163EyMdUzRYjUsjoCyyFLN42NkpSJM6W/IMG_1200.jpg

<p><div class="pull-left">https://steemitimages.com/DQmZTNBGKSEDC5JQL6nmZXEmCNH6syRnggzyND6efN21SJC/IMG_1206.jpg</div>
https://steemitimages.com/DQmTjMPZperLkfgkKTJP51nrpaczDnQS7ed2vN4rxRUKJmW/IMG_1196.jpg<div class="pull-right">https://steemitimages.com/DQmZWPX4aYGUvUULRT6BxTGKzrifiG1Lrk6xfnt9VWVC9hi/IMG_1207.jpg</div>

We made a round into the orchard and found the May Haw trees in full bloom!  Well, some of them had dropped their blooms and already had small fruit on them. The Mulberry is already full of small fruit. It's still green though.
Our last stop before putting all the tools away was the bottle tree!  It's in full bloom.  I think I need to add to it, I going to the store, Huny, do you need anything?

<center>https://steemitimages.com/DQmVo6epPD7FFuGoepns5NCxqUjG69FTtQzUCUXgXwJtzHi/IMG_1212.jpg</center>

<center>Thanks for reading!  

CARRY ON!</center>

<center>https://steemitimages.com/0x0/https://steemitimages.com/DQmXmdadCYFMH2MEcHc92CYHHhVCUyCzqEUw4V3GXxWUosF/bar1.PNG</center></center> 
https://steemitimages.com/0x0/http://brandonfrye.biz/wp-content/uploads/steem.gif 
<center> 

<a href="https://steemit.com/woodworking/@beekerst/pecky-cypress-glow-in-the-dark-coffee-table"><img src="http://i.imgur.com/sK3LEbt.gif"/></a> 

<a href="https://steemit-production-imageproxy-upload.s3.amazonaws.com/DQmZ2vur8K61vgqaPA6fBF4mUZpgseRmPk3Hzpzs8zRPPAx"><img src="http://i.imgur.com/9IsAlFg.gif"/></a>

<center>https://steemitimages.com/0x0/https://steemitimages.com/DQmXmdadCYFMH2MEcHc92CYHHhVCUyCzqEUw4V3GXxWUosF/bar1.PNG</center>

**Comment by roadscape** [comment]
May be resolved in https://github.com/steemit/condenser/pull/3063
