### ISSUE TITLE
Follower-counter is not counting

### ISSUE THREAD

**Issue by Fl4shboot** [steemit/condenser#2647]
#### Expected behavior
If you click the "FOLLOW"-Button on a profile, the follower-counter should increase by 1 and if you click the "UNFOLLOW"-Button, the counter should decrease by 1.

#### Actual behavior
The follower counter is not counting when you click the "FOLLOW"- or "UNFOLLOW"-Button.

#### How to reproduce
Open a profile and click "FOLLOW" or "UNFOLLOW" and watch the counter.

* Browser: Chrome
* Operating system: Windows 10
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@flashboot/follower-counter-is-not-counting">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by pkattera** [comment]
@Fl4shboot Thanks for adding this.

It looks like the counter does work but it requires a page refresh. 

The ideal behavior for this is to dynamically increment the counter upon pressing the follow / unfollow button without requiring a page refresh.

**Comment by roadscape** [comment]
Thanks for the report; closing as low priority. Happy to accept a PR for this change.
