### ISSUE TITLE
I need help changing my username can somebody help my display name

### ISSUE THREAD

**Issue by zenashopson** [steemit/condenser#2648]
Hi I need help changing my display name/user name on this platform nobody seems to be able to help me https://steemit.com/@zenashopson if you go on my profile you will see my display name as N/A I would like to change it to Zenas Hopson but every time I get a error message saying this (Server Returned Error)

**Comment by Smittyvb** [comment]
Try [this SteemConnect link](https://steemconnect.com/sign/profile-update?name=Zenas%20Hopson).

**Comment by zenashopson** [comment]
It’s not allowing me to login  which one of my passwords I should use?

**Comment by zenashopson** [comment]
It’s not working

**Comment by Smittyvb** [comment]
Either your master password, or your active key. You can’t use your posting key to change your display name.

**Comment by zenashopson** [comment]
The active Key and the  owner key does not work in this website   I get this error message  Password or key is not valid

**Comment by Smittyvb** [comment]
Make sure you’re using your private key, not
a public key. Public keys start with STM, private keys start with 5J, and master password start with something else (I can’t remember)

**Comment by zenashopson** [comment]
[
![e1748b73-2b55-4946-9a08-5fbfe3a3c935](https://user-images.githubusercontent.com/19496842/37491712-b68febf4-286c-11e8-80f0-361fc0dca6e2.png)

 This is the error message I’m getting

**Comment by zenashopson** [comment]
It’s not working look at the picture above

**Comment by zenashopson** [comment]
It’s not working!! Help   Do you think you can take over my computer and show me how it works

**Comment by Smittyvb** [comment]
What password/key are you entering in the second box?

**Comment by Smittyvb** [comment]
For example:
- master password
- active key

**Comment by zenashopson** [comment]
This is the URL that I am on and I filled out the password like you said using the master password this is the  Picture 


![dc12680e-8d95-4b81-b354-abed7f687f0a](https://user-images.githubusercontent.com/19496842/37492301-d76fee62-286e-11e8-83b8-ce20fb6c07fe.jpeg)
![80df0594-a3c9-496e-b403-04865352dd96](https://user-images.githubusercontent.com/19496842/37492302-d7865a4e-286e-11e8-8838-d517eae0ce5c.jpeg)

**Comment by zenashopson** [comment]
This is what my dashboard says it does not say master  password  and private key  here’s a picture I blurred out my password 
![fe552038-e948-4c9a-9fad-4c1297a9fe2d](https://user-images.githubusercontent.com/19496842/37492462-816be560-286f-11e8-81ae-51ece460a337.jpeg)

**Comment by Smittyvb** [comment]
Try using your active key to login to SteemConnect. Press “LOGIN TO SHOW” beside your active key — STM5n3EPaGuMDMgPBJZFAj1qtL6SrdTU6Mj96nMdY7ZLPEpZCUPa3 — and it will change. Use that new value on the SteemConnect link.

**Comment by zenashopson** [comment]
Are you saying put the password did you put  in to the password on Steemit connect

**Comment by Smittyvb** [comment]
Put the new value that STM5n3EPaGuMDMgPBJZFAj1qtL6SrdTU6Mj96nMdY7ZLPEpZCUPa3 changed too? It should start with 5J.

**Comment by zenashopson** [comment]
I don’t know how to do this

**Comment by zenashopson** [comment]
![25bd3b28-d560-4669-ba3c-470aec795d11](https://user-images.githubusercontent.com/19496842/37521689-9afce288-28ef-11e8-8eca-7fdf23e39cc6.jpeg)
![696fca47-4179-494f-a4b6-158d7f221313](https://user-images.githubusercontent.com/19496842/37521824-07207c90-28f0-11e8-8dd1-6d38946f0625.png) 
 What does this mean?

**Comment by zenashopson** [comment]
![6f2d2ab4-9b00-4d9e-87d2-6bddf2338d82](https://user-images.githubusercontent.com/19496842/37523196-2cfe9fb0-28f4-11e8-8b83-39773c2aff3b.jpeg)
![f6517345-33ce-4b5e-a4da-6b7ef96107bf](https://user-images.githubusercontent.com/19496842/37523197-2d104620-28f4-11e8-9cfb-1fc5667d3ad3.png)
 What does this mean?

**Comment by roadscape** [comment]
Hi, this looks like a potential steemconnect issue combined with steemit.com instability. Everything should be resolved now.
