### ISSUE TITLE
Pasting a copied text on steemit 

### ISSUE THREAD

**Issue by kodeblacc** [steemit/condenser#2653]
#### Expected behavior
I expected that when I paste a copied text it should appear on first click.

#### Actual behavior
When I use the editor tool(example bold tool) and I deactivate it and paste a copied text it doesn't show until I paste it again and it creates a duplicate of the text in an unordered manner.

#### How to reproduce
- Login to steemit on MOBILE PHONE
- Copy a text from anywhere
- Create a post
- Select the text editor
- Select any of the tools (bold preferably)
- Deselect the bold tool
- Paste the copied content and it won't show the first time
- Paste it again and it becomes a duplicate.
<hr>

* Browser: google chrome on android
* Operating system: android 7.0

#### Recording Of The Bug
https://youtu.be/vQeWhyFXD6k
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kodeblacc/pasting-a-copied-text-on-steemit">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by roadscape** [comment]
Hi, thanks for the report. This behavior is unfortunate but the current editor doesn't support it.
