### ISSUE TITLE
Cover photo and profile disappear from wallet page after a transfer with active key

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2657]
I noticed that after I do a transfer from my wallet (using my active key) that when the page reloads, my cover photo and profile information has disappeared. Related to https://github.com/steemit/condenser/issues/2306, which was fixed.

![image](https://user-images.githubusercontent.com/20735105/37324472-90e6378a-2657-11e8-99a5-fcf71a01b7a6.png)

**Comment by roadscape** [comment]
Non issue after wallet split
