### ISSUE TITLE
[spike] Research the viability of using AskSteem for Search

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2661]
Our search experience on Steemit.com could be improved. We currently use the free version of Google which displays a block of advertisements before displaying results.

![screen shot 2018-03-13 at 9 38 59 pm](https://user-images.githubusercontent.com/1121139/37383624-09e41f3a-2707-11e8-82a9-27d2d3934566.png)

Let's investigate using AskSteem for our site search. 
https://www.asksteem.com

A few advantages of using AskSteem:
- Autocomplete search results based on Steem indexed documents
- Ability to search for users
- Ability to search based on Steem specific attributes (like reputation)
- Supports a developer in our ecosystem and gives AskSteem more visibility to other Steem entrepreneurs. 

This post outlines some of the Steem specific queries you can do:
https://steemit.com/asksteem/@thekyle/new-asksteem-feature-user-search

**The task**
- Research the quality of search results from it vs Google (e.g. how fast does it index content, how do the rankings work etc.)
- Security implications. Is it open-source? Can we host it?
- Research the complexity of integrating it
- Research the cost of using AskSteem (if any)

**Comment by sneak** [comment]
I think we should use our own already-extant index from `sbds` to power search instead of relying on an external service, for security reasons.

**Comment by sneak** [comment]
Some basic search methods could be added to `sbds` without a huge amount of trouble, and then it would just be a matter of building a query UI to call them and display the results.

**Comment by roadscape** [comment]
Closing in favor of https://github.com/steemit/condenser/issues/3410
