### ISSUE TITLE
BUG: Incorrect following list is shown on UI when you follow someone using follow function in cli_wallet

### ISSUE THREAD

**Issue by git-iaf** [steemit/condenser#2663]
<center>

Incorrect following list is shown on [Steemit](http://steemit.com), [Busy](http://busy.org) & [Utopian](http://utopian.io) when you follow someone using `follow` function in `cli_wallet`

---
##### `follow` function prototype

```
annotated_signed_transaction follow(string follower, string following, set<string> what, bool broadcast)
```

---
In an attempt to follow [@ned](http://steemit.com/@ned) I executed the below command in `cli_wallet`

```
follow "iaf" "ned" ["blog"] true
```

Transaction ID of the above operation is [`dd94bc340465379aab307621136b92e9614f2795`](http://steemd.com/tx/dd94bc340465379aab307621136b92e9614f2795)

In my following list on Steemit [@ned](http://steemit.com/@ned) is shown with the @ sign. On click it takes to user [@@ned](http://steemit.com/@@ned) which of course doesn't exist. Same has been observed on Busy & Utopian as well. However, on [steemd.com](http://steemd.com) it's shown properly (Thanks to @roadscape 🙂).

<div class="pull-left">

![Steemit Screenshot](https://steemitimages.com/DQmT6jpZ6LzTjAMxU88hqY5FtFRQFWbyxvPDgHMTwLk5PDD/SteemitScreenshot.jpg)
<sup>[_steemit.com/@iaf/followed_](http://steemit.com/@iaf/followed)</sup>

</div>
<div class="pull-right">

![Busy Screenshot](https://steemitimages.com/DQmTN4A6HAXCe91h2RLSmhHL7rPiZPaKNqtxtKJiYBDGBTV/BusyScreenshot.jpg)
<sup>[_busy.org/@iaf/followed_](http://busy.org/@iaf/followed)</sup>

</div>
<div class="pull-left">

![Utopian Screenshot](https://steemitimages.com/DQmbFmqsA92THpdEcngtaSDkQaMaBGmTku1d3RsKFU2YJJA/UtopianScreenshot.jpg)
<sup>[_utopian.io/@iaf/followed_](http://utopian.io/@iaf/followed)</sup>

</div>
<div class="pull-right">

![SteemD Screenshot](https://steemitimages.com/DQmZFU3gMvnwbmDtV1VvGnDwsKkGpcgXWKjcBA14LDv8vkk/SteemDScreenshot.jpg)
<sup>[_steemd.com/@iaf_](http://steemd.com/@iaf)</sup>

</div>

</center>

---
<center>

_Posted on [Utopian.io -  Rewarding Open Source Contributors](http://utopian.io/utopian-io/@iaf/bug-incorrect-following-list-is-shown-on-ui-when-you-follow-someone-using-follow-function-in-cliwallet)_

</center>

**Comment by roadscape** [comment]
Hi, most likely there was an issue with the format of the operation. Please compare to the format used by steemit.com currently.
