### ISSUE TITLE
Savings withdrawal request ID is displayed in the wrong column in wallet history view

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#2667]
![screenshot 2018-03-15 at 14 26 11](https://user-images.githubusercontent.com/408977/37492029-f88ffe32-285c-11e8-8ce5-099640a14e50.png)

**Comment by bnchdrff** [comment]
should we display the request id in the memo column?

**Comment by sneak** [comment]
I don’t think the savings withdrawal request id is relevant to the user.
