### ISSUE TITLE
on my PC when I paste a copied text, the text box moves

### ISSUE THREAD

**Issue by kodeblacc** [steemit/condenser#2668]
#### Expected behavior
I expected I could paste a copied text on my blog post page without any hassle

#### Actual behavior
When I paste a copied text, the text box resizes and changes position.

#### How to reproduce
- login to steemit on your PC with google chrome or mozilla firefox
- copy any text from any where
- paste it on the text box and it changes position.

* Browser:  google chrome
* Operating system: Windows 7 professional 

#### Recording Of The Bug
https://youtu.be/gRXsU16Kr4g

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kodeblacc/on-my-pc-when-i-paste-a-copied-text-the-text-box-moves">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by roadscape** [comment]
Hi, thanks for the report. This bug may be resolved already but I couldn't access your recording.
