### ISSUE TITLE
Number of followers and number of posts

### ISSUE THREAD

**Issue by staszewski** [steemit/condenser#2672]
Hello,
I would like to report bug that i found on my profile, couldn't find anything similar here or on steemit about it. So, when i go to my profile i see that i have same number of posts and followers. 

My profile: https://steemit.com/@staszewski/followers

If you go there you can find out that i wrote 64 posts. I haven't, it's around 25-30. Same with followers. It looks like i have 64 of them (same number what posts), but when i copy my followers list to excel it shows that i have 50 of them. 

Thanks

**Comment by Smittyvb** [comment]
Firstly, the posts count under your username includes comments, not just root posts.

Secondly, you do have 64 followers. I counted. Steemit just doesn't show all of them on one page, so you have to press the "NEXT" button:
![NEXT button](https://vgy.me/imQApL.png)

**Comment by roadscape** [comment]
Also: posts count includes comments
