### ISSUE TITLE
Post does not appear when using the correct tag

### ISSUE THREAD

**Issue by imwatsi** [steemit/condenser#2673]
# Expected behavior

Four days ago I used the tag sndboxsummercamp to write a post. The tag is used by the organisers of a contest so they can search for all the entry posts for evaluation. Here's a snapshot of my post with the tag. If I click on the tag it should take me to the trending/hot/new page and list all the posts with this tag. https://steemit.com/dlive/@livinguktaiwan/f80be4a0-253a-11e8-9f90-91c8f29d5287

![screenshot1](https://steemitimages.com/0x0/https://res.cloudinary.com/hpiynhbhq/image/upload/v1521093915/wwjcrnlhxmk40hxnpew2.jpg)

# Actual behavior

When I click on the tag, I land on the trending page (this proves my tag is spelt correctly) but my post is not there. I go to the new page instead and scroll all the way down to the oldest post which is 5 days old, a day older than mine. My posts still does not appear anywhere. I have recorded me doing this and embedded the video below.

# How to reproduce

You just need to type in the tag sndboxsummercamp and you will see the bug. I am using chrome and Windows 10 on my PC. The same bug also happens when I am browsing on my android mobile phone.

- Browser: Chrome
- Operating system: Windows 10
- Recording Of The Bug

# Recording of the bug

[Found on YouTube](https://youtu.be/Jj_naxOesJs)

I would hate for this to happen to anyone else in case they use a tag for a specific purpose but their post is not seen by anybody as in my case. Thanks.

---

Posted on [Utopian.io - Rewarding Open Source Contributors](https://utopian.io/utopian-io/@livinguktaiwan/post-does-not-appear-when-using-the-correct-tag)

*This issue was submitted on behalf of Utopian.io user @[livinguktaiwan](https://utopian.io/@livinguktaiwan) due to an error*

---

**Comment by TimCliff** [comment]
This is likely the same issue as https://github.com/steemit/condenser/issues/986

**Comment by roadscape** [comment]
Hi, thanks for the report! This behavior should be resolved with new hive API.
