### ISSUE TITLE
Improving Tags column 

### ISSUE THREAD

**Issue by bitcoiners** [steemit/condenser#2679]
I would like to see my most used tags (posting and reading) show up first.
Ability to order/manipulate tags that show up in Tags column would be useful.

**Comment by Dolomich** [comment]
Just the ability to select some favorite tags is needed, I'm surprised there isn't this function yet and I've seen a 2 years old post complaining about it. 
Is there any reason why we can't ? If there's already a function to sort posts by tags this should be easy to do right ?

**Comment by roadscape** [comment]
Rolled into https://github.com/steemit/condenser/issues/2061
