### ISSUE TITLE
Can't logout and switch account when using steemconnect

### ISSUE THREAD

**Issue by Hazae41** [steemit/condenser#2686]
I am logged in busy.org with Account A

I disconnect because I want to use Account B

Once disconnected I click on the "login" button on busy.org

But Account A is logged in steemconnect.com, then Account A is **automatically** choosen in order to use busy.org

Therefore, it is impossible to use Account B

**Comment by Smittyvb** [comment]
You can sign out from SteemConnect at https://steemconnect.com/dashboard

**Comment by Hazae41** [comment]
This do not fix the problem, when I disconnect from steemconnect, then click on the login button on Busy or Utopian, I get connected to Account A

**Comment by TimCliff** [comment]
@Hazae41 this repository is technically unrelated to SteemConnect and Busy. They each have their own separate GitHub repositories. If you want to file an issue, you should do it there - but you may have better luck if you go to the Busy.org Discord chat and ask for help in the #steemconnect channel: https://discord.gg/5qymr5.
