### ISSUE TITLE
Transaction history in the Wallet menu (@user/transfers) should be collapsible

### ISSUE THREAD

**Issue by Katamori** [steemit/condenser#2690]
Very small frontend update request; actually, I may even try to solve it on my own.

The Wallet page of any user may become inconveniently long with sufficiently long transaction history. It may even slow down some browsers I guess?

I think it should be collapsible, or hideable.

**Comment by roadscape** [comment]
Hi, thanks for the feedback. Currently this is low priority but if anyone wants to work on it please file it at https://github.com/steemit/wallet/issues
