### ISSUE TITLE
Content blacklist should be polled at runtime rather than compiled into the application

### ISSUE THREAD

**Issue by goldibex** [steemit/condenser#2706]
- There should be an S3 bucket on our account containing a JSON file with a blacklist of content. 
- The JSON file should contain a list of objects, each one of which must contain at least the following information:
  - the block, transaction, and permlink containing the offending content
  - the person authorizing the blacklisting
  - the time at which the content was blacklisted
  - the reason for the blacklisting
- The file should have reasonable cache settings (~15 min?) to keep it from bottlenecking the application.
- Prior to displaying any content from the blockchain, condenser should check the blacklist. If the content is blacklisted, it should be treated as though it was not found.

**Comment by roadscape** [comment]
Wrt storage, we should consider checking the json file into a git repo and serving from githubusercontent.com directly -- this gives us free editing UI, transparent audit log, and standard review process tools built in.

**Comment by gl2748** [comment]
refs
https://github.com/steemit/steempunks/issues/179
and
https://github.com/steemit/steempunks/issues/178
