### ISSUE TITLE
Steemit's internal market shows zero price in open orders

### ISSUE THREAD

**Issue by littleboy0k** [steemit/condenser#2715]
#### Expected behavior
Open orders are expected to show the correct price at which the order was submitted

#### Actual behavior
Open orders show price as zero ($0.000000)

#### How to reproduce
1. Visit https://steemit.com/market
2. Add an order to buy steem with a price lower than the market price
3. It will than appear in the open orders section in the bottom
4. In the open orders section, prices of orders always show $0.000000

* Browser: Chrome 65
* Operating system: Windows 10

**Comment by michael-joyner** [comment]
duplicate of #2692

**Comment by littleboy0k** [comment]
Closing since it is a duplicate of #2692
