### ISSUE TITLE
The translate@steemit.com "email us" link in the FAQ doesn't work

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2719]
The "email us" link should link to `translate@steemit.com`, but it does not.

![image](https://user-images.githubusercontent.com/20735105/38589628-b516c628-3cf1-11e8-8b0a-47eb23241a42.png)

**Comment by free999enigma** [comment]
is that email still in use? i sent an email no reply after 1-2 months...

**Comment by roadscape** [comment]
Solved by removing the `mailto` link.
