### ISSUE TITLE
Missing Translation on login form

### ISSUE THREAD

**Issue by ausbitbank** [steemit/condenser#2724]
On the condensor login form, if you enter a short username and change focus to the password field we get this error : "missing translation: en.chainvalidation_js.account_name_shouldbe_longer"

![image](https://user-images.githubusercontent.com/1692203/38657117-cffe2f14-3e61-11e8-8ede-a4c7e16a76ea.png)

**Comment by pkattera** [comment]
Thanks @ausbitbank – I can confirm this bug happens for me too, as described.
