### ISSUE TITLE
Cannot Power Up

### ISSUE THREAD

**Issue by jl2035** [steemit/condenser#2730]
I'm getting "Transaction broadcast error." when I try to Power Up. In fact I think I cannot do any action.. cannot post, cannot comment.. Could the reason be that I currently have 0 Steem Power? If this is the case, then how do you Power Up, if you can't do any action. Is my account lost forever?

**Comment by Smittyvb** [comment]
What’s the name of your Steem account?

**Comment by jl2035** [comment]
Hi @Smittyvb ,

the name of my account is: @jaka

**Comment by free999enigma** [comment]
@jl2035 you can't do any action on steem/steemit (comment,post,upvote,downvote,power up,power down) if you don't have Bandwidth. https://steemd.com/@jaka
https://i.gyazo.com/631c5ea4087016f7a8451559ff1e896d.png

Wait for your Bandwidth to recharge.

**Comment by Smittyvb** [comment]
I gave you some Steem Power, try powering up now.

**Comment by jl2035** [comment]
@Smittyvb it worked! Thanks

**Comment by gl2748** [comment]
Also would be addressed by:
https://github.com/steemit/condenser/pull/2685
