### ISSUE TITLE
Unlimited tries for phone numbers on sign up

### ISSUE THREAD

**Issue by gryter** [steemit/condenser#2731]
There is absolutely no legitimate reason a user needs to try more than one or two numbers "already linked to an existing account or under review". The presence of limitless tries allows scammers the option to cycle through myriad sms numbers in order in order find an unused one. We tried 20 different numbers from different countries that were already in use.

**Reasoning:**
User may need to try multiple numbers until one on a supporting carrier is found. Users whose carrier doesn't support the function would typically borrow a friend's or family member's phone to complete the registration. They would need to change the number on signup for that.

**Proposed Solution:**

- Limit the "already linked to an existing account or under review" to 2 tries before lockout.
- Limit the Edit function to 5 tries before lockout.

**RELATED ISSUE:** _Ability to swap between countries/regions._
The initial area code suggestion defaults to the registrant's geographic location. Unsuccessful attempts and edit-prompted attempts both allow the registrant to swap their area code. We have successfully swapped our code to Russia, Ukraine, South Africa, Great Britain and so forth while cycling through our list of free sms numbers.

**Reasoning:**
Text reception may be restricted in a user's geographical location.

**Proposed Solution:**
Limit the area code selection function to the 5 proposed Edit tries before lockout.

Post with graphics can be found here https://steemit.com/steem/@guiltyparties/account-creation-issues-solutions

**Comment by TimCliff** [comment]
@gryter - the signup process is not part of condenser. Can you please open this issue in the faucet repository?

https://github.com/steemit/faucet/issues

**Comment by gryter** [comment]
thanks tim, didn't think this was the right place but didn't know faucet has its own section
