### ISSUE TITLE
Can't Receive sms while signing up

### ISSUE THREAD

**Issue by yashpratapkanthriya** [steemit/condenser#2733]
Hi,
I failed in receiving SMS while registering as a new member, with India's phone numbers, though I passed the step of email confirmation, with the same email with this GitHub account.

I hope this problem will be solved asap.

Thanks,
YashPratap

**Comment by gl2748** [comment]
Hi @yashpratapkanthriya, I am assuming you are using the +91 country code
If you are, we are aware of this issue and are working hard to get you an account.

In the meantime - please have a look at this https://support.twilio.com/hc/en-us/articles/223134167-Limitations-sending-SMS-messages-to-Indian-mobile-devices

As there might be some things you can do ...
