### ISSUE TITLE
Replace phishing urls in account profile field with warning

### ISSUE THREAD

**Issue by gryter** [steemit/condenser#2735]
xref #2732 update to Phishing.js required first (to create full list of phishing urls)

Hackers are adding the phishing urls to the hacked users' profile fields in order to bypass the anti-phishing bots. 

![image](https://user-images.githubusercontent.com/31012685/38844538-eca882b4-41c1-11e8-89fa-b3928e583a5e.png)

Strikeout/black text if url on Phishing.js may work/be a relatively simple solution. Replacing with warning would be optimal. 

Here is a writeup by Arcange on the issue with more graphics: https://steemit.com/steemit/@arcange/phishing-reported-scammers-use-account-s-profile

**Comment by pkattera** [comment]
Thanks for adding this one @gryter – we'll take a look into it.
