### ISSUE TITLE
steemit.com/tags is broken

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2741]
No content is rendering on https://steemit.com/tags

![screen shot 2018-04-18 at 4 26 11 pm](https://user-images.githubusercontent.com/1121139/38963195-8ffdd4c8-4325-11e8-9098-0b1982da9ffa.png)

There doesn't seem to be any console errors.

Tested on a few browsers, Chrome, Firefox, Safari, Opera.

**Comment by free999enigma** [comment]
Same here tested on Vivaldi and Brave
