### ISSUE TITLE
Login/Signup buttons overflowing when search bar is expanded

### ISSUE THREAD

**Issue by Nicknyr** [steemit/condenser#2767]
When the search bar at the top is clicked so that it expands it causes the sign up button to overlap the log in link and both overflow like so.

I can fix this, just want to make sure no one is already on it.

![screenshot from 2018-04-29 01-07-25](https://user-images.githubusercontent.com/8207697/39403435-2a7977ba-4b4a-11e8-9116-0b72a444f4d0.png)

**Comment by gl2748** [comment]
closed by #2772
