### ISSUE TITLE
Evaluate slate.js implementation

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#2775]
Evaluate what, if any, changes are needed for release.

Base branch: `bridge-api-dev`

This commit shows the packages that were added. The `slate*` packages are quite out of date:
https://github.com/steemit/condenser/commit/e8fd6edc3fc4f295e599a2916212486361cfed12

**Comment by pkattera** [comment]
Acceptance criteria:
- List out all remaining issues preventing Production deployment.

**Comment by gl2748** [comment]
See branch here:
https://github.com/steemit/condenser/tree/2775-slate-update

Basically, the best option is to use the `slate-react` package, however this makes use of `React.memo` which only appears in `react v.16.6` or greater, which we do not have on condenser. (While the 16 upgrade has been attempted, it is very hard to have any kind of confidence in such a large change to this codebase).

Therefore, to use `slate`, we have to use the vanilla JS implementation, which the branch that I noted `2775-slate-update` does.

The remaining work on this branch is to:
- Implement our custom slate schema. 
- Implement proper serialization / deserialization of the initial / persisted state of the editor.
- Implement the various custom handlers that the editor appears to have.

**Comment by roadscape** [comment]
React 16 blocker details: https://github.com/steemit/condenser/issues/2214

**Comment by roadscape** [comment]
Leaving as-is; report any problems as new issue
