### ISSUE TITLE
Full account history is not displaying on 'My wallet' page

### ISSUE THREAD

**Issue by pkattera** [steemit/condenser#2778]
As a user, 
I want to see my full account history, 
so that I can reconcile past transfers.

---------------------------

Steemit.com currently shows a limited set of transactions on the wallet page, e.g.: https://steemit.com/@username/transfers

It should actually show the full history. Note: Busy.org is currently able to display my full history.

**Comment by pkattera** [comment]
@free999enigma I like those suggestions. I'd also want the ability to filter by token type (e.g. STEEM, SP, SBD)

**Comment by roadscape** [comment]
Blocked by https://github.com/steemit/condenser/issues/2244; not strictly but essentially proper resolution of #2244 would make this a non-issue.

**Comment by pkattera** [comment]
As per @roadscape, closing this issue. Will be resolved by #2244.
