### ISSUE TITLE
Community - Add setting to enable/disable post reward options

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2779]
As a user who likes to make different choices for whether to post for '50/50' payout and 'decline payout', it is nice to be able to make that choice when I am creating a post. I understand that this is a 'power user' feature, and most users will prefer to just use the default (with no option to select while posting). For users who like to toggle though, it would be nice to have an option in the settings to enable/disable whether the payout reward options are available to change via the post editor.

**Comment by roadscape** [comment]
@anyx:
> Perhaps we want the 'power user feature' to be something like "Show rewards options on post/comment submissions [ y/n ]"

**Comment by TimCliff** [comment]
completed
