### ISSUE TITLE
Add share on StumbleUpon link

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2784]
StumbleUpon is a content discovery tool that is good for sharing interesting articles and blog posts. I created a local branch to add a StumbleUpon share button: https://github.com/TimCliff/condenser/tree/stumbleupon. If this is approved, I will submit a PR.

**Comment by pkattera** [comment]
Hi @TimCliff – Stumbleupon is officially being closed down in favor of mix.com on June 30. I'm not sure if Mix has similar share functionality or if this platform is worth pursuing. I'm going to close this ticket for now. Let's review Mix.com in a couple of months.
