### ISSUE TITLE
blocktrades recipient `undefined`

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#2794]
Seems there is an issue with some 'Buy with Blocktrades' dialog:

> We're getting some url with the recipient set to "undefined" (for eth -> steem). I strongly suspect it is some bug with condenser. I'm going to prevent those from creating deposit addresses, but it's best if it gets fixed on condenser side.

**Comment by Smittyvb** [comment]
This happens when you are logged out of condenser, and press here on the side menu:
![BlockTrades link on sidebar](https://vgy.me/eHJ5gr.png)

**Comment by roadscape** [comment]
When hovering over the item in the menu while logged out
![image](https://user-images.githubusercontent.com/5168676/41786040-071add00-760a-11e8-858d-9192ff8e9ea6.png)
the url shows 'undefined' param:
![image](https://user-images.githubusercontent.com/5168676/41786057-0ecb1c0e-760a-11e8-9d30-8b4e62821b00.png)
