### ISSUE TITLE
Move signin to SteemConnect.

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2796]
It would be nice if Condenser's signin process was handled by SteemConnect.

**Comment by Smittyvb** [comment]
Right now, Condenser logins are directly with a username and password. SteemConnect’s model would require an active key, as SteemConnect’s model would require Steemit to create an account (day steemit.app), which users would give their posting permission.

However, the main problem with this, is that this would mean Steemit Inc. would have access to user accounts. Right now, Steemit has no access to user accounts — transactions are signed in the browser. Having a large portion of accounts having Steemit authorized to have full account access would cause massive centralization, which is bad. If Steemit was compromised, then almost every Steem account would be compromised under this model.

Now, this is also a problem with SteemConnect — SteemConnect has posting access to all apps, and is also ran by Steemit Inc., so could in theory use that to post as a large portion of users, but not all users use SteemConnect to authorize apps. Most SteemConnect apps only ask for posting permission, but Steemit would need the active and posting permissions. Active permission allows one to transfer Steem/SBD, so almost no SteemConnect apps require it. Steemit would need it though, to handle transfers on the wallet page.

**Comment by gl2748** [comment]
Hey @Smittyvb thanks for this.
