### ISSUE TITLE
3 bugs - XSS vulnerability, buggy tags removal, minor bug on empty href

### ISSUE THREAD

**Issue by mycatnamedweb** [steemit/condenser#2801]
Please see my post here: https://steemit.com/steemit-issues/@gaottantacinque/steemit-minor-bugs-reporting

Please comment my post if you have further questions.

Thanks for the good work you do,
Gabriele

**Comment by mycatnamedweb** [comment]
https://steemit.com/security/@gaottantacinque/steemit-and-the-internet-in-general-is-a-safe-place

**Comment by roadscape** [comment]
Hi, please leave any details directly in the issue, and one issue for each bug. Thanks!
