### ISSUE TITLE
Welcome hero image is unnecessarily large

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2803]
https://github.com/steemit/condenser/blob/fd7915cefff90a7a3b694f66cc00f4f2d61dee9b/src/app/components/elements/WelcomePanel.jsx#L22

Image is: 630px x 628px, despite having CSS constraint of 360px:

https://github.com/steemit/condenser/blob/94e7eed3055e2247520967b684c86ca0276f645c/src/app/components/App.scss#L173

**Comment by bnchdrff** [comment]
2x pixel density

**Comment by pkattera** [comment]
Happy to keep the 2x res (most modern phones and desktop screens are at least 2x these days).

I'm going to close this ticket. But I'll try to further optimize the image to reduce it down from 205kb.
