### ISSUE TITLE
Images with QueryString Parameters are Incorrectly Interpreted (Steemit/Condenser)

### ISSUE THREAD

**Issue by DoctorLai** [steemit/condenser#2822]
This is original reported here: https://steemit.com/utopian-io/@justyy/images-with-querystring-parameters-are-incorrectly-interpreted-steemit-condenser

Expected behavior
Images that are with query string parameters should be displayed correctly.

Actual behavior
Images that are with query string parameters are ignored, and therefore displayed incorrectly or broken.

How to reproduce
I have got two images:

1. https://uploadbeta.com/api/pictures/random/test/?key=aa
2. https://uploadbeta.com/api/pictures/random/test/

As you can see, the first image URL has a query string,, they are two totally different images. If you add them to steemit, they will automatically prepended:

1. https://cdn.steemitimages.com/0x0/https://uploadbeta.com/api/pictures/random/test/?key=aa
2. https://cdn.steemitimages.com/0x0/https://uploadbeta.com/api/pictures/random/test/
However, The image with query string is shown incorrectly, in fact, it is shown as the second image.

Please note that if you use busy.org to read this post, two images are displayed correctly

This is a critical bug which I think has been introduced lately (regression). I found this bug because I use a API to insert pictures with query parameters but suddenly it doesn't work anymore.

Browser/App version: Chrome v66
Operating system: Win 10 64-bit

**Comment by jredbeard** [comment]
This has been resolved. Thank's so much for your bug report.

**Comment by osorno7** [comment]
I have been having the same issue "object object" error while writing content. June 1-2, 2018. Is there any fix for this?

**Comment by osorno7** [comment]
![image](https://user-images.githubusercontent.com/39867742/40882147-347a0496-66a7-11e8-82df-810f376f52f9.png)

**Comment by osorno7** [comment]
Tried closing browser and reopening it, using different browsers, sending the image by email and copying from there and then pasting. Nothing works.

**Comment by osorno7** [comment]
I have posted hundreds of images in the last month. Does that matter?

**Comment by jredbeard** [comment]
@osorno7 this sounds like a different issue, as the OP did not have an error of 'object Object', nor did the other linked issued.

Can you open a new issue with exact steps to reproduce? It would also be helpful to know the filename of the image, file type, and size.

**Comment by rebuildman** [comment]
@jredbeard I have the same problem as @osorno7 
 " image upload : error [object Object ] 

-> post / api / v1 / isToAccepted 500

**Comment by osorno7** [comment]
I think there is a daily or weekly limit on how many images one may upload.

 

De: Junior Frederico [mailto:notifications@github.com] 
Enviado el: viernes, 22 de junio de 2018 22:21
Para: steemit/condenser <condenser@noreply.github.com>
CC: osorno7 <osorno777@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [steemit/condenser] Images with QueryString Parameters are Incorrectly Interpreted (Steemit/Condenser) (#2822)

 

@jredbeard <https://github.com/jredbeard>  I have the same problem as @osorno7 <https://github.com/osorno7> 
" image upload : error [object Object ]

-> post / api / v1 / isToAccepted 500
