### ISSUE TITLE
When uploading image, you can't just drop it - text cursor must stay where you want the image to be posted. When it finishes, it jumps to end of text.

### ISSUE THREAD

**Issue by royachiron** [steemit/condenser#2832]
This is a very minor nuisance, but a nuisance none the less.
Also it's a meta bug, as I took notice at another less than friendly behavior, where let's say in GitHub where you drop it as where it will be inserted in the editor, no matter where your cursor is the moment it finishes uploading. As soon as you drop it it crates a text string placeholder that gets replaced automatically when the file is online, and doesn't move the cursor, even if at that moment the user is actively typing elsewhere as I am doing right now to demonstrate this behavior:
![19](https://user-images.githubusercontent.com/23020420/40813593-5daf6d74-6544-11e8-885e-3643c48d6234.gif)

Here it is on steemitstage:

![18](https://user-images.githubusercontent.com/23020420/40813244-6d9c7a30-6542-11e8-9814-37e1e80124b4.gif)

As can be seen from GitHub it can be improved a lot, but having it go to right after where the image string was posted would be sufficiently friendly IMO. The way it jumps to the bottom of the document is quite off putting.

**Comment by quochuy** [comment]
@roadscape fix proposal on https://github.com/steemit/condenser/pull/3376
I need help testing as I can't get image upload to work on my dev environment.
