### ISSUE TITLE
Auto generated CDN image in markdown does not always work 

### ISSUE THREAD

**Issue by Any-X** [steemit/condenser#2833]
The steemit.com site has generated the following:
https://cdn.steemitimages.com/0x0/https://www.dropbox.com/s/ais9gztb3rivoh6/steemcleanerslogo.png?dl=1
from the actual image link:
https://www.dropbox.com/s/ais9gztb3rivoh6/steemcleanerslogo.png?dl=1

It was added to a post in markdown like: `![](https://www.dropbox.com/s/ais9gztb3rivoh6/steemcleanerslogo.png?dl=1)`, it was not uploaded. But the image attempting to be shown on Steemit.com is the cdn broken one, not the original. The image works with any other content viewer, the only thing broken is specifically Steemit.com changing the link.

See (broken):
https://steemit.com/steemcleaners/@steemcleaners/steemcleanersreportformay25-2018part2
And (works):
https://busy.org/@steemcleaners/steemcleanersreportformay25-2018part2

It was also pointed out that removing the cdn allows the image to load properly:
https://steemitimages.com/0x0/https://www.dropbox.com/s/ais9gztb3rivoh6/steemcleanerslogo.png?dl=1

**Comment by netuoso** [comment]
This appears to be resolved. Please check

**Comment by plink01001** [comment]
Closing due to no additional reports. If this is still occurring, please re-open.
