### ISSUE TITLE
Restore default vesting route upon account recovery

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#2835]
Moved from https://github.com/steemit/steem/issues/2498:

> Hackers have been changing the set_withdraw_vesting_route to their own accounts to continue milking victims after recovery.
> 
> We need to have the set_withdraw_vesting_route auto-revoked (the to_account reset to from_account) and restored to default upon recovery.
> 
> Example:
> ![maruharraca steem - 2018-05-24_17-36-48](https://user-images.githubusercontent.com/31012685/40515189-e2c7db0c-5f79-11e8-89d0-553ff264c43a.png)
> 
> The sami100 account belongs to a know hacker who runs a script that finds accidentally posted passwords and active keys.

Upon resetting an account's owner, condenser should broadcast a tx which clears all withdraw routes.

Important: we cannot add cancel power down and clearing of routes in the recovery tx because at the time of auth checking the account still has the wrong authority. It needs to be a separate tx and condenser must verify the first operation next through first. (TODO: does it need to be irreversible or is waiting 1 block safe?)

**Comment by pkattera** [comment]
Here are three solutions. I recommend option 3 in the short term.

**Option 1:** Build a fully functional UI in condenser

This fully functional UI includes:
– Auto_vesting
– Ability to add accounts
– Ability to change percentages
– Ability to remove accounts individually, or in bulk

With this option, we'd need intelligent error handling when a user enters numbers which exceed 100%. If it's under 100%, we would just allocate the rest to the original person.

![option 1 full functionality](https://user-images.githubusercontent.com/1121139/41273235-8946b73a-6dcd-11e8-98f2-476e417e3ae9.png)

**Option 2:** Offer limited functionality to prevent attackers

- No auto_vest or ability to manage accounts or percentages
- Only display the accounts and percentages (there is no ability to change the percentages)
- Include a single option to delete all third parties.
- This should effectively notify people if there is one or multiple vesting routes set up by an attacker. They can sort themselves out by deleting the third parties.

![option 2 limited functionality](https://user-images.githubusercontent.com/1121139/41273342-e4c65df4-6dcd-11e8-8bd5-ed92a8350722.png)


**Option 3:** On account recovery, wipe out all current routes and notify the user. 

No UI is required for this change.

**Comment by Gandalf-the-Grey** [comment]
also reset recovery account to `steem`

**Comment by bnchdrff** [comment]
lightbox during condenser account recovery saying "all vesting accounts reset, recovery account reset to steem"

and then poll for recovery tx; once it's in a block, then actually reset recovery account

use steem-js calls to do this -- it'll happen in-browser, and we need to make it clear to the user that they have to keep their session going / do not close browser window until these calls are done.

need to research details of looking up all vesting routes.

**Comment by bnchdrff** [comment]
concerns:

wait until head block - 1

how many vesting routes can be cleared per block?

**Comment by pkattera** [comment]
The message in the lightbox:

"For your safety, all vesting routes are being reset to your account and the recovery account has been set to @steem."

**Comment by bnchdrff** [comment]
reverted the fix for this

need to address https://github.com/steemit/condenser/issues/2943

**Comment by TimCliff** [comment]
@gl2748 did the https://github.com/steemit/condenser/pull/2949 PR that was submitted for this also address the issue of restoring the recovery account back to `steem`?
