### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TopCoding** [steemit/condenser#2845]
RPCError: Assert Exception:method_itr != api_itr->second.end(): Could not find method get_state RPCError: Assert Exception:method_itr != api_itr->second.end(): Could not find method get_state

I replace the http address as follows
![guqsp5n_ sq5 t5tlmzggp](https://user-images.githubusercontent.com/27414779/40950389-146ad77a-68a5-11e8-9f79-06e4c007cf53.png)
errors
![6pto9 _uy3_ lg20573kkt](https://user-images.githubusercontent.com/27414779/40950415-2f29636a-68a5-11e8-8bec-ce117b52bb43.png)

**Comment by roadscape** [comment]
I would recommend using https://api.steemit.com instead of your local node. The problem is probably that steem-js does not know how to specifically ask for `condenser_api`. This needs to be fixed but in the meantime api.steemit.com (jussi) performs the translation.
