### ISSUE TITLE
Support GIFV

### ISSUE THREAD

**Issue by themarkymark-steem** [steemit/condenser#2851]
I'd really love to see `gifv` embed support for gif.  It is a much more efficient format than gif and most sites/apps support gifv natively.  

Can read why `gifv` is so much better performance and quality here:
https://www.addictivetips.com/web/what-is-gifv-imgur/

Gifv reduces the file size of gifs while offering far superior playback performance.

**Comment by themarkymark-steem** [comment]
Great example I just ran across

https://i.imgur.com/S9nsTwm.gifv

vs 

https://i.imgur.com/S9nsTwm.gif

**Comment by netuoso** [comment]
https://github.com/steemit/condenser/pull/2998

**Comment by roadscape** [comment]
This would be nice to have but roadblocks were noted in #2998
