### ISSUE TITLE
Request: BBCode?

### ISSUE THREAD

**Issue by pablorg94** [steemit/condenser#2856]
I think you must add BBcode to the post and a visit counter too.
Thanks.

**Comment by Smittyvb** [comment]
A visit counter used to exist, but was removed. One reason for this was because tracking views across multiple Steem-based apps isn’t possible, so sometimes weird situations happened, where a post had more votes than views.

**Comment by roadscape** [comment]
This is a platform wide change that would need significant traction to work effectively
