### ISSUE TITLE
Update Welcome.md

### ISSUE THREAD

**Issue by gryter** [steemit/condenser#2857]
The Steemit Welcome page is arguably the most important part of the site as it's the first page new users see. 

The current Welcome page has grammatical mistakes, broken links, outdated and abandoned projects, confusing information, and is generally difficult to read. It has seen patchwork updates but no overhaul.  

**Proposed Welcome page:**
https://github.com/gryter/condenser/blob/gryter-welcome1/src/app/help/en/welcome.md  (updated branch)

_Submitting the issue for discussion/input pending the finalization of the proposed update and Pull Request._ 

**Changes:** 
- Grammatical, spelling and wording errors corrected
- Optimized for compatibility with Google Translate into various languages
- Helpful Posts from Steemit Users section re-formatted, trimmed and amended to remove posts with expired information and replace with relevant ones
- Broken link fixed
- https://www.steemithelp.net/ link removed. The site is abandoned and out of date (ie. informs users they can edit a post for 30 days)
- Clarifying points added and information updated 
- Steem/Steemit changed around to make more sense
- Steem markup course link added

**Finalization:**
- Helpful Posts from Steemit Users section will likely see a few more posts as per input/community suggestions
- Icons will be verified and final formatting checked 
- Final text optimization 

**Community input:**
Significant input was sought and received from community members both via posts and chats. 
https://steemit.com/steemit/@guiltyparties/steemit-welcome-page
https://steemit.com/steemit/@guiltyparties/user-links-on-welcome-page
https://steemit.com/steemit/@guiltyparties/translation-of-the-welcome-page

**Comment by plink01001** [comment]
Closed via https://github.com/steemit/condenser/pull/2946
