### ISSUE TITLE
Help Wanted-Unable to login to steemconnect

### ISSUE THREAD

**Issue by Priyad007** [steemit/condenser#2867]
Am unable to login to Dlive which requires to connect via steemconnect. The problem is only with steemconnect as i tried to login to steemhunt and here again steemconnect did not allow. (The message is incorrect key or password) Unable to transfer Steem to buy Steem power as again steemconnect login is required which is not working. Tried private and master key. Trying since 10 days, still no success. Not sure whom to contact or how to solve this issue.
Am able to login to all other accounts where steemconnect is "NoT Required", using the private key including DTUBE and Dsound. Trying since past 10 days.
Thanks in advance!

**Comment by TimCliff** [comment]
The condenser repository is technically not the right place for this issue. For SteemConnect support you can go to their discord channel: https://discord.gg/DkWCreA. 

If you are having login issues though, you should check to see if your password has been changed without your consent.  If you go to steemd.com/@youraccount, was the password recently changed? (What are the dates for "Last owner update" and "Last account update"?) If it was, you should complete the "Stolen Accounts Recovery" right away.

**Comment by Priyad007** [comment]
Thank you Tim, Today after almost two weeks i am able to login to steemconnect related accounts, not sure who corrected this. I will join the steemconnect discord channel as well.
