### ISSUE TITLE
Community - Upvote causing location to jump is not ideal user behavior for curating comments

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2872]
When I am going through a post and curating comments, I like to scroll down and read all the comments + upvote the ones that I like as I go. With the current behavior, every time I update a comment, my position on the page jumps to wherever the upvoted comment ended up. In order to continue on with my reading, I have to scroll back and find my position again.

**Comment by TimCliff** [comment]
Update: The issue is happening on Chrome, but it is working as expected on Safari.

**Comment by quochuy** [comment]
@TimCliff I cannot reproduce this anymore on Chrome (Mac)

**Comment by TimCliff** [comment]
Agreed, closing.
