### ISSUE TITLE
Bandwidth visualization

### ISSUE THREAD

**Issue by youkaicountry** [steemit/condenser#2889]
As a user, I should be able to see how much bandwidth I have remaining as well as my maximum, so that I can make informed decisions about my use of the site/product.

**Comment by sneak** [comment]
This is cognitive load that provides no benefit whatsoever for the majority of site users.

**Comment by sneak** [comment]
In addition, by making site actions seem to consume a scarce resource, even users that would not approach bandwidth limits may be dissuaded from engaging when they might otherwise comment or post.
