### ISSUE TITLE
Steem chat is vulnerable to tabnabbing and clickjacking

### ISSUE THREAD

**Issue by mycatnamedweb** [steemit/condenser#2894]
See my post: https://steemit.com/security/@gaottantacinque/steemit-chat-is-unsafe

**Comment by TimCliff** [comment]
Steem chat is not part of condenser, but I will forward this issue to the team that maintains that application.

**Comment by mycatnamedweb** [comment]
Ok, is https://signup.steemit.com/ part of the condenser instead? It's affected to..

**Comment by TimCliff** [comment]
The signup system is this repository: https://github.com/steemit/faucet/

Can you please open an issue there?

**Comment by mycatnamedweb** [comment]
Will do
