### ISSUE TITLE
refactor state `accounts` access

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#2899]
### Overview

condenser in many cases assumes the state `accounts` map contains various expected accounts with various expected keys.

`app/redux/SagaShared` contains a `getAccount` method which attempts to read the requested account from state, and fetches it via `getAccountsAsync` if it's not present. There is an optional `force` parameter which, if set to True, will force re-fetch the account.

We should audit the codebase to make sure this method is always used where we need assurance that the account is present and up-to-date (login, transfer, wallet, etc).

However, there are some cases which are not as straightforward:
 - wallet pages use the `transfer_history` key which is only populated in `getState` -- i.e., `getAccounts` will not be able to fill in this data without extra calls
 - account pages use `blog`, `feed`, `comments`, and `recent_replies` keys -- they contain a list of permlinks to serve on specific account pages (tabs). these are only initialized via `getState`; and appended to via other API calls when loading more pages.

GlobalReducer uses a `mergeAccounts` function; comment reads: `Merging accounts: A get_state will provide a very full account but a get_accounts will provide a smaller version this makes sure we don't overwrite`.

### Audit

```
grep -rn '[^_\/a-z ]accounts[^ ]' * \
  --exclude-dir tmp \
  --exclude-dir lib \
  --exclude-dir dist \
  --exclude-dir src/db \
  --exclude-dir src/app/help \
  --exclude-dir node_modules \
  --exclude-dir api_mockdata \
  --color=always
```

What follows is a slightly cleaned-up set of results from the command above:

```
src/app/utils/ExtractMeta.js:36:        const author = chain_data.accounts[rp.username];
src/app/utils/ExtractMeta.js:87:        const account = chain_data.accounts[rp.accountname];
src/app/components/elements/Userpic.jsx:57:            'accounts',
src/app/components/elements/Author/index.jsx:160:    const account = state.global.getIn(['accounts', author]);
src/app/components/elements/ConvertToSteem.jsx:130:        const account = state.global.getIn(['accounts', username]);
src/app/components/elements/Memo/index.jsx:136:            state.global.getIn(['accounts', ownProps.fromAccount, 'reputation'])
src/app/components/modules/PromotePost.jsx:163:            'accounts',
src/app/components/modules/Settings.jsx:556:        const account = state.global.getIn(['accounts', accountname]).toJS();
src/app/components/modules/Transfer.jsx:562:            'accounts',
src/app/components/modules/Header/index.jsx:367:    const account_user = state.global.get('accounts');
src/app/components/pages/Witnesses.jsx:417:                current_user && state.global.getIn(['accounts', username]);
src/app/components/pages/Market.jsx:956:                account: state.global.getIn(['accounts', username]),
src/app/components/pages/UserProfile.jsx:724:                account: state.global.getIn(['accounts', account_name]),
src/app/components/pages/PostsIndex.jsx:292:                account = state.global.getIn(['accounts', account_name])
src/app/redux/GlobalReducer.test.js:83:            actual.getIn(['accounts', payload.account.name, 'name'])
src/app/redux/GlobalReducer.test.js:86:            actual.getIn(['accounts', payload.account.name, 'beList'])
src/app/redux/GlobalReducer.test.js:89:            actual.getIn(['accounts', payload.account.name, 'beOrderedMap'])
src/app/redux/GlobalReducer.test.js:155:        expect(actual.get('accounts')).toEqual(expected.get('accounts'));
src/app/redux/GlobalReducer.test.js:278:            actual.getIn(['accounts', payload.account, 'witness_votes'])
src/app/redux/GlobalReducer.test.js:304:        expect(actual.getIn(['accounts', payload.account])).toEqual(expected);
src/app/redux/GlobalReducer.test.js:463:            actual1.getIn(['accounts', payload.accountname, payload.category])
src/app/redux/FetchDataSaga.js:93:            state.global.getIn(['accounts', username, 'transfer_history'])
src/app/redux/UserSaga.js:467:        state.global.getIn(['accounts', username])
src/app/redux/UserSaga.js:470:        console.error('Missing global.accounts[' + username + ']');
src/app/redux/UserSaga.js:523:        state.global.getIn(['accounts', username, 'owner', 'key_auths'])
src/app/redux/SagaShared.js:24:        state.global.get('accounts').get(username)
src/app/redux/tests/global.json:38:    "accounts": {},
src/app/redux/TransactionSaga.js:497:    //     if (posting) update.accounts[account].posting = posting
src/app/redux/TransactionSaga.js:498:    //     if (active) update.accounts[account].active = active
src/app/redux/TransactionSaga.js:499:    //     if (owner) update.accounts[account].owner = owner
src/app/redux/GlobalReducer.js:66:    return state.updateIn(['accounts', account.get('name')], Map(), a =>
src/app/redux/GlobalReducer.js:104:            return payload.accounts.reduce((acc, curr) => {
src/app/redux/GlobalReducer.js:196:                ['accounts', account, 'witness_votes'],
src/app/redux/GlobalReducer.js:207:            return state.setIn(['accounts', account, 'proxy'], proxy);
src/app/redux/GlobalReducer.js:271:                const key = ['accounts', accountname, category];
src/server/api/general.js:64:        logRequest('accounts_wait', this, { account });
src/server/api/general.js:105:        logRequest('accounts', this, { account });
src/shared/UniversalRender.jsx:281:            Object.getOwnPropertyNames(onchain.accounts).length === 0 &&
```

I believe all the use cases boil down to:

1. Logged in user: full profile, pubkeys, balances. transfer_history?
2. Currently viewed user: full profile, pubkeys, balances, *posts keys*, *transfer_history*
3. Discussion thread: need comments' author's json_metadata

### Potential solutions

1. Break out various portions of account data (full profile, light profile, post lists, transfer history) into separate branches. Enforce that if a key is present, all relevant data is loaded. Basically, ensure that there is never partial data. And if the key is not present, load from the appropriate API call.
2. Create a client-side `getState` proxy method. This will allow us to (a) audit all usage, (b) fill in gaps from hive, and (c) to eventually break up the monolith into constituent calls.
3. Rip out `getState` entirely (is this even possible without some combo of 1 & 2?)

### See also

 - #2244 remove core reliance on get_state
 - #2684 remove get_state: part 1

**Comment by bnchdrff** [comment]
i think option 1 is the best for now. there aren't so many usages of this part of the state; we can effectively audit & refactor.

option 1 is how things should work anyways... the state tree should have separate account trees for each flavor of account data, maybe as sub-reducers.

**Comment by roadscape** [comment]
Project complete
