### ISSUE TITLE
Community - Wallet page history is delayed to show transactions

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2900]
After completing a wallet transaction, it often takes a minute or so for the transaction to show up in the History section. This can be very alarming/confusing for users, and possibly even dangerous - if they are led to believe that their transaction did not go through.

Ideally the wallet history should instantly show the results of any successfully completed transaction.

If this cannot be done, then the next best thing would be to include a warning message in the history that the results may be delayed by X amount of time.

**Comment by bnchdrff** [comment]
add warning to user wallet component "Transactions will not show until they are confirmed on the blockchain, which may take a few minutes."
