### ISSUE TITLE
Issue on wallet

### ISSUE THREAD

**Issue by sourovafrin** [steemit/condenser#2902]
![screenshot_7](https://user-images.githubusercontent.com/38147368/41773302-6a7cc006-763d-11e8-94e5-395fb5adce8c.png)

Facing this issue often

**Comment by Smittyvb** [comment]
What’s the problem? The commas? The lack of space between commas and the numbers?

**Comment by TimCliff** [comment]
@sourovafrin - if you go under your settings tab, what language does it have selected?

**Comment by sourovafrin** [comment]
@TimCliff - English

**Comment by TimCliff** [comment]
I was not able to reproduce it on my end, but it seems that your browser may be trying to do some type of language translation. The , instead of . is a European language convention.
