### ISSUE TITLE
Image Upload Object Error

### ISSUE THREAD

**Issue by KINGdotNET** [steemit/condenser#2906]
I recently update https://yehey.org using the latest copy of the condenser. I've noticed in the default.json config still point to "img_proxy_prefix": "https://steemitdevimages.com/", which is not working.

In the past upgrade, I can fix this pointing to https://steemitimages.com and the upload will work ok.

After the upgrade, I'm getting an error when I tried to upload an image.
Image upload : Error: [object Object]

Is this a bug? What is the alternative solution.

Best regards,
@yehey

**Comment by rebuildman** [comment]
Hey man, a sent you how to fix in discord to...

have you solved the problem of uploading images?
I believe the problem might be in the! default.config "connectSrc, put" https://steemitimages.com "without (") img_proxy_prefix: "https://steemitimages.com" | Upload_image: "https://steemitimages.com"

**Comment by KINGdotNET** [comment]
I have that in my default.json configuration.

Both steemit.com and steeming.com (condenser) got the same error when I tried to upload an image.
Image upload : Unable to contact the server.

I will try it again later using a different computer.

**Comment by KINGdotNET** [comment]
This is what I have on my default.json file.

"connectSrc": "'self' steemit.com https://api.steemit.com/ https://steemitimages.com/",
"img_proxy_prefix": "https://steemitimages.com/",
"upload_image": "https://steemitimages.com/",

**Comment by roadscape** [comment]
Hi, as this issue is stale I'm closing it for now. Please reopen if unresolved.
