### ISSUE TITLE
Community - Voting Error: Assert Exception:o.weight !=0 Vote weight cannot be 0.

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#2920]
There are some users that are reporting the following error after https://github.com/steemit/condenser/pull/2887 was applied:
![image](https://user-images.githubusercontent.com/20735105/42040966-8702c7e8-7ab6-11e8-928f-02b55af6291c.png)

If users adjust their slider to anything other than 100% and vote, it seems to resolve the error.

**Comment by firepowernaik** [comment]
The issue crops up randomly on login. There's no pattern to when it can occur and stop. Atleast in my experience. 

It doesn't matter if you are in regular browser window or incognito mode. Issue occurs when you are trying to vote for the first time after logging in. 

Just login normally and you may have to adjust the slider and vote. If not you will see the RPC error listed by Tim. 

Adjusting the slider even by 1% from 100% to 99% fixes it. But % of slider movement is irrelevant.

**Comment by plink01001** [comment]
Closed via https://github.com/steemit/condenser/pull/2941
