### ISSUE TITLE
Users not taking Password Backup Seriously, Need for an Instructional Video to play explaining user's need to backup their password, and how it cannot be reset.

### ISSUE THREAD

**Issue by ackza** [steemit/condenser#2921]
This is ackza's first Issue for pull request, let ackza know how to redo this post to fit guidelines and please only speak English with this version of ackza 0.97.2 beta 

We all know there is a problem with many users expecting there to be a Password Recovery System. Too many users are losing unrecoverable passwords, and until we have a main Steem or Steemit App with a full suite of key backup features similar to Exodus email backup, we must simply educate our new users with a simple Video with useful and educational content and someone demanding attention in one way or another to ensure the user understands in crystal clear terms that they must save their Password for steem because it is a cryptocurrency key like Bitcoin where once you loose it, no one can recover it because of the decentralized nature of the system.  Too many users are ending up loosing passwords and then telling others about their terrible user experience of making money and getting locked out of it, essentially loosing it because what they felt was a lack of communication from Steemit Inc or whoever created their account, about how serious it is to not loose a steem password.  

If we can educate more users when they first signup, perhaps by placing an educational video made by the steemit inc team simply of 1 person, maybe even Ned, which explains to users that saving their key is necessary, serious, and when it is given to them it should never be called a password except in parenthesis after PRIVATE KEY which should be in all caps, red, and have multiple warning boxes around it which make it EXTREMELY clear that "WARNING: THIS IS A STEEM PRIVATE KEY, AND IT IS YOUR PASSWORD WHICH CAN NEVER BE RESET SO DONT LOOSE IT!"  

Something like the above text should actually help us cut down on users who just don't ever get the idea that they cannot ever have a forgotten password reset. 

The lack of a password reset is a very unique feature to steem which almost no other crypto websites use, and since steem is one of the first revolutionary ground breaking crypto social media that anyone can use, it will have many users who will come here from Facebook Twitter Youtube etc which are all websites which CAN reset your password and very easily using multiple backup methods including a final manual backup that involved a phone or email verification  with a customer support person.  This is an important distinction to make that Steem is NOT like the normal website which can just reset your password.  I believe we can solve this problem of users losing passwords with a few simple red text boxes in all caps on the Signup Page and a embedded short youtube link to a Video that plays during Signup maybe only 30 seconds to 1 minute but which can be mandatory and display a frivolous loading screen behind it to make a user believe their account is being "processed" (which it technically will be) and while they wait they must watch this video, and the video can have  Ned or someone like Andrarchy, explaining that you must backup your steem password! (maybe to lastpass or another service we can even partner with officially in the future) and then after watching the video they can get their account now having been Told that they Cannot loose the password! And they should again be reminded the VERY first time they log in and maybe even the second time if possible . Thanks for reading and I do apologize in advance for whatever rules I already have broken in my guidelines, Thanks

**Comment by Smittyvb** [comment]
Issues relating to signup should go in the steemit/faucet repo.

Also, this situation could also be helped by having Steemit store account keys for a few days after creation. Advanced users would be able to change their password to revoke Steemit’s access, but normal users would have a password reset functionality. This could also be implemented as giving the Steemit account owner authority, then have Steemit revoke itself.

**Comment by roadscape** [comment]
Thanks @ackza, noted. For now condenser only allows posting key login. Signup key delivery needs to be addressed in the future.
