### ISSUE TITLE
Check up on the the new notification system.

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2928]
Make sure the new-notification system ui is good to go. Make sure it can be wrapped in feature flag and works as expected.

**Comment by gl2748** [comment]
See:
https://github.com/steemit/condenser/tree/notification-ui-rebased-squashed

**Comment by gl2748** [comment]
Refactor wip is here: 
https://github.com/steemit/condenser/tree/im/refactor-notifs-components

**Comment by bnchdrff** [comment]
see https://docs.google.com/document/d/16THc1tpBikICN66cFlmqacJX8mcb4ErPPPNRlqEKHUY/edit
