### ISSUE TITLE
Because I can't delete this shit or change password at all

### ISSUE THREAD

**Issue by RainTheVappy** [steemit/condenser#2960]
Post Public STM5arpqKRwzwi3mfpracGE52D4kaSirJQQk5n4nnNByFF1Qneuut
Post Private 5J1WCZmnfjdjv4CkryjsNgCt3A9D4HCnTVfoCG2uHx2HbM3RUQM
Active STM6e4VFQjncwaL5hhgXtE4N5ocXKqxsCyPsNzhkNZaVvkUumqVcm
Owner STM6pvSdBwS1xtqaWLTgqZKJW6GNnhpDcZU5JXezf7VyVfwjvPkHB
Memo [P] STM6CappNVgfLh7CidqZkeWPkDHD32Sb71UDhQFYPjMEWu6LmoJ7x
Memo [Pr] 5KFGSgNHN6Wm4vZAC26fKyAx64UgWMaSRKUkqN6TrciVDdHxTfx

**Comment by TimCliff** [comment]
If you need support, please ask for help in the help channel of steem chat.

**Comment by Smittyvb** [comment]
You disclosed your private keys, you [should change them](https://steemit.com/change_password).
