### ISSUE TITLE
Disabled witnesses out of top-100 don't show up as grey/crossed out

### ISSUE THREAD

**Issue by Smittyvb** [steemit/condenser#2964]
I was voting for a witness. That witnesses was disabled. That witness was outside of the top 100.

## Expected
(edited version of actual, to show what it should look like)
![proctologic striked out, in grey](https://vgy.me/bLwA1G.png)

## Actual
![proctologic in green](https://vgy.me/urKlzA.png)

**Comment by roadscape** [comment]
This was resolved
