### ISSUE TITLE
Transactions show out of order on wallet page

### ISSUE THREAD

**Issue by themarkymark-steem** [steemit/condenser#2967]
Transactions should show up in reverse chronological order.  Many times you will find transactions out of order.  Typically a refresh will fix this, **if** the page loads properly.

The wallet page is the most important page on Steemit for 99% of the users.  It should be reliable, and trustworthy.

**Comment by roadscape** [comment]
Addressed in #3090 but needs to move to https://github.com/steemit/wallet
