### ISSUE TITLE
Duplicate transactions in the wallet page

### ISSUE THREAD

**Issue by themarkymark-steem** [steemit/condenser#2970]
Frequently when visiting a wallet page, mine or another user I will see a recent transaction show up, then another copy of the transaction show up a few lines down out of chronological order and as a duplicate similar transaction.  This happens often and typically for newer transactions in my experience.

The wallet page is the most important page on Steemit for 99% of the users. It should be reliable, and trustworthy.

**Comment by roadscape** [comment]
Addressed in #3090 but needs to move to https://github.com/steemit/wallet
