### ISSUE TITLE
Can post / vote from another account when logged into another account

### ISSUE THREAD

**Issue by themarkymark-steem** [steemit/condenser#2971]
I am well aware of the issues where when you log out you can still vote as a user.  Today I had another issue that to me is even worse.

I was logged into my account, I logged out.  I logged into another account.  I could see that accounts icon in the top right avatar.  I made a test post to test a community support bot and the post was posted as my account I previously logged out of.

I typically hit refresh when switching accounts, to make sure I'm really in the account I am trying to be in.  This was the first time I saw the icon of the account yet posted as the other account.

**Comment by mac128k** [comment]
I had a similar result with an upvote between two accounts. I logged out of account 1 and in with account 2. I upvoted with account 2 successfully but when I logged out of account 2 and back into account 1 and tried to upvote, I was warned that I was removing my vote (I never made a vote with account 1).

**Comment by voorash** [comment]
I can't say 100 percent but if you turn off stay logged in or save login whatever it is called it generally stops this.

**Comment by roadscape** [comment]
We don't currently support account switching, but would accept a PR to fix any bugs around it
