### ISSUE TITLE
Wallet memos can't be seen on mobile 

### ISSUE THREAD

**Issue by Smittyvb** [steemit/condenser#2972]
Wallet memos can't be seen on mobile.
![](https://vgy.me/0YBsPe.jpg)
This is happening to me, on iOS.
Scrolling left and right doesn't work.

**Comment by netuoso** [comment]
This is because it contains `show-for-medium` CSS class. If you think it would look alright with the transfer info shown on two lines (the second line for the memo) I could get an example of that.

On mobile, you can probably change your view to landscape to see the memos

**Comment by eonwarped** [comment]
Yeah I basically request the desktop version on my phone to see them.

**Comment by roadscape** [comment]
Please move this to https://github.com/steemit/condenser/wallet if it hasn't been resolved.
