### ISSUE TITLE
The Chinese Comma should not display at the beginning of a line

### ISSUE THREAD

**Issue by DoctorLai** [steemit/condenser#2976]
https://steemit.com/cn/@justyy/6d-mark-ii

![image](https://user-images.githubusercontent.com/1764434/43940837-628fb0c2-9c69-11e8-91f4-16f5b1587158.png)

**Comment by quochuy** [comment]
@DoctorLai Do you have another example as the post above has been edited.

**Comment by quochuy** [comment]
Although it seems like it's already fixed.
![Screen Shot 2019-05-22 at 7 41 35 pm](https://user-images.githubusercontent.com/310654/58164713-ad57e480-7cc9-11e9-866e-e79e8e22ff8a.jpg)

**Comment by DoctorLai** [comment]
@quochuy  this looks odd to me:
https://steemit.com/cn/@justyy/g6zrm-2

![image](https://user-images.githubusercontent.com/1764434/58548432-35297b80-8201-11e9-8234-f4a6b7ceb65b.png)

**Comment by quochuy** [comment]
@DoctorLai that is normal, the grey icon appears when the link leads to an external page. In this case, there is not enough space to render the icon next to the link `here` so the browser just breaks the line.

**Comment by roadscape** [comment]
@DoctorLai I concur w/ @quochuy that the last example is a special case which is not related to locale. If there are no other cases shall we close this issue for now?

**Comment by DoctorLai** [comment]
@roadscape  ok... we can re-open this if we find some other cases later.
