### ISSUE TITLE
Wrapped sign up button

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/condenser#2979]
At a certain browser window size, the Sign up button wraps itself when clicking into the Search field.

![wrap-bug](https://user-images.githubusercontent.com/4613678/44003573-6d5cd47a-9e22-11e8-93c9-3cbb754bb2e9.png)

**Comment by pkattera** [comment]
It looks like there is a media query on the search icon:
– if screen size is less than 1200px, tapping the search icon goes straight to the search page.
– if the screen size is 1200px or larger, the search icon expands to the search bar.

The above works fine for logged in users but breaks for logged out users between 1200px – 1360px in screen width.

Ideally, we'll do the following:

- For logged in users, we'll leave the breakpoints as is.
- For logged out users, we'll create a new breakpoint which only starts expanding the search box when the screen width is at least 1360px wide.

**Comment by roadscape** [comment]
Closing for now; if issue persists please reopen.
