### ISSUE TITLE
Grammarly does not display spelling error squiggles properly in post/comments

### ISSUE THREAD

**Issue by themarkymark-steem** [steemit/condenser#2984]
While related to [2983](https://github.com/steemit/condenser/issues/2983), it is a different issue.

When using Grammarly not only are the spelling error fixes reverted, the squiggly lines are no where near where the spelling errors are.  While this sounds like a Grammarly issue it doesn't happen on any other site.  Add in the fact text is magically reverted [issue 2983](https://github.com/steemit/condenser/issues/2983) I believe it is some wonky magic happening in the post/comment entry forms that is causing this behavior.

Normally spelling errors would line up with the actually spelling error like this:
![](https://i.imgur.com/S8hBKHc.png)

But frequently the red line is shown no where near the actual error and many times not even in the text edit form.

**Comment by roadscape** [comment]
Quite likely a subset of #2983 or a Grammarly bug
