### ISSUE TITLE
Guys is it possible that you whitelist more iframe link?

### ISSUE THREAD

**Issue by tngflx** [steemit/condenser#2986]
look at medium.com whitelisted embeds. https://help.medium.com/hc/en-us/articles/214981378-Embeds.
It should be more than just vimeo, youtube and soundcloud. Can you guys at least add another one in SanitizeConfig.js? I wish to have reader to listen to my podcast service served by anchor.fm. Can you guys whitelist that?

**Comment by Smittyvb** [comment]
Can you post the anchor.fm embed code?

Using the Embed.ly software Medium uses is closed-source, and paid. They have a free version, but it has Embedly branding on it.

**Comment by tngflx** [comment]
Or is it possible to just whitelist an embedded audio player? https://support.jwplayer.com/articles/how-to-embed-external-playlists-and-rss--json-feeds. Then we can use the iframe src from somewhere else.

**Comment by roadscape** [comment]
Hi, please check for an existing issue or submit an issue/PR for a specific service. Thanks!
