### ISSUE TITLE
Resteem on comments

### ISSUE THREAD

**Issue by psoscrypto** [steemit/condenser#2994]
When you access to repleis option and click on a replei there is a resteem button that generate an error if you try to resteem that comment

**Comment by relativityboy** [comment]
@psoscrypto - can you provide a screenshot with the error?

**Comment by psoscrypto** [comment]
![img_20181022_214434_645](https://user-images.githubusercontent.com/42246415/47318472-0e401100-d644-11e8-9788-3e88087bb4ec.JPG)

**Comment by quochuy** [comment]
@roadscape
I can't reproduce this neither in desktop or mobile browser.
The resteem button does not show up.

The code confirms it too (Reblog.jsx):
`    render() {
        if (this.props.author == this.props.account || this.props.parent_author)
            return null;`

**Comment by roadscape** [comment]
Thanks for looking into this @quochuy! Closing.
