### ISSUE TITLE
Missing posting authority for umlaut character in markdown images alternative title

### ISSUE THREAD

**Issue by CanRau** [steemit/condenser#2997]
hey guys great work!
just wanted to mention that we (@gaiama) just had this issue while trying to post on steemit.com `Missing posting authority` it seems to happen sometimes and people seem to have different solutions, just wanted to add mine as it might be interesting to add some encoding
so in our case we had an `ü` (german umlaut) within the markdown square brackets of an image (the alt tag) like 

```
![müll](https..)
```

changing it to "muell" solved it

don't have any capacity to look into it myself right now, just posting, cause I would feel bad not doing it^^

#1820, #1075 might be related but are already closed and still slightly different so opening new issue

**Comment by roadscape** [comment]
Is this still an issue?

**Comment by CanRau** [comment]
Good question haven't steemed in a while so can't tell 🤷‍♂️

**Comment by roadscape** [comment]
Ok, please reopen if the issue pops up again.
