### ISSUE TITLE
When signing up for SteemIt account, API limit doesn't show error

### ISSUE THREAD

**Issue by jamesroseman** [steemit/condenser#3000]
*Overview*

I was trying to create a SteemIt account. I went through the registration flow at https://signup.steemit.com/ I entered my phone number and clicked next. Checking the phone number, I saw that I'd entered the wrong one. I clicked "go back" and entered my corrected phone number, but when I clicked "continue", nothing happened on the page.

<img width="1150" alt="screenshot 2018-09-04 00 03 59" src="https://user-images.githubusercontent.com/1159190/45009416-0a91f580-afd6-11e8-9f11-ccf7171fd437.png">

When I go into the dev-tools console, I can see clearly that the API limit has been reached. However, this error isn't made transparent to the user.

<img width="704" alt="screenshot 2018-09-04 00 04 43" src="https://user-images.githubusercontent.com/1159190/45009434-22697980-afd6-11e8-8114-2c5396b1ae3f.png">

- - -

GIVEN A user accessing https://signup.steemit.com/
AND The user has filled out their phone number and progressed to the next step
AND The user has clicked "Go back button"
AND The user has filled out a different phone number
WHEN The user clicks "continue"
AND The API action limit has been reached
THEN The user is notified in the page that the action limit has been reached, and to try again later

- - -

I'm a full-stack developer and would love to contribute to the project by fixing this bug, but don't want to do any unneeded work. Let me know!

**Comment by roadscape** [comment]
Hi, this should be resolved but if not please re-open
