### ISSUE TITLE
Community - Hardfork 20 - Resource Credit errors should have a user friendly error message

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#3001]
After hardfork 20, it is likely that many users will be running into errors where they try to submit transactions when they don't have enough RCs. It would be good to provide a user friendly message that explains why they are running into the limitation and what can be done to help, similar to what is there today for bandwidth.

This is the message that is currently shown:
![image](https://user-images.githubusercontent.com/20735105/45231796-e9116200-b292-11e8-8085-5e8816de177a.png)

Also, on the condenser testnet when voting for witnesses, the vote button just spins but this error is logged in the developer console:
![image](https://user-images.githubusercontent.com/20735105/45231898-41486400-b293-11e8-8da0-3c09f2bd1eab.png)

**Comment by mac128k** [comment]
SD-384
