### ISSUE TITLE
d.tube search problem

### ISSUE THREAD

**Issue by zerkoth** [steemit/condenser#3006]
So, even if your video is called like "Black Clover XXXXX" you can't find it just by typing black clover in the search window. I don't know why but i tried on diffrent devices and without an account. (My first thought was i just can't find my own videos).
Is it a bug or i'm just making something wrong?

**Comment by Smittyvb** [comment]
This repo is for issues relating to Condenser and Steemit.com. You should report issues relating to DTube in the [DTube issue tracker](https://github.com/dtube/dtube/issues).
