### ISSUE TITLE
Unable to recover account

### ISSUE THREAD

**Issue by stm12** [steemit/condenser#3016]
Error found, "Recent authority not found in authority history."

**Comment by pkattera** [comment]
@stm12 We're looking into this issue. Can you please provide some more context around this.

For example, what was the username for this account? Did you attempt to complete the recovery process for an account that had previously started a recovery more than 30 days ago?

**Comment by stm12** [comment]
> @stm12 We're looking into this issue. Can you please provide some more context around this.
> 
> For example, what was the username for this account? Did you attempt to complete the recovery process for an account that had previously started a recovery more than 30 days ago?

Hello @pkattera. How to send the username to you privately?

**Comment by relativityboy** [comment]
@stm12 - please email da@steemit.com
