### ISSUE TITLE
Remove steemit shop references

### ISSUE THREAD

**Issue by relativityboy** [steemit/condenser#3018]
The Steemit Shop is going to be down for some time. The steemit shop needs to be removed from condenser so that I don't feel teased.

[approx location in src](https://github.com/steemit/condenser/blob/master/src/app/components/modules/SidePanel/index.jsx#L93)

**AC**
- [ ] link is removed 
- [ ] references to thesteemit shop are removed from condenser.

**Comment by Birdinc** [comment]
Link to thesteemitshop.com should be removed from the side menu on steemit.com.
