### ISSUE TITLE
Community - HF20 Change "Bandwidth" to "Resource Credits" in Insufficient bandwidth modal

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#3019]
For issue https://github.com/steemit/condenser/issues/3001, a change was made to display the "Insufficient bandwidth modal" when an insufficient RC error is returned by the blockchain. The modal that is shown though still uses the word "bandwidth" instead of "resource credits".

![image](https://user-images.githubusercontent.com/20735105/45961114-5e936700-bfe3-11e8-8a02-2db945c98307.png)

- [x] Update the text for the Insufficient bandwidth modal to use "Resource Credits" in place of "Bandwidth".

I will submit the PR for this change.

**Comment by pkattera** [comment]
Thanks @TimCliff
