### ISSUE TITLE
Community - Transfer to Account modal spinning after wallet transfer

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#3024]
After I did a wallet transfer, the "Transfer to Account" modal page just kept spinning.

Here is a screen shot of the developer console:
![image](https://user-images.githubusercontent.com/20735105/45989200-3ab23e80-c040-11e8-9af6-33eab2748006.png)

**Comment by pkattera** [comment]
Hi @TimCliff – I'm unable to reproduce this error. Can you please try again? I wonder if it had to do with the HF20 issues earlier this week?

**Comment by TimCliff** [comment]
This seems to be happening on a regular basis now. Re-opening.

Here is the error from the dev console when I tried to do a transfer via Chrome:
![image](https://user-images.githubusercontent.com/20735105/56329566-ba713900-6149-11e9-9e8a-2c03b609963e.png)

**Comment by JonathanPorta** [comment]
Hey @TimCliff I've looked into this issue the last day or so and I am having troubles reproducing it. Do you have any further info that might help me troubleshoot this?

**Comment by TimCliff** [comment]
Hi @JonathanPorta . I am using Chrome. It happens every single time i do a transfer. I don't have any unusual plugins installed or settings that I'm aware of. The error from the developer console is the same as what I posted above.

**Comment by svemirac1** [comment]
Hello, I am having the same problem for quite some time now. 
I am using Brave/Chrome browsers at this moment - but I guess they have the same engine.  It happens even if I start power up, or transfer to any other account. 

What is weird is that I can see the funds moving from liquid into the powered up steem part - but the circle is still chasing its tail.

**Comment by roadscape** [comment]
Fixed in https://github.com/steemit/wallet/pull/51 and deployed. Thanks for the reports.
