### ISSUE TITLE
Community - Missing active posts from "New" and "Trending"

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#3042]
Usually when browsing a tag for "New" (example: https://steemit.com/created/witness-category) it would show all of the active posts from the past seven days. There are lots of examples recently where posts that are less than seven days old are not showing up.

Example:
https://steemit.com/witness/@themarkymark/jerry-bandfield-sold-his-witness-account-and-is-now-producing
![image](https://user-images.githubusercontent.com/20735105/46263723-20f97700-c4d8-11e8-851d-7a6a84ccd674.png)

https://steemit.com/created/witness-category
![image](https://user-images.githubusercontent.com/20735105/46263737-5900ba00-c4d8-11e8-99c6-9857e1ac80c9.png)

The post also does not show up anywhere under "Trending":
https://steemit.com/trending/witness-category

**Comment by roadscape** [comment]
Resolved w/ hive API
