### ISSUE TITLE
An old post is editable

### ISSUE THREAD

**Issue by akipponn** [steemit/condenser#3045]
I found that an old post is editable on Steemit under a certain circumstance.

By default a post can't be edited after 7 days since it has been posted. However by following the steps below I could edit an old article:

1. Open editor of a post on Steemit in a browser tab before the 7th day.
1. Close the tab.
1. Open the post again with the same browser after the editable period pasts.
1. Editor is shown and one can update the post.

My environment is:
- Mac OS 10.13.6
- Google Chrome v69.0.3497.100

After editing the post once, the editor is closed and never open again. Frontend wise it's not a big issue but this means there is a way to send RPC to author a post anytime to the backend.

<img width="885" alt="2018-10-01 9 21 00" src="https://user-images.githubusercontent.com/170129/46275204-6e1f2c80-c55c-11e8-8d42-0a5658e4bd0d.png">

**Comment by TimCliff** [comment]
The plan is to fully remove the 7 day restriction on editing posts.

**Comment by akipponn** [comment]
Hi Tim, I see. Thank you for reply. I close this issue :)
