### ISSUE TITLE
Followed users page displays incorrect follow state when transaction is rejected

### ISSUE THREAD

**Issue by ausbitbank** [steemit/condenser#3051]
When I unfollow users too quickly using the buttons [here](https://steemit.com/@ausbitbank/followed) I get denied due to the 1 custom json operation per block rule. 

The error is displayed, the transaction is denied, but the button still updates to "follow", instead of remaining as "unfollow".

I've uploaded a short clip of this behavior here https://youtu.be/41D5jCY2DUA

I assume (but have not tested) that this issue also affects https://steemit.com/@user/followers as well as https://steemit.com/@user/followed

Software Used : Firefox 63.0b11 (64-bit) on Windows 10

**Comment by pkattera** [comment]
@ausbitbank We appreciate the video demonstration.
I can confirm this is a bug for me too on Mac / Chrome.

**Comment by gryter** [comment]
Same if you try to follow (it's the same operation) but goes back to normal after refresh. 

![image](https://user-images.githubusercontent.com/31012685/46507290-cdec3080-c805-11e8-9c9b-582bd8622287.png) 
Pictured is three accounts, error on middle, restored on refresh, other two went through and are accurate.

**Comment by gadrian78** [comment]
I'm not sure if the situations are comparable code-wise, but if they are, would a solution similar to how witness voting page operates be good? I tried to break the witness voting page the same way by unapproving/approving two witnesses within 3 seconds and there was no error and no issue with how the votes were displayed.
