### ISSUE TITLE
Testnet - Unable to transfer tokens to another account via wallet page

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#3067]
If I try to transfer "TESTS" or "TBD" to another account on the testnet, I receive an error.

![image](https://user-images.githubusercontent.com/20735105/47180198-9beacc00-d2e5-11e8-9049-ad5e1c5de842.png)

Here are the details from the developer console:
![image](https://user-images.githubusercontent.com/20735105/47180206-a2794380-d2e5-11e8-8fdc-e4ac92e814f5.png)

**Comment by roadscape** [comment]
Closing as it's testnet and wallet has split from repo
