### ISSUE TITLE
signup.steemit - Page is looping popup reCAPTCHA, cant connect

### ISSUE THREAD

**Issue by Canule** [steemit/condenser#3077]
I'm unable to register since the [page](https://signup.steemit.com/) is looping with popups it cant connect to the reCAPTCHA server after finishing the check. Firefox 62.0.3 
The by Google crap provided reCAPTCHA is generally not a functional problem on websites.

**Comment by Smittyvb** [comment]
Issues relating to signup should go in the [steemit/faucet repo](https://github.com/steemit/faucet/issues).
