### ISSUE TITLE
Add the tag "tags" as first and the post is not shown

### ISSUE THREAD

**Issue by wehmoen** [steemit/condenser#3082]
When you add the tag "tags" as the first tag to your post you can not open it on steemit.com.

https://steemit.com/tags/@guest123/3pa2rv-test

**Comment by pkattera** [comment]
I can confirm, I'm getting the same error. 

After posting with a tag of "tags", the URL goes to a 404 page error. 

I wonder if "tags" is a special term that has been reserved for for https://steemit.com/tags ?

**Comment by wehmoen** [comment]
I think so. I also tried the tags "trending" and "market" but they work fine.

**Comment by roadscape** [comment]
`/tags` route regex needs to be fixed

**Comment by quochuy** [comment]
@roadscape looks like it's already been fixed? Can't reproduce it.

**Comment by roadscape** [comment]
Aha good catch. It was probably resolved with hivemind API. Closing.
