### ISSUE TITLE
Issue with open graph properties

### ISSUE THREAD

**Issue by BFuks** [steemit/condenser#3094]
The open graph properties of the posts are not formatted correctly, which prevents users to share images together with their post on other media (the text is nicely shared, but not the images going with it). The metadata should actually be fixed.

**Comment by roadscape** [comment]
Hi, could you describe the specific issues?

**Comment by BFuks** [comment]
I think this has been fixed in the meantime. It is however hard to remember as this was like 5-6 months ago.
