### ISSUE TITLE
Wallet shows balance of $122628521 per STEEM 

### ISSUE THREAD

**Issue by LKNX** [steemit/condenser#3101]
<img width="1026" alt="screen shot 2018-11-22 at 2 43 01 am" src="https://user-images.githubusercontent.com/9309101/48888645-5bf59800-ee01-11e8-8171-b16e953233b2.png">

**Comment by TimCliff** [comment]
Possibly due to https://github.com/steemit/steem-js/issues/418

**Comment by LKNX** [comment]
thank you @TimCliff
