### ISSUE TITLE
Add *Estimated* to pending payout, because now it's really off.

### ISSUE THREAD

**Issue by Transisto** [steemit/condenser#3115]
From 
![image](https://user-images.githubusercontent.com/388716/49500441-b39ef500-f83e-11e8-848b-1eb0dd33b458.png)

to
![image](https://user-images.githubusercontent.com/388716/49500490-d0d3c380-f83e-11e8-91da-abc411f18c2e.png)

**Comment by bobinson** [comment]
@Transisto : can you elaborate the problem bit more ? We can try to pass it on to the utopian folks or so and an detailed description and acceptance criteria will helpful.

**Comment by Transisto** [comment]
Adding "estimated" won't cut it.

Estimate have to be done using manually calculated median.

https://steemit.com/witness-category/@oflyhigh/why-is-medianhistoryprice-no-longer-the-median-of-feed-price-my-investigation

https://steemit.com/smartsteem/@smartsteem/fairer-price-calculation


I hope that helps.

On Dec 7, 2018 04:20, "Bobinson K B" <notifications@github.com> wrote:

@Transisto <https://github.com/Transisto> : can you elaborate the problem
bit more ? We can try to pass it on to the utopian folks or so and an
detailed description and acceptance criteria will helpful.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/steemit/condenser/issues/3115#issuecomment-445171593>,
or mute the thread

**Comment by roadscape** [comment]
From #3125:

> This dropdown is going to need an overhaul if we add much more to it, and for now the original issue does not seem all that relevant because SBD has been much closer to the peg since the last HF. Closing for now.
