### ISSUE TITLE
Ads changes breaks EVERYTHING THAT REQUIRES LOGIN

### ISSUE THREAD

**Issue by Smittyvb** [steemit/condenser#3128]
The permission page reloads on key input.
![monsuta steemit](https://user-images.githubusercontent.com/10530973/50026489-26cf0680-ffb7-11e8-9b2c-78857956d6c0.gif)

**Comment by Smittyvb** [comment]
All logins refresh page before operations can be broadcast on-chain. THIS BREAKS A LOT, INCLUDING TRANFERS, THE MARKET!!!!!!

**Comment by Smittyvb** [comment]
I CAN'T LOGIN, either!

**Comment by investwarrior** [comment]
ye had same proble, but only in firefox, in chrome all works, so seems they need to update it in firefox

**Comment by KINGdotNET** [comment]
Ok. Thank you @Smittyvb

**Comment by propertunist** [comment]
I've had a similar issue in Dtube for a few days in firefox latest - not sure if it is related.

**Comment by investwarrior** [comment]
> I've had a similar issue in Dtube for a few days in firefox latest - not sure if it is related.

yep same for me in firefox. but only started yesterday

**Comment by rjungemann** [comment]
Thankyou for alerting us to this issue. We have reverted this change while we investigate.

**Comment by jredbeard** [comment]
Thanks everyone for your feedback. This has been fixed in #3130
