### ISSUE TITLE
Following count

### ISSUE THREAD

**Issue by pjanaway** [steemit/condenser#3135]
![following-count](https://user-images.githubusercontent.com/12845422/50186121-c4a53700-0311-11e9-8df2-5e32e4890dff.PNG)

The following count is incorrect, I only have 69 but it says 166.

**Comment by pjanaway** [comment]
I just checked and Steemit is using api-int.steemit.com

![apiint](https://user-images.githubusercontent.com/12845422/50227128-ee577000-039c-11e9-9399-a2cfde866ab4.PNG)

**Comment by anthonyadavisii** [comment]
Following error attempting to get_following:


```
786, in get_following
    name_list = [x['following'] for x in self._get_followers(direction="following", limit=limit)]
  File "/home/sfr/miniconda3/lib/python3.6/site-packages/beem/account.py", line 825, in _get_followers
    followers = self.steem.rpc.get_following(query, api='follow')['following']
TypeError: list indices must be integers or slices, not str

```
