### ISSUE TITLE
Integrate New Paid Sign Up Flow

### ISSUE THREAD

**Issue by realnedscott** [steemit/condenser#3152]
On signup.steemit.com:

1. Integrate Steem.Ninja credit card - based signup flow (https://steemit.com/introduceyourself/@steem.ninja/steem-ninja-account-sign-ups-with-credit-card-and-referral-reward-system)

2. Deprecate Wait List flow.

**Comment by Smittyvb** [comment]
Issues relating to signup.steemit.com should be in the [steemit/faucet repo](https://github.com/steemit/faucet).

**Comment by TimCliff** [comment]
@wehmoen I think the intention is to go one step further than that PR and make the Steem.Ninja credit card based signup flow the primary signup method, in place of the "waiting list" for free accounts that is there today.

**Comment by TimCliff** [comment]
I opened a corresponding faucet issue: https://github.com/steemit/faucet/issues/400
