### ISSUE TITLE
Community - Follow lists are not in alphabetical order

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#3165]
A user reported an issue in steem.chat help with regards to the follow lists not being in alphabetical order. Creating this as a condenser issue, although it could possibly be a https://github.com/steemit/hivemind issue.

**Comment by Redpossum** [comment]
Hey, I'm Redpossum. I've been on Steemit for 267 days now, according to Steemd. My lists of those following me and those I am following have both always been sorted alphabetically. Then about 4 days ago, they both suddenly became scrambled. They may perhaps be sorted by some order which is not apparent to me, but at any rate they are no longer sorted alphabetically. I looked around in settings, but was not able to find any options for sort order. I asked in #help on Steemchat and TimCliff suggested I post this report here.

And that's all the relevant info I can think of. Gratitude to TimCliff for helping me get this posted here. Gratitude to those who code Steemit, which has changed my life for the better. Let me know if you have any questions and I'll do my best to answer them for you.

**Comment by roadscape** [comment]
Thanks for the report, this is a backend behavior with discussion here: https://github.com/steemit/hivemind/issues/167

(The new order is newest relationships first.)
