### ISSUE TITLE
collapse excessive whitespace

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#3179]
Even though there are endless ways to abuse whitespace, we should consider handling simple cases like these:
https://steemit.com/actifit/@abusereports/abusereports-re-abusereportsabusereports-re-abusereportsabusereports-re-abusereportsabusereports-re-mitradoactifit-mitrado-20190118t233353131z

**Comment by quochuy** [comment]
Should the clean up be done before storing into the blockchain or at rendering?

**Comment by roadscape** [comment]
Most utility will be had at rendering since it will cover excessive whitespace from other UI's too.

**Comment by quochuy** [comment]
https://github.com/steemit/condenser/pull/3333

**Comment by roadscape** [comment]
Decided against this for now -- doesn't seem to be a big problem and a proper solution may be a bit more involved. If the issue comes up again we may need to look at using max-height for comments with overflow:scroll. That will only partially address the display issue; a more effective solution may be to wait for moderation features.
