### ISSUE TITLE
Comment layers are not visible enough

### ISSUE THREAD

**Issue by therealwolf42** [steemit/condenser#3195]
Currently, we only have this little dot showing us on which comment-level/layer we are, which is not visible enough IMO. I actually didn't know it existed, because I didn't see it until @eonwarped told me about it:

![image](https://user-images.githubusercontent.com/31614097/51802841-1ebce480-224e-11e9-9e3c-e71c95457aef.png)

I would prefer to have something along the lines of this:

![image](https://user-images.githubusercontent.com/31614097/51802849-32684b00-224e-11e9-97a5-4c14441d3601.png)

**Comment by roadscape** [comment]
Making comments a little more condensed and as well-defined blocks would also help

**Comment by quochuy** [comment]
This feature had been added to my Chrome Extension Steemed Phish for a while now. It was achieved  by injecting this CSS into Steemit pages:
`.Comment__body {
    border-left: 3px dotted #ededed;
    padding-left: 5px;
    padding-bottom: 2px;
}`

![Screen Shot 2019-05-06 at 8 26 02 am](https://user-images.githubusercontent.com/310654/57201181-bd3cac80-6fd8-11e9-83ad-9d5d269cd515.jpg)

**Comment by quochuy** [comment]
https://github.com/steemit/condenser/pull/3332

![Screen Shot 2019-05-10 at 9 58 15 am](https://user-images.githubusercontent.com/310654/57494084-2be87580-730b-11e9-8b48-679ed161d2d5.jpg)
