### ISSUE TITLE
Request features 

### ISSUE THREAD

**Issue by Azemblage** [steemit/condenser#3207]
Hey, I am using for a bit steemit and there are a lot of little things it could improve to become even better. My experience is not the best since I have to go to a lot of 3rd party sites to find my own information and had the recent problem of ruining out of credit to even comment or upvote, just for the lack of that information on the steemit platform. 

I will list below the crucial things I find important to have to all users new and already there for a while.  

1- Add notifications to steemit. ( Now other than checking the comments, blog, and replies we never know when we have new activity... Please add a notification element near the profile picture on the top right corner to easily click there and find all the new activity );

2- Add a voting power and resource credits to the wallet tab for example named "Account Health" or something like that. ( So we can always know the limits we are without running out and just be able to find out after being at 0 from another 3rd party website);

3- Estimations ( This is relative to point 2 on the power and resource credits add the possibility if it reaches low number to know how many days it will take to reach full power again)

4- Add a undo option when posting and updating posts( currently when you want to update a post it counts as a new posts, that makes the use of credits as well and it's a problem since if you just have enough to 1 post.. and for a typo mistake or the keyboard changed by mistake  sentence. You know have not enough credits to update and improve your own post. With a undo function that could be prevented that way we could have same time even after posting to correct any problem, without any credit 'punishment')

Hope this makes sense and there are more people that hose feature would help as well. To comment and help reach the top so this can be seen. 

Thanks for reading!

**Comment by wehmoen** [comment]
1) Try busy: https://busy.org
2) You can always check on https://steemd.com/@<your username>
3) see above
4) Every update needs resources. Every update is a single transaction and therefore need Ressource Credits. If you need more RC try power up more STEEM, rent a delegation or wait until your RC has recovered. You can check your current RC level at steemd.com

**Comment by Azemblage** [comment]
> * Try busy: https://busy.org
> * You can always check on https://steemd.com/@
> * see above
> * Every update needs resources. Every update is a single transaction and therefore need Ressource Credits. If you need more RC try power up more STEEM, rent a delegation or wait until your RC has recovered. You can check your current RC level at steemd.com

Thanks @wehmoen, I was already using steemd but was more to have just one platform to view all but I didn't new busy.. and seems great and have everything there from what I can see even the notification. 

Thanks man, for the help. steemit should take some hints from busy

**Comment by roadscape** [comment]
Thanks for the feedback. Your suggestions are noted.
