### ISSUE TITLE
[Documentation]: Condenser for a local testnet

### ISSUE THREAD

**Issue by SirVeryBritish** [steemit/condenser#3221]
Greetings, my team is developing a project for the Steem platform and wanted to boost our productivity by setting up Condenser for our local testnet. We found it difficult to configure Condenser correctly, in fact we never managed to use Condenser to interact with our local testnet, only the cli_wallet worked for us so far. We would like to leverage the powerful Condenser fronted, to be able to visualize our work on our testnet. 

If someone has experience in this, we would appreciate help tremendously! Additionally I would like to suggest to add those steps to the documentation and would volunteer to create a pull request, once I get a hang of how it is working.

The Steem blockchain and Condenser will run on the same machine. We don't require any test data from the main net. So tinman (as far as I understand) is not needed. We tried to use tintoy, but on all of our available machines ( new installed Ubuntu 18.04 & 16.04 ) we got the same issue about a refused connection, when trying to use a python library. 

## Steem blockchain's config.ini:
log-appender = {"appender":"stderr","stream":"std_error"} {"appender":"p2p","file":"logs/p2p/p2p.log"}
log-logger = {"name":"default","level":"info","appender":"stderr"} {"name":"p2p","level":"warn","appender":"p2p"}
backtrace = yes
plugin = witness webserver p2p json_rpc witness account_by_key tags follow market_history account_history
plugin = database_api account_by_key_api network_broadcast_api tags_api follow_api market_history_api condenser_api account_history_api block_api rc_api
history-disable-pruning = 0
account-history-rocksdb-path = "blockchain/account-history-rocksdb-storage"
block-data-export-file = NONE
block-log-info-print-interval-seconds = 86400
block-log-info-print-irreversible = 1
block-log-info-print-file = ILOG
shared-file-dir = "blockchain"
shared-file-size = 54G
shared-file-full-threshold = 0
shared-file-scale-rate = 0
follow-max-feed-size = 500
follow-start-feeds = 0
market-history-bucket-size = [15,60,300,3600,86400]
market-history-buckets-per-size = 5760
p2p-endpoint = 127.0.0.1:12001
{"listen_endpoint":"0.0.0.0:0","accept_incoming_connections":true,"wait_if_endpoint_is_busy":true,"private_key":"0000000000000000000000000000000000000000000000000000000000000000","desired_number_of_connections":20,"maximum_number_of_connections":200,"peer_connection_retry_timeout":30,"peer_inactivity_timeout":5,"peer_advertising_disabled":false,"maximum_number_of_blocks_to_handle_at_one_time":200,"maximum_number_of_sync_blocks_to_prefetch":2000,"maximum_blocks_per_peer_during_syncing":200,"active_ignored_request_timeout_microseconds":6000000} )
rc-skip-reject-not-enough-rc = 0
rc-compute-historical-rc = 0
statsd-batchsize = 1
tags-start-promoted = 0
tags-skip-startup-update = 0
transaction-status-block-depth = 64000
transaction-status-track-after-block = 0
webserver-http-endpoint = 127.0.0.1:8091
webserver-ws-endpoint = 127.0.0.1:8092
webserver-thread-pool-size = 32
enable-stale-production = 1
required-participation = 0
witness = "initminer"
private-key = xxxxxxxxxxxxxxxxxxxxx
witness-skip-enforce-bandwidth = 1

## Steems config.hpp
The file was not touched.

## Changed default.json from Condenser project:
Changed properties:
"steemd_connection_client": "http://127.0.0.1:8091",
"steemd_connection_server": "http://127.0.0.1:8091", 
"steemd_use_appbase": "true",
"chain_id": "9afbce9f2416520733bacb370315d32b6b2c43d6097576df1c1222859d91eecc",

So far we've tried, with a running and blocks producing blockchain setup, configured as shown above:

1. Cloning the repo, changing the default.json and build the Condenser project.
2. Using Docker and providing env variables to configure the project.

In both cases we were not able to get a result when browsing localhost:8080

**Comment by roadscape** [comment]
Hi, any progress with this?

**Comment by rabbykst** [comment]
is this problem solved?

**Comment by danirabbani90** [comment]
when you post some issue atleast try to give some answers to that  ?   did you resolve the issue ?

**Comment by ausbitbank** [comment]
May as well close this issue on this repo, if you want support and an actual community you should look into Hive. This project is dead.

**Comment by danirabbani90** [comment]
> May as well close this issue on this repo, if you want support and an actual community you should look into Hive. This project is dead.

yes true .. but we cannot build private chain on hive as well  due to that hive.fund account Treasury account .?

**Comment by SirVeryBritish** [comment]
Hi @danirabbani90, the issue was never addressed or resolved and the project I was working for was shelved. I remember that we did not want to waste any more time and just bought a bunch of Steem and started to work and test on the real Steem network.

I will close this issue now, thanks for reminding I still had it open.

**Comment by danirabbani90** [comment]
> Hi @danirabbani90, the issue was never addressed or resolved and the project I was working for was shelved. I remember that we did not want to waste any more time and just bought a bunch of Steem and started to work and test on the real Steem network.
> 
> I will close this issue now, thanks for reminding I still had it open.

Thank you for your response but can you please let me know that your new project hive ?? allows private chain building because steem had issues later for steem.dao ?
