### ISSUE TITLE
Image uploads on profile no worky

### ISSUE THREAD

**Issue by nynhex** [steemit/condenser#3222]
- Assuming latest condenser
- Editing profile
- Chrome/Brave/Firefox/Safari
- Uploads a new png or jpg to change profile photo
- Asks for WIF/Key
- Confirms updated
- After 10-15 minutes of waiting on butter to yield, cache doesn't invalidate.

**Comment by roadscape** [comment]
Functionality now lives at https://github.com/steemit/wallet/issues
