### ISSUE TITLE
No detailed user profile (cover image, rep, location, about...)  on reward pages

### ISSUE THREAD

**Issue by economicstudio** [steemit/condenser#3224]
On curation & author reward pages, rep is set to default (25) and the cover image and other info (e.g., location) isn't shown.

For instance,
- https://steemit.com/@blockchainstudio/curation-rewards
- https://steemit.com/@blockchainstudio/author-rewards

![](https://user-images.githubusercontent.com/38183982/53820627-10a46700-3f64-11e9-994b-e503d63361e2.png)

All other tabs are working well. But whenever reward tabs are clicked, this reset occurs. Browsers & login don't matter. But when logged in, if you go pages directly, then they work, but they don't if you first go to other tabs and then go to reward tabs. (Other tabs are working well even if you visit the tab later.)

**Comment by economicstudio** [comment]
I've done some debugging and basically rewards pages are routed to transfers.




```
  json_metadata: '',
  active:
   { weight_threshold: 1,
     account_auths: [],
     key_auths: [ [Array] ] },
  posting_rewards: 0,
  vesting_withdraw_rate: '0.000000 VESTS',
  guest_bloggers: [],
  sbd_seconds_last_update: '2019-03-05T18:45:03',
  created: '2018-03-02T16:02:06',
  last_post: '2019-03-05T17:38:21',
  savings_sbd_last_interest_payment: '2018-03-14T02:00:21',
  name: 'blockchainstudio',
  savings_sbd_balance: '0.000 SBD',
  witnesses_voted_for: 15,
  voting_power: 6996,
  to_withdraw: 0,
  proxy: '',
  next_vesting_withdrawal: '1969-12-31T23:59:59',
  vesting_balance: '0.000 STEEM',
  savings_sbd_seconds: '0',
  reward_vesting_steem: '0.000 STEEM',
  comment_count: 0,
  post_count: 4011,
  lifetime_vote_count: 0,
  sbd_last_interest_payment: '2019-02-28T03:08:24',
  last_account_recovery: '1970-01-01T00:00:00',
  proxied_vsf_votes: [ '22031319052256', 0, 0, 0 ],
  mined: false,
  market_history: [],
  sbd_balance: '31.627 SBD',
  pending_claimed_accounts: 0,
  post_bandwidth: 0,
  owner:
   { weight_threshold: 1,
     account_auths: [],
     key_auths: [ [Array] ] },
  savings_withdraw_requests: 0,
  voting_manabar:
   { current_mana: '2612250522640', last_update_time: 1551811503 },
  last_root_post: '2019-03-04T02:46:12',
  sbd_seconds: '6437026758',
  post_history: [],
  savings_balance: '0.000 STEEM',
  reputation: 0,
  last_vote_time: '2019-03-05T17:37:03',
  can_vote: true,
  reward_steem_balance: '0.000 STEEM',
  curation_rewards: 0,
  memo_key: 'STM5Wor19nvKKDFPEkpXngsnHvHVvwwjwo1AUJkJFoJshsD8wRVPd',
  id: 789067,
  tags_usage: [],
  balance: '0.003 STEEM',
  reset_account: 'null',
  last_owner_update: '2019-01-25T21:22:30',
  vote_history: [],
  withdraw_routes: 0,
  received_vesting_shares: '407940.240540 VESTS',
  reward_vesting_balance: '0.000000 VESTS' }
  --> GET /@blockchainstudio/curation-rewards 200 635ms 106.91kB fb1983d514847e6d4681dfdfd9
```
https://github.com/steemit/condenser/blob/e51e63a36d0b853df53253a0c08fcdf54b975d2a/src/app/components/pages/UserProfile.jsx#L173-L176


And `transfers` page, `account` returns `json_metadata: ''` and `reputation: 0`.

You can actually see the user profile is reset as in rewards pages, but then update the user profile.
Try this: https://steemit.com/@blockchainstudio/transfers

But `curation-rewards` and `author-rewards` don't update user profile later.

**Comment by roadscape** [comment]
This is a non-issue now that these pages have moved.
