### ISSUE TITLE
master build fails - Module not found: Error: Can't resolve 'react-headroom'

### ISSUE THREAD

**Issue by economicstudio** [steemit/condenser#3225]
The current master version can't build. Maybe related to https://github.com/marmelab/react-admin/issues/2941

```
ERROR in ./src/app/components/modules/Header/index.jsx
Module not found: Error: Can't resolve 'react-headroom' in 'GitHub/condenser/src/app/components/modules/Header'
 @ ./src/app/components/modules/Header/index.jsx 46:21-46
 @ ./src/app/components/App.jsx
 @ ./src/app/RootRoute.js
 @ ./src/shared/UniversalRender.jsx
 @ ./src/app/Main.js
 @ multi babel-polyfill ./src/app/Main.js
```

**Comment by economicstudio** [comment]
After updating packages, I can build them successfully again on my dev server. Although I can't see the log on steemit AWS, I'm pretty sure that that's the cause. So please update the packages for build tests. Thank you.

**Comment by jredbeard** [comment]
@economicstudio So, the AWS CodeBuild CI will always fail on external branches for security reasons - that is expected. We have to convert it to an internal branch before it will pass there. However, if it is passing on circleci you can be assured that it will pass on AWS CI once converted to an internal branch.

**Comment by economicstudio** [comment]
@jredbeard Thanks a lot for your answers! Hope my PRs: #3183 #3193 #3202 will be merged soon :)
