### ISSUE TITLE
sorting options for followers / followings

### ISSUE THREAD

**Issue by economicstudio** [steemit/condenser#3236]
Since Hivemind, the default order is chronological. This may be useful (thought some people don't like it in terms of "privacy"), but it's much better if there is a way to order it in a different way, at least alphabetically as before.

Currently, it's too difficult to find someone in the lists.

**Comment by roadscape** [comment]
For now we're going to leave it as-is, and a future search feature will make it easier to find friends. Also, since follower data is public I'm sure there are tools which let you see them all in detail.
