### ISSUE TITLE
This question is for account recovery.

### ISSUE THREAD

**Issue by ayogom** [steemit/condenser#3245]
If the user requests the account recovery because the master password is stolen,
Both hackers and users can apply for recovery via email.
To make it clearer, can I use the e-mail registered at the time of subscription to allow only the owner of the e-mail to apply for account recovery?

**Comment by Jolly-Pirate** [comment]
The user must use the same email as the one they signed up with, or the recovery is ignored.

**Comment by ayogom** [comment]
> The user must use the same email as the one they signed up with, or the recovery is ignored.

So, can I check the email I registered at sign up? I can not remember what email I signed up for.

**Comment by roadscape** [comment]
It must be the original email, yes.
