### ISSUE TITLE
I don't know the email I registered when I signed up Therefore, I can't recover my account.

### ISSUE THREAD

**Issue by ayogom** [steemit/condenser#3255]
My friend was hacked right now.
I've applied for account recovery, but I have not received any reply in a few days.
As a result, I noticed that the email he requested and the email he requested were different.
However, he does not know what e-mail he registered at sign up.

Currently, the account is still powered down, and assets may be taken away.

Because Steemit does not have the logic to change email, I'm looking for a new way to find his account.
Help me.

**Comment by roadscape** [comment]
Hi, right now the email has to be the one you signed up with and we cannot change it.
