### ISSUE TITLE
Post redirecting to steemitwallet.com domain

### ISSUE THREAD

**Issue by pjau-steem** [steemit/condenser#3277]
I don't know what it is with this specific url, but it keeps redirecting me to the steemitwallet.com domain

https://steemit.com/marketcap/@sevillaespino/coinmarketcap-04-15-2019
redirects to
https://steemitwallet.com/marketcap/@sevillaespino/coinmarketcap-04-15-2019

---

But if I remove the tag it works fine

https://steemit.com/@sevillaespino/coinmarketcap-04-15-2019
redirects to 
https://steemit.com/marketcap/@sevillaespino/coinmarketcap-04-15-2019

---

This is in Chrome, on both desktop and mobile. I have asked others and they get the same response.

**Comment by roadscape** [comment]
Thanks for the report. Solution is to fix [sdc frontend](https://github.com/steemit/sdc-frontend) redirect.

**Comment by pjau-steem** [comment]
This has been fixed now.
