### ISSUE TITLE
short comment permlinks

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#3278]
We should consider making generated comment permlinks short and stop nesting parent author/permlinks

Refs. https://github.com/steemit/condenser/issues/2161

**Comment by quochuy** [comment]
@roadscape would converting something like
"re-buggedout-re-quochuy-re-buggedout-revisiting-bidbots-a-necessary-evil-20190509t050808008z"

to
"re-buggedout-revisiting-bidbots-a-necessary-evil-20190509t074215724z"

good enough? With "buggedout" being the author of the comment being replied to.

**Comment by quochuy** [comment]
https://github.com/steemit/condenser/pull/3328

**Comment by roadscape** [comment]
Hi @quochuy, we could consider going even shorter -- e.g. `20190509-074215`. It's possible to go even shorter by using unix timestamp and converting to base36. For instance, a timestamp of `1557413901` converts to `pr8s99` in base36. There is little use in having overly verbose comment permlinks -- they should be reserved for top-level posts but comments would benefit from being short and convenient.

**Comment by quochuy** [comment]
@roadscape, I can see SEO benefits in having the title in the URL. Not sure it's important for comments though, although it could potentially bring more organic traffic...

**Comment by roadscape** [comment]
@quochuy comment permlinks do not need to be (and should not be?) optimized for SEO, but for top-level posts we definitely want to keep the title in the URL.

**Comment by quochuy** [comment]
@roadscape OK, I'll update the PR

**Comment by quochuy** [comment]
@roadscape https://github.com/steemit/condenser/pull/3328 updated

**Comment by economicstudio** [comment]
@roadscape Isn't it better to include at least parent author? now it's too uninformative.
