### ISSUE TITLE
Content near top of screen is sometimes obscured

### ISSUE THREAD

**Issue by JonathanPorta** [steemit/condenser#3281]
Observed Behavior:
Some pages load with their top-most content obscured by the header/ad bar.

Expected Behavior:
Any content at the top of a page should be visible below the header/ad bar.

Reproduction:
1. Load a user's profile such as: https://steemit.com/@justinw
2. Perform several non-cache-busting page reloads until the content is obscured (e.g. ctrl/cmd+r)

Additional Info:
1. Performing a cache-busting page reload seems to always result in the proper layout with no obscured content. (e.g. ctrl/cmd+shift+r)

Screenshots:
![image](https://user-images.githubusercontent.com/1451007/56618428-d8261e80-65df-11e9-97fa-c24fd59bba6c.png)

**Comment by bala41288** [comment]
Wondering why this issue was closed. I see that this is still an issue. It is inconsistent but definitely happening.

**Comment by JonathanPorta** [comment]
@bala41288 I closed a version of this issue that I accidentally opened against the wallet repo. Planning on fixing this soon. :)

**Comment by lukestokes** [comment]
Just noticed this on [my own post here](https://steemit.com/dac/@lukestokes/working-with-the-dac-it-s-not-personal).

![image](https://user-images.githubusercontent.com/344748/57094371-68e6b380-6cde-11e9-8ef6-91aa86d63dad.png)

Strangely, it looks okay in private mode:

![image](https://user-images.githubusercontent.com/344748/57094449-8e73bd00-6cde-11e9-9833-2f02a7c861b6.png)

**Comment by quochuy** [comment]
I managed to reproduce this consistently, it happens if you land on any page for the first time. The page loads without the ad banner and when the banner appears it widen the header block without pushing the actual content block down.

Subsequent navigation to another page fixes it as the banner is already rendered but if you reload the page again the issue will occur again.

**Comment by quochuy** [comment]
Here is a fix proposal which needs help with testing as I can't get ads to work on my dev environment:
https://github.com/steemit/condenser/pull/3377

**Comment by quochuy** [comment]
@roadscape has this been deployed to steemit.com ?
The issue is still happening.

**Comment by roadscape** [comment]
@quochuy it has been deployed but there seems to be a lingering issue which appears to be documented in #3385

**Comment by quochuy** [comment]
@roadscape when you have time, could you please test my fix attempt https://github.com/steemit/condenser/pull/3377 or let me know how to setup my local Condenser so that it displays ads.

**Comment by JonathanPorta** [comment]
@quochuy I used your suggestion as a partial fix in https://github.com/steemit/condenser/pull/3404.

To get ads to show up locally set these environment variables:
```
GPT_ENABLED=true
GOOGLE_AD_CLIENT=ca-pub-9368037717385698
GOOGLE_AD_ENABLED=true 
```
