### ISSUE TITLE
Text enhancement to non-posting key dialogue box

### ISSUE THREAD

**Issue by thecryptodrive** [steemit/condenser#3290]
`View my Positing Key at Steemit Wallet` doesn't sound 100% right, maybe `View my Posting Key in the Steemit Wallet` or `View my Posting Key at steemitwallet.com` will sound a bit better.

![image](https://user-images.githubusercontent.com/22358264/56775847-21af7d00-681d-11e9-89a8-3c03b758e89b.png)

**Comment by quochuy** [comment]
Suggestion: `Open my Steemit Wallet to access and view my posting key`
