### ISSUE TITLE
Misleading FAQ - What can users post to Steemit?

### ISSUE THREAD

**Issue by hakonhall** [steemit/condenser#3294]
According to the FAQ: "Steem is an open platform meant to host and welcome any legal content. Users can post anything they want, ...".

"legal content" may easily be confused with a reference to the laws of the country. Instead, the Terms of Service is a better description of the limitations on content. To my knowledge the following users were filtered based on ToS violations, not for having posted unlawful content, and so the distinction is material:

https://github.com/steemit/condenser/commit/5fe2aa84689b61855cc89b67ca7330bbca9f9ddb
https://github.com/steemit/condenser/commit/7bdee0d3a3a221c977df7bac66a7ace12106a0f2
https://github.com/steemit/condenser/commit/4d40cf0c08cd5a59255557b0f73d84bef4dc2b99

I suggest clarifying the answer in the FAQ.

**Comment by Smittyvb** [comment]
The ToS is a legal contract. Violating it is illegal. Thus that content was indeed posted illegally.

**Comment by hakonhall** [comment]
I am no lawyer, but whether violating the terms of a contract can be deemed "illegal" seems to be debatable, e.g. https://www.quora.com/Is-it-illegal-to-violate-a-companys-terms-and-conditions.But my point was rather that the common use of the phrase "illegal content" is often understood as illegal by the laws of the country, and thus the FAQ answer is misleading and confusing. At minimum, add a link to the ToS?

People come to this part of the FAQ because they are genuinely interested knowing more about where you stand on the scale of freedom of speech vs censorship/policing of content. Some may have been banned (or know of people that have been banned) and want to know if they can feel safe here. Others want to get away from toxic debates and want to know if you remove negative contents.

All social media platforms welcome legal content by their own standard, but where does Steemit stand? I think that's what people are looking for in the FAQ answer.

**Comment by Smittyvb** [comment]
Good point, this will be closed by #3300.

**Comment by hakonhall** [comment]
Great 👍
