### ISSUE TITLE
Unable to embed dtube video on steemit ("Unsupported")                         

### ISSUE THREAD

**Issue by blind-spot1** [steemit/condenser#3304]
Uploaded and copied link from dtube. Tried to embed video on steemit on post and tried it on comment later, but this is what shows up: 
``(Unsupported https://emb.d.tube/#!/blind-spot/x6sdu8j0)``

Used brave browser, tried with chrome with no result. 

![image](https://user-images.githubusercontent.com/50171871/57017522-dbdd2500-6c1f-11e9-8a55-65bf1eef770a.png)

**Comment by tibfox** [comment]
It seams to be an issue with your username. I tried some other creators (dtube.forum for example) with special characters in their name and it doesn't work as well. All other videos can get embedded.
