### ISSUE TITLE
Pin post in steemit

### ISSUE THREAD

**Issue by clixmoney** [steemit/condenser#3312]
I've been on steem blockchain for almost two years and sometimes I write really important post about the community or I just like to promote something on my page for a while. 

I think it will be good to add the option of pinning post in steemit. 

We can pin for example important announcements or our introduction post, or anything important to us. 

We can also unpin like in other social media and pin an other if we want. 

Regards.

**Comment by roadscape** [comment]
Hi, thanks for the suggestion. Pinned posts are a planned part of the communities feature; draft specifications are here: https://github.com/steemit/hivemind/blob/spec-update/docs/communities.md
