### ISSUE TITLE
Reputation inconsistency across blog page

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/condenser#3316]
Same user, different rep values.
Goes to 25 (visual only) after flag. 
(BTW: Due to my rep being lower than author's, I'm not affecting his rep anyway.)
![reputation_inconsistency](https://user-images.githubusercontent.com/6341057/57214166-55db2880-6fe9-11e9-8996-3b8645566339.png)

**Comment by jredbeard** [comment]
Thanks, this was due to `reputation_api` being mistakingly excluded from the default config in steemd `master` which is currently running in production with `MIRA`. It will be resolved soon: https://github.com/steemit/steem/pull/3290/files
