### ISSUE TITLE
Excessive CPU usage

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#3338]
Noticed increased CPU usage in the last 7 days or so, server-side. Let's profile and see where CPU is spending the most time. There is likely lots of room for improvement in general, but it would be nice if we could pinpoint the specific change.

**Comment by roadscape** [comment]
Reported to be a scalyr bug.

**Comment by jredbeard** [comment]
Confirmed that this was an issue with the most recent version of scalyr agent.

The scalyr team is troubleshooting the issue - for now, we have moved back to an older version of scalyr agent for condenser and wallet in production. All other production services will switch back on next deployment (no other applications seem to be effected by this bug, but this will avoid them being impacted). Closing this issue as it is unlikely that we'll upgrade to the latest version until it is necessary.
