### ISSUE TITLE
non-existing posts do not result in 404

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#3340]
This seems to be new behavior:

https://steemit.com/dontexist/@abc/this-post-doesnt-exist
![image](https://user-images.githubusercontent.com/5168676/57637751-c944e300-7571-11e9-8af7-f06a147c5feb.png)

**Comment by economicstudio** [comment]
this happens only when you have a main tag(category). without it, 404 is shown correctly.
e.g., https://steemit.com/@abc/this-post-doesnt-exist

hope this helps to figure out the bug.

**Comment by economicstudio** [comment]
@roadscape finally, done by me :)
