### ISSUE TITLE
The interface needs improvement.

### ISSUE THREAD

**Issue by ayogom** [steemit/condenser#3343]
An interface problem has occurred with the recent addition of a down-voting icon.

![image](https://user-images.githubusercontent.com/40152930/57828219-b4708580-77e5-11e9-97d0-bbb77ffe9ab9.png)

Since the picture is expressed in Korean, you may not be able to read it.
The 43 Voting next the re-steem icon. However, it cannot be used because there is an overlap between 43 voting ▼ and the re-steem icon.

So I think this should be an improvement.

This issue is mentioned in the post below.
https://steemit.com/kr/@dmsqlc0303/q-and-a#@naha/re-dmsqlc0303-q-and-a-20190516t031338132z

**Comment by roadscape** [comment]
Resolved in https://github.com/steemit/condenser/issues/3346
