### ISSUE TITLE
style error

### ISSUE THREAD

**Issue by economicstudio** [steemit/condenser#3351]
`yarn run fmt` says these two files need to be reformatted.

- jspdf.min.js
- HtmlReady.js

**Comment by roadscape** [comment]
Reason for closed PR #3352:

> Hi @economicstudio, we should avoid changing jspdf.min.js since it's vendored. It should ideally be excluded from prettier. And the HtmlReady change is minor enough that we can ignore it until next time it's modified.

**Comment by economicstudio** [comment]
@economicstudio Thanks! In that case, I think it should be properly handled by `.prettierignore` done by #3361
