### ISSUE TITLE
allow users to moderate their posts

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#3360]
To combat spam and harassment, we should place extra weight on downvotes placed on comments by the OP. These posts should not be hidden entirely; rather, they should be moved to the bottom of the post ("grayed out"), or hidden behind the "low value" gate.

For transparency, we could indicate that the author has chosen to hide (or "gray out") some posts. This behavior could potentially be an option in each account's `json_metadata` but for now the simplest solution would suffice.

**Comment by wehmoen** [comment]
I second this!
