### ISSUE TITLE
Invalid Date on Chrome Mobile iPhone

### ISSUE THREAD

**Issue by DoctorLai** [steemit/condenser#3367]
![image](https://user-images.githubusercontent.com/1764434/58131913-d455de00-7c17-11e9-9bbc-7ee0436886d3.png)

**Comment by roadscape** [comment]
Thanks for the report! Proposed fix: https://github.com/steemit/condenser/pull/3368

**Comment by DoctorLai** [comment]
Hello, but I am using Chrome browser - not firefox as you commented in your fix. Are you sure, this also fixes this?
