### ISSUE TITLE
"delete" is not shown after deleting child comment.

### ISSUE THREAD

**Issue by economicstudio** [steemit/condenser#3386]
### How to reproduce

- Write nested comments as follows:

![](https://user-images.githubusercontent.com/38183982/58593401-b06f4980-8262-11e9-87c3-5a260e4239b3.png)

- Delete the child comment **and refresh**

![](https://user-images.githubusercontent.com/38183982/58593477-de548e00-8262-11e9-9e70-f585fc85f8ad.png)

- You can't see "delete" anymore no matter how many times you refresh. (Of course, there was no vote or child).

### Cause

![](https://user-images.githubusercontent.com/38183982/58593535-0a700f00-8263-11e9-9b79-df45fb8e2ab6.png)

Even after deleted, steemd says that `children = 1`

I deleted that comment by using API, but this is reproducible. I've tested twice.

Seems Hivemind problem, since api.steemit.com returned `children = 0`

**Comment by quochuy** [comment]
@roadscape is this another Hivemind issue?

**Comment by quochuy** [comment]
@economicstudio maybe raise this in https://github.com/steemit/hivemind/issues ?

**Comment by roadscape** [comment]
Definitely seems to be a hivemind bug, thanks all.
