### ISSUE TITLE
Suggestion: Allow authors to pin comments

### ISSUE THREAD

**Issue by wehmoen** [steemit/condenser#3388]
It would be cool if authors could pin one or more comments to the top of the comment tree to highlight important or well written feedback above the normal comment sorting.

From a tech pov this could work by using the root posts json_metadata to store author and permlink of the pinned comment/s. Only direct replies to the root comment should be allowed to pin. Replies to replies would most likely lack some context for readers. Any thoughts on this?

**Comment by roadscape** [comment]
Potentially related to https://github.com/steemit/condenser/issues/3360

**Comment by wehmoen** [comment]
Closing in regards of #3360
