### ISSUE TITLE
Your transaction failed to process (2 weeks with this error)

### ISSUE THREAD

**Issue by marjuanm** [steemit/condenser#3419]
Hello, greetings from Mexico:

  I have a recent blog on steemit (https://steemit.com/@marjuanm), I have already posted some posts, made comments, voted to other users, etc and in general I have not had major problems with steemit. However for almost two weeks I can not do anything in steemit, every time I try I get the error message:

_Your transaction failed to process
Why? You've run out of Resource Credits
Actions such as posting and voting use computing resources, placing a real cost on the community members who run the Steem blockchain for everyone.

To keep things free, Steem intelligently allocates Resource Credits to each user based on their Steem Power holdings, which can be used to submit a limited number of feeless transactions. When a user runs low on Resource Credits, they will either need to wait for them to recharge, or purchase additional Steem Power. This system prioritizes actions by good community members while limiting spam.

To keep interacting on Steemit:

Buy and hold more Steem Power
Wait until your Resource Credits recharge
Wait until the network usage decreases
Buy Steem Power_

  Previously this message prevented me from posting in steemit for 12 hours, then changed to 4 days and now I have almost two weeks without being able to use it, I can not post, comment or vote, what happens ?, please correct this problem, thanks, greetings.

**Comment by roadscape** [comment]
As far as I can tell, the `@marjuanm` has more than enough resource credits to perform all the basic actions. Could you confirm that you're logged into the correct account and try to vote on a post?

If you get the error again please post a screenshot with the message. Thanks!

**Comment by marjuanm** [comment]
Thank you very much for your reply. Attach screens of the presented problem:

Logged with my Steemit account:
![steemit01](https://user-images.githubusercontent.com/30614131/60463105-b5803980-9c10-11e9-9441-fb850d55fb34.png)

I want to vote for a publication (from another Steemit participant)
![steemit02](https://user-images.githubusercontent.com/30614131/60463169-e6606e80-9c10-11e9-96e0-889ed2b5d2ce.png)

I press the green button to cast my vote and I get this message
![steemit03](https://user-images.githubusercontent.com/30614131/60463256-1871d080-9c11-11e9-890f-c9051c2b2f32.png)

When I close the dialogue I get this additional message
![steemit04](https://user-images.githubusercontent.com/30614131/60463319-45be7e80-9c11-11e9-8108-cd995a2cf8ea.png)

The same thing happens if I want to comment on Steemit or create a new post.
Thank you for your support, I am waiting for a solution, thank you very much again.

**Comment by marjuanm** [comment]
Hello, status ?, already delete all the browser cache and everything remains the same, the same error message.

**Comment by roadscape** [comment]
Possibly related to https://github.com/steemit/steem/issues/3351

Will reach out to confirm.

**Comment by marjuanm** [comment]
Thanks, greetings.
----------------------------------------------
Mi blog http://marjuanm.blogspot.mx

**Comment by roadscape** [comment]
Hi @marjuanm, it does indeed sound like https://github.com/steemit/steem/issues/3351 is the cause of this bug. Unfortunately you may have to wait until the backend fix is deployed, which could be another 2 weeks or so.

However, in the meantime, I've delegated an additional 20 SP to your account. This may help you bypass the error for now.

**Comment by marjuanm** [comment]
*I've delegated an additional 20 SP to your account. This may help you
bypass the error for now. *
Thanks, but have not yet appeared in the account:
[image: image.png]

*Unfortunately you may have to wait until the backend fix is deployed,
which could be another 2 weeks or so.*
It's okay, I can wait 😊

I will try if I can already write an article (I have one pending that I
want to publish in my account), but it will be until today in the afternoon
because I do not have it with me at this moment and I will inform you.
Thanks again.



----------------------------------------------
Mi blog http://marjuanm.blogspot.mx

**Comment by marjuanm** [comment]
[image: image.png]
Working!!!!!, post created, thanks very much, then exists a bug on steemit?


----------------------------------------------
Mi blog http://marjuanm.blogspot.mx


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by marjuanm** [comment]
Hi:

  I have'nt this problem again and the related problem link has already been closed, please mark this post as solved, thanks.

**Comment by marjuanm** [comment]
thanks, greetings.
----------------------------------------------
Mi blog http://marjuanm.blogspot.mx
