### ISSUE TITLE
Comments links jump to wrong URL

### ISSUE THREAD

**Issue by Transisto** [steemit/condenser#3420]
When going to this URL https://steemit.com/@crystalliu/comments

And clicking the post title or date it sends me to https://steemit.com/pu02ic , a broken link.
If I open in new page it does load https://steemit.com/crystal/@crystalliu/pu02ic

![image](https://user-images.githubusercontent.com/388716/60523595-fc296e80-9cb8-11e9-810d-6244944f09f5.png)

Tested with chrome, firefox, opera.

**Comment by gryter** [comment]
After testing it out, this is the same issue as #3424 

The link doesn't work because the category is unspecified. 

![image](https://user-images.githubusercontent.com/31012685/60751336-74c25080-9f81-11e9-956a-a3e15e1e800c.png)

**Comment by roadscape** [comment]
Closing in favor of #3424. Thanks for the reports!
