### ISSUE TITLE
Dark Theme: REsteem confirmation text does not show up

### ISSUE THREAD

**Issue by lukestokes** [steemit/condenser#3422]
![image](https://user-images.githubusercontent.com/344748/60604180-19c40a00-9d85-11e9-8318-eba93b5eed68.png)
![image](https://user-images.githubusercontent.com/344748/60604193-1f215480-9d85-11e9-9f70-938a8498be31.png)

Might be a quick CSS fix to change "background-color" to just "background" on `.theme-dark`

**Comment by gryter** [comment]
The issue is in the` .reveal {background-color: #fefefe;} `parameter, not the above.

**Fix:**
Remove:
` .reveal {background-color: #fefefe;} `

Add these two classes: 

```
    .theme-dark .reveal {
      background-color: #000;
    }
```

```
    .theme-light .reveal {
      background-color: #fff;
    }
```
