### ISSUE TITLE
Blank category param link error

### ISSUE THREAD

**Issue by gryter** [steemit/condenser#3424]
Where a 3rd party app fails to fill in the "category" parameter when posting, the category remains blank and condenser is unable to create a working link. 

Notice the category is blank:
![image](https://user-images.githubusercontent.com/31012685/60745692-72440480-9f49-11e9-8419-256c2af18441.png)

![image](https://user-images.githubusercontent.com/31012685/60745484-6c99ef00-9f48-11e9-8c5d-7ce152202318.png)
(screenshot above was provided by acostaeladio)

Condenser link in blog view links to https://steemit.com/@acostaeladio/segundo-aniversario-en-steemit-breve-relato
Due to lack of derived category, URL parses to https://steemit.com/segundo-aniversario-en-steemit-breve-relato 
Manually entering the URL linked from the blog view or correcting the URL brings up the post.

**Comment by acostaeladio** [comment]
It is a good opportunity to investigate why this error exists. Celebrating my two years at Steemit and Palnet's platform gives me this surprise

**Comment by jredbeard** [comment]
This is likely caused by a bug in hivemind and how it handles blank categories: https://github.com/steemit/hivemind/issues/205

cc @roadscape to confirm

**Comment by roadscape** [comment]
https://github.com/steemit/hivemind/issues/205 would effectively mitigate this condition, assuming there's always at least one tag present in `json_metadata`.

**Comment by jredbeard** [comment]
Resolved in https://github.com/steemit/hivemind/pull/217
