### ISSUE TITLE
get_state modifications

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#3453]
~Identify how to structure new APIs~

1. ~Simple way to use `condenser_api2` namespace?~
2. ~Otherwise, rename all methods to e.g. `get_state2`?~
3. ~Can we stop using `call` format? Otherwise, entirely `call2` format?~

`callBridge` approach: https://github.com/steemit/condenser/commit/8d2d8cdb871cbe33c12aed91c224a42c0c34c929

---

Switch condenser to use alternate `get_state`

1. all current get_state calls to use `bridge.get_state` (done in https://github.com/steemit/condenser/commit/8d2d8cdb871cbe33c12aed91c224a42c0c34c929).
2. `bridge.get_state` needs an `observer` param for current logged in account
3. ~condenser to stop calling `get_state` on *every* page~
   1. ~e.g. `@user/followers` (as opposed to @user/blog, @user/comments)~
   2. ~e.g. do not call `get_state` on `/submit.html`~
4. ~remove reliance on `get_state`  header: `props` and `feed_price` keys~
   1. ~Only keys which are still used: `feed_price` and `steem_price`?~

**Comment by roadscape** [comment]
Work is progressing on [bridge-api](https://github.com/steemit/condenser/tree/bridge-api) branch.

Remaining tasks:
 - do we switch to calling `getState` explicitly as needed, or do we keep the logic in [`fetchState`](https://github.com/steemit/condenser/blob/bridge-api/src/app/redux/FetchDataSaga.js#L35) and whitelist specific paths?
 - evaluate effort required to remove reliance on `feed_price` and `steem_price` props in state response

**Comment by gl2748** [comment]
- I think we whitelist certain paths in  the `fetchState` Saga at `FetchDataSaga.js` I've made a branch today to start doing this.
- Are there alternative endpoints that can give us `feed_price` and `steem_price` directly, or at a lesser cost than deriving them from `get_state`, looks like you can get latest feed price from user data for example, `getLatestFeedPrice()` in `UserSaga.js`

**Comment by gl2748** [comment]
Regarding:
> need the option for bridge.getState to take an observer parameter (currently-logged-in account name)
As i understand it, we add an (optional?) param to this call:
https://github.com/steemit/condenser/commit/8d2d8cdb871cbe33c12aed91c224a42c0c34c929#diff-602fe9366b82a2d613cfd6d33a7a14b2R6
and pass it through the the call to the bridge endpoint here:
https://github.com/steemit/condenser/commit/8d2d8cdb871cbe33c12aed91c224a42c0c34c929#diff-602fe9366b82a2d613cfd6d33a7a14b2R24

**Comment by roadscape** [comment]
> As i understand it, we add an (optional?) param to this call:
https://github.com/steemit/condenser/commit/8d2d8cdb871cbe33c12aed91c224a42c0c34c929#diff-602fe9366b82a2d613cfd6d33a7a14b2R6
and pass it through the the call to the bridge endpoint here:
https://github.com/steemit/condenser/commit/8d2d8cdb871cbe33c12aed91c224a42c0c34c929#diff-602fe9366b82a2d613cfd6d33a7a14b2R24

Yes, the challenge will be to catch all uses of the function and feed proper state

**Comment by roadscape** [comment]
> I think we whitelist certain paths in  the `fetchState` Saga at `FetchDataSaga.js` I've made a branch today to start doing this.

Sounds good.

> Are there alternative endpoints that can give us `feed_price` and `steem_price` directly, or at a lesser cost than deriving them from `get_state`, looks like you can get latest feed price from user data for example, `getLatestFeedPrice()` in `UserSaga.js`

I was mistaken -- the two props are `feed_price` and *`sbd_print_rate`*. `feed_price` may be easier to remove as there is a provision for using `getLatestFeedPrice()` when available anyway. However it looks like `sbd_print_rate` is used in Voting calculations. Ideally `sbd_print_rate` would be lazy-loaded via `get_dynamic_global_properties` only when needed. Alternatively, we could leave this field in place and plan to move the reliant logic into the backend later.

**Comment by roadscape** [comment]
Reference for proposed API restrictions: https://github.com/steemit/hivemind/commit/71e8893fa62ca88a5b8e81f8febaab9d29be1d10

**Comment by gl2748** [comment]
Looking at replacing `feed_price` with `getLatestFeedPrice()` now. I'll also briefly look at `get_dynamic_global_properties` as a `sbd_print_rate` replacement.

After that I will move onto adding the optional `observer` param to getStateAsync.

**Comment by roadscape** [comment]
Remainder is covered by https://github.com/steemit/condenser/issues/3462
