### ISSUE TITLE
Cannot post a blog or comment

### ISSUE THREAD

**Issue by KavinduZoysa** [steemit/condenser#3466]
When I am trying to post a blog or add a comment I am getting below error always.
![Screenshot_20190816-174858](https://user-images.githubusercontent.com/28332708/63173662-f5369f80-c05d-11e9-8b3f-b4f991400eb6.png)
Could you please help me to solve this issue.

Thank you.

**Comment by TimCliff** [comment]
there is some info on that here:
https://steemit.com/faq.html#How_do_Resource_Credits_work_on_the_Steem_blockchain
