### ISSUE TITLE
When less than 5 comments only display 1 ad in comments section

### ISSUE THREAD

**Issue by jredbeard** [steemit/condenser#3480]
Current behavior with only one comment:

![image (3)](https://user-images.githubusercontent.com/23157604/63967655-e4c5f200-ca6b-11e9-9541-2286310a1aa6.png)

**Comment by jredbeard** [comment]
Looking into this a little more closely, I believe the bottom ad is the 'bottom footer ad' and not a comment ad. Since this is the case, the behavior should be '*don't display an ad in the comments at all if less than 5 comments exist*'. Further, '*don't display above the comments ad if there are zero comments*'.

**Comment by quochuy** [comment]
@jredbeard all of the ads below the post are tagged with the css class `Post_footer__ad`.
There is one before the comment block and one after the comment block.
Then there is one ad inserted every 5 ads.

My suggestion is to not display the bottom most ad if less than 5 comment exist. This means, an ad will show before the comment block: more visibility for the ad = ad impression. Also ads a visible break between the post and the comment block.

If there are zero comments, the above will take care of it as zero is less than 5 which means there will be only one ad displayed below the post (the one that displays below the comment block).
