### ISSUE TITLE
Weird links redirect issue, (at least two bugs)

### ISSUE THREAD

**Issue by Transisto** [steemit/condenser#3481]
click here
![image](https://user-images.githubusercontent.com/388716/63971106-c3690400-ca73-11e9-9eca-88192a989d88.png)

end up there https://steemit.com/steemit/@gmichelbkk/curation-rewards-explained-simply

![image](https://user-images.githubusercontent.com/388716/63971156-dda2e200-ca73-11e9-9dca-4a4da688fe14.png)

remove the tag

![image](https://user-images.githubusercontent.com/388716/63971213-fca17400-ca73-11e9-8271-361a7c4e9dee.png)

end up here 

![image](https://user-images.githubusercontent.com/388716/63971225-088d3600-ca74-11e9-9ea0-f8a290ccb37c.png)
![image](https://user-images.githubusercontent.com/388716/63971232-0d51ea00-ca74-11e9-8d82-80086dd7b6ad.png)

then find the post, click here

![image](https://user-images.githubusercontent.com/388716/63971345-42f6d300-ca74-11e9-901b-ed041f96e338.png)

Works

![image](https://user-images.githubusercontent.com/388716/63971382-543fdf80-ca74-11e9-99bc-93b84c451e17.png)

Going to link directly desn't work.

![image](https://user-images.githubusercontent.com/388716/63971426-6752af80-ca74-11e9-8239-57c8eab1cee9.png)

**Comment by quochuy** [comment]
@Transisto Very odd issue but I think I know why.

**Comment by quetzalcoatl** [comment]
I hit that bug long time ago and reported it on steemd "help thread": https://steemit.com/steemd/@roadscape/steemd-com-help-and-feedback#@ookamisuuhaisha/pvoldz however after short investigation it was discarded, as it's a transient issue - after some time all links seem to work just fine, and those links I provided there don't have any issues now.

However, I can provide any number of fresh links with this issue, for example, today this one doesn't work:
https://steemit.com/dtube/@crystalliu/5qgh63qbsd7 - broken
while this does:
https://steemit.com/@crystalliu/5qgh63qbsd7 - works

Replacing steemit with steemd:
https://steemit.com/dtube/@crystalliu/5qgh63qbsd7 - broken
https://steemit.com/@crystalliu/5qgh63qbsd7 - broken

Also, some apps like steempeak have no issues opening either of those, strange.

**Comment by quetzalcoatl** [comment]
I suppose #3464 is about the same thing as well

**Comment by quetzalcoatl** [comment]
Oh, it seems I also registered that issue here as well #3454

**Comment by quochuy** [comment]
Thanks @quetzalcoatl will check them out

**Comment by quochuy** [comment]
@quetzalcoatl this one is tricky to debug and I’m suspecting a Hivemind or Steemd issue triggered by something in the post. @roadscape?
