### ISSUE TITLE
Show Post beneficiaries on Condenser UI

### ISSUE THREAD

**Issue by thecryptodrive** [steemit/condenser#3498]
This would be good to do to develop a culture of setting a beneficiary to @null, saves users from having to look on Steemd or take the author's word for it that they have set a specific beneficiary.

**Comment by roadscape** [comment]
The beneficiaries PR has been merged

**Comment by thecryptodrive** [comment]
Nice, good to hear!

**Comment by thecryptodrive** [comment]
I can see in the advanced settings that you can now set beneficiaries, however I can't see on the condenser frontend from a reader's perspective where to identify the beneficiaries set on a particular post.

**Comment by jredbeard** [comment]
Just click on the payout amount, you get a dropdown and is listed there (same as on busy and steempeak I believe) @thecryptodrive

**Comment by thecryptodrive** [comment]
Ok perfect I see it now:

![image](https://user-images.githubusercontent.com/22358264/65556802-0dff7280-df85-11e9-961b-a64906c9ee72.png)
