### ISSUE TITLE
community explorer

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#3507]
This page lists all communities, ordered by rank. The API is paginated and this interface should implement infinite scrolling to load more results. The response is a standard list of community objects. Only basic stats need to be shown. Each item should have a subscribe button which properly reflects the current user's subscribe state. (Details forthcoming, API in progress)

Notes:
 - subscribed communities will be returned first (this page doubles as sub management)
 - investigate cheap text search/filter

**Comment by roadscape** [comment]
#3542 merged

**Comment by gadrian78** [comment]
You mention this @roadscape:

> This page lists all communities, *ordered by rank*

Does the rank include:
* number of subscribers
* number of posts
* number of *new* subscribers (last 30 days?)
* number of *new* posts

Will there be different ordering options (like rank and individual criteria like the ones listed above)?

Communities are only in open beta for a short while and there are already quite a few of them. Ordering, filtering and searching will be important, and I'm glad you included a search/filter among the priorities for this issue.

**Comment by roadscape** [comment]
@gadrian78 rank includes pending payouts, subscribers, and posts. There will be more sorting/filtering options added in the future.
