### ISSUE TITLE
DTube video in comments autoplays

### ISSUE THREAD

**Issue by pfunks** [steemit/condenser#3535]
Firefox 69.0.1 (latest)

I visited a post from an account's blog page on steemit.com and a DTube embedded video, hosted on YouTube, posted in the comments played automatically.

The post, which going to directly doesn't seem to trigger autoplay: https://steemit.com/ieo/@dtube/last-week-to-claim-your-dtube-account-for-free

The comment: 
https://steemit.com/ieo/@maciejficek/pwu1nt
https://steemd.com/ieo/@maciejficek/pwu1nt

How to reproduce:
Visit @dtube's blog page at https://steemit.com/@dtube and click the "Last week to claim your DTube account for free !" post.

Edit: Though the link is to DTube, it appears the DTube post video is hosted by YouTube.

**Comment by roadscape** [comment]
Is this still an issue?

**Comment by pfunks** [comment]
Seems to be fixed
