### ISSUE TITLE
roles editor adjustments

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#3578]
- [x] the existing form should be wrapped in a dialog box:
    ![image](https://user-images.githubusercontent.com/5168676/67234397-ae24ac00-f40a-11e9-879d-6dd8f1075cf3.png)
    When a table row is clicked, the dialog will be shown and username filled out (and read-only). There needs to be a button to "Add User" which brings up the dialog box with username blank and editable.
- [x] the roles editor needs to be aware of the current user's role. this can be accessed via `get_community_context(name, account)`. users with a role same to, or higher, than viewer cannot be edited. otherwise, the user can set user roles to anything below their own.

**Comment by gl2748** [comment]
this issue mentions using `get_community_context(name, account)` to get current user’s role but it would actually be better to call `get_community(name, observer`) — because this will return full community metadata plus observer role

**Comment by roadscape** [comment]
#3579 merged
