### ISSUE TITLE
search/filter communities

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#3651]
As a user, I want to be able to quickly find communities relevant to my interests. The 'Explore Communities' page should accept a search term and offer a language filter.

Additionally, it would be good to offer a sort option.

Blocked: needs an API endpoint

**Comment by gl2748** [comment]
WIP branch is:
https://github.com/steemit/condenser/tree/3651-search-communities

Awaiting API endpoint. 

@roadscape another option would be to just filter the existing list of Communities that's in app state... on the front end...

**Comment by roadscape** [comment]
API endpoint is currently available on dev. The call is the same (`list_communities`) and now accepts two additional params: `query` (plaintext string) and `sort` (can be `rank`, `subs`, or `new`).

**Comment by roadscape** [comment]
Works great 👍  Only usability issue is that text search seems to require `<Enter>` key to submit, which may be an issue for mobile. Perhaps we need an 'Apply' button?

**Comment by roadscape** [comment]
https://github.com/steemit/condenser/pull/3698 merged
