### ISSUE TITLE
Lack of error when attempting posting to blog through set community with hive tag

### ISSUE THREAD

**Issue by gryter** [steemit/condenser#3673]
Posting to blog from the specific community's interface while manually using that community's tag as category causes the submit spinner to continuously go without producing any error on the frontend. Replicated during different times. Attempted from the hive-104689 community interface, posting to blog, manually inputting the hive-104689 tag as first tag.

![image](https://user-images.githubusercontent.com/31012685/72482822-fdda0000-37cc-11ea-90f2-dad304a27d95.png)

**Comment by roadscape** [comment]
Fixed in https://github.com/steemit/condenser/pull/3682
