### ISSUE TITLE
misc usability issues

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#3686]
Using this issue to track relatively minor usability issues. More items to be added shortly.

- [ ] cover image upload [once moved back to condenser] should show recommended size. [ref1](https://beta.steemit.com/hive-144703/@gadrian/new-user-feedback-my-own-observations) [ref2](https://steemit.com/steemit/@bruce-pendragon/okay-so-does-this-site-even-work)

**Comment by pfunks** [comment]
I don't know if they count as minor or not, but a couple that bug me:

-Notifications remain even after sending the "setLastRead" custom JSON to the blockchain.

-Clicking on the Steemit logo in the upper left takes you to the trending page and not the personal feed. There is no convenient link I can see to bring me to steemit.com/@user/feed either.

**Comment by roadscape** [comment]
> Notifications remain even after sending the "setLastRead" custom JSON to the blockchain.

@pfunks does a refresh solve this? There may be a 10s delay on the backend (which we can mitigate w/ optimistic updated on frontend), but this feature should be working.

> Clicking on the Steemit logo in the upper left takes you to the trending page and not the personal feed. There is no convenient link I can see to bring me to steemit.com/@user/feed either.

Filed at https://github.com/steemit/condenser/issues/3713

**Comment by pfunks** [comment]
Notification clearing appears to work now.

**Comment by pfunks** [comment]
Nevermind that, it didn't quite work for me until I jumped through some hoops. I tried logging in in a private browsing window and the notifications were cleared.  I tried logging out and back in in my main browser window and the notifications remained. I had to log out, close the browser entirely, open it again and log in for the notification icon to clear. While that seems to fix it, it would be a smoother UX if notifications would clear without logging out and back in again even if that is only a one time deal.

Firefox 73.0.1

**Comment by pfunks** [comment]
Nevermind again, the notification indicator has returned with 504 notifications.

**Comment by roadscape** [comment]
@pfunks - notification status is saved server-side; the unread count will not be reset until "Mark as read" is clicked. When clicked, your account will issue a custom json op containing a payload such as `["setLastRead",{"date":"2020-02-27T14:01:08"}]`. It may take up to 6-9s for hivemind to read this operation and reset your unread count.

This is the intended behavior. Could you provide any more insight which would help narrow down where this process is failing?
