### ISSUE TITLE
URL does not work on beta site

### ISSUE THREAD

**Issue by themarkymark-steem** [steemit/condenser#3691]
https://beta.steemit.com/c/@don.quijote/posts-votados-por-el-equipo-don-quijote-07-03-2019-23-34-08-03-2019-23-34

This URL throws a 404 and fails to load, but on Steemit.com it loads fine.

**Comment by roadscape** [comment]
Current route definition: `'<tag>', '([\\w\\W\\d-]{2,32})'`

Need to evaluate if we should allow 1-char tags

**Comment by roadscape** [comment]
https://github.com/steemit/condenser/pull/3694 merged
