### ISSUE TITLE
UX: access feed

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#3713]
> Clicking on the Steemit logo in the upper left takes you to the trending page and not the personal feed. There is no convenient link I can see to bring me to steemit.com/@user/feed either.

**Comment by roadscape** [comment]
It's possible https://github.com/steemit/condenser/pull/3719 addresses this issue. Unclear if user was referring to mobile view.

**Comment by pfunks** [comment]
Firefox 73.0.1 on desktop

**Comment by roadscape** [comment]
Feed in terms of followed users vs. followed communities is a bit ambiguous... open to suggestions

**Comment by gl2748** [comment]
I think for the most part #3719 addresses this.

**Comment by pfunks** [comment]
I see the dilemma. "Followed feed" and "Community feed"? The nomenclature in condenser for communities seems to be subscribing to communities vs. following them.

**Comment by roadscape** [comment]
We fixed (#3719) a bug with being able to access 'Friend Feed' on mobile. It's unclear if many or most of the reports were from mobile. As for the issue of changed terminology, it's best to give it some time to see it users can adjust. We don't have to end the discussion but for the purpose of accounting for technical/functional issues, I'm closing this issue.
