### ISSUE TITLE
UX: mobile tag/community nav

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#3714]
> the default setting shows "My communities", aka posts from all communities that I follow. However, after I've clicked on any of the specific communities that I Subscribe to, or to 'All posts" which obv gives me all posts on Steemit, the option to go back to "My communities" dissapear. You may want to add that back as one of the top two default options

![image](https://user-images.githubusercontent.com/5168676/74965400-cae1e800-53da-11ea-9b93-96be130e6424.png)

**Comment by gl2748** [comment]
Inject 'My Friends' into menu.

**Comment by roadscape** [comment]
https://github.com/steemit/condenser/pull/3719 merged
