### ISSUE TITLE
UX: Cannot close activity log modal on mobile.

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#3723]
When viewing the activity log for a community, the `Reveal` component seems to be missing a close button, making it very difficult to dismiss on mobile devices.

<img width="403" alt="Screen Shot 2020-02-21 at 8 13 29 AM" src="https://user-images.githubusercontent.com/3374538/75037426-24e9b880-5482-11ea-948b-12799a97b70d.png">

**Comment by roadscape** [comment]
https://github.com/steemit/condenser/pull/3731 merged
