### ISSUE TITLE
Rename condenser to concensor

### ISSUE THREAD

**Issue by pfunks** [steemit/condenser#3761]
I named condenser originally, but twinner came up with a better one.

**Comment by pfunks** [comment]
You guys are completely insane
https://github.com/steemit/condenser/commits/bridge-api-dev-test

**Comment by IntinteDAO** [comment]
@pfunks 
https://github.com/openhive-network/hive/issues/5

?? Both networks are broken now

**Comment by jiangyy0824** [comment]
Thanks for your suggestion.

**Comment by pfunks** [comment]
You're welcome. When will it be implemented?
