### ISSUE TITLE
steemit.com doesn't show newly created posts

### ISSUE THREAD

**Issue by steemchiller** [steemit/condenser#3786]
Looks like the RPC nodes that are being used on the site got stuck.
Calling `api.steemit.com` externally returns the data correctly.

Last visible post is 6 hours old:
https://steemit.com/created

**Comment by themarkymark-steem** [comment]
I was looking forward to checking out day 33 of Steem.  Please fix it soon.

**Comment by steemchiller** [comment]
Fixed.
