### ISSUE TITLE
My posts and comments are censored by Steemit

### ISSUE THREAD

**Issue by VIM-Arcange** [steemit/condenser#3797]
![image](https://user-images.githubusercontent.com/21260036/84335276-ceb99600-ab94-11ea-85bb-ccde770fa3e1.png)

**Comment by Doctor-Victor-Frankenstein** [comment]
Your account was blocked due to TOS violation.

I would suggest checking sections 12, 13, 22, and 24 of the TOS.

**Comment by Doctor-Victor-Frankenstein** [comment]
Your account has been blocked due to a violation of the terms of use.

I would suggest checking sections 12, 13, 22, and 24 of the TOS.
