### ISSUE TITLE
BUG:  GIF of 18MB can't be inserted

### ISSUE THREAD

**Issue by DoctorLai** [steemit/condenser#3897]
If you add the following to the steemit editor, it can't be inserted.

`![](https://weibomiaopai.com/static/how-to-solve-403-denied-by-acl-video-download-error.gif)
`
![image](https://github.com/steemit/condenser/assets/1764434/d326cec0-17c6-45c8-a70d-46a051143bcd)

413 Error
![image](https://github.com/steemit/condenser/assets/1764434/1b66dd2e-1b38-4f17-9133-4105f16a9251)

The HTTP 413 Content Too Large response status code indicates that the request entity is larger than limits defined by server; the server might close the connection or return a Retry-After header field. Prior to RFC 9110 the response phrase for the status was Payload Too Large .

However, in this case, I think we should simply use the user's image URL without redirection/proxy.

**Comment by melodyzxd** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by ety001** [comment]
Because of the operation requirements we can not remove the prefix `https://steemitimages.com/`.
