### ISSUE TITLE
Add a "Favorites" post storage

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#408]
Give the users a way to save their favorite posts within the site.

https://steemit.com/steemit/@royaltiffany/i-need-a-favorite-button

**Comment by cloh76** [comment]
Adding a link to my Concept and post for a Personal Favorites feature as well

https://steemit.com/steemit/@cloh76/steemit-update-suggestion-personal-favorites

**Comment by sneak** [comment]
Just vote things up, then use a block explorer to see all the posts you've upvoted. :)

**Comment by roadscape** [comment]
No immediate plans for this but I think a future "Reactions" functionality could be used for bookmarks
