### ISSUE TITLE
comment link does not show full post when followed

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#440]
The link to a comment should take the user to the full post page, with the comment highlighted/in viewport.

**Comment by aaroncox** [comment]
Are you talking about links like this?

https://steemit.com/bounties/@paxmagnus/re-pkattera-my-full-application-for-ned-s-steemit-bounty-management-forum-milestone-1-design-phase-20161005t204252537z

**Comment by roadscape** [comment]
@sneak is probably referring to cases like these: https://steemit.com/@pkattera/recent-replies

I believe this was a workaround for the "popup" post modal, since it has nested scrolling

**Comment by mcifani** [comment]
What is the last consensus on this: Implementing @sneak suggestion seems good to me. Any preference thoughts @roadscape ?

**Comment by plink01001** [comment]
Has this been addressed / can this be closed?

**Comment by plink01001** [comment]
Closing as it appears to be resolved on the live site.
