### ISSUE TITLE
command-click (or middle click) does not open new tab when clicking on usernames

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#446]
it opens a popup with "profile", and follow and mute buttons. middle-clicking should open the link target (profile page) in another tab.

**Comment by sneak** [comment]
works on /@username/feed

not on /tag/@username/postname

**Comment by relativityboy** [comment]
An example of the popup behavior on /tag/
<img width="502" alt="screen shot 2017-08-25 at 2 43 31 pm" src="https://user-images.githubusercontent.com/599528/29729990-0abb7bd4-89a4-11e7-9eed-65b6915af252.png">

I'm thinking the 'down carrot' should open the popup, but the username should be a classic link to the user.

**Comment by relativityboy** [comment]
After a conversation with the UI team, the decision was made to move the popup to the user logo, and have the username be a link (as it is in most, if not all other locations in the site)

**Comment by relativityboy** [comment]
After addl review, the popup will be on click of the down-carrot only. It'll be considered an 'expert level' feature. We'll revisit pending user feedback as we do design upgrades.

**Comment by plink01001** [comment]
Has this been addressed / can this be closed?
