### ISSUE TITLE
Make resteemed posts stand out visually in the feed

### ISSUE THREAD

**Issue by petermz** [steemit/condenser#495]
Now that Steemit has the resteem feature, my feed contains both posts by authors I follow, and posts they have resteemed. I'd like to be able to easily tell one kind of posts from the other.

Some implementation ideas:
- Apply different background to resteemed posts
- Have a "Hide resteemed posts" check box

label: enhancement

**Comment by roadscape** [comment]
Fine for now, might get updated when we refresh the design
