### ISSUE TITLE
Create a subscription that emails story snippets to users

### ISSUE THREAD

**Issue by hizzvizz** [steemit/condenser#562]
The AAAS/Science has a top notch email with over 10 compelling articles that forced me to read through the entire list.  I clicked through a couple stories and found very high quality share-worthy content.  

It would be nice if people who don't want to browse Steem, but instead want articles sent to their inbox could create a newsletter based kn high tipped, newly created, or high commented content.

**Comment by Tadasu85** [comment]
I would think that this is out of scope for steemit.com, it is however possible to access the steem blockchain (IE where all that data resides) with numerous APIs there is piston for Python interaction and Radiator for ruby on rails interaction it is my understanding that there is also a JS API but I do not know what the name of it is. There is also the possibility of using direct RPC calls if you care to design your own API routes you can read about STEEMs API on steem.io I hope this has helped you.

**Comment by roadscape** [comment]
Something like this can be implemented into a new notification service; it's not a condenser concern though.
