### ISSUE TITLE
Post Exposure : a letter to the team

### ISSUE THREAD

**Issue by tylermyler** [steemit/condenser#58]
Dear Steemit Team,
Dear @ned-scott ,
Dear @bytemaster ,

I am on Steemit for a full day now and want to share my experiences. Why here? Cause I dont know how to get exposure on the blogging platform. I learned about Steemit from reddit. It is presented as a platform to make money with posts. Piles of money. I don't think that is a good picture because it gives a wrong message. But let's move on. 

I am currently trying to accumulate funds to help out my sick mother. I thought I would give Steemit a try becasue of the exposure it is getting and because it is very new. Also I saw a girl generating an incredible amount of money for a make-up video.

I am somewhat desperate about my cause... so i registered and read everything about Steemit that I could find. I don't think i understand even 20% of it by now. But I learned about formatting and categorys and texts. I wanted to make a good first introduction to my cause and why I joined Steemit.

https://steemit.com/introduceyourself/@tylermyler/let-me-introduce-my-mother

After I posted it I was really excited because there were people that commented almost instantly.. I somehow do have my doubts that they actually read my post though. But it stagnated. The worst is that after posting it I couldn't find the post myself anymore. 

I don't know how to see the post or how other people can discover the post. Maybe people are just not interested in my story too much. Which is okay because there probably is more interesting things in life. But I dont want to leave anything untried for my cause. My mum really deserves it and I actually felt being clever jumping on this platform and writing posts while maybe at some point being able to pay that renovation of the bathroom. 

My article isn't even listed anymore on the page. And I don't see the benefits of spamming the community with it. I don't think anyone will benefit from it. But it is a bit nerve-wrecking to see what kind of posts get attention and what kind of posts don't.... and how the hell can I find my own post.. and how should others?

I am not yet giving up but it is a bit frustrating to see how this is working out. With 9 "upvotes" my posting earned 0.00 dollars. To be honest and I hope this does not sound greedy and selfish I hoped for it to be in the 10-35€ region (judging by other introduction posts) - because this would be a sum that we could actually put aside and safe for the bathtub. 

I do have plans for new posts about my job. And I dont mean to get rich on your platform. But in order for it to be worth it the time of posting and educating people about my mother, my job, philosophy or life there would need to be some return... say 5$ per post. But my post now disappeared completely somehow. I don't know how I can continue if this is the return the platform has to offer - except you get lucky I guess and your post catches fire.

I am sorry to steal your time on that matter and even more sorry that I have taken this way here to get attention from the team of steemit on my matter. You will see a few more posts by me and who knows... maybe it will work out eventually. But given the current circumstances I don't see this happening.

All the best from me and I really think you are doing a good job with your platform. Kudos to you. The idea is great and I do hope it will work out in the long run. For everyone. You and the users.

Michael ([@tylermyler](https://steemit.com/@tylermyler))

If it is helpful I would leave a few short suggestions about post exposure:
- when setting tags there could be recommended ones that are commonly used
- it is not really getting clear that the first tag is the chosen category of the post 
- categories and tags could be split for better management
- have a category in the dropdown: random posts - so people could even find posts like mine that else just disappear

Other great things I felt missing in the past 24 hours:
- a notification on your user icon when you have a new reply, comment, (upvote) - basically like the notification on reddit or facebook
- being able to subscribe people (i saw that it is possible but where to I see their posts?)
- the option to follow a certain category
- a dedicated search that is modifyable if you search for users posts... or only within a certain category
- a clear information about the meaning of Steem, SteemPower, SteemDollars
-

**Comment by roadscape** [comment]
@tylermyler, thank you for the note. I too, would be disappointed with the site after that experience. I can say we've made some of the improvements you mentioned. The others are well on their way.
