### ISSUE TITLE
Feature Request: Allow anyone to see raw source text of post/comment

### ISSUE THREAD

**Issue by arhag** [steemit/condenser#6]
Currently only an author of the post/comment can see the raw text of the body field by clicking on Edit. I propose that everyone be able to see a read-only version of that if they choose to. This is useful when  quoting a specific section of a parent comment that you are replying to.

**Comment by tibonova** [comment]
This could be achievable with a link to the post on steemd.com, if it is not a problem that it wouldn't be a full in-house solution. 

The link is the same, except steem**it**.com/xyz --> steem**d**.com/xyz. 
A link to the steemd raw data in the line of voting/reply would solve this issue (and other type of raw data requests as well). The link could be the word "raw", an icon, or "</>". (I bet on the last one, but it could be anything that doesn't consume much space and represent its function well.)

**Comment by ausbitbank** [comment]
Seems to me like this ticket could be closed now, since the "share post" function now has a link to steemd.

![image](https://cloud.githubusercontent.com/assets/1692203/24505456/aec6f9f6-15a5-11e7-911b-e122a14cc3a8.png)

**Comment by mcifani** [comment]
@ausbitbank Thanks, closing(sources are now included for users).
