### ISSUE TITLE
Denmark phone number not accepted for registration.

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/condenser#611]
I'm sharing this ticket with a gentlemen who is trying to register. Can you give him an answer please?

**Comment by Whytehorse** [comment]
I can confirm this for US, UK, France and Germany phone numbers as well. It looks like the verification backend is down and rejecting all numbers.

**Comment by jcalfee** [comment]
Many US, UK, France and Germany numbers are listed as Delivered and I see new accounts.  Can you pick one case and email contact@steemit.com some information to help us debug the issue.
