### ISSUE TITLE
Comment button in Posts List should load comments only

### ISSUE THREAD

**Issue by sean0010** [steemit/condenser#620]
Sometimes it's slow.
- Steemit.com server could be slow
- User internet connection could be slow
- The content might have HD images in it

When someone comments on your post, you want to check what's new in there quickly.
It should not load the original post.
Open up Lightbox modal and load comments only. Faster and better.

**Comment by roadscape** [comment]
This can be done from 'Replies' tab in your profile. We can look at splitting them later.
