### ISSUE TITLE
navigate though user's blog history (prev/next)

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#652]
It is requested that we show links to prev/next posts (by the same author) on each post.

**Comment by sneak** [comment]
@roadscape requested by whom?

@mcifani please focus on fixing functionality bugs before adding new features.

**Comment by mcifani** [comment]
@sneak this was requested by Dan.  Yes, bugs are getting highest priority.

**Comment by sneak** [comment]
@bytemaster please create new feature requests in Trello and link the associated issues for prioritization.
