### ISSUE TITLE
Feed/Replies Notification count increases when posts are edited

### ISSUE THREAD

**Issue by abitmore** [steemit/condenser#666]
The number on "Replies" will increase when someone edited a reply?

**Comment by roadscape** [comment]
IIRC, this was a bug long ago. I can't replicate it now.

**Comment by abitmore** [comment]
Steps to reproduce:
* account A: create a new post
* account B: reply to the post.
* now the number in A's browser will show "1". Don't click on it, let it stay at "1".
* account B: edit the reply.
* now the number in A's browser will show "2".

**Comment by abitmore** [comment]
IMHO, in the scenario described above it should show "1". But if A clicked on the number "1", and B edited the reply after that, it SHOULD show "1" again (perhaps best if show a "new" symbol next to the title of new and/or edited replies when opening the "replies" page, and perhaps order by last edit time (descending)).

**Comment by roadscape** [comment]
Still a problem?

**Comment by plink01001** [comment]
This should already be resolved, but in case it is not, it should be handled in https://github.com/steemit/condenser/issues/72.
