### ISSUE TITLE
I just found a bug in steemit system : After logged out I can upvote,comment or post

### ISSUE THREAD

**Issue by steemit-royalmacro** [steemit/condenser#667]
Today I just found a bug in steemit system. After logged out my account I can “upvote or comment or even make a new post“.Look into this now :
https://steemit.com/til/@royalmacro/i-just-found-a-bug-in-steemit-system-after-logged-out-i-can-upvote-comment-or-post

**Comment by jcalfee** [comment]
I could have all the tabs logout by adding a small framework so they can communicate.  The accepted answer here says local storage emits a StorageEvent event when a change is made.  The event contains a key and the new value so the cost of listening to and reacting to a logout should be very low.

http://stackoverflow.com/questions/2236828/javascript-communication-between-tabs-windows-with-same-origin#12514384

**Comment by jcalfee** [comment]
I hit a snag.  This appears to work (I get several iterations of 'ret' until done === true) but it is not actually dispatching the logout:
```javascript
function* logoutAction() {
    yield put(user.actions.logout())
}

export function logoutStorageHandler(storageEvent) {
    console.log('storageEvent', storageEvent)
    if(storageEvent.key === 'logout_event') {
        const iterator = logoutAction()
        let ret
        do {
            ret = iterator.next()
            console.log('ret', ret)
        } while(!ret.done)
    }
}
```
![image](https://cloud.githubusercontent.com/assets/204121/20721661/4a57d020-b629-11e6-8da1-7ab58b0d45fb.png)

**Comment by theghost1980** [comment]
Hello guys. I was playing a bit with some issues and I have found that this one looks like it is already solved (tested on safari on MacOS).
May I ask If somebody could close it? (i mean one less should make you all fell better right?) 💃 

The latests results are, after you log out and you try to upvote, the system asks you to log in again:

<img width="590" alt="screen shot 2017-03-29 at 15 56 21" src="https://cloud.githubusercontent.com/assets/24734575/24473985/28d9acf6-1499-11e7-8cce-9e5ef40cfb38.png">

**Comment by mcifani** [comment]
Thanks @theghost1980.
