### ISSUE TITLE
Reblog/Resteem Notifications

### ISSUE THREAD

**Issue by KrNel** [steemit/condenser#683]
Similar to Facebook when someone "Shares" one of your posts, you get notified that someone appreciated your post and shared it for greater visibility.

Can this be added? Not urgent, but helps with interconnectivity in some respect.

Thank you for your work.

**Comment by TimCliff** [comment]
Seems related to https://github.com/steemit/condenser/issues/72 - could probably be combined into one single "notification overhaul" issue.
