### ISSUE TITLE
Can't login [username does not exist] or Register [username taken]

### ISSUE THREAD

**Issue by FileTransferProtocol** [steemit/condenser#696]
Cannot login because my username does not exist.

Cannot register with my username because the username is taken.

Please help me login to my steemit account: kinetiktrader

**Comment by roadscape** [comment]
Note: Username does not exist on the chain, so it appears to be stuck in registration process.

**Comment by FileTransferProtocol** [comment]
so what do I do...

**Comment by roadscape** [comment]
We will check on this and get back to you!

**Comment by valzav** [comment]
that's strange - kinetiktrader account is not registered on the blockchain, you should be able to registered it the regular way, just click on the email confirmation link and continue to phone input.

**Comment by FileTransferProtocol** [comment]
I still get that phone number is still in use.

​

**Comment by arminbusatlic** [comment]
I registered today using username arminbusatlic. Confirmed my account, wrote down my pass. I tried to login, says "Username does not exist".

**Comment by mbe24** [comment]
Me, too. Is there a possibility to check whether the registration has already been confirmed on the steem blockchain?

**Comment by gtkpr** [comment]
i'm having the exact same problem as arminbusatlic

**Comment by oisilener1982** [comment]
Same Exact Problem. @mayward username does not exist although it is Approved

Hi again,
 
Great news, we've just approved your account.
 
You now have exclusive control over your Steem account, plus some free Steem to help you get started.
 
On Steemit you get rewarded for your curation and content according to the will of the crowd. To login, click the link below.
 https://steemit.com/start/09c8e1a5c4c2c31ff52e3b2d65
 See you on Steemit,
 
- The Steemit Team

**Comment by schweitzerb** [comment]
One more here with the same issue.

**Comment by gtkpr** [comment]
for an up-and-coming blockchain? platform this can't be a good sign...

**Comment by oisilener1982** [comment]
It's Working Fine now

**Comment by bdervishi** [comment]
Hi
I registred days ago and I stil lget "Username does not exist "
username: bvd

What can I do?

**Comment by valzav** [comment]
@bdervishi: looks like your account wasn't created on the blockchain due to micro forking issues steem has been experiencing a week ago. You need to create your account again, you will receive another invitation.

**Comment by lehoang1000** [comment]
Hi,
I forgot username
email: alias10134@gmail.com

**Comment by Jolly-Pirate** [comment]
@lehoang1000 ask for help on https://steem.chat/help

**Comment by lehoang1000** [comment]
Can't login with email register :D

**Comment by lehoang1000** [comment]
@Jolly-Pirate I can't login with register guy. Please help me!

**Comment by lehoang1000** [comment]
No. I registered steemit.com

**Comment by TimCliff** [comment]
@lehoang1000 please register for an account at steem.chat and ask for support in the help channel.

**Comment by ibitbe** [comment]
i have the same problem with steemit.com, my account information has been verified a month ago, my email is changchuiyong@outlook.com,why always say "Username does not exist",

**Comment by TimCliff** [comment]
@ibitbe please ask for help in the help channel of steem.chat.
