### ISSUE TITLE
Request: hashtags for comments

### ISSUE THREAD

**Issue by surpassinggoogle** [steemit/condenser#719]
Good day! How are you doing? I have a very important post thus the need to drop by here. deep down i hope it can reach developers of steemit but i dont know how to make that work. https://steemit.com/steemit/@surpassinggoogle/just-this-simple-tweak-to-steemit-and-it-will-become-instant-h-aven-for-steemit-users

**Comment by TimCliff** [comment]
If I understand correctly, you want two things:
1. The ability to bookmark a comment
2. The ability to browse comments using hashtags

Is that correct?

**Comment by surpassinggoogle** [comment]
Yes, Tim. So that when one sees makes a reply to a thread of comments that fascinates him, it can form a tiny post in the hashtag. To understand this better. Remember when you to your replies and you click on a reply, what appears next looks like a standalone post with the option to choose to see the full text or direct parent. So something like that. If I reply to a comment or thread of comments that's amazing, why doesn't also cause a tiny standalone post to be formed. I think you got the summary cos you may understand these better n I don't, really. But I just notice that when I had a small chat conversation in the comment section, he mentioned a playful suggestion you know and he said why not #steemfest2 take place in Mexico. Now I would If think that if I click on the clickable link it will lead somewhere and it does but to an empty place. Basically, the idea is a way to prevent comments from staying lost foroever with the post that gathers them mostly cos that post on its own didn't get seen. Some comments are valid as post yet never get seen. So I am ask the ability, to help make an important comment thread that you see get seen. I was thinking perhaps being able to hashtag comments with hashtags will fix that and will make steemit more of a home. So that constant use of a particular hashtag with comments will amassing until it forms a small category of it's own filled with standalone posts which are mostly comments. Too, there is another issue that I forgot to write about she may contact you to explain it better. It is that the mentioning or tagging option doesn't work. Many important posts especially post that are cries for help n wants to gather opinion mention some people to join the conversation but people don't get notified when they are mentioned of tagged so to speak!                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: TimCliffSent: Friday, November 25, 2016 10:04 AMTo: steemit/steemit.comReply To: steemit/steemit.comCc: surpassinggoogle; AuthorSubject: Re: [steemit/steemit.com] A simple tweak that will instantly make steemit a haven for newbies! (#719)If I understand correctly, you want two things:

The ability to bookmark a comment
The ability to browse comments using hashtags

Is that correct?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/steemit/steemit.com","title":"steemit/steemit.com","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/steemit/steemit.com"}},"updates":{"snippets":[{"icon":"PERSON","message":"@TimCliff in #719: If I understand correctly, you want two things:\r\n1. The ability to bookmark a comment\r\n2. The ability to browse comments using hashtags\r\n\r\nIs that correct?"}],"action":{"name":"View Issue","url":"https://github.com/steemit/steemit.com/issues/719#issuecomment-262866725"}}}

**Comment by TimCliff** [comment]
So for the first one, this is actually already supported. As an example, here is a link to your comment where you replied to me in your post: https://steemit.com/steemit/@surpassinggoogle/just-this-simple-tweak-to-steemit-and-it-will-become-instant-h-aven-for-steemit-users#@surpassinggoogle/re-timcliff-re-surpassinggoogle-just-this-simple-tweak-to-steemit-and-it-will-become-instant-h-aven-for-steemit-users-20161125t092325696z

For the second one, I think that this would end up creating a lot of confusion for users browsing content. _Most_ comments are really only useful when they are in the context of the post / conversation that they are in. If we started including comments when users browsed tags, it would add a lot of content that people would want to ignore. If you end up with good comments that are interesting / useful just by themselves, then it would probably be a good idea to create a post with whatever it is about.

**Comment by sneak** [comment]
Please use descriptive titles for issues and not clickbait.

**Comment by surpassinggoogle** [comment]
Pls stop! I didn't know how to use github n my first time there. Someone told me, I can suggest  there then I got on there. Don't always be fast in making conclusions. Nobody's clickbaiting!                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Jeffrey PaulSent: Saturday, November 26, 2016 10:39 PMTo: steemit/steemit.comReply To: steemit/steemit.comCc: surpassinggoogle; AuthorSubject: Re: [steemit/steemit.com] A simple tweak that will instantly make steemit a haven for newbies! (#719)Please use descriptive titles for issues and not clickbait.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/steemit/steemit.com","title":"steemit/steemit.com","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/steemit/steemit.com"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sneak in #719: Please use descriptive titles for issues and not clickbait."}],"action":{"name":"View Issue","url":"https://github.com/steemit/steemit.com/issues/719#issuecomment-263066733"}}}

**Comment by roadscape** [comment]
I'm not sure I fully understand the request, but we can revisit this in a few months.
