### ISSUE TITLE
Notifications / Alerts for Replies, Upvotes, Rewards, etc

### ISSUE THREAD

**Issue by fleurilafleur** [steemit/condenser#72]
Hey guys, I think you know about that already but it seems like a missing crucial feature for the people. Notifications. About replies, upvotes, downvotes etc. 

I made a browser extension for Google Chrome that provides this feature to the users but it would be even better if we could have this feature natively integrated into the platform. 

It can be found here: https://steemit.com/steemit/@fleuri/steemit-notifications-browser-extension-download-now

I would like to share some of the future ideas I have for the next upcoming version and maybe you can integrate something similar into your platform!

Please check the drafts:

http://i.imgur.com/Cx8yn35.jpg
http://i.imgur.com/kUILUUI.jpg

Hope this can be helpful in the process of designing the notifications. If you need any further help please let me know I'd love to help out!

**Comment by JasonMcz** [comment]
@fleurilafleur  @bytemaster 

Also perhaps you can change the current notification to more stylish ones. I found it boring with those notification printed out as long strings or assertion errors.

Instead perhaps add more classes to it?
https://github.com/pburtchaell/react-notification

**Comment by mvandeberg** [comment]
In addition to the social alerts, there needs to be alerts when the owner authority changes, savings withdraw requests are created, power downs are initiated, and limit orders are placed. I would much rather see confirmation of my actions then to have an attacker stealthily drain my account without my notice.

**Comment by sneak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notifications](https://trello.com/c/jDODakyR/19-notifications)

**Comment by sneak** [comment]
@valzav do we have a spec for what this will and will not include?

**Comment by valzav** [comment]
There are plans to support the following delivery methods:
1. In-app - it will show badges in red with numbers of updated items
2. In-browser - it will show browser-based desktip notifications when somebody performs some action you are subscribe to
3. Email

Also there will be settings section where user can setup the details level and frequency.

On the first stage 1) In-app notifications are going to be implemented.

**Comment by sneak** [comment]
Ok.  Please update the Trello card with this first stage spec - all product plans need to be in there, including what *isn't* in the first stage. :)

**Comment by roadscape** [comment]
#683 suggests also Resteem Notifications

**Comment by pkattera** [comment]
This issue is now outdated. We have the [Yo (notifications)](https://github.com/steemit/yo/issues) repo which contains the remaining work to be done.
