### ISSUE TITLE
Front Page Marketing: "Learn More" Link Slightly Outdated / Slogan Change Insight

### ISSUE THREAD

**Issue by taoteh1221** [steemit/condenser#734]
Just a quick head's up here related to the main page of steemit.com for new NON-logged in users: The "Learn More" button's linked page is a bit outdated, mentions the july payout etc. Also, "Welcome to the Blockchain! Your voice is worth something" may not quickly grab a very busy visitor's attention as good as something catchy that mentions being paid for authoring / curating and being censorship resistant. This is the most important page where you have one shot at capturing the attention of brand new visitors, and converting them to new users. Might be good to be absolutely sure you are maximizing it's marketing potential.

**Comment by taoteh1221** [comment]
Just leaving a note here on related issue: https://github.com/steemit/steemit.com/issues/768

**Comment by plink01001** [comment]
Has this been addressed / can this be closed?

**Comment by plink01001** [comment]
This seems to be addressed. Closing.
