### ISSUE TITLE
Slider to control withdraw_vesting amount

### ISSUE THREAD

**Issue by roelandp** [steemit/condenser#766]
Would be nice/smart(?) to give users who opt to `withdraw_vesting` via the GUI to give them the option to allow them to not only powerdown all vests within the given timeframe (13/104 weeks) but allow through the GUI to set the amount of `vesting_shares` (% of total shares) to powerdown over that given timeframe. I think a % - slider could do the job.

_In 13 weeks you will powerdown x% of your SteemPower_

Also a double confirm could be nice after the request to powerdown: 

_Are you sure you want to powerdown XX SteemPower? SteemPower gives you more control over post payouts and allow you to earn on curation rewards_

**Comment by finleyexp** [comment]
@pfunks thanks...I looked but missed this. :D

**Comment by plink01001** [comment]
Has this been addressed / can this be closed?

**Comment by plink01001** [comment]
This issue seems to be addressed. Closing.
