### ISSUE TITLE
Add Banner and TOC to the "Welcome to Steemit" Page

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#768]
- Add a Graphic banner at the top (It will be approved by Steemit before using)
- Better organize the content, including a table of contents
- Tell people how to find the welcome page (via the hamburger menu) if they want to get back to it later
- Add setting avatar pic + profile to the "todo list"
- Change introduceyourself to introducemyself, since that seems to be the new tag people are using for that
- When referring to "Helpful Posts from Steemit Users" in the text, mention that it is at the bottom of 'this page' - for clarity
- Some new links in the "Helpful Posts from Steemit Users" section (also to be approved by Steemit before using)

Please assign to @thebitcoiner for the PR

**Comment by sneak** [comment]
I can't assign members outside of our team. :(

**Comment by TimCliff** [comment]
That's OK. @thebitcoiner and I will plan to work on it. He'll be the one submitting the PR.

**Comment by TimCliff** [comment]
Most of the content changes in the original issue got submitted along with the PR for issue #723. The two things that are left are to:
- Add a table of contents
- Add a banner image at the top of the page

**Comment by roadscape** [comment]
I believe this is all done :)
