### ISSUE TITLE
UI auto-hrefs @username tags for users that don't exist

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#771]
shouldn't make links if the username isn't valid

**Comment by svk31** [comment]
That would mean firing off api calls for every @ mentioned name to check whether it exists or not, is it really worth it?

**Comment by sneak** [comment]
When we have some additional microservices for this sort of data, that would be totally fine... and I imagine that the services that provide per-user profile information will accept lists of usernames and return lists of corresponding results, so it should only be a single call.

**Comment by sneak** [comment]
I imagine pounding steemd with this right now is probably suboptimal, I just didn't want to lose track of this bug for now.

**Comment by svk31** [comment]
A service like that would be great to have indeed, can we add a "microservice-needed" label?

**Comment by pkattera** [comment]
@sneak It looks like this may have been fixed.

I just tested it here: https://steemit.com/test/@test-safari/tester
It looks like the registered account names link, while the unregistered names do not.

I'm going to close it. Please re-open if I misunderstood the original ticket and it is still not fixed.
