### ISSUE TITLE
Ability to delete/deactivate accounts

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/condenser#787]
I know the blockchain is an immutable record. But right now quite a few users pointed out that they would like their acccount deactivated. 

Would it be possible to create a function where someone could deactivate their account and get their content to not display anymore on the website?

**Comment by sneak** [comment]
Possibly.  It's obviously a feature that appeals to a relatively small total market - we are going to focus first on features that have widespread, mass appeal.

This would be a fairly easy thing to add as part of our moderation layer we are building out in 2017.  Tagging appropriately.

**Comment by RenaudGagne** [comment]
in the meanwhile when there are requests on Facebook, what do I tell them when they want their account to be taken out?

**Comment by roadscape** [comment]
There's nothing we can do right now. Some users have edited their posts to make them blank. In the future we might have a way for authors to ask frontends to hide any of their posts.
