### ISSUE TITLE
Feature Request - Promoted Function Bid

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/condenser#800]
I used the "promoted" this morning for one of my post and I would have liked to know where my bid would position me on the "promoted" tab. I believe that could definitely increase the use of this function. Any advertiser would like to know this.

**Comment by sneak** [comment]
Agreed. Unfortunately this one is probably going to have to take a backseat to some other larger features we're working on, so I wouldn't hold your breath on this one.  It's a good suggestion and I'm classifying it appropriately.

**Comment by RenaudGagne** [comment]
Thanks

**Comment by TimCliff** [comment]
@RenaudGagne - it looks like someone  from the community developed a tool for this. I haven't tried it, but it looks like what you are asking for.
https://steemit.com/promotion/@ausbitbank/new-tool-how-much-should-i-promote-my-post-for-steemviz-com-promo

**Comment by roadscape** [comment]
This would be a natural progression of promoted post functionality when we're ready to build it out.
