### ISSUE TITLE
meta-discussion over change to URL routes

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#807]
I propose the following changes to the main URL routes:

(variables are prefixed with `$` sigil to distinguish from byte literals)

`/@$username` becomes `/$username`

`/$category/@$author/$permaslug` becomes `/$author/$permaslug`

(old `/$category/@$author/$permaslug` links should redirect to the new scheme)

current `/@$username/(.*)` routes get moved to `/$username/meta/$1` to distinguish from permalinks to articles

current `/$sortmode/$tagname` becomes `/headline/$sortmode/$tagname` (`/` being implicit `/headline/trending`).

`/s/(.*)` reserved for steemit.com specific pages such as help and documentation, the tag list (currently at the bizarre `/tags.html/created` route), static assets, et c.

I want our permalinks to be beautiful and concise.  The `@` is noise and the top tag doesn't need to be in the URL.

Thoughts?

**Comment by sneak** [comment]
@valzav @roadscape @bytemaster @mcifani Your feedback is requested.

**Comment by mcifani** [comment]
Definately in favor of the simplified routes suggested. Removing all the .html was talked about prior and good.  The reserved /s/ seems also clean for internal pages.  @sneak

**Comment by roadscape** [comment]
`/@name` is an elegant (albeit non-compliant) way of namespacing.. better than `/~name`or `/u/name`, short of not using a ns at all, though this creates other conflicts.

Here's a potential layout without using `@`s:


```
Post:         /<community>/<user>/<permlink>
User:         /<user>
User meta:    /<user>/<tab>
Tag:          /tags/<tag>
Tag, sorted:  /tags/<tag>?sort=<sort>
Docs:         /docs/<page>
Users:        /users/<action>          (create, recover, etc)
```

Basically, a URL with 3 segments is always a post. A URL with 1 or 2 segments always starts with a username (some of which have been reserved for internal use).

Important to figure out what to do with communities vs. tags.. IMO communities would almost entirely replace them anyway (reddit), and tags could still be accessed via search (twitter). Tags will be a mess as they are not moderated, so they'd need to be combined with a relevance search anyway. Moderated (or even just *branded*) spaces will be the source for high SNR. (IMO category-based communities could work quite well even without blockchain-level consensus support)

**Comment by sneak** [comment]
Settled on C from https://github.com/steemit/steempunks/wiki/URL-Routes

**Comment by clayop** [comment]
Many users have been asking to shorten the sort method url, currently `created`, `trending`, and `hot` because of difficulty in memorizing and typing (especially in mobile).
I personally prefer to having `n` (new), `t` (top or trending) and `h` (hot).

**Comment by sneak** [comment]
@clayop ability to be typed from memory is not really a design goal for these, although keeping things concise (which has that as a side effect is).  Going to single letters is too cryptic, and serves only our existing power user base.

**Comment by sneak** [comment]
## New


### Part 1: Users/communities.  Usernames at top level.

- `/<user|community>`
- `/<user|community>/wallet` (formerly /@username/transfers)
- `/<user>/permalink`
- `/<community>/<user>/permalink`

### Part 2: Tags

- `/t/<tag>`
- `/t/<tag>/<sort>`

### Part 3: Steemit Inc
- `/s/<static pages>`
- `/s/faq`

### Part 4: Condenser

- `/c/api/<old condenser api endpoints>`
- `/c/login`
- `/c/change_password`
- `/c/<etc ...>`

**Comment by sneak** [comment]
@valzav what is the route for global hot/trending/et c?  I see the one in the docs for per-tag.

Also, what is the route for a community's hot/trending/et c?

**Comment by relativityboy** [comment]
@sneak I believe global order for hot/trending/etc is `t/all/${order}`

**Comment by valzav** [comment]
@sneak, @relativityboy is correct - it's `/t/all/${order}`.
Community's hot/trending/et shouldn't be a problem, e.g. it can be `/community-nmae/t/all/trending`, 
 but communities are out of scope of this refactoring. The only assumption made in regard to communities is that a community urls are prefixed with `/community-name`.

**Comment by sneak** [comment]
It's not out of scope; this is the implementation of the new URL scheme that needs to last us the next 5+ years.

The `/t/` concept doesn't work for a community, as the 'all' identifier doesn't mean anything in that context.  We need something better.

**Comment by valzav** [comment]
It can be just `/community/trending` - we can decide on this later, probably @roadscape is already working on url schema for the communities

**Comment by valzav** [comment]
@sneak, I thought I'm commenting on this branch's thread https://github.com/steemit/condenser/pull/1826, not on general urls metaissue. Right communities are not out of scope here. I guess @roadscape is already working on communities url schema...

**Comment by roadscape** [comment]
Closing as out-of-date. New discussion to follow
