### ISSUE TITLE
"view count" sort order option for post lists

### ISSUE THREAD

**Issue by clayop** [steemit/condenser#812]
This is not a blockchain level fetching, but I think steemit.com can utilize views information to pick popular posts. The weakness is that it can be abused by crawling bots.

**Comment by sneak** [comment]
Not a bad idea, but our view counts right now are super naïve.  We wanted to ship something to get people a rough idea.  We're going to circle back to them in a few months but I wouldn't hold your breath for this feature.

(At the moment we are primarily focused on adding features around new user acquisition and user retention.  While I want to do a lot of these little nice-to-haves, way more important right now is growing the size of the community.)

**Comment by clayop** [comment]
IMHO, view count is important at the moment since majority of voting count is consisted by bots and hence view count is a way to distinguish "popular among humans". This suggestion is in a vein of making human-oriented social community.

**Comment by arhag** [comment]
> view count is important at the moment since majority of voting count is consisted by bots and hence view count is a way to distinguish "popular among humans"

@clayop: If you make view count important by giving it a sort order, then the current naïve implementation will be even more abused by bots than the vote count metric. And I think it makes sense to not make it a priority right now to make the view count more robust against abuse, since there are far more important things for the devs to focus their efforts on.

**Comment by stellabelle** [comment]
By not making this a priority, user retention will be problematic. The fact that the "product" is not able to properly identify true viral content that has value both within Steemit and in the broader social media sphere, is one of the central reasons that readers and bloggers don't find it currently valuable. If for example, another Tab was added next to Promoted, that measured human eyeball views plus comments, readers would be able to quickly find content that real humans are reading and interacting with. Sure, bots could manipulate this, but readers would be the final decision makers. Humans can still tell the difference, and would most likely pass over the manipulated content. The longer this is ignored, the harder it will be to retain users. The actual product must be improved before any real demand for the platform and currency exists.

**Comment by roadscape** [comment]
We understand views are a very important and useful metric. 

However (a) it needs to be more robust before we could implement features like the one described in OP and (b) building the required infrastructure for it is low priority atm.
