### ISSUE TITLE
view page for specific comment does not display comment's children

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#814]

**Comment by roadscape** [comment]
Might be dupe of #440

**Comment by mcifani** [comment]
@sneak comment reply tree should be showing on a specific comment/permalink. Could you describe a bit further you thoughts for this. Thanks

**Comment by mcifani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [view page for specific comment does not display comment's children #814](https://trello.com/c/g9HxXWA8/161-view-page-for-specific-comment-does-not-display-comment-s-children-814)

**Comment by plink01001** [comment]
Has this been addressed / can this be closed?

**Comment by plink01001** [comment]
This seems resolved. Closing.
