### ISSUE TITLE
Notification Unread Count Does Not Update

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#853]
I open steemit and open a bunch of stuff in new tabs.  On one of those tabs I click my profile icon and click on "replies" which has a red unread count.  I read all my replies.

I go to the other tabs that I opened before and they still show an unread count on my notifications, but there have been no new notifications.  The unread count in the other tabs isn't updating as I clear the notifications.

**Comment by sneak** [comment]
This is sort of an instance of the general "how do we update the site UI in realtime as changes happen" problem, which we should discuss and solve.

**Comment by roadscape** [comment]
Low priority, and notifications service will undergo major overhaul anyway.
