### ISSUE TITLE
Promote transaction showing up twice in wallet

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#865]
I recently promoted a post for $5, and the transaction is showing up twice in my wallet page.

![image](https://cloud.githubusercontent.com/assets/20735105/21248895/d2d539aa-c2ff-11e6-9cd7-4f75b8e13e49.png)

Here it shows that the post was only promoted for a total of $5:
![image](https://cloud.githubusercontent.com/assets/20735105/21248909/f0100b80-c2ff-11e6-9113-8302e3efa7e4.png)

**Comment by roadscape** [comment]
Can you reproduce this? Loading your wallet shows it fine for me.

**Comment by roadscape** [comment]
@pfunks had a (potentially) similar issue where a transfer was listed on the curation rewards page. He suspects they may have occurred in the same block (i.e. at the same time)

**Comment by TimCliff** [comment]
The same transaction is only showing up once now. I don't know what changed to 'fix' it.

**Comment by pfunks** [comment]
![image](https://cloud.githubusercontent.com/assets/22420130/21285063/1a76bcd0-c3f4-11e6-81e3-eebd39e9425c.png)

Screenshot of what @roadscape mentioned. I saw two other memos from other transactions on different pages, the likelihood of the transfers all occurring in the same blocks as these post payouts is low. I wasn't able to replicate the bug.

**Comment by roadscape** [comment]
If anyone is still experiencing this issue, please leave a URL exhibiting the behavior here.

**Comment by roadscape** [comment]
Closing, please update if this comes up

**Comment by TimCliff** [comment]
Here's another instance of the issue. 

This transaction was showing up twice:
![image](https://cloud.githubusercontent.com/assets/20735105/22392397/2bb7f3de-e4be-11e6-9960-8d7c769a353b.png)


I checked the account now and it is no longer showing up twice:
![image](https://cloud.githubusercontent.com/assets/20735105/22392410/561825a4-e4be-11e6-9d6a-14b4ffb061ab.png)

**Comment by roadscape** [comment]
Thanks, unfortunately this case seems to have resolved itself. Please send more if you see them, we need to catch this bug live.

**Comment by TimCliff** [comment]
Ok, will do. All of the instances so far that I have seen have been right after the transaction occurs. It doesn't seem to persist for very long. I'll continue to monitor and will let you know if I see it again. Hopefully we can catch it while it is happening.

**Comment by TimCliff** [comment]
Another user reported an instance of this today. By the time I checked, it was already gone.

https://steemit.com/@ebryans/transfers

Here it is right after the transfer:
![image](https://cloud.githubusercontent.com/assets/20735105/24124958/19bd4b12-0d94-11e7-8263-f0e4d81bc908.png)

Here it is now:
![image](https://cloud.githubusercontent.com/assets/20735105/24124970/26c1557e-0d94-11e7-8805-8da24833ce8c.png)

**Comment by TimCliff** [comment]
I haven't seen any instances of this recently. Closing unless it is re-observed.
