### ISSUE TITLE
Optimization: Replace body with body_summary for some content based API calls

### ISSUE THREAD

**Issue by jcalfee** [steemit/condenser#879]
Add body_summary (first 512 bytes of the body) and remove "body" from all posts within the content array returned from:

- get_state @username
- get_state /(best|updated|hot|votes|responses|trending|trending30|promoted|cashout|created|recent|active)
- get_discussions_by_*

We could probably at least double page load times anywhere we load or page though a list of posts.  Right now we get full content for every post even if we only want to view a one sentence summary for the post.

Instead, pages like `/@username` and `/trending` could return a `body_summary` instead of the full `body` text of the posts.  The UI will call `get_content author permlink` when viewing a full post, so that is the best time to return the full `body`.

Ideally we should do this in steemd once and it would cover both cases:
* static pages from nodejs
* UI navigation changes that translate to a get_state API call directly to steemd

The catch is, the UI strips out markdown and HTML then looks at what is left to find the first line of readable text.  So, I would not expect steemd to do this.  Instead it can extend way beyond 140 characters still leaving it up to the UI to do the filtering.  Invalid HTML should not cause a problem, parsers are built for that.

Related:
> get_state /@steemsports returns a frame that is about 3.77MB. I'm able to copy the frame and paste it into a fast text editor that has a word wrap. It looks like a lot of content. I believe get_state should probably return content summary instead of the full content while get_content can fill in the rest.

https://github.com/steemit/steemit.com/issues/873

**Comment by roadscape** [comment]
Backend implementation underway: https://github.com/steemit/steem/issues/779
