### ISSUE TITLE
Steemit post link should pull up fingernail.

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/condenser#887]
The chat does it, it would be nice if steemit did, too?

**Comment by roadscape** [comment]
Are you referring to cases when posts are linked to from comments?

**Comment by TimCliff** [comment]
@roadscape - I think the request is to make Steemit posts and comments work the way Steemit.chat does, in that if a user pastes a post URL into their post/comment, that Steemit renders it with the thumbnail/preview.

**Comment by FreeBornAngel** [comment]
Yes, exactly, @timcliff.

**Comment by roadscape** [comment]
This would be nice to see but out of scope in terms of near future
