### ISSUE TITLE
Display Vote Power on profiles

### ISSUE THREAD

**Issue by sykochica** [steemit/condenser#898]
Could we get our Vote Power Percentage displaying on Steemit.com? 

It could just be added into the profile area of the blog with an example being [here.](http://i.imgur.com/h7PwRni.jpg) I'd figure this wouldn't be more than a display line in the UI, since the data is already available and used in external sites like the eSteem app and steemd.com.

Often for new people, they ask questions on what they see on the site. Adding the VP% in would get them asking that question, which leads into many important aspects like how $ is given in posts (beyond just the SP aspect) as well as on curation rewards.

This obviously is a rather low-priority, but I'd also assume would be rather low hanging fruit.

**Comment by Tadasu85** [comment]
This would be absolutely excellent!

**Comment by pfunks** [comment]
And if it were implemented, I'd like to see the power be calculated virtually as steemd.com does. Since the blockchain is "lazy" in the words of Dan himself, steemd won't actually return an account's current voting power, but rather the voting power it had on its last vote. It will still virtually recharge, but the new vote power won't be calculated until the next vote.

**Comment by TimCliff** [comment]
This may be considered a 'power user' function (i.e. users who go to steemd.com). I've seen a lot of newer users get confused and misled by not understanding their voting power, thinking that they need to stop voting and let it recharge if it starts to drop. I'm not set on this, but a large part of me thinks it may be better for the average user to _not_ show them their voting power.

**Comment by plink01001** [comment]
There are no plans to implement this on steemit.com at this time. There are many third party services that offer this information for users that are interested. @sneak to close.

**Comment by sneak** [comment]
This is not a “no plans”, this is an explicit “no”. We plan to avoid implementing this.
