### ISSUE TITLE
voting on comments on a post-modal when logged out destroys post-modal's page state

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#974]
Got bit by this one today, and it's particularly annoying.

1. be logged out
1. visit https://steemit.com/@steemitblog
1. click top post
1. read comments. collapse a bunch of top-level threads
1. comment or vote
1. be prompted to log in. enter credentials
1. after success, find yourself on /@steemitblog instead of the post modal, with all of your scroll position and collapsed threads lost

this is on latest mobilesafari on latest ios on a 7+

**Comment by sneak** [comment]
In fact, it would be great if we could store all the collapsed comment threads comment ids in localstorage and re-collapse them on subsequent pageviews, no?

**Comment by plink01001** [comment]
Is this still an issue?

**Comment by plink01001** [comment]
Closing as modals have been removed. Please re-open if this is still an issue.
