### ISSUE TITLE
Coinomi wallet addition

### ISSUE THREAD

**Issue by kopykatA** [steemit/condenser#978]
I would like to talk with someone about the possibility to add steem to coinomi wallet. 
AVailable on chat as well and most slack channels (as kopykat).

 Thank you

**Comment by nedsteem** [comment]
Hi Kopykat,

That sounds great. Let us know how we can help

Ned

**Comment by kopykatA** [comment]
Coinomi rends 2 azure backend servers for each coin seperately. Setup, maintenace and rent is 100$ per month with 1 year prepaid. If you have any questions dont hesitate to ask. I hope you know what coinomi offers (http://coinomi.com). Also there is a desktop(multiplatform) version coming really soon.

**Comment by liondani** [comment]
Are we sure he is a official representative of coinomi?  (0 followers,  and weird they ask for money!)

**Comment by liondani** [comment]
@kopykatA if we get confirmation from @erasmospunk or https://github.com/GeorgeKimionis we can continue our conversation.

**Comment by GeorgeKimionis** [comment]
I can confirm that @kopykatA has been appointed by Coinomi to initiate the process of bringing in the best of altcoins.

**Comment by kopykatA** [comment]
I am here and we can also discuss in steemit.chat. Thank you

**Comment by pfunks** [comment]
@GeorgeKimionis Is he authorized to spam github pages asking for $1200 up front?

**Comment by kopykatA** [comment]
@pfunks please my first mail and the answer i got. I also didnt ask, but i clearly said whats the pricing available atm. If you need a discussion to be less clear and shadowy, its easier.

**Comment by liondani** [comment]
I would make a post on steemit and ask approval from the community.... It is very likely you get the funds you ask... Or you get part of it and offer your services for limited time until you raise more funds from a future post... We have many projects going like this...

**Comment by GeorgeKimionis** [comment]
@liondani sounds good, I hope it goes well this time (unlike [this time](https://steemit.com/lets/@romangelsi/lets-get-coinomi-to-support-steem)). For what it's worth, this is also a great review on steemit for coinomi that could support your call for funds: https://steemit.com/bitcoin/@libert/coinomi-bitcoin-altcoin-wallet-review

**Comment by kopykatA** [comment]
@liondami i hope it works out. We 're here for any further info.

**Comment by GeorgeKimionis** [comment]
@liondani any updates?

**Comment by TimCliff** [comment]
@roadscape / @sneak - close?
