### ISSUE TITLE
Encrypted memos broken in web interface

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/condenser#98]
See [this bug report](https://steemit.com/steem/@youkaicountry/bug-report-transfers-that-contain-private-memos-do-not-send-from-steemit-com).  I suspect the memo key might have fallen through the cracks with the key handling changes that were implemented in response to the hack.

**Comment by roadscape** [comment]
Still not working for me in Chrome, where are we at with this issue?

**Comment by plink01001** [comment]
Are there plans to make any changes for this issue, or should it be closed?

**Comment by pkattera** [comment]
I just tested this out. Placing a `#` before a memo in transfer processes the transaction fine (with the encrypted memo working).

Please let me know if it's not working for you.

Closing this issue.
