### ISSUE TITLE
Missing Post When Browsing a Tag using "New"

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#986]
If you browse the "qm-lessons" tag using "New":
https://steemit.com/created/qm-lessons

A post is missing here (see arrow in screen shot)
![image](https://cloud.githubusercontent.com/assets/20735105/21874944/d9e192d6-d83d-11e6-86d1-e116f6592214.png)

The URL of the post that is missing is:
https://steemit.com/science/@lemouth/quantum-mechanics-lessons-on-steemit-2-particles-interactions-and-conservation-laws

Here is the meta data for the post, showing that it is using the "qm-lessons" tag:
![image](https://cloud.githubusercontent.com/assets/20735105/21874966/08da8e1c-d83e-11e6-83c8-d0a6431b17ed.png)

**Comment by roadscape** [comment]
Appears to be backend issue. Issue filed: https://github.com/steemit/steem/issues/781

**Comment by roadscape** [comment]
We'll probably get this implemented in middleware before it will be fixed in the backend.

**Comment by roadscape** [comment]
Resolved with new hive API.
