### ISSUE TITLE
Steemit Website UX/UI Suggestions to Make it Easier to Buy Steem Power

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#99]
Here are five (what I think to be) easy updates that could be made to the Steemit.com UI, that would make it a lot easier for newcomers to invest in Steem/SP. Could these be worked on?

https://steemit.com/ux/@timcliff/four-steemit-website-ux-ui-suggestions-making-it-easier-to-buy-steem-power

**Comment by roadscape** [comment]
No longer using this dialog
