### ISSUE TITLE
Payout Shown in STEEM instead of SBD

### ISSUE THREAD

**Issue by clayop** [steemit/condenser#992]
A large portion of socio-psychological hardship in Steemit has come from reward distribution. People sometimes compare much smaller payouts than the bright past in July when trending posts easily got over $1000 (SBD). However, as matter of a fact, rewards in STEEM has not changed muchand what has changed is STEEM price denominated in SBD.

STEEM is a share of Steem blockchain, and can be considered as a reward point in Steem ecosystem, like Karma of Reddit or Marking of Poloniex. If we can make people to think the reward as a perk, at the same time make them free from money value, Steemit would be more enjoyable and less stressful.

**Comment by iamsmooth** [comment]
I think this is a good idea and even better is to just display it as "points" the way reddit does rather than as what can still easily be interpreted as a monetary unit.

At payout time, each "point" can be converted into 1 STEEM, or possibly using a different exchange ratio.

**Comment by FreeBornAngel** [comment]
I agree that it could show in steem, but to reduce it to points is to confuse that it isn't points, it's money.

It was frustrating to watch a .02 post round down to zero at payout.
I know the vests are the same, but the psychology isn't.

**Comment by pfunks** [comment]
Don't discount the marketing strength of the $ sign under posts. One of Steem(it)'s biggest strengths as far as an every day person is concerned, if not the biggest, is being able to earn money from it. To hide it away would be to hide its crown jewel feature.

**Comment by clayop** [comment]
STEEM can be money but more likely to be an asset (or point) that can be converted to fiat. A similar example is stones of jordan Diablo 2.

**Comment by pfunks** [comment]
Then we're crossing into the SBD debate. I've already expressed my opinions about that, mostly in @KrNel's post on Steemit. It really boils down to: if the goal of Steem and Steemit is to attract users, SBD and the $ sign are helping, not hurting.

**Comment by iamsmooth** [comment]
> if the primary goal of Steem and Steemit right now is to attract users, SBD and the $ sign are helping, not hurting

That's probably true.

On the topic of points someone (sorry don't remember) in a conversation elsewhere suggested using a higher amount for psychological reasons. Instead of 0.001 STEEM, which looks very small, you might get 1 point (1000 points = 1 STEEM).

**Comment by FreeBornAngel** [comment]
We just got to get more bodies through the gates.

**Comment by valzav** [comment]
@pfunks I agree $ sign can help to attract more people, but I think it's doing more harm when it comes to retaining those people - only small percentage is able to earn anything above $1 after first several posts, but they feel like they promised to be able to earn a ton of money, so after their expectation is not met they would leave. I think it's better to under promise than over promise.
It would be good to talk to some bloggers that posted several times and then left and asked them if the money was a factor.

**Comment by abitmore** [comment]
I remember these was a phrase: come for the money, stay for the community. If there was no $ sign, perhaps those authors won't come at all.

**Comment by abitmore** [comment]
Another case is that many people who had got thousands have also left. Apparently money only is not enough to retain those people.

**Comment by iamsmooth** [comment]
When people don't earn (enough relative to their other income opportunities at least), most of their friends are not on this site, and it isn't that much fun, they won't stay. It probably doesn't matter much whether the rewards are displayed in $ or points or STEEM or not at all. The idea of showing something other than $ is interesting, and could help (or hurt), but it is quite likely would not _dramatically_ change anything. It might be reasonable idea to split test on new visitors/users and see how it affects registration and retention but aside from that we are jus guessing.

**Comment by clayop** [comment]
The crux of this suggested change is in user's perception. Actually, dollar-denominated reward is a function of a perceived post quality and the value of Steem ecosystem (i.e. Steem price). If we change it to STEEM (or point) it becomes purely a function of perceived post quality (relative to other posts in a day).

Removing Steem's value part in the reward display is meaningful. Users can easily figure out the degree to which their post is well perceived regardless of Steem's value. Also they are less likely to complain other posts with very high dollar rewards during the STEEM-to-da-moon period if they see them in STEEM (e.g. 10,000 SBD reward in the past and 500 SBD reward posts now can have equal reward in STEEM). When users focus on STEEM, I also expect that they put more efforts to increase STEEM value, which consequently benefit them.

@iamsmooth Introducing another unit may confuse users more, and it has no significant implication if it has constant exchange ratio with STEEM. However, if users prefer an integer unit, we can use new unit that equals to `STEEM * 1000` (but it can exaggerate whales curation reward. e.g. blocktrades earns over 30,000 POINT per curation).

**Comment by FreeBornAngel** [comment]
I think wording on the 'give us your phone number' page needs to include 2fa language.
If I say f**k, did you think fork?
If I say g**k, did you think grok?
If I say give me your phone number do you think it is for the safety of your bank account?
A $20 phone is cheap insurance against a $1000 online, imo.

Tipping is how to reward the little guys, then the little guys can spread the wealth farther, easier, and without assistance from the hierarchy of sp.

The crushing of steemsports, safecrack, steembets, et al,'s redistribution schemes have put a real dent in my miniscule (relatively) rewards that I have made to this point.
Without them I am under what, 200sp?
After 5 months of daily grind?
(Folks just don't get the irony of rewarding me well,...)

I read the white paper, again, and still don't understand how rewarding with sbd places any obligation on steemit to create steem, the market will/can(?) balance all that absent a promise from steemit?

I agree that pennies for the newbs hardly create incentive.
Maybe some language that says if steem was a dollar your post would have been worth x?
Maybe some high sp votes on coherent posts with less than 20 votes and no visible rewards in cashout would create some excitement, too.

Tfyt.

**Comment by samupaha** [comment]
> The crux of this suggested change is in user's perception. Actually, dollar-denominated reward is a function of a perceived post quality and the value of Steem ecosystem (i.e. Steem price). If we change it to STEEM (or point) it becomes purely a function of perceived post quality (relative to other posts in a day).

This is actually good point, I hadn't thought about it this way.

> I remember these was a phrase: come for the money, stay for the community. If there was no $ sign, perhaps those authors won't come at all.

Yes! So far we have been looking too much monetary incentives. But those alone can't create a great community. There have been a lot of great writers here, some of who have made a lot of money, but haven't stayed because this platform didn't offer them a group they wanted to be part of. They didn't create meaningful relationships with other users.

I've been saying this for a while now: In its current form Steemit is just a publishing platform, not a social network.

**Comment by samupaha** [comment]
How about this: let's give users an option to choose between seeing dollars or steems as units for rewards.

This should be very simple to implement and people could try whether or not they like this change.

**Comment by roadscape** [comment]
Rewards in condenser will continue to be shown in SBD for now. There is good opportunity for other frontends to experiment with changes to the reward display. Maybe in communities it could be a per-community display setting.
